export const vorioProduct = {
  id: "vorio",
  slug: "vorio",
  name: "VORIO",
  category: "Field-service operations",
  description: "Realtime field-service dispatch and execution for organisations coordinating their own workforce.",
  status: "COMING_SOON",
  public: true,
  href: "/products/vorio",
  order: 3,
  seo: {
    title: "VORIO \u2014 Field Service Dispatch & Execution Platform | Kravia",
    description: "VORIO by Kravia is a field-service dispatch and execution platform being developed for faster technician assignment, SLA visibility, mobile field workflows and customer tracking.",
  },
  enquiryCategory: "Product enquiry \u00b7 VORIO \u2014 Field-service dispatch / early access",
  hero: {
    eyebrow: "A KRAVIA PRODUCT / FIELD OPERATIONS",
    title: "Field operations, kept in motion.",
    intro: "VORIO is being developed as a rapid field-service dispatch and execution platform for organisations that coordinate their own technicians.",
  },
  lifecycle: [
    "Service request",
    "Priority + SLA",
    "Eligible technicians",
    "Rank + dispatch",
    "Acceptance",
    "Live status / route",
    "Arrival",
    "Work + evidence",
    "Completion",
    "Customer status + operational insights",
  ],
  faqs: [
    ["What is VORIO?", "VORIO is a Kravia product in development for field-service organisations. It is designed to connect service requests, dispatch, technician mobile work, customer updates and operational insight in one coordinated flow."],
    ["Who is VORIO designed for?", "VORIO is designed for organisations that operate their own field workforce, including service teams in HVAC, electrical work, plumbing, equipment maintenance, facilities, utilities, telecom and technical support."],
    ["How does VORIO dispatch technicians?", "VORIO is designed to surface eligible technicians before a dispatcher makes an assignment, considering availability, service region, skills, certifications and service-level commitments."],
    ["Can VORIO help with SLA tracking?", "Yes. VORIO is being designed around priority and SLA-aware operations so teams can see the requests that require attention and keep service handoffs legible."],
    ["Does VORIO include a technician mobile workflow?", "VORIO is being developed with a technician mobile workflow for receiving work, updating status, following job checklists and recording completion evidence."],
    ["Can customers track service progress?", "VORIO is designed to give customers appropriate progress visibility from request through completion without exposing internal operational detail."],
    ["Does VORIO support audio or video assistance?", "VORIO's product direction includes controlled audio and video assistance for operational support. Availability will depend on the approved product release scope."],
    ["Does VORIO use artificial intelligence?", "Product intelligence may assist information organisation and operational workflows. Dispatch and service decisions remain governed by defined operational controls and people; VORIO is not presented as an autonomous decision-maker."],
    ["Does VORIO replace dispatchers?", "No. VORIO is designed to reduce coordination load and make the available operational context clearer. Dispatchers and service leaders remain responsible for decisions."],
    ["Does VORIO work without AI?", "The core operating workflow\u2014requests, eligibility, assignment, service status, evidence and reporting\u2014is designed to remain useful without relying on autonomous AI."],
    ["Is VORIO available in India?", "VORIO is being developed with India-aware configuration, including INR, Indian address and phone conventions, Asia/Kolkata time and metric units. Provider integrations are subject to approved scope and credentials."],
    ["Is VORIO available in the United States?", "VORIO is being developed with United States-aware configuration, including USD, US address and phone conventions, multiple time zones, daylight-saving time and imperial presentation options. Provider integrations are subject to approved scope and merchant eligibility."],
    ["Does VORIO replace public emergency services?", "No. VORIO supports private and commercial priority field-service operations. It is not a substitute for public emergency services such as 911 or 112."],
    ["Who builds VORIO?", "VORIO is a product of Kravia Private Limited."],
    ["How is customer and location data handled?", "The product direction includes tenant isolation, role-aware access, controlled data lifecycle and traceable operational actions. Public certifications are not claimed unless independently verified."],
    ["Can VORIO integrate with existing systems?", "VORIO is being designed for integration-ready workflows. Specific integrations and production availability will be confirmed only when approved for release."],
    ["How can a business learn more about VORIO?", "Use the VORIO early-access route to contact Kravia. Your request enters the existing corporate enquiry workflow with the VORIO product context attached."],
  ],
} as const;
