import type { Capability } from "@/lib/corporate/permissions";

export const officeSections = {
  dashboard: { title: "Corporate overview", eyebrow: "EXECUTIVE WORKSPACE", capability: "compliance.view", description: "A decision-oriented view of upcoming obligations, approvals, meetings and corporate activity.", empty: "No attention items are available for the selected financial year." },
  board: { title: "Board Room", eyebrow: "GOVERNANCE WORKSPACE", capability: "meeting.view", description: "Controlled meetings, notices, agendas, minutes, resolutions and action items.", empty: "No Board meetings have been scheduled for this financial year." },
  meetings: { title: "Board meetings", eyebrow: "GOVERNANCE RECORDS", capability: "meeting.view", description: "Meeting lifecycles are controlled. Formal records are versioned and final records are locked.", empty: "No meeting records match this view." },
  resolutions: { title: "Resolution register", eyebrow: "GOVERNANCE RECORDS", capability: "meeting.view", description: "Final resolution references are immutable. Circulation responses remain attributable.", empty: "No resolutions have been recorded." },
  compliance: { title: "Compliance", eyebrow: "REVIEW-LED ENGINE", capability: "compliance.view", description: "Recommendations remain linked to versioned official sources and professional review; the system never declares compliance by assumption.", empty: "No active compliance obligations are configured." },
  registrations: { title: "Company registrations", eyebrow: "CONTROLLED REGISTRY", capability: "registration.view", description: "Registration metadata, expiry information and evidence are held privately with masked identifiers by default.", empty: "No registration records are available to this role." },
  documents: { title: "Document Vault", eyebrow: "PRIVATE RECORDS", capability: "document.view", description: "Private-by-default documents use classification, versions, checksums, retention metadata and controlled delivery.", empty: "No documents are available to this role." },
  "statutory-registers": { title: "Statutory registers", eyebrow: "CONTROLLED REGISTERS", capability: "registration.view", description: "Enable each register definition only after professional confirmation of its applicability.", empty: "No statutory register definitions are enabled." },
  finance: { title: "Finance & tax", eyebrow: "RESTRICTED WORKSPACE", capability: "registration.view", description: "Financial records, tax metadata and supporting evidence are access-assigned rather than broadly visible.", empty: "No financial records are assigned to your role." },
  gst: { title: "GST workspace", eyebrow: "RESTRICTED WORKSPACE", capability: "compliance.view", description: "Registration, return periods, review status and filing evidence remain internal. Filed status requires evidence.", empty: "No GST records are configured." },
  auditor: { title: "Professional workspace", eyebrow: "ASSIGNED ACCESS", capability: "document.view", description: "CA, CS, auditor and legal work is assigned by scope and expiry—not by blanket access.", empty: "No professional requests are assigned to you." },
  ip: { title: "Intellectual property", eyebrow: "ASSET REGISTER", capability: "registration.view", description: "Trademarks, domains and other assets are tracked with evidence and renewal reminders.", empty: "No intellectual-property records are configured." },
  contracts: { title: "Contracts", eyebrow: "CONTROLLED REPOSITORY", capability: "document.view", description: "Agreements retain owner, dates, renewal timing, classification and signed evidence.", empty: "No contracts are available to this role." },
  disclosures: { title: "Public disclosure workflow", eyebrow: "PUBLICATION GATE", capability: "disclosure.review", description: "A public artifact is reviewed and approved separately; a private bucket is never made public by a status switch.", empty: "No disclosure publication requests are awaiting review." },
  privacy: { title: "Privacy governance", eyebrow: "DATA GOVERNANCE", capability: "compliance.view", description: "Data inventory, retention, legal holds and privacy requests support governed handling—not automated deletion.", empty: "No privacy governance records require attention." },
  security: { title: "Security administration", eyebrow: "RESTRICTED ADMINISTRATION", capability: "security.manage", description: "Access review, security events and high-risk controls are available only to authorised administrators.", empty: "No security events require action." },
  audit: { title: "Audit trail", eyebrow: "APPEND-ORIENTED EVIDENCE", capability: "audit.view", description: "Significant business actions are recorded without copying sensitive document content into audit metadata.", empty: "No audit events are available to this role." },
  settings: { title: "Corporate settings", eyebrow: "CONTROLLED CONFIGURATION", capability: "access.manage", description: "Company applicability, rule-review cadence, roles and retention policies require controlled changes and audit evidence.", empty: "No settings are available to this role." },
} as const satisfies Record<string, { title: string; eyebrow: string; capability: Capability; description: string; empty: string }>;

export type OfficeSection = keyof typeof officeSections;
export const officeNavigation = Object.entries(officeSections).map(([slug, item]) => ({ slug, title: item.title }));
