package com.kravia.companyos.platform;

public enum WorkflowType {
    BOARD_MEETING_APPROVAL,
    DOCUMENT_REVIEW,
    COMPLIANCE_SUBMISSION,
    TASK_ASSIGNMENT,
    PRODUCT_RELEASE_APPROVAL,
    PURCHASE_APPROVAL,
    VENDOR_ONBOARDING,
    EXPENSE_APPROVAL,
    CONTRACT_REVIEW,
    COMPLIANCE_FILING,
    LEAVE_APPROVAL,
    RECRUITMENT_APPROVAL,
    CUSTOMER_ONBOARDING,
    GENERAL
}