"use client";

import { FormEvent, useState } from "react";
import { FileUp, LoaderCircle, LockKeyhole } from "lucide-react";

export function DocumentUploadForm() {
  const [pending, setPending] = useState(false); const [status, setStatus] = useState<string>();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setStatus(undefined); try { const response = await fetch("/api/corporate/documents/upload", { method: "POST", body: new FormData(event.currentTarget) }); const result = await response.json() as { error?: string; id?: string }; if (!response.ok) { setStatus(result.error ?? "The document could not be uploaded."); return; } event.currentTarget.reset(); setStatus(`Private document ${result.id ?? ""} was uploaded as a draft. It is not public.`); } catch { setStatus("The document could not be uploaded. Please try again."); } finally { setPending(false); } }
  return <section className="content-studio"><header><div><p className="eyebrow">PRIVATE DOCUMENT VAULT</p><h2>Upload corporate evidence</h2><p>Files are validated, checksummed and stored in the private corporate bucket. Uploading never makes a document public.</p></div><LockKeyhole aria-hidden="true" /></header><form onSubmit={submit} className="content-studio-form"><label>Document title<input name="title" required maxLength={180} /></label><label>Category<input name="category" required maxLength={80} placeholder="Policy, Board, Registration…" /></label><label>Classification<select name="classification" defaultValue="CONFIDENTIAL"><option>INTERNAL</option><option>CONFIDENTIAL</option><option>HIGHLY_CONFIDENTIAL</option><option>DIRECTORS_ONLY</option><option>PROFESSIONAL_ASSIGNED</option></select></label><label className="content-wide">File<input name="file" required type="file" accept="application/pdf,image/png,image/jpeg,image/webp,.docx,.xlsx" /></label>{status ? <p className="content-status" role="status">{status}</p> : null}<button className="button button-dark" disabled={pending}>{pending ? <LoaderCircle className="spin" aria-hidden="true" /> : <FileUp aria-hidden="true" />}{pending ? "Uploading securely…" : "Upload to private vault"}</button></form></section>;
}
