"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, BookOpenText, CircleAlert, FileCheck2, LoaderCircle, Megaphone, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-knowledge-hub.module.css";

type Caps={policy_read:boolean;policy_manage:boolean;policy_publish:boolean;announcement_read:boolean;announcement_manage:boolean;knowledge_read:boolean;knowledge_manage:boolean;knowledge_publish:boolean};
type Person={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null};
type Policy={id:string;policy_code:string;title:string;category:string;audience_type:string;audience_key?:string|null;acknowledgement_required:boolean;owner_user_id:string;current_version?:number|null;status:string;created_by:string};
type PolicyVersion={id:string;policy_id:string;version:number;content_text:string;effective_on?:string|null;change_summary?:string|null;status:string;created_by:string;published_by?:string|null;published_at?:string|null;content_sha256:string};
type Ack={policy_version_id:string;user_id:string;acknowledged_at:string};
type Announcement={id:string;announcement_code:string;title:string;body_text:string;announcement_type:string;audience_type:string;audience_key?:string|null;requires_ack:boolean;priority:string;status:string;published_at?:string|null;expires_at?:string|null;created_by:string};
type Receipt={announcement_id:string;user_id:string;read_at:string;acknowledged_at?:string|null};
type Article={id:string;article_code:string;title:string;category:string;audience_type:string;audience_key?:string|null;owner_user_id:string;current_version?:number|null;status:string;created_by:string};
type ArticleVersion={id:string;article_id:string;version:number;content_text:string;change_summary?:string|null;status:string;created_by:string;published_by?:string|null;published_at?:string|null;content_sha256:string};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};capabilities:Caps;policies:Policy[];policy_versions:PolicyVersion[];policy_acknowledgements:Ack[];announcements:Announcement[];announcement_receipts:Receipt[];articles:Article[];article_versions:ArticleVersion[];people:Person[];disclaimer:string};
type View="policies"|"announcements"|"knowledge";
type Modal={kind:"POLICY"}|{kind:"POLICY_VERSION";policy:Policy}|{kind:"ANNOUNCEMENT"}|{kind:"KNOWLEDGE"}|{kind:"KNOWLEDGE_VERSION";article:Article};

async function api<T>(options?:RequestInit):Promise<T>{const r=await fetch("/api/office-knowledge",{...options,cache:"no-store",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Knowledge Hub action failed");return b as T}
function date(v?:string|null){if(!v)return "—";const d=new Date(v.length===10?v+"T00:00:00":v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:v.length>10?"short":undefined}).format(d)}

export function OfficeKnowledgeHub(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("policies");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();const[query,setQuery]=useState("");
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive)setData(n)}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load Knowledge Hub")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(p=>[p.user_id,p])),[data?.people]);
 const policyVersions=useMemo(()=>{const map=new Map<string,PolicyVersion[]>();for(const v of data?.policy_versions??[]){const a=map.get(v.policy_id)||[];a.push(v);map.set(v.policy_id,a)}return map},[data?.policy_versions]);
 const articleVersions=useMemo(()=>{const map=new Map<string,ArticleVersion[]>();for(const v of data?.article_versions??[]){const a=map.get(v.article_id)||[];a.push(v);map.set(v.article_id,a)}return map},[data?.article_versions]);
 const acked=useMemo(()=>new Set((data?.policy_acknowledgements??[]).map(a=>a.policy_version_id)),[data?.policy_acknowledgements]);
 const receipts=useMemo(()=>new Map((data?.announcement_receipts??[]).map(a=>[a.announcement_id,a])),[data?.announcement_receipts]);
 const q=query.trim().toLowerCase();

 async function act(body:unknown,message:string){setBusy(true);setError(undefined);try{await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await reload(message)}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="POLICY")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_POLICY",title:draft.title,category:draft.category||"OTHER",audience_type:draft.audience_type||"COMPANY",audience_key:draft.audience_type==="COMPANY"?undefined:draft.audience_key,acknowledgement_required:draft.ack!=="NO",owner_user_id:draft.owner_user_id,content:draft.content,effective_on:draft.effective_on||undefined,change_summary:draft.change_summary||undefined})});
  else if(modal.kind==="POLICY_VERSION")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"NEW_POLICY_VERSION",policy_id:modal.policy.id,content:draft.content,effective_on:draft.effective_on||undefined,change_summary:draft.change_summary||undefined})});
  else if(modal.kind==="ANNOUNCEMENT")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_ANNOUNCEMENT",title:draft.title,body:draft.body,announcement_type:draft.announcement_type||"GENERAL",audience_type:draft.audience_type||"COMPANY",audience_key:draft.audience_type==="COMPANY"?undefined:draft.audience_key,requires_ack:draft.ack==="YES",priority:draft.priority||"NORMAL",expires_at:draft.expires_at?new Date(draft.expires_at).toISOString():undefined})});
  else if(modal.kind==="KNOWLEDGE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_KNOWLEDGE",title:draft.title,category:draft.category||"SOP",audience_type:draft.audience_type||"COMPANY",audience_key:draft.audience_type==="COMPANY"?undefined:draft.audience_key,owner_user_id:draft.owner_user_id,content:draft.content,change_summary:draft.change_summary||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"NEW_KNOWLEDGE_VERSION",article_id:modal.article.id,content:draft.content,change_summary:draft.change_summary||undefined})});
  await reload("Knowledge Hub updated.");setModal(undefined);setDraft({});
 }catch(e){setError(e instanceof Error?e.message:"Knowledge Hub action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Knowledge Hub unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading Knowledge Hub</h2></div></section>;
 const pendingPolicies=data.policies.filter(p=>{const pub=(policyVersions.get(p.id)||[]).find(v=>v.status==="PUBLISHED");return Boolean(pub&&p.acknowledgement_required&&!acked.has(pub.id))}).length;
 const unreadAnnouncements=data.announcements.filter(a=>!receipts.has(a.id)).length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>POLICY · ANNOUNCEMENTS · KNOWLEDGE</p><h2>One internal source for rules, updates, SOPs and runbooks.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{pendingPolicies}</b><span>policy acknowledgements due</span></article><article><b>{unreadAnnouncements}</b><span>unread announcements</span></article><article><b>{data.articles.filter(a=>a.status==="PUBLISHED").length}</b><span>published articles</span></article></div></header>
  <div className={styles.toolbar}>{(["policies","announcements","knowledge"] as View[]).map(v=><button key={v} type="button" data-active={view===v} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}<input aria-label="Search Knowledge Hub" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="policies"&&data.capabilities.policy_manage?<button type="button" onClick={()=>{setDraft({category:"OTHER",audience_type:"COMPANY",ack:"YES"});setModal({kind:"POLICY"})}}><Plus/>New policy</button>:null}{view==="announcements"&&data.capabilities.announcement_manage?<button type="button" onClick={()=>{setDraft({announcement_type:"GENERAL",audience_type:"COMPANY",ack:"NO",priority:"NORMAL"});setModal({kind:"ANNOUNCEMENT"})}}><Plus/>New announcement</button>:null}{view==="knowledge"&&data.capabilities.knowledge_manage?<button type="button" onClick={()=>{setDraft({category:"SOP",audience_type:"COMPANY"});setModal({kind:"KNOWLEDGE"})}}><Plus/>New article</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="policies"?<div className={styles.grid}>{data.policies.filter(p=>!q||p.title.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)).map(p=>{const versions=policyVersions.get(p.id)||[];const pub=versions.find(v=>v.status==="PUBLISHED");return <article className={styles.card} key={p.id}><header><div><small>{p.policy_code} · {p.category}</small><h3>{p.title}</h3><span>{p.audience_type}{p.audience_key?" · "+p.audience_key:""} · owner {people.get(p.owner_user_id)?.display_name||p.owner_user_id}</span></div><em className={styles.badge} data-status={p.status}>{p.status}</em></header>{pub?<><p className={styles.content}>{pub.content_text}</p><div className={styles.kv}><span>Version<b>{pub.version}</b></span><span>Effective<b>{date(pub.effective_on)}</b></span><span>Published<b>{date(pub.published_at)}</b></span><span>SHA-256<b>{pub.content_sha256.slice(0,16)}…</b></span></div>{p.acknowledgement_required&&!acked.has(pub.id)?<button type="button" disabled={busy} onClick={()=>void act({action:"ACK_POLICY",version_id:pub.id},"Policy acknowledged.")}><FileCheck2/>Acknowledge current version</button>:p.acknowledgement_required?<span className={styles.done}><BadgeCheck/>Acknowledged</span>:null}</>:<p>No published version yet.</p>}<div className={styles.actions}>{data.capabilities.policy_manage?<button type="button" onClick={()=>{setDraft({content:pub?.content_text||"",effective_on:"",change_summary:""});setModal({kind:"POLICY_VERSION",policy:p})}}>New version</button>:null}{data.capabilities.policy_publish?versions.filter(v=>v.status==="DRAFT"&&v.created_by!==data.actor.user_id).map(v=><button key={v.id} type="button" disabled={busy} onClick={()=>void act({action:"PUBLISH_POLICY",version_id:v.id},"Policy version published.")}><ShieldCheck/>Publish v{v.version}</button>):null}</div></article>})}{!data.policies.length?<div className={styles.empty}>No policies in your audience.</div>:null}</div>:null}

  {view==="announcements"?<div className={styles.grid}>{data.announcements.filter(a=>!q||a.title.toLowerCase().includes(q)||a.body_text.toLowerCase().includes(q)).map(a=>{const r=receipts.get(a.id);return <article className={styles.card} key={a.id}><header><div><small>{a.announcement_code} · {a.announcement_type}</small><h3>{a.title}</h3><span>{date(a.published_at)} · {a.priority}</span></div><em className={styles.badge} data-status={a.priority}>{a.priority}</em></header><p className={styles.content}>{a.body_text}</p><div className={styles.actions}>{!r?<button type="button" disabled={busy} onClick={()=>void act({action:"ANNOUNCEMENT_RECEIPT",announcement_id:a.id,acknowledged:a.requires_ack},a.requires_ack?"Announcement acknowledged.":"Announcement marked read.")}>{a.requires_ack?<FileCheck2/>:<Megaphone/>}{a.requires_ack?"Acknowledge":"Mark read"}</button>:<span className={styles.done}><BadgeCheck/>{r.acknowledged_at?"Acknowledged":"Read"}</span>}</div></article>})}{!data.announcements.length?<div className={styles.empty}>No active announcements in your audience.</div>:null}</div>:null}

  {view==="knowledge"?<div className={styles.grid}>{data.articles.filter(a=>!q||a.title.toLowerCase().includes(q)||a.category.toLowerCase().includes(q)).map(a=>{const versions=articleVersions.get(a.id)||[];const pub=versions.find(v=>v.status==="PUBLISHED");return <article className={styles.card} key={a.id}><header><div><small>{a.article_code} · {a.category}</small><h3>{a.title}</h3><span>{a.audience_type}{a.audience_key?" · "+a.audience_key:""} · owner {people.get(a.owner_user_id)?.display_name||a.owner_user_id}</span></div><em className={styles.badge} data-status={a.status}>{a.status}</em></header>{pub?<><p className={styles.content}>{pub.content_text}</p><div className={styles.kv}><span>Version<b>{pub.version}</b></span><span>Published<b>{date(pub.published_at)}</b></span><span>SHA-256<b>{pub.content_sha256.slice(0,16)}…</b></span></div></>:<p>No published version yet.</p>}<div className={styles.actions}>{data.capabilities.knowledge_manage?<button type="button" onClick={()=>{setDraft({content:pub?.content_text||"",change_summary:""});setModal({kind:"KNOWLEDGE_VERSION",article:a})}}>New version</button>:null}{data.capabilities.knowledge_publish?versions.filter(v=>v.status==="DRAFT"&&v.created_by!==data.actor.user_id).map(v=><button key={v.id} type="button" disabled={busy} onClick={()=>void act({action:"PUBLISH_KNOWLEDGE",version_id:v.id},"Knowledge version published.")}><BookOpenText/>Publish v{v.version}</button>):null}</div></article>})}{!data.articles.length?<div className={styles.empty}>No published knowledge in your audience.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED KNOWLEDGE ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="POLICY"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Category<select value={draft.category||"OTHER"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["GOVERNANCE","HR","SECURITY","PRIVACY","FINANCE","PROCUREMENT","LEGAL","ENGINEERING","AI","REMOTE_WORK","ATTENDANCE","LEAVE","ETHICS","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><Audience draft={draft} setDraft={setDraft}/><label>Acknowledgement required<select value={draft.ack||"YES"} onChange={e=>setDraft({...draft,ack:e.target.value})}><option>YES</option><option>NO</option></select></label><label>Policy text<textarea required minLength={10} value={draft.content||""} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label>Effective date<input type="date" value={draft.effective_on||""} onChange={e=>setDraft({...draft,effective_on:e.target.value})}/></label><label>Change summary<textarea value={draft.change_summary||""} onChange={e=>setDraft({...draft,change_summary:e.target.value})}/></label></>
   :modal.kind==="POLICY_VERSION"?<><p>New immutable version of <b>{modal.policy.title}</b>.</p><label>Policy text<textarea required minLength={10} value={draft.content||""} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label>Effective date<input type="date" value={draft.effective_on||""} onChange={e=>setDraft({...draft,effective_on:e.target.value})}/></label><label>Change summary<textarea value={draft.change_summary||""} onChange={e=>setDraft({...draft,change_summary:e.target.value})}/></label></>
   :modal.kind==="ANNOUNCEMENT"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Type<select value={draft.announcement_type||"GENERAL"} onChange={e=>setDraft({...draft,announcement_type:e.target.value})}>{["GENERAL","POLICY","SECURITY_ALERT","HOLIDAY","OFFICE","PRODUCT","EMERGENCY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select value={draft.priority||"NORMAL"} onChange={e=>setDraft({...draft,priority:e.target.value})}>{["LOW","NORMAL","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><Audience draft={draft} setDraft={setDraft}/><label>Body<textarea required minLength={3} value={draft.body||""} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><div className={styles.two}><label>Requires acknowledgement<select value={draft.ack||"NO"} onChange={e=>setDraft({...draft,ack:e.target.value})}><option>NO</option><option>YES</option></select></label><label>Expires<input type="datetime-local" value={draft.expires_at||""} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></label></div></>
   :modal.kind==="KNOWLEDGE"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Category<select value={draft.category||"SOP"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["SOP","RUNBOOK","ARCHITECTURE","HANDBOOK","PRODUCT","SECURITY","FINANCE","HR","LEGAL","SUPPORT","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><Audience draft={draft} setDraft={setDraft}/><label>Content<textarea required minLength={10} value={draft.content||""} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label>Change summary<textarea value={draft.change_summary||""} onChange={e=>setDraft({...draft,change_summary:e.target.value})}/></label></>
   :<><p>New immutable version of <b>{modal.article.title}</b>.</p><label>Content<textarea required minLength={10} value={draft.content||""} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label>Change summary<textarea value={draft.change_summary||""} onChange={e=>setDraft({...draft,change_summary:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Save</button></footer>
  </form></div>:null}
 </section>;
}

function Audience({draft,setDraft}:{draft:Record<string,string>;setDraft:(next:Record<string,string>)=>void}){
 return <div className={styles.two}><label>Audience<select value={draft.audience_type||"COMPANY"} onChange={e=>setDraft({...draft,audience_type:e.target.value,audience_key:""})}><option>COMPANY</option><option>DEPARTMENT</option><option>ROLE</option></select></label>{draft.audience_type&&draft.audience_type!=="COMPANY"?<label>Audience key<input required value={draft.audience_key||""} onChange={e=>setDraft({...draft,audience_key:e.target.value.toUpperCase()})}/></label>:<span/>}</div>;
}
