"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, CreditCard, FileCheck2, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-corporate-cards.module.css";

type Caps={read:boolean;manage:boolean;review:boolean;spend_request:boolean;spend_review:boolean};
type Person={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null};
type Card={id:string;card_code:string;issuer_name:string;issuer_account_reference?:string|null;issuer_card_reference?:string|null;last4:string;card_type:string;cardholder_user_id:string;department_code?:string|null;cost_center?:string|null;currency:string;per_transaction_limit_minor?:number|null;monthly_limit_minor?:number|null;allowed_merchant_categories:string[];online_allowed:boolean;international_allowed:boolean;atm_allowed:boolean;valid_through_month?:number|null;valid_through_year?:number|null;status:string;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;review_note?:string|null};
type Spend={id:string;request_code:string;card_id:string;requester_user_id:string;merchant_or_purpose:string;merchant_category?:string|null;amount_minor:number;currency:string;project_reference?:string|null;expense_reference?:string|null;needed_by?:string|null;status:string;reviewer_user_id?:string|null;reviewed_at?:string|null;review_note?:string|null;issuer_transaction_reference?:string|null;receipt_reference?:string|null;used_at?:string|null;created_at:string};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};scope:{type?:string|null;key?:string|null};capabilities:Caps;cards:Card[];spend_requests:Spend[];people:Person[];disclaimer:string};
type View="cards"|"spend";
type Modal=
 |{kind:"CARD"}
 |{kind:"CARD_REVIEW";card:Card}
 |{kind:"SPEND";card?:Card}
 |{kind:"SPEND_REVIEW";spend:Spend}
 |{kind:"USED";spend:Spend};

async function api<T>(options?:RequestInit):Promise<T>{
 const r=await fetch("/api/office-corporate-cards",{...options,cache:"no-store",credentials:"same-origin"});
 const b=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Corporate-card operation failed");
 return b as T;
}
function date(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function money(minor?:number|null,currency="INR"){if(minor==null)return "—";return currency+" "+(minor/100).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function categories(v?:string){return (v||"").split(",").map(x=>x.trim().toUpperCase()).filter(Boolean)}
function toIso(v?:string){if(!v)return undefined;const d=new Date(v);return Number.isNaN(d.getTime())?undefined:d.toISOString()}

export function OfficeCorporateCards(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("cards");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive)setData(n)}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load corporate cards")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(p=>[p.user_id,p])),[data?.people]);
 const cards=useMemo(()=>new Map((data?.cards??[]).map(c=>[c.id,c])),[data?.cards]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="CARD")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_CARD",issuer:draft.issuer,account_reference:draft.account_reference||undefined,card_reference:draft.card_reference||undefined,last4:draft.last4,card_type:draft.card_type||"PHYSICAL",holder_user_id:draft.holder_user_id,department:draft.department||undefined,cost_center:draft.cost_center||undefined,currency:draft.currency||"INR",per_transaction_limit_minor:draft.per_limit?Math.round(Number(draft.per_limit)*100):undefined,monthly_limit_minor:draft.monthly_limit?Math.round(Number(draft.monthly_limit)*100):undefined,allowed_merchant_categories:categories(draft.categories),online_allowed:draft.online!=="NO",international_allowed:draft.international==="YES",atm_allowed:draft.atm==="YES",valid_through_month:draft.month?Number(draft.month):undefined,valid_through_year:draft.year?Number(draft.year):undefined})});
  else if(modal.kind==="CARD_REVIEW")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_CARD",card_id:modal.card.id,status:draft.status,per_transaction_limit_minor:draft.per_limit?Math.round(Number(draft.per_limit)*100):undefined,monthly_limit_minor:draft.monthly_limit?Math.round(Number(draft.monthly_limit)*100):undefined,allowed_merchant_categories:categories(draft.categories),online_allowed:draft.online!=="NO",international_allowed:draft.international==="YES",atm_allowed:draft.atm==="YES",note:draft.note||undefined})});
  else if(modal.kind==="SPEND")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REQUEST_SPEND",card_id:draft.card_id||modal.card?.id,purpose:draft.purpose,merchant_category:draft.category||undefined,amount_minor:Math.round(Number(draft.amount)*100),currency:draft.currency||modal.card?.currency||"INR",project_reference:draft.project_reference||undefined,expense_reference:draft.expense_reference||undefined,needed_by:toIso(draft.needed_by)})});
  else if(modal.kind==="SPEND_REVIEW")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_SPEND",request_id:modal.spend.id,status:draft.status,note:draft.note||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"MARK_USED",request_id:modal.spend.id,transaction_reference:draft.transaction_reference,receipt_reference:draft.receipt_reference})});
  await reload("Corporate-card record updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Corporate-card action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Corporate cards unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading corporate cards</h2></div></section>;
 const active=data.cards.filter(c=>c.status==="ACTIVE").length;
 const requested=data.spend_requests.filter(s=>s.status==="REQUESTED").length;
 const approved=data.spend_requests.filter(s=>s.status==="APPROVED").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>CORPORATE CARDS · SPEND CONTROL</p><h2>Control company-card spend without storing card secrets or bypassing finance review.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{active}</b><span>active cards</span></article><article><b>{requested}</b><span>spend requests</span></article><article><b>{approved}</b><span>approved not used</span></article></div></header>
  <div className={styles.warning}><CreditCard/><div><b>Masked registry only</b><span>Only last four digits and issuer references are stored. KRAVIA never asks for a full card number, CVV, PIN or issuer card token.</span></div></div>
  <div className={styles.toolbar}><button type="button" data-active={view==="cards"} onClick={()=>setView("cards")}>Cards</button><button type="button" data-active={view==="spend"} onClick={()=>setView("spend")}>Spend requests</button><button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="cards"&&data.capabilities.manage?<button type="button" onClick={()=>{setDraft({card_type:"PHYSICAL",currency:"INR",online:"YES",international:"NO",atm:"NO"});setModal({kind:"CARD"})}}><Plus/>Add card record</button>:null}{view==="spend"&&data.capabilities.spend_request&&data.cards.some(c=>c.cardholder_user_id===data.actor.user_id&&c.status==="ACTIVE")?<button type="button" onClick={()=>{setDraft({});setModal({kind:"SPEND"})}}><Plus/>Request spend</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="cards"?<div className={styles.grid}>{data.cards.map(card=><article className={styles.card} key={card.id}><header><div><small>{card.card_code} · {card.issuer_name}</small><h3>•••• {card.last4}</h3><span>{card.card_type} · {card.currency}</span></div><em className={styles.badge} data-status={card.status}>{card.status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Cardholder<b>{people.get(card.cardholder_user_id)?.display_name||(card.cardholder_user_id===data.actor.user_id?"You":card.cardholder_user_id)}</b></span><span>Per transaction<b>{money(card.per_transaction_limit_minor,card.currency)}</b></span><span>Monthly limit<b>{money(card.monthly_limit_minor,card.currency)}</b></span><span>Cost center<b>{card.cost_center||"—"}</b></span><span>Online<b>{card.online_allowed?"Allowed":"Blocked"}</b></span><span>International<b>{card.international_allowed?"Allowed":"Blocked"}</b></span><span>ATM<b>{card.atm_allowed?"Allowed":"Blocked"}</b></span><span>Valid through<b>{card.valid_through_month&&card.valid_through_year?String(card.valid_through_month).padStart(2,"0")+"/"+card.valid_through_year:"—"}</b></span></div><div className={styles.tags}>{card.allowed_merchant_categories.length?card.allowed_merchant_categories.map(x=><span key={x}>{x}</span>):<span>All categories require reviewer judgement</span>}</div><div className={styles.actions}>{data.capabilities.review&&card.cardholder_user_id!==data.actor.user_id&&card.created_by!==data.actor.user_id&&card.status!=="CLOSED"?<button type="button" onClick={()=>{setDraft({status:card.status==="PENDING_REVIEW"?"ACTIVE":card.status,per_limit:card.per_transaction_limit_minor!=null?String(card.per_transaction_limit_minor/100):"",monthly_limit:card.monthly_limit_minor!=null?String(card.monthly_limit_minor/100):"",categories:card.allowed_merchant_categories.join(","),online:card.online_allowed?"YES":"NO",international:card.international_allowed?"YES":"NO",atm:card.atm_allowed?"YES":"NO",note:card.review_note||""});setModal({kind:"CARD_REVIEW",card})}}><ShieldCheck/>Review controls</button>:null}{data.capabilities.spend_request&&card.cardholder_user_id===data.actor.user_id&&card.status==="ACTIVE"?<button type="button" onClick={()=>{setDraft({card_id:card.id,currency:card.currency});setModal({kind:"SPEND",card})}}>Request spend</button>:null}</div></article>)}{!data.cards.length?<div className={styles.empty}>No corporate-card records in your scope.</div>:null}</div>:null}

  {view==="spend"?<div className={styles.grid}>{data.spend_requests.map(spend=>{const card=cards.get(spend.card_id);return <article className={styles.card} key={spend.id}><header><div><small>{spend.request_code} · {card?card.issuer_name+" •••• "+card.last4:"Corporate card"}</small><h3>{spend.merchant_or_purpose}</h3><span>{money(spend.amount_minor,spend.currency)}{spend.merchant_category?" · "+spend.merchant_category:""}</span></div><em className={styles.badge} data-status={spend.status}>{spend.status}</em></header><div className={styles.kv}><span>Requester<b>{spend.requester_user_id===data.actor.user_id?"You":people.get(spend.requester_user_id)?.display_name||spend.requester_user_id}</b></span><span>Needed by<b>{date(spend.needed_by)}</b></span><span>Project ref<b>{spend.project_reference||"—"}</b></span><span>Expense ref<b>{spend.expense_reference||"—"}</b></span><span>Issuer transaction<b>{spend.issuer_transaction_reference||"—"}</b></span><span>Receipt<b>{spend.receipt_reference||"—"}</b></span></div>{spend.review_note?<p><b>Review note:</b> {spend.review_note}</p>:null}<div className={styles.actions}>{spend.status==="REQUESTED"&&data.capabilities.spend_review&&spend.requester_user_id!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({status:"APPROVED",note:""});setModal({kind:"SPEND_REVIEW",spend})}}><ShieldCheck/>Review spend</button>:null}{spend.status==="APPROVED"&&spend.requester_user_id===data.actor.user_id?<button type="button" onClick={()=>{setDraft({});setModal({kind:"USED",spend})}}><FileCheck2/>Record used transaction</button>:null}</div></article>})}{!data.spend_requests.length?<div className={styles.empty}>No corporate-card spend requests in your scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED CORPORATE-CARD ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="CARD"?<><div className={styles.two}><label>Issuer<input required minLength={2} value={draft.issuer||""} onChange={e=>setDraft({...draft,issuer:e.target.value})}/></label><label>Last four digits<input required inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={draft.last4||""} onChange={e=>setDraft({...draft,last4:e.target.value.replace(/\D/g,"").slice(0,4)})}/></label></div><p className={styles.muted}>Do not enter a full card number, CVV, PIN or issuer token.</p><div className={styles.two}><label>Issuer account reference<input value={draft.account_reference||""} onChange={e=>setDraft({...draft,account_reference:e.target.value})}/></label><label>Issuer card reference<input value={draft.card_reference||""} onChange={e=>setDraft({...draft,card_reference:e.target.value})}/></label></div><label>Cardholder<select required value={draft.holder_user_id||""} onChange={e=>setDraft({...draft,holder_user_id:e.target.value})}><option value="">Select cardholder</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><div className={styles.three}><label>Card type<select value={draft.card_type||"PHYSICAL"} onChange={e=>setDraft({...draft,card_type:e.target.value})}><option>PHYSICAL</option><option>VIRTUAL</option></select></label><label>Currency<input required maxLength={3} value={draft.currency||"INR"} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label><label>Cost center<input value={draft.cost_center||""} onChange={e=>setDraft({...draft,cost_center:e.target.value})}/></label></div><div className={styles.two}><label>Per-transaction limit<input inputMode="decimal" value={draft.per_limit||""} onChange={e=>setDraft({...draft,per_limit:e.target.value})}/></label><label>Monthly limit<input inputMode="decimal" value={draft.monthly_limit||""} onChange={e=>setDraft({...draft,monthly_limit:e.target.value})}/></label></div><label>Allowed merchant categories — comma separated<input value={draft.categories||""} onChange={e=>setDraft({...draft,categories:e.target.value})}/></label><div className={styles.three}><label>Online<select value={draft.online||"YES"} onChange={e=>setDraft({...draft,online:e.target.value})}><option>YES</option><option>NO</option></select></label><label>International<select value={draft.international||"NO"} onChange={e=>setDraft({...draft,international:e.target.value})}><option>YES</option><option>NO</option></select></label><label>ATM<select value={draft.atm||"NO"} onChange={e=>setDraft({...draft,atm:e.target.value})}><option>YES</option><option>NO</option></select></label></div><div className={styles.two}><label>Valid-through month<input type="number" min="1" max="12" value={draft.month||""} onChange={e=>setDraft({...draft,month:e.target.value})}/></label><label>Valid-through year<input type="number" min="2020" max="2200" value={draft.year||""} onChange={e=>setDraft({...draft,year:e.target.value})}/></label></div></>
   :modal.kind==="CARD_REVIEW"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{modal.card.status==="PENDING_REVIEW"?<option>ACTIVE</option>:<>{["ACTIVE","FROZEN","REISSUE_PENDING","CLOSED"].map(v=><option key={v}>{v}</option>)}</>}</select></label><div className={styles.two}><label>Per-transaction limit<input required={draft.status==="ACTIVE"} inputMode="decimal" value={draft.per_limit||""} onChange={e=>setDraft({...draft,per_limit:e.target.value})}/></label><label>Monthly limit<input required={draft.status==="ACTIVE"} inputMode="decimal" value={draft.monthly_limit||""} onChange={e=>setDraft({...draft,monthly_limit:e.target.value})}/></label></div><label>Allowed merchant categories<input value={draft.categories||""} onChange={e=>setDraft({...draft,categories:e.target.value})}/></label><div className={styles.three}><label>Online<select value={draft.online||"YES"} onChange={e=>setDraft({...draft,online:e.target.value})}><option>YES</option><option>NO</option></select></label><label>International<select value={draft.international||"NO"} onChange={e=>setDraft({...draft,international:e.target.value})}><option>YES</option><option>NO</option></select></label><label>ATM<select value={draft.atm||"NO"} onChange={e=>setDraft({...draft,atm:e.target.value})}><option>YES</option><option>NO</option></select></label></div><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="SPEND"?<><label>Assigned card<select required value={draft.card_id||modal.card?.id||""} onChange={e=>{const card=cards.get(e.target.value);setDraft({...draft,card_id:e.target.value,currency:card?.currency||draft.currency})}}><option value="">Select active assigned card</option>{data.cards.filter(c=>c.cardholder_user_id===data.actor.user_id&&c.status==="ACTIVE").map(c=><option key={c.id} value={c.id}>{c.issuer_name} · •••• {c.last4}</option>)}</select></label><label>Merchant / purpose<input required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><div className={styles.two}><label>Amount<input required inputMode="decimal" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Currency<input readOnly value={draft.currency||modal.card?.currency||"INR"}/></label></div><label>Merchant category<input value={draft.category||""} onChange={e=>setDraft({...draft,category:e.target.value.toUpperCase()})}/></label><div className={styles.two}><label>Project reference<input value={draft.project_reference||""} onChange={e=>setDraft({...draft,project_reference:e.target.value})}/></label><label>Expense reference<input value={draft.expense_reference||""} onChange={e=>setDraft({...draft,expense_reference:e.target.value})}/></label></div><label>Needed by<input type="datetime-local" value={draft.needed_by||""} onChange={e=>setDraft({...draft,needed_by:e.target.value})}/></label></>
   :modal.kind==="SPEND_REVIEW"?<><label>Decision<select value={draft.status||"APPROVED"} onChange={e=>setDraft({...draft,status:e.target.value})}><option>APPROVED</option><option>REJECTED</option></select></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :<><p>Record evidence for an issuer-side card transaction. KRAVIA will not execute the transaction.</p><label>Issuer transaction reference<input required minLength={3} value={draft.transaction_reference||""} onChange={e=>setDraft({...draft,transaction_reference:e.target.value})}/></label><label>Receipt reference<input required minLength={3} value={draft.receipt_reference||""} onChange={e=>setDraft({...draft,receipt_reference:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
