"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CalendarDays, CircleAlert, DoorOpen, LoaderCircle, Plus, RefreshCw, ShieldCheck, UserRoundCheck, Wrench, X } from "lucide-react";
import styles from "./office-physical-office.module.css";

type Capabilities={room_read:boolean;room_book:boolean;visitor_invite:boolean;visitor_manage:boolean;issue_report:boolean;facilities_manage:boolean};
type Site={id:string;site_code:string;name:string;address_text?:string|null;timezone_name:string;status:string};
type Room={id:string;site_id:string;room_code:string;name:string;room_type:string;capacity:number;physical_zone_id?:string|null;status:string};
type Booking={id:string;room_id:string;organizer_user_id:string;title:string;purpose?:string|null;visibility:string;starts_at:string;ends_at:string;status:string;cancellation_reason?:string|null};
type Visitor={id:string;visitor_code:string;site_id:string;host_user_id:string;full_name:string;email?:string|null;phone?:string|null;organization?:string|null;purpose:string;scheduled_from:string;scheduled_to:string;status:string;review_note?:string|null;checked_in_at?:string|null;checked_out_at?:string|null};
type Incident={id:string;site_id:string;room_id?:string|null;reporter_user_id:string;owner_user_id?:string|null;category:string;priority:string;title:string;description:string;status:string;resolution?:string|null;created_at:string};
type Identity={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null;status:string};
type Credential={id:string;visitor_id:string;status:string;issued_at:string;expires_at:string};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};capabilities:Capabilities;sites:Site[];rooms:Room[];bookings:Booking[];visitors:Visitor[];incidents:Incident[];identities:Identity[];credentials:Credential[];disclaimer:string};
type View="rooms"|"visitors"|"issues";
type Modal=
 |{kind:"BOOK";room:Room}
 |{kind:"CANCEL";booking:Booking}
 |{kind:"INVITE"}
 |{kind:"REVIEW";visitor:Visitor;decision:"APPROVED"|"DENIED"}
 |{kind:"CREDENTIAL";visitor:Visitor}
 |{kind:"CHECKIN";visitor:Visitor}
 |{kind:"CHECKOUT";visitor:Visitor}
 |{kind:"ISSUE"}
 |{kind:"TRANSITION";incident:Incident};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-facilities",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Physical Office request failed");
 return body as T;
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function toIso(value?:string){if(!value)return undefined;const d=new Date(value);return Number.isNaN(d.getTime())?undefined:d.toISOString()}

export function OfficePhysicalOffice(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("rooms");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();const[oneTimeToken,setOneTimeToken]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load Physical Office")});return()=>{alive=false}},[]);
 const sites=useMemo(()=>new Map((data?.sites??[]).map(row=>[row.id,row])),[data?.sites]);
 const rooms=useMemo(()=>new Map((data?.rooms??[]).map(row=>[row.id,row])),[data?.rooms]);
 const people=useMemo(()=>new Map((data?.identities??[]).map(row=>[row.user_id,row])),[data?.identities]);
 const activeCredential=useMemo(()=>{const map=new Map<string,Credential>();for(const row of data?.credentials??[])if(row.status==="ACTIVE"&&!map.has(row.visitor_id))map.set(row.visitor_id,row);return map},[data?.credentials]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);setOneTimeToken(undefined);try{
  if(modal.kind==="BOOK")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"BOOK_ROOM",room_id:modal.room.id,title:draft.title,purpose:draft.purpose||undefined,visibility:draft.visibility||"INTERNAL",starts_at:toIso(draft.starts_at),ends_at:toIso(draft.ends_at)})});
  else if(modal.kind==="CANCEL")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CANCEL_BOOKING",booking_id:modal.booking.id,reason:draft.reason})});
  else if(modal.kind==="INVITE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"INVITE_VISITOR",site_id:draft.site_id,name:draft.name,email:draft.email||undefined,phone:draft.phone||undefined,organization:draft.organization||undefined,purpose:draft.purpose,starts_at:toIso(draft.starts_at),ends_at:toIso(draft.ends_at)})});
  else if(modal.kind==="REVIEW")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_VISITOR",visitor_id:modal.visitor.id,decision:modal.decision,note:draft.note||undefined})});
  else if(modal.kind==="CREDENTIAL"){const result=await api<{credential_token:string}>({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ISSUE_VISITOR_CREDENTIAL",visitor_id:modal.visitor.id,expires_at:toIso(draft.expires_at)})});setOneTimeToken(result.credential_token);await reload("Temporary visitor credential issued. Copy it now; KRAVIA stores only its SHA-256 hash.");setModal(undefined);setDraft({});return}
  else if(modal.kind==="CHECKIN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CHECK_IN_VISITOR",visitor_id:modal.visitor.id})});
  else if(modal.kind==="CHECKOUT")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CHECK_OUT_VISITOR",visitor_id:modal.visitor.id})});
  else if(modal.kind==="ISSUE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REPORT_FACILITY_ISSUE",site_id:draft.site_id,room_id:draft.room_id||undefined,category:draft.category||"OTHER",priority:draft.priority||"NORMAL",title:draft.title,description:draft.description})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_FACILITY_ISSUE",incident_id:modal.incident.id,status:draft.status,owner_user_id:draft.owner_user_id||undefined,note:draft.note||undefined})});
  await reload("Physical Office operation updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Physical Office action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Physical Office unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading Physical Office</h2><p>Resolving facilities and visitor authority.</p></div></section>;
 const liveBookings=data.bookings.filter(row=>row.status==="BOOKED"&&new Date(row.ends_at).getTime()>Date.now()).length;
 const checkedIn=data.visitors.filter(row=>row.status==="CHECKED_IN").length;
 const openIssues=data.incidents.filter(row=>!["RESOLVED","CLOSED","CANCELLED"].includes(row.status)).length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>PHYSICAL OFFICE · ROOMS · VISITORS · FACILITIES</p><h2>Run office access and facility operations without leaving KRAVIA.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{liveBookings}</b><span>active bookings</span></article><article><b>{checkedIn}</b><span>visitors onsite</span></article><article><b>{openIssues}</b><span>open issues</span></article></div></header>
  <div className={styles.toolbar}>
   {(["rooms","visitors","issues"] as View[]).map(item=><button type="button" key={item} data-active={view===item} onClick={()=>setView(item)}>{item==="rooms"?"Rooms":item==="visitors"?"Visitors":"Facilities"}</button>)}
   <button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>
   {view==="visitors"&&data.capabilities.visitor_invite?<button type="button" onClick={()=>{setDraft({});setModal({kind:"INVITE"})}}><Plus/>Invite visitor</button>:null}
   {view==="issues"&&data.capabilities.issue_report?<button type="button" onClick={()=>{setDraft({category:"OTHER",priority:"NORMAL"});setModal({kind:"ISSUE"})}}><Plus/>Report issue</button>:null}
  </div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}
  {oneTimeToken?<div className={styles.token}><b>One-time visitor credential</b><code>{oneTimeToken}</code><small>Share only through an authorised channel. This value is not persisted by KRAVIA.</small></div>:null}

  {view==="rooms"?<div className={styles.grid}>{data.rooms.map(room=>{const site=sites.get(room.site_id);const bookings=data.bookings.filter(b=>b.room_id===room.id&&b.status==="BOOKED").slice(0,4);return <article className={styles.card} key={room.id}><header><div><small>{room.room_code} · {site?.site_code||"SITE"}</small><h3>{room.name}</h3><span>{room.room_type} · {room.capacity} seats</span></div><em className={styles.badge} data-status={room.status}>{room.status}</em></header>{site?<p className={styles.muted}>{site.name}{site.address_text?" · "+site.address_text:""}</p>:null}<div className={styles.timeline}>{bookings.map(b=><div key={b.id}><CalendarDays/><span><b>{b.title}</b>{date(b.starts_at)} → {date(b.ends_at)}</span>{(b.organizer_user_id===data.actor.user_id||data.capabilities.facilities_manage)&&b.status==="BOOKED"?<button type="button" onClick={()=>{setDraft({reason:""});setModal({kind:"CANCEL",booking:b})}}>Cancel</button>:null}</div>)}{!bookings.length?<span className={styles.emptyInline}>No active booking.</span>:null}</div>{data.capabilities.room_book&&room.status==="ACTIVE"?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({visibility:"INTERNAL"});setModal({kind:"BOOK",room})}}><DoorOpen/>Book room</button></div>:null}</article>})}{!data.rooms.length?<div className={styles.empty}>No active rooms are configured yet. Facilities authority must configure a site and rooms before booking can begin.</div>:null}</div>:null}

  {view==="visitors"?<div className={styles.grid}>{data.visitors.map(v=><article className={styles.card} key={v.id}><header><div><small>{v.visitor_code} · {sites.get(v.site_id)?.name||"Office site"}</small><h3>{v.full_name}</h3><span>{v.organization||"Visitor"} · Host: {people.get(v.host_user_id)?.display_name||(v.host_user_id===data.actor.user_id?"You":"Employee")}</span></div><em className={styles.badge} data-status={v.status}>{v.status.replaceAll("_"," ")}</em></header><p>{v.purpose}</p><div className={styles.kv}><span>Scheduled<b>{date(v.scheduled_from)}</b></span><span>Until<b>{date(v.scheduled_to)}</b></span><span>Credential<b>{activeCredential.has(v.id)?"Active":"—"}</b></span><span>Contact<b>{v.email||v.phone||"—"}</b></span></div>{v.review_note?<p className={styles.muted}>Review note: {v.review_note}</p>:null}{data.capabilities.visitor_manage?<div className={styles.actions}>{v.status==="REQUESTED"&&v.host_user_id!==data.actor.user_id?<><button type="button" onClick={()=>{setDraft({note:""});setModal({kind:"REVIEW",visitor:v,decision:"APPROVED"})}}><ShieldCheck/>Approve</button><button type="button" onClick={()=>{setDraft({note:""});setModal({kind:"REVIEW",visitor:v,decision:"DENIED"})}}>Deny</button></>:null}{v.status==="APPROVED"?<><button type="button" onClick={()=>{setDraft({});setModal({kind:"CREDENTIAL",visitor:v})}}><UserRoundCheck/>Issue credential</button><button type="button" onClick={()=>setModal({kind:"CHECKIN",visitor:v})}>Check in</button></>:null}{v.status==="CHECKED_IN"?<button type="button" onClick={()=>setModal({kind:"CHECKOUT",visitor:v})}>Check out</button>:null}</div>:null}</article>)}{!data.visitors.length?<div className={styles.empty}>No visitor activity in your authorised scope.</div>:null}</div>:null}

  {view==="issues"?<div className={styles.grid}>{data.incidents.map(i=><article className={styles.card} key={i.id}><header><div><small>{i.category} · {sites.get(i.site_id)?.name||"Office site"}</small><h3>{i.title}</h3><span>{rooms.get(i.room_id||"")?.name||"Site-wide"} · reported {date(i.created_at)}</span></div><em className={styles.badge} data-status={i.priority==="URGENT"?"URGENT":i.status}>{i.status.replaceAll("_"," ")}</em></header><p>{i.description}</p><div className={styles.kv}><span>Priority<b>{i.priority}</b></span><span>Owner<b>{i.owner_user_id?people.get(i.owner_user_id)?.display_name||"Assigned":"Unassigned"}</b></span><span>Reporter<b>{people.get(i.reporter_user_id)?.display_name||(i.reporter_user_id===data.actor.user_id?"You":"Employee")}</b></span><span>Resolution<b>{i.resolution||"—"}</b></span></div>{data.capabilities.facilities_manage&&!["CLOSED","CANCELLED"].includes(i.status)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:i.status,owner_user_id:i.owner_user_id||"",note:""});setModal({kind:"TRANSITION",incident:i})}}><Wrench/>Update issue</button></div>:null}</article>)}{!data.incidents.length?<div className={styles.empty}>No facility issues in your authorised scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED PHYSICAL-OFFICE ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="BOOK"?<><label>Room<input readOnly value={modal.room.name}/></label><label>Title<input required minLength={2} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Purpose<textarea value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><div className={styles.two}><label>Start<input required type="datetime-local" value={draft.starts_at||""} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></label><label>End<input required type="datetime-local" value={draft.ends_at||""} onChange={e=>setDraft({...draft,ends_at:e.target.value})}/></label></div><label>Visibility<select value={draft.visibility||"INTERNAL"} onChange={e=>setDraft({...draft,visibility:e.target.value})}><option>INTERNAL</option><option>CONFIDENTIAL</option></select></label></>
   :modal.kind==="CANCEL"?<label>Cancellation reason<textarea required minLength={3} value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>
   :modal.kind==="INVITE"?<><label>Site<select required value={draft.site_id||""} onChange={e=>setDraft({...draft,site_id:e.target.value})}><option value="">Select office site</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className={styles.two}><label>Visitor name<input required minLength={2} value={draft.name||""} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Organization<input value={draft.organization||""} onChange={e=>setDraft({...draft,organization:e.target.value})}/></label></div><div className={styles.two}><label>Email<input type="email" value={draft.email||""} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Phone<input value={draft.phone||""} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label></div><label>Purpose<textarea required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><div className={styles.two}><label>From<input required type="datetime-local" value={draft.starts_at||""} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></label><label>Until<input required type="datetime-local" value={draft.ends_at||""} onChange={e=>setDraft({...draft,ends_at:e.target.value})}/></label></div></>
   :modal.kind==="REVIEW"?<label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>
   :modal.kind==="CREDENTIAL"?<label>Credential expiry<input type="datetime-local" value={draft.expires_at||""} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/><small>Cannot extend beyond the approved visitor window.</small></label>
   :modal.kind==="CHECKIN"||modal.kind==="CHECKOUT"?<p>Confirm {modal.kind==="CHECKIN"?"visitor arrival":"visitor departure"} for <b>{modal.visitor.full_name}</b>.</p>
   :modal.kind==="ISSUE"?<><label>Site<select required value={draft.site_id||""} onChange={e=>setDraft({...draft,site_id:e.target.value,room_id:""})}><option value="">Select site</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Room<select value={draft.room_id||""} onChange={e=>setDraft({...draft,room_id:e.target.value})}><option value="">Site-wide</option>{data.rooms.filter(r=>r.site_id===draft.site_id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className={styles.two}><label>Category<select value={draft.category||"OTHER"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["POWER","HVAC","CLEANING","SAFETY","SECURITY","ACCESS","FURNITURE","WATER","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select value={draft.priority||"NORMAL"} onChange={e=>setDraft({...draft,priority:e.target.value})}>{["LOW","NORMAL","HIGH","URGENT"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>
   :<><div className={styles.two}><label>Status<select value={draft.status||modal.incident.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{["OPEN","TRIAGED","IN_PROGRESS","WAITING_VENDOR","RESOLVED","CLOSED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Keep current</option>{data.identities.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><label>Note / resolution<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>
}