"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, CircleAlert, FileLock2, Gavel, ListChecks, LoaderCircle, Plus, ScrollText, ShieldCheck, UserCheck, UsersRound, X } from "lucide-react";
import styles from "./office-board-workspace.module.css";

type Person = { user_id: string; display_name?: string | null; job_title?: string | null; primary_department?: string | null };
type Meeting = { id: string; meeting_code: string; meeting_kind: string; title: string; scheduled_start: string; scheduled_end?: string | null; timezone: string; venue_mode: string; venue_details?: string | null; status: string; chair_user_id?: string | null; chair_name?: string | null; secretary_user_id?: string | null; notice_reference?: string | null; notice_issued_at?: string | null; agenda_locked_at?: string | null; quorum_confirmed?: boolean | null; quorum_note?: string | null; started_at?: string | null; completed_at?: string | null; minutes_locked_at?: string | null };
type Participant = { id: string; meeting_id: string; participant_user_id?: string | null; participant_name: string; capacity: string; invitation_status: string; attendance_status: string; attendance_note?: string | null; conflict_note?: string | null };
type Agenda = { id: string; meeting_id: string; item_no: number; title: string; purpose: string; background_note?: string | null; proposed_resolution_text?: string | null; owner_user_id?: string | null; presenter_name?: string | null; status: string; decision_note?: string | null };
type Minutes = { id: string; meeting_id: string; version_no: number; body: string; status: string; prepared_by: string; review_submitted_at?: string | null; approved_by?: string | null; approved_at?: string | null; approval_note?: string | null; locked_by?: string | null; locked_at?: string | null; content_hash?: string | null };
type Resolution = { id: string; resolution_code: string; meeting_id: string; agenda_item_id: string; resolution_type: string; title: string; resolution_text: string; approval_basis: string; approved_by_name?: string | null; recorded_at: string; content_hash: string; source_reference?: string | null; status: string };
type BoardAction = { id: string; action_code: string; meeting_id: string; agenda_item_id?: string | null; resolution_id?: string | null; title: string; description?: string | null; owner_user_id: string; due_at?: string | null; status: string; blocker_note?: string | null; completion_note?: string | null };
type Followup = { id: string; followup_code: string; meeting_id?: string | null; resolution_id?: string | null; title: string; authority: string; form_code?: string | null; due_at?: string | null; due_basis: string; source_reference: string; owner_user_id: string; reviewer_user_id?: string | null; status: string; filing_reference?: string | null; evidence_reference?: string | null };
type BoardEvent = { id: number; meeting_id: string; event_type: string; entity_type?: string | null; previous_status?: string | null; new_status?: string | null; note?: string | null; created_at: string };
type Caps = { manage_board: boolean; manage_agenda: boolean; prepare_minutes: boolean; lock_minutes: boolean; record_resolution: boolean; manage_followup: boolean; director: boolean };
type Payload = { generated_at: string; actor: { user_id: string; roles: string[] }; capabilities: Caps; people: Person[]; meetings: Meeting[]; participants: Participant[]; agenda: Agenda[]; minutes: Minutes[]; resolutions: Resolution[]; actions: BoardAction[]; followups: Followup[]; events: BoardEvent[]; disclaimer: string };
type Modal = { kind: string; meeting?: Meeting; participant?: Participant; agenda?: Agenda; minutes?: Minutes; action?: BoardAction; followup?: Followup; resolution?: Resolution };

async function api<T>(body?: Record<string, unknown>): Promise<T> {
  const response = await fetch("/api/office-board", body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), cache: "no-store", credentials: "same-origin" } : { cache: "no-store", credentials: "same-origin" });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof payload.detail === "string" ? payload.detail : "Board request failed");
  return payload as T;
}
function label(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/(^|\s)\S/g, (c) => c.toUpperCase()); }
function dateTime(value?: string | null) { if (!value) return "—"; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(d); }
function isoLocal(value: string) { return value ? new Date(value).toISOString() : undefined; }

export function OfficeBoardWorkspace() {
  const [data, setData] = useState<Payload>();
  const [error, setError] = useState<string>();
  const [notice, setNotice] = useState<string>();
  const [selectedId, setSelectedId] = useState<string>();
  const [view, setView] = useState<"meetings" | "actions" | "followups" | "resolutions">("meetings");
  const [modal, setModal] = useState<Modal>();
  const [draft, setDraft] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);

  async function reload(message?: string) { const next = await api<Payload>(); setData(next); if (message) setNotice(message); }
  useEffect(() => { let alive = true; void api<Payload>().then((next) => { if (alive) { setData(next); setSelectedId((current) => current || next.meetings[0]?.id); } }).catch((caught: unknown) => { if (alive) setError(caught instanceof Error ? caught.message : "Board workspace unavailable"); }); return () => { alive = false; }; }, []);

  const people = useMemo(() => new Map((data?.people ?? []).map((person) => [person.user_id, person])), [data?.people]);
  const selected = data?.meetings.find((meeting) => meeting.id === selectedId);
  const participants = (data?.participants ?? []).filter((item) => item.meeting_id === selectedId);
  const agenda = (data?.agenda ?? []).filter((item) => item.meeting_id === selectedId).sort((a,b) => a.item_no-b.item_no);
  const minutes = (data?.minutes ?? []).filter((item) => item.meeting_id === selectedId).sort((a,b) => b.version_no-a.version_no);
  const resolutions = (data?.resolutions ?? []).filter((item) => item.meeting_id === selectedId);
  const actions = (data?.actions ?? []).filter((item) => item.meeting_id === selectedId);
  const followups = (data?.followups ?? []).filter((item) => item.meeting_id === selectedId);
  const events = (data?.events ?? []).filter((item) => item.meeting_id === selectedId).slice(0,80);

  function open(kind: string, context: Omit<Modal, "kind"> = {}, defaults: Record<string,string> = {}) { setDraft(defaults); setModal({ kind, ...context }); }
  async function mutate(body: Record<string, unknown>, message: string) { setBusy(true); setError(undefined); try { await api(body); await reload(message); setModal(undefined); setDraft({}); } catch (caught) { setError(caught instanceof Error ? caught.message : "Board operation failed"); } finally { setBusy(false); } }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!modal) return;
    const meeting = modal.meeting || selected;
    switch (modal.kind) {
      case "CREATE_MEETING": return void mutate({ action: "CREATE_MEETING", kind: draft.kind || "BOARD", title: draft.title, start: isoLocal(draft.start), end: draft.end ? isoLocal(draft.end) : undefined, timezone: draft.timezone || "Asia/Kolkata", venue_mode: draft.venue_mode || "VIDEO", venue_details: draft.venue_details || undefined, chair_user_id: draft.chair_user_id || undefined, chair_name: draft.chair_name || undefined, secretary_user_id: draft.secretary_user_id || undefined }, "Meeting created in draft state.");
      case "ADD_PARTICIPANT": return void mutate({ action: "ADD_PARTICIPANT", meeting_id: meeting?.id, user_id: draft.user_id || undefined, name: draft.name, capacity: draft.capacity || "DIRECTOR" }, "Participant added to the meeting record.");
      case "ADD_AGENDA": return void mutate({ action: "ADD_AGENDA", meeting_id: meeting?.id, title: draft.title, purpose: draft.purpose || "DISCUSSION", background: draft.background || undefined, proposed_resolution: draft.proposed_resolution || undefined, owner_user_id: draft.owner_user_id || undefined, presenter: draft.presenter || undefined }, "Agenda item added. It remains editable until agenda lock.");
      case "ISSUE_NOTICE": return void mutate({ action: "ISSUE_NOTICE", meeting_id: meeting?.id, notice_reference: draft.notice_reference }, "Notice issuance recorded with evidence reference.");
      case "START_MEETING": return void mutate({ action: "START_MEETING", meeting_id: meeting?.id, quorum_note: draft.quorum_note }, "Meeting started after human quorum confirmation.");
      case "ATTENDANCE": return void mutate({ action: "RECORD_ATTENDANCE", participant_id: modal.participant?.id, status: draft.status, note: draft.note || undefined, conflict: draft.conflict || undefined }, "Attendance and conflict note recorded.");
      case "DECIDE_AGENDA": return void mutate({ action: "DECIDE_AGENDA", item_id: modal.agenda?.id, outcome: draft.outcome, note: draft.note }, "Agenda outcome recorded.");
      case "SAVE_MINUTES": return void mutate({ action: "SAVE_MINUTES", meeting_id: meeting?.id, body: draft.body }, "New minutes draft version saved.");
      case "APPROVE_MINUTES": return void mutate({ action: "APPROVE_MINUTES", minutes_id: modal.minutes?.id, note: draft.note || undefined }, "Minutes approved independently by a director.");
      case "RESOLUTION": return void mutate({ action: "RECORD_RESOLUTION", item_id: modal.agenda?.id, type: draft.type || "BOARD", title: draft.title, resolution_text: draft.resolution_text, approval_basis: draft.approval_basis, approved_by_name: draft.approved_by_name || undefined, source_reference: draft.source_reference || undefined }, "Resolution recorded with integrity hash.");
      case "CREATE_ACTION": return void mutate({ action: "CREATE_ACTION", meeting_id: meeting?.id, agenda_item_id: draft.agenda_item_id || undefined, resolution_id: draft.resolution_id || undefined, title: draft.title, description: draft.description || undefined, owner_user_id: draft.owner_user_id, due_at: draft.due_at ? isoLocal(draft.due_at) : undefined }, "Board action assigned.");
      case "UPDATE_ACTION": return void mutate({ action: "UPDATE_ACTION", action_id: modal.action?.id, status: draft.status, note: draft.note || undefined }, "Board action updated.");
      case "CREATE_FOLLOWUP": return void mutate({ action: "CREATE_FOLLOWUP", meeting_id: meeting?.id, resolution_id: draft.resolution_id || undefined, title: draft.title, authority: draft.authority, form_code: draft.form_code || undefined, due_at: draft.due_at ? isoLocal(draft.due_at) : undefined, due_basis: draft.due_basis, source_reference: draft.source_reference, owner_user_id: draft.owner_user_id, reviewer_user_id: draft.reviewer_user_id || undefined }, "Secretarial follow-up created from a recorded human/professional due basis.");
      case "UPDATE_FOLLOWUP": return void mutate({ action: "UPDATE_FOLLOWUP", followup_id: modal.followup?.id, status: draft.status, filing_reference: draft.filing_reference || undefined, evidence_reference: draft.evidence_reference || undefined }, "Secretarial follow-up status updated.");
    }
  }

  if (error && !data) return <section className={styles.state}><CircleAlert /><div><h2>Board workspace unavailable</h2><p>{error}</p></div></section>;
  if (!data) return <section className={styles.state}><LoaderCircle className={styles.spin} /><div><h2>Loading board workspace</h2><p>Resolving board authority and secretarial evidence.</p></div></section>;

  const upcoming = data.meetings.filter((item) => !["COMPLETED","MINUTES_DRAFTED","MINUTES_LOCKED","CANCELLED"].includes(item.status)).length;
  const openActions = data.actions.filter((item) => !["DONE","CANCELLED"].includes(item.status)).length;
  const openFollowups = data.followups.filter((item) => !["CLOSED","NOT_REQUIRED"].includes(item.status)).length;

  return <section className={styles.shell}>
    <header className={styles.hero}><div><p>BOARD & SECRETARIAL OPERATIONS</p><h2>Notice → agenda → meeting → minutes → resolution → follow-up.</h2><span>{data.disclaimer}</span></div>{data.capabilities.manage_board ? <button type="button" onClick={() => open("CREATE_MEETING", {}, { kind:"BOARD", venue_mode:"VIDEO", timezone:"Asia/Kolkata", chair_user_id:data.actor.user_id, secretary_user_id:data.actor.user_id })}><Plus /> Schedule meeting</button> : null}</header>
    <div className={styles.metrics}><article><CalendarDays /><b>{upcoming}</b><span>active meetings</span></article><article><ListChecks /><b>{openActions}</b><span>open board actions</span></article><article><ScrollText /><b>{data.resolutions.length}</b><span>recorded resolutions</span></article><article><FileLock2 /><b>{openFollowups}</b><span>open follow-ups</span></article></div>
    {notice ? <div className={styles.notice}><ShieldCheck />{notice}<button type="button" onClick={() => setNotice(undefined)} aria-label="Dismiss"><X /></button></div> : null}
    {error ? <div className={styles.error}><CircleAlert />{error}</div> : null}
    <div className={styles.tabs}>{(["meetings","actions","followups","resolutions"] as const).map((key) => <button type="button" key={key} data-active={view===key} onClick={() => setView(key)}>{label(key)}</button>)}</div>

    {view === "meetings" ? <div className={styles.meetingLayout}><aside className={styles.meetingList}>{data.meetings.map((meeting) => <button type="button" data-active={meeting.id===selectedId} key={meeting.id} onClick={() => setSelectedId(meeting.id)}><span><code>{meeting.meeting_code}</code><b>{meeting.title}</b><small>{dateTime(meeting.scheduled_start)} · {label(meeting.meeting_kind)}</small></span><em>{label(meeting.status)}</em></button>)}{!data.meetings.length ? <div className={styles.empty}><Gavel /><b>No board meetings recorded</b><span>Create the first real meeting; no samples are generated.</span></div> : null}</aside>{selected ? <MeetingDetail data={data} meeting={selected} people={people} participants={participants} agenda={agenda} minutes={minutes} resolutions={resolutions} actions={actions} followups={followups} events={events} open={open} mutate={mutate} /> : null}</div> : null}

    {view === "actions" ? <div className={styles.cards}>{data.actions.map((item) => <article key={item.id}><header><div><code>{item.action_code}</code><h3>{item.title}</h3></div><em>{label(item.status)}</em></header><p>{item.description || "No additional description."}</p><footer><span>Owner: {people.get(item.owner_user_id)?.display_name || "Assigned user"} · Due {dateTime(item.due_at)}</span>{!["DONE","CANCELLED"].includes(item.status) ? <button type="button" onClick={() => open("UPDATE_ACTION", { action:item }, { status:item.status })}>Update</button> : null}</footer></article>)}{!data.actions.length ? <Empty text="No board actions recorded." /> : null}</div> : null}

    {view === "followups" ? <div className={styles.cards}>{data.followups.map((item) => <article key={item.id}><header><div><code>{item.followup_code}</code><h3>{item.title}</h3></div><em>{label(item.status)}</em></header><p>{item.authority}{item.form_code ? ` · ${item.form_code}` : ""}</p><div className={styles.meta}><span>Due: {dateTime(item.due_at)}</span><span>Basis: {item.due_basis}</span><span>Source: {item.source_reference}</span></div>{data.capabilities.manage_followup && !["CLOSED","NOT_REQUIRED"].includes(item.status) ? <footer><button type="button" onClick={() => open("UPDATE_FOLLOWUP", { followup:item }, { status:item.status })}>Update follow-up</button></footer> : null}</article>)}{!data.followups.length ? <Empty text="No secretarial follow-ups recorded." /> : null}</div> : null}

    {view === "resolutions" ? <div className={styles.cards}>{data.resolutions.map((item) => <article key={item.id}><header><div><code>{item.resolution_code}</code><h3>{item.title}</h3></div><em>{item.resolution_type}</em></header><p>{item.resolution_text}</p><div className={styles.meta}><span>Approval basis: {item.approval_basis}</span><span>SHA-256: {item.content_hash.slice(0,16)}…</span><span>{dateTime(item.recorded_at)}</span></div></article>)}{!data.resolutions.length ? <Empty text="No resolutions recorded from decided agenda items." /> : null}</div> : null}

    {modal ? <BoardModal modal={modal} draft={draft} setDraft={setDraft} data={data} selected={selected} agenda={agenda} resolutions={resolutions} busy={busy} submit={submit} close={() => setModal(undefined)} /> : null}
  </section>;
}

function MeetingDetail({ data, meeting, people, participants, agenda, minutes, resolutions, actions, followups, events, open, mutate }: { data:Payload; meeting:Meeting; people:Map<string,Person>; participants:Participant[]; agenda:Agenda[]; minutes:Minutes[]; resolutions:Resolution[]; actions:BoardAction[]; followups:Followup[]; events:BoardEvent[]; open:(kind:string,context?:Omit<Modal,"kind">,defaults?:Record<string,string>)=>void; mutate:(body:Record<string,unknown>,message:string)=>Promise<void> }) {
  const latestMinutes = minutes[0];
  return <div className={styles.detail}>
    <header className={styles.detailHead}><div><code>{meeting.meeting_code}</code><h2>{meeting.title}</h2><p>{dateTime(meeting.scheduled_start)} · {meeting.venue_mode}{meeting.venue_details ? ` · ${meeting.venue_details}` : ""}</p></div><span data-status={meeting.status}>{label(meeting.status)}</span></header>
    <div className={styles.lifecycle}>{["DRAFT","NOTICE_ISSUED","AGENDA_LOCKED","IN_PROGRESS","COMPLETED","MINUTES_DRAFTED","MINUTES_LOCKED"].map((step) => <div key={step} data-current={meeting.status===step} data-done={statusIndex(meeting.status)>=statusIndex(step)}><b>{label(step)}</b></div>)}</div>
    <div className={styles.meetingActions}>{data.capabilities.manage_board && meeting.status==="DRAFT" ? <button type="button" onClick={() => open("ISSUE_NOTICE",{meeting})}>Issue notice</button> : null}{data.capabilities.manage_agenda && meeting.status==="NOTICE_ISSUED" ? <button type="button" onClick={() => void mutate({action:"LOCK_AGENDA",meeting_id:meeting.id},"Agenda locked. Later changes require a separate governed process.")}>Lock agenda</button> : null}{(data.capabilities.manage_board||data.capabilities.director) && ["AGENDA_LOCKED","ADJOURNED"].includes(meeting.status) ? <button type="button" onClick={() => open("START_MEETING",{meeting})}>Start meeting</button> : null}{(data.capabilities.manage_board||data.capabilities.director) && meeting.status==="IN_PROGRESS" ? <button type="button" onClick={() => void mutate({action:"COMPLETE_MEETING",meeting_id:meeting.id},"Meeting completed. Minutes may now be drafted.")}>Complete meeting</button> : null}{data.capabilities.prepare_minutes && ["COMPLETED","MINUTES_DRAFTED"].includes(meeting.status) ? <button type="button" onClick={() => open("SAVE_MINUTES",{meeting})}>Draft minutes</button> : null}{data.capabilities.manage_board ? <button type="button" onClick={() => open("CREATE_ACTION",{meeting},{owner_user_id:data.actor.user_id})}>Add action</button> : null}{data.capabilities.manage_followup ? <button type="button" onClick={() => open("CREATE_FOLLOWUP",{meeting},{owner_user_id:data.actor.user_id})}>Add follow-up</button> : null}</div>

    <section className={styles.block}><header><div><UsersRound /><h3>Participants & attendance</h3></div>{data.capabilities.manage_board && ["DRAFT","NOTICE_ISSUED"].includes(meeting.status) ? <button type="button" onClick={() => open("ADD_PARTICIPANT",{meeting},{capacity:"DIRECTOR"})}><Plus /> Participant</button> : null}</header><div className={styles.rows}>{participants.map((person) => <article key={person.id}><div><b>{person.participant_name}</b><span>{person.capacity} · {label(person.invitation_status)}</span></div><em>{label(person.attendance_status)}</em>{data.capabilities.manage_board && ["AGENDA_LOCKED","IN_PROGRESS","ADJOURNED"].includes(meeting.status) ? <button type="button" onClick={() => open("ATTENDANCE",{participant:person},{status:person.attendance_status==="PENDING"?"PRESENT":person.attendance_status,note:person.attendance_note||"",conflict:person.conflict_note||""})}><UserCheck /> Attendance</button> : null}</article>)}{!participants.length ? <p className={styles.emptyLine}>No participants recorded.</p> : null}</div></section>

    <section className={styles.block}><header><div><ListChecks /><h3>Agenda</h3></div>{data.capabilities.manage_agenda && ["DRAFT","NOTICE_ISSUED"].includes(meeting.status) ? <button type="button" onClick={() => open("ADD_AGENDA",{meeting},{purpose:"DISCUSSION"})}><Plus /> Agenda item</button> : null}</header><div className={styles.agenda}>{agenda.map((item) => <article key={item.id}><header><div><code>Item {item.item_no}</code><b>{item.title}</b><span>{item.purpose}</span></div><em>{label(item.status)}</em></header>{item.background_note ? <p>{item.background_note}</p> : null}<footer>{meeting.status==="IN_PROGRESS" && item.status==="LOCKED" && (data.capabilities.manage_board||data.capabilities.director) ? <button type="button" onClick={() => open("DECIDE_AGENDA",{agenda:item},{outcome:item.purpose==="INFORMATION"?"NOTED":"DECIDED"})}>Record outcome</button> : null}{item.status==="DECIDED" && data.capabilities.record_resolution && !resolutions.some((resolution) => resolution.agenda_item_id===item.id) ? <button type="button" onClick={() => open("RESOLUTION",{agenda:item},{type:"BOARD",title:item.title,resolution_text:item.proposed_resolution_text||"",approval_basis:item.decision_note||""})}>Record resolution</button> : null}</footer></article>)}{!agenda.length ? <p className={styles.emptyLine}>No agenda items recorded.</p> : null}</div></section>

    <section className={styles.block}><header><div><ScrollText /><h3>Minutes</h3></div></header>{latestMinutes ? <article className={styles.minutes}><header><div><b>Version {latestMinutes.version_no}</b><span>{label(latestMinutes.status)}</span></div>{latestMinutes.content_hash ? <code>SHA-256 {latestMinutes.content_hash.slice(0,20)}…</code> : null}</header><p>{latestMinutes.body}</p><footer>{latestMinutes.status==="DRAFT" && latestMinutes.prepared_by===data.actor.user_id && data.capabilities.prepare_minutes ? <button type="button" onClick={() => void mutate({action:"SUBMIT_MINUTES",minutes_id:latestMinutes.id},"Minutes submitted for independent director/chair review.")}>Submit for review</button> : null}{latestMinutes.status==="CHAIR_REVIEW" && data.capabilities.director && latestMinutes.prepared_by!==data.actor.user_id ? <button type="button" onClick={() => open("APPROVE_MINUTES",{minutes:latestMinutes})}>Approve minutes</button> : null}{latestMinutes.status==="APPROVED" && data.capabilities.lock_minutes ? <button type="button" onClick={() => void mutate({action:"LOCK_MINUTES",minutes_id:latestMinutes.id},"Approved minutes locked with SHA-256 integrity hash.")}>Lock minutes</button> : null}</footer></article> : <p className={styles.emptyLine}>No minutes version recorded.</p>}</section>

    <section className={styles.block}><header><div><CheckCircle2 /><h3>Actions & statutory follow-up</h3></div></header><div className={styles.split}><div><h4>Board actions</h4>{actions.map((item) => <p key={item.id}><b>{item.action_code}</b> · {item.title} · {label(item.status)} · {people.get(item.owner_user_id)?.display_name||"Owner"}</p>)}{!actions.length?<span>No actions.</span>:null}</div><div><h4>Secretarial follow-up</h4>{followups.map((item) => <p key={item.id}><b>{item.followup_code}</b> · {item.title} · {label(item.status)} · {item.authority}</p>)}{!followups.length?<span>No follow-ups.</span>:null}</div></div></section>

    <section className={styles.block}><header><div><ShieldCheck /><h3>Meeting timeline</h3></div></header><div className={styles.timeline}>{events.map((event) => <article key={event.id}><span>{dateTime(event.created_at)}</span><b>{label(event.event_type)}</b><small>{event.previous_status&&event.new_status?`${label(event.previous_status)} → ${label(event.new_status)}`:event.new_status?label(event.new_status):event.note||event.entity_type||"Recorded"}</small></article>)}{!events.length?<p className={styles.emptyLine}>No events.</p>:null}</div></section>
  </div>;
}

function BoardModal({ modal,draft,setDraft,data,selected,agenda,resolutions,busy,submit,close }: { modal:Modal; draft:Record<string,string>; setDraft:(next:Record<string,string>)=>void; data:Payload; selected?:Meeting; agenda:Agenda[]; resolutions:Resolution[]; busy:boolean; submit:(event:FormEvent<HTMLFormElement>)=>void; close:()=>void }) {
  const input=(key:string,value:string)=>setDraft({...draft,[key]:value});
  const heading:Record<string,string>={CREATE_MEETING:"Schedule meeting",ADD_PARTICIPANT:"Add participant",ADD_AGENDA:"Add agenda item",ISSUE_NOTICE:"Record notice issuance",START_MEETING:"Confirm quorum and start",ATTENDANCE:"Record attendance",DECIDE_AGENDA:"Record agenda outcome",SAVE_MINUTES:"Draft minutes",APPROVE_MINUTES:"Approve minutes",RESOLUTION:"Record resolution",CREATE_ACTION:"Create board action",UPDATE_ACTION:"Update board action",CREATE_FOLLOWUP:"Create secretarial follow-up",UPDATE_FOLLOWUP:"Update secretarial follow-up"};
  return <div className={styles.backdrop} role="presentation" onMouseDown={() => !busy&&close()}><form className={styles.dialog} onSubmit={submit} onMouseDown={(e)=>e.stopPropagation()}><header><div><p>GOVERNED BOARD WORKFLOW</p><h3>{heading[modal.kind]||label(modal.kind)}</h3></div><button type="button" onClick={close} aria-label="Close"><X /></button></header>
    {modal.kind==="CREATE_MEETING"?<><div className={styles.two}><label>Kind<select value={draft.kind||"BOARD"} onChange={e=>input("kind",e.target.value)}>{["BOARD","COMMITTEE","AGM","EGM","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Venue mode<select value={draft.venue_mode||"VIDEO"} onChange={e=>input("venue_mode",e.target.value)}>{["VIDEO","PHYSICAL","HYBRID"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Title<input value={draft.title||""} onChange={e=>input("title",e.target.value)} minLength={3} maxLength={220} required /></label><div className={styles.two}><label>Start<input type="datetime-local" value={draft.start||""} onChange={e=>input("start",e.target.value)} required /></label><label>End<input type="datetime-local" value={draft.end||""} onChange={e=>input("end",e.target.value)} /></label></div><label>Venue / video reference<input value={draft.venue_details||""} onChange={e=>input("venue_details",e.target.value)} maxLength={1000}/></label><div className={styles.two}><label>Chair Office user<select value={draft.chair_user_id||""} onChange={e=>input("chair_user_id",e.target.value)}><option value="">External / named chair</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label><label>External chair name<input value={draft.chair_name||""} onChange={e=>input("chair_name",e.target.value)} maxLength={180}/></label></div><label>Secretary<select value={draft.secretary_user_id||""} onChange={e=>input("secretary_user_id",e.target.value)}><option value="">Not assigned</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label></>:null}
    {modal.kind==="ADD_PARTICIPANT"?<><label>Office identity (optional)<select value={draft.user_id||""} onChange={e=>{const id=e.target.value;const p=data.people.find(x=>x.user_id===id);setDraft({...draft,user_id:id,name:p?.display_name||draft.name||""});}}><option value="">External participant</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label><label>Participant name<input value={draft.name||""} onChange={e=>input("name",e.target.value)} minLength={2} maxLength={180} required/></label><label>Capacity<select value={draft.capacity||"DIRECTOR"} onChange={e=>input("capacity",e.target.value)}>{["CHAIR","DIRECTOR","CS","SHAREHOLDER","INVITEE","AUDITOR","LEGAL","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label></>:null}
    {modal.kind==="ADD_AGENDA"?<><label>Title<input value={draft.title||""} onChange={e=>input("title",e.target.value)} minLength={3} maxLength={220} required/></label><label>Purpose<select value={draft.purpose||"DISCUSSION"} onChange={e=>input("purpose",e.target.value)}>{["INFORMATION","DISCUSSION","DECISION","RESOLUTION"].map(v=><option key={v}>{v}</option>)}</select></label><label>Background<textarea value={draft.background||""} onChange={e=>input("background",e.target.value)} maxLength={8000}/></label><label>Proposed resolution text<textarea value={draft.proposed_resolution||""} onChange={e=>input("proposed_resolution",e.target.value)} maxLength={8000}/></label><div className={styles.two}><label>Owner<select value={draft.owner_user_id||""} onChange={e=>input("owner_user_id",e.target.value)}><option value="">No owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label><label>Presenter<input value={draft.presenter||""} onChange={e=>input("presenter",e.target.value)} maxLength={180}/></label></div></>:null}
    {modal.kind==="ISSUE_NOTICE"?<><p className={styles.warning}>Record the notice evidence/reference. The system does not decide whether a statutory notice period is legally sufficient.</p><label>Notice reference<input value={draft.notice_reference||""} onChange={e=>input("notice_reference",e.target.value)} minLength={3} maxLength={500} required/></label></>:null}
    {modal.kind==="START_MEETING"?<><p className={styles.warning}>Quorum is a human/company-law determination. KRAVIA Office records your confirmation; it does not calculate legal quorum.</p><label>Quorum confirmation basis<textarea value={draft.quorum_note||""} onChange={e=>input("quorum_note",e.target.value)} minLength={3} maxLength={2000} required/></label></>:null}
    {modal.kind==="ATTENDANCE"?<><label>Attendance<select value={draft.status||"PRESENT"} onChange={e=>input("status",e.target.value)}>{["PRESENT","ABSENT","LEAVE_OF_ABSENCE"].map(v=><option key={v}>{v}</option>)}</select></label><label>Attendance note<textarea value={draft.note||""} onChange={e=>input("note",e.target.value)} maxLength={1000}/></label><label>Conflict / interest note<textarea value={draft.conflict||""} onChange={e=>input("conflict",e.target.value)} maxLength={2000}/></label></>:null}
    {modal.kind==="DECIDE_AGENDA"?<><label>Outcome<select value={draft.outcome||"DECIDED"} onChange={e=>input("outcome",e.target.value)}>{["NOTED","DECIDED","DEFERRED","WITHDRAWN"].map(v=><option key={v}>{v}</option>)}</select></label><label>Decision note<textarea value={draft.note||""} onChange={e=>input("note",e.target.value)} minLength={3} maxLength={4000} required/></label></>:null}
    {modal.kind==="SAVE_MINUTES"?<><p className={styles.warning}>Each save creates a new version. A locked version cannot be silently edited or deleted.</p><label>Minutes body<textarea className={styles.largeText} value={draft.body||""} onChange={e=>input("body",e.target.value)} minLength={20} maxLength={50000} required/></label></>:null}
    {modal.kind==="APPROVE_MINUTES"?<><p className={styles.warning}>The preparer cannot approve the same version. Approval is distinct from final locking.</p><label>Approval note<textarea value={draft.note||""} onChange={e=>input("note",e.target.value)} maxLength={2000}/></label></>:null}
    {modal.kind==="RESOLUTION"?<><label>Type<select value={draft.type||"BOARD"} onChange={e=>input("type",e.target.value)}>{["BOARD","ORDINARY","SPECIAL","CIRCULAR","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Title<input value={draft.title||""} onChange={e=>input("title",e.target.value)} minLength={3} maxLength={220} required/></label><label>Resolution text<textarea className={styles.largeText} value={draft.resolution_text||""} onChange={e=>input("resolution_text",e.target.value)} minLength={10} maxLength={20000} required/></label><label>Approval basis<textarea value={draft.approval_basis||""} onChange={e=>input("approval_basis",e.target.value)} minLength={3} maxLength={2000} required/></label><div className={styles.two}><label>Approved by / chair name<input value={draft.approved_by_name||""} onChange={e=>input("approved_by_name",e.target.value)} maxLength={180}/></label><label>Source reference<input value={draft.source_reference||""} onChange={e=>input("source_reference",e.target.value)} maxLength={500}/></label></div></>:null}
    {modal.kind==="CREATE_ACTION"?<><label>Title<input value={draft.title||""} onChange={e=>input("title",e.target.value)} minLength={3} maxLength={220} required/></label><label>Description<textarea value={draft.description||""} onChange={e=>input("description",e.target.value)} maxLength={4000}/></label><div className={styles.two}><label>Owner<select value={draft.owner_user_id||""} onChange={e=>input("owner_user_id",e.target.value)} required>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label><label>Due<input type="datetime-local" value={draft.due_at||""} onChange={e=>input("due_at",e.target.value)}/></label></div><div className={styles.two}><label>Agenda item<select value={draft.agenda_item_id||""} onChange={e=>input("agenda_item_id",e.target.value)}><option value="">Not linked</option>{agenda.map(a=><option key={a.id} value={a.id}>Item {a.item_no} · {a.title}</option>)}</select></label><label>Resolution<select value={draft.resolution_id||""} onChange={e=>input("resolution_id",e.target.value)}><option value="">Not linked</option>{resolutions.map(r=><option key={r.id} value={r.id}>{r.resolution_code} · {r.title}</option>)}</select></label></div></>:null}
    {modal.kind==="UPDATE_ACTION"?<><label>Status<select value={draft.status||modal.action?.status||"OPEN"} onChange={e=>input("status",e.target.value)}>{["OPEN","IN_PROGRESS","BLOCKED","DONE","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label><label>Status note<textarea value={draft.note||""} onChange={e=>input("note",e.target.value)} maxLength={2000} placeholder="Required for blocked, done or cancelled"/></label></>:null}
    {modal.kind==="CREATE_FOLLOWUP"?<><p className={styles.warning}>Due date and applicability are not calculated here. Enter the professional/source basis used to determine the follow-up.</p><label>Title<input value={draft.title||""} onChange={e=>input("title",e.target.value)} minLength={3} maxLength={220} required/></label><div className={styles.two}><label>Authority<input value={draft.authority||""} onChange={e=>input("authority",e.target.value)} minLength={2} maxLength={180} required/></label><label>Form / action code<input value={draft.form_code||""} onChange={e=>input("form_code",e.target.value)} maxLength={80}/></label></div><label>Due basis<textarea value={draft.due_basis||""} onChange={e=>input("due_basis",e.target.value)} minLength={3} maxLength={2000} required/></label><label>Source reference<input value={draft.source_reference||""} onChange={e=>input("source_reference",e.target.value)} minLength={3} maxLength={500} required/></label><div className={styles.two}><label>Due date/time<input type="datetime-local" value={draft.due_at||""} onChange={e=>input("due_at",e.target.value)}/></label><label>Resolution link<select value={draft.resolution_id||""} onChange={e=>input("resolution_id",e.target.value)}><option value="">Meeting-level</option>{resolutions.map(r=><option key={r.id} value={r.id}>{r.resolution_code}</option>)}</select></label></div><div className={styles.two}><label>Owner<select value={draft.owner_user_id||""} onChange={e=>input("owner_user_id",e.target.value)} required>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label><label>Reviewer<select value={draft.reviewer_user_id||""} onChange={e=>input("reviewer_user_id",e.target.value)}><option value="">Not assigned</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.job_title||p.user_id}</option>)}</select></label></div></>:null}
    {modal.kind==="UPDATE_FOLLOWUP"?<><label>Status<select value={draft.status||modal.followup?.status||"OPEN"} onChange={e=>input("status",e.target.value)}>{["OPEN","PREPARED","APPROVED","FILED","ACKNOWLEDGED","NOT_REQUIRED","CLOSED"].map(v=><option key={v}>{v}</option>)}</select></label><label>Filing reference<input value={draft.filing_reference||""} onChange={e=>input("filing_reference",e.target.value)} maxLength={500}/></label><label>Evidence / acknowledgement reference<input value={draft.evidence_reference||""} onChange={e=>input("evidence_reference",e.target.value)} maxLength={500}/></label></>:null}
    <footer><button type="button" onClick={close} disabled={busy}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>} Confirm</button></footer></form></div>;
}
function Empty({text}:{text:string}){return <div className={styles.empty}><Gavel/><b>No record</b><span>{text}</span></div>}
function statusIndex(value:string){const order=["DRAFT","NOTICE_ISSUED","AGENDA_LOCKED","IN_PROGRESS","COMPLETED","MINUTES_DRAFTED","MINUTES_LOCKED"];const index=order.indexOf(value);return index<0?-1:index}
