"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, ClipboardCheck, FileCheck2, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-quality.module.css";

type Caps={read:boolean;process_manage:boolean;process_publish:boolean;report:boolean;nc_manage:boolean;capa_manage:boolean;capa_review:boolean};
type Person={user_id:string;display_name?:string|null};
type Process={id:string;process_code:string;title:string;department_code:string;owner_user_id:string;status:string;current_version?:number|null;next_review_on?:string|null;created_by:string};
type Version={id:string;process_id:string;version:number;purpose:string;scope_text:string;procedure_text:string;control_points:string[];evidence_requirements:string[];standard_reference?:string|null;content_sha256:string;status:string;created_by:string};
type Nc={id:string;nc_code:string;process_id?:string|null;reporter_user_id:string;department_code?:string|null;source_type:string;severity:string;title:string;description:string;evidence_reference?:string|null;immediate_containment?:string|null;owner_user_id?:string|null;status:string;created_at:string};
type Capa={id:string;capa_code:string;nonconformance_id:string;action_type:string;owner_user_id:string;root_cause:string;action_plan:string;due_on?:string|null;status:string;completion_evidence_reference?:string|null;effectiveness_evidence_reference?:string|null;review_note?:string|null;created_by:string};
type Payload={actor:{user_id:string;department?:string|null};capabilities:Caps;processes:Process[];process_versions:Version[];nonconformances:Nc[];capas:Capa[];people:Person[];disclaimer:string};
type View="processes"|"nonconformances"|"capa";
type Modal=
 |{kind:"PROCESS"}
 |{kind:"VERSION";process:Process;version?:Version}
 |{kind:"PUBLISH";version:Version}
 |{kind:"REPORT_NC"}
 |{kind:"MANAGE_NC";nc:Nc}
 |{kind:"CLOSE_NC";nc:Nc}
 |{kind:"CAPA";nc:Nc}
 |{kind:"CAPA_STATUS";capa:Capa};

async function api<T>(options?:RequestInit):Promise<T>{
 const r=await fetch("/api/office-quality",{...options,cache:"no-store",credentials:"same-origin"});
 const b=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Quality operation failed");
 return b as T;
}
function fmtDate(v?:string|null){if(!v)return "—";const d=new Date(v.length===10?v+"T00:00:00":v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(d)}
function list(v?:string){return (v||"").split("\n").map(x=>x.trim()).filter(Boolean)}
function ncNext(n:Nc){if(n.status==="REPORTED")return ["TRIAGED","CANCELLED"];if(n.status==="TRIAGED")return ["CONTAINED","CAPA_REQUIRED","AWAITING_CLOSE_REVIEW","CANCELLED"];if(n.status==="CONTAINED")return ["CAPA_REQUIRED","AWAITING_CLOSE_REVIEW"];if(n.status==="CAPA_REQUIRED")return ["AWAITING_CLOSE_REVIEW"];return []}
function capaNext(c:Capa,review:boolean){if(c.status==="DRAFT")return ["IN_PROGRESS"];if(c.status==="IN_PROGRESS")return ["AWAITING_VERIFICATION","CANCELLED"];if(c.status==="AWAITING_VERIFICATION")return review?["VERIFIED_EFFECTIVE","VERIFIED_INEFFECTIVE"]:[];if(c.status==="VERIFIED_EFFECTIVE")return review?["CLOSED"]:[];if(c.status==="VERIFIED_INEFFECTIVE")return ["IN_PROGRESS"];return []}

export function OfficeQualityWorkspace(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("processes");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive)setData(n)}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load Quality")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(p=>[p.user_id,p])),[data?.people]);
 const processMap=useMemo(()=>new Map((data?.processes??[]).map(p=>[p.id,p])),[data?.processes]);
 const ncMap=useMemo(()=>new Map((data?.nonconformances??[]).map(n=>[n.id,n])),[data?.nonconformances]);
 const latest=useMemo(()=>{const m=new Map<string,Version>();for(const v of data?.process_versions??[])if(!m.has(v.process_id))m.set(v.process_id,v);return m},[data?.process_versions]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="PROCESS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_PROCESS",title:draft.title,department:draft.department,owner_user_id:draft.owner_user_id,purpose:draft.purpose,scope:draft.scope,procedure:draft.procedure,controls:list(draft.controls),evidence_requirements:list(draft.evidence_requirements),standard_reference:draft.standard_reference||undefined,next_review_on:draft.next_review_on||undefined})});
  else if(modal.kind==="VERSION")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"NEW_PROCESS_VERSION",process_id:modal.process.id,purpose:draft.purpose,scope:draft.scope,procedure:draft.procedure,controls:list(draft.controls),evidence_requirements:list(draft.evidence_requirements),standard_reference:draft.standard_reference||undefined,change_summary:draft.change_summary||undefined})});
  else if(modal.kind==="PUBLISH")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"PUBLISH_PROCESS",version_id:modal.version.id})});
  else if(modal.kind==="REPORT_NC")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REPORT_NC",process_id:draft.process_id||undefined,source:draft.source||"OTHER",severity:draft.severity||"MEDIUM",title:draft.title,description:draft.description,evidence:draft.evidence||undefined})});
  else if(modal.kind==="MANAGE_NC")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"MANAGE_NC",nonconformance_id:modal.nc.id,status:draft.status,owner_user_id:draft.owner_user_id||undefined,containment:draft.containment||undefined,note:draft.note||undefined})});
  else if(modal.kind==="CLOSE_NC")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CLOSE_NC",nonconformance_id:modal.nc.id,evidence:draft.evidence,note:draft.note||undefined})});
  else if(modal.kind==="CAPA")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_CAPA",nonconformance_id:modal.nc.id,action_type:draft.action_type||"CORRECTIVE",owner_user_id:draft.owner_user_id,root_cause:draft.root_cause,action_plan:draft.action_plan,due_on:draft.due_on||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_CAPA",capa_id:modal.capa.id,status:draft.status,completion_evidence:draft.completion_evidence||undefined,effectiveness_evidence:draft.effectiveness_evidence||undefined,note:draft.note||undefined})});
  await reload("Quality record updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Quality action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Quality unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading Quality & CAPA</h2></div></section>;
 const openNc=data.nonconformances.filter(n=>!["CLOSED","CANCELLED"].includes(n.status)).length;
 const openCapa=data.capas.filter(c=>!["CLOSED","CANCELLED"].includes(c.status)).length;
 const verifyQueue=data.capas.filter(c=>c.status==="AWAITING_VERIFICATION").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>QUALITY · NONCONFORMANCE · CAPA</p><h2>Control process quality with evidence, root cause and independent verification.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{openNc}</b><span>open nonconformances</span></article><article><b>{openCapa}</b><span>open CAPAs</span></article><article><b>{verifyQueue}</b><span>awaiting verification</span></article></div></header>
  <div className={styles.toolbar}>{(["processes","nonconformances","capa"] as View[]).map(v=><button key={v} type="button" data-active={view===v} onClick={()=>setView(v)}>{v==="capa"?"CAPA":v[0].toUpperCase()+v.slice(1)}</button>)}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="processes"&&data.capabilities.process_manage?<button type="button" onClick={()=>{setDraft({department:data.actor.department||""});setModal({kind:"PROCESS"})}}><Plus/>New process</button>:null}{view==="nonconformances"&&data.capabilities.report?<button type="button" onClick={()=>{setDraft({source:"OTHER",severity:"MEDIUM"});setModal({kind:"REPORT_NC"})}}><Plus/>Report nonconformance</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="processes"?<div className={styles.grid}>{data.processes.map(p=>{const v=latest.get(p.id);const hash=v?.content_sha256? v.content_sha256.slice(0,10)+"…"+v.content_sha256.slice(-8):"—";return <article className={styles.card} key={p.id}><header><div><small>{p.process_code} · {p.department_code}</small><h3>{p.title}</h3><span>Owner: {people.get(p.owner_user_id)?.display_name||p.owner_user_id}</span></div><em className={styles.badge} data-status={p.status}>{p.status}</em></header><div className={styles.kv}><span>Version<b>{p.current_version??"Draft"}</b></span><span>Next review<b>{fmtDate(p.next_review_on)}</b></span><span>Content hash<b>{hash}</b></span></div>{v?<details><summary>Latest revision</summary><p><b>Purpose:</b> {v.purpose}</p><p><b>Scope:</b> {v.scope_text}</p><p><b>Procedure:</b> {v.procedure_text}</p></details>:null}<div className={styles.actions}>{data.capabilities.process_manage?<button type="button" onClick={()=>{setDraft({purpose:v?.purpose||"",scope:v?.scope_text||"",procedure:v?.procedure_text||"",controls:(v?.control_points||[]).join("\n"),evidence_requirements:(v?.evidence_requirements||[]).join("\n"),standard_reference:v?.standard_reference||"",change_summary:""});setModal({kind:"VERSION",process:p,version:v})}}>New revision</button>:null}{data.capabilities.process_publish&&v?.status==="DRAFT"&&v.created_by!==data.actor.user_id?<button type="button" onClick={()=>setModal({kind:"PUBLISH",version:v})}><ShieldCheck/>Publish revision</button>:null}</div></article>})}{!data.processes.length?<div className={styles.empty}>No quality processes in your scope.</div>:null}</div>:null}

  {view==="nonconformances"?<div className={styles.grid}>{data.nonconformances.map(n=><article className={styles.card} key={n.id}><header><div><small>{n.nc_code} · {n.source_type}</small><h3>{n.title}</h3><span>{processMap.get(n.process_id||"")?.title||"Unlinked process"} · {fmtDate(n.created_at)}</span></div><div className={styles.badges}><em className={styles.badge} data-status={n.status}>{n.status.replaceAll("_"," ")}</em><em className={styles.badge} data-status={n.severity==="CRITICAL"?"CRITICAL":""}>{n.severity}</em></div></header><p>{n.description}</p><div className={styles.kv}><span>Reporter<b>{n.reporter_user_id===data.actor.user_id?"You":people.get(n.reporter_user_id)?.display_name||"Restricted"}</b></span><span>Owner<b>{n.owner_user_id?people.get(n.owner_user_id)?.display_name||n.owner_user_id:"—"}</b></span><span>Evidence<b>{n.evidence_reference||"—"}</b></span><span>Containment<b>{n.immediate_containment||"—"}</b></span></div><div className={styles.actions}>{data.capabilities.nc_manage&&ncNext(n).length?<button type="button" onClick={()=>{setDraft({status:ncNext(n)[0],owner_user_id:n.owner_user_id||"",containment:n.immediate_containment||"",note:""});setModal({kind:"MANAGE_NC",nc:n})}}>Triage / manage</button>:null}{data.capabilities.capa_manage&&["TRIAGED","CONTAINED","CAPA_REQUIRED"].includes(n.status)?<button type="button" onClick={()=>{setDraft({action_type:"CORRECTIVE"});setModal({kind:"CAPA",nc:n})}}><Plus/>Create CAPA</button>:null}{data.capabilities.capa_review&&n.status==="AWAITING_CLOSE_REVIEW"&&n.reporter_user_id!==data.actor.user_id&&n.owner_user_id!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({evidence:"",note:""});setModal({kind:"CLOSE_NC",nc:n})}}><FileCheck2/>Independent closure</button>:null}</div></article>)}{!data.nonconformances.length?<div className={styles.empty}>No nonconformances in your scope.</div>:null}</div>:null}

  {view==="capa"?<div className={styles.grid}>{data.capas.map(c=>{const n=ncMap.get(c.nonconformance_id);const next=capaNext(c,data.capabilities.capa_review);return <article className={styles.card} key={c.id}><header><div><small>{c.capa_code} · {c.action_type}</small><h3>{n?.title||"CAPA"}</h3><span>Due {fmtDate(c.due_on)}</span></div><em className={styles.badge} data-status={c.status}>{c.status.replaceAll("_"," ")}</em></header><p><b>Root cause:</b> {c.root_cause}</p><p><b>Action plan:</b> {c.action_plan}</p><div className={styles.kv}><span>Owner<b>{people.get(c.owner_user_id)?.display_name||c.owner_user_id}</b></span><span>Completion evidence<b>{c.completion_evidence_reference||"—"}</b></span><span>Effectiveness evidence<b>{c.effectiveness_evidence_reference||"—"}</b></span><span>Review note<b>{c.review_note||"—"}</b></span></div>{next.length&&(c.owner_user_id===data.actor.user_id||data.capabilities.capa_manage||data.capabilities.capa_review)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:next[0],completion_evidence:c.completion_evidence_reference||"",effectiveness_evidence:c.effectiveness_evidence_reference||"",note:c.review_note||""});setModal({kind:"CAPA_STATUS",capa:c})}}><ClipboardCheck/>Advance / verify</button></div>:null}</article>})}{!data.capas.length?<div className={styles.empty}>No CAPA records in your scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED QUALITY ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="PROCESS"?<ProcessFields draft={draft} setDraft={setDraft} people={data.people} includeDepartment />
   :modal.kind==="VERSION"?<ProcessFields draft={draft} setDraft={setDraft} people={[]} />
   :modal.kind==="PUBLISH"?<p>Publish process revision <b>v{modal.version.version}</b>? The previously published revision becomes superseded.</p>
   :modal.kind==="REPORT_NC"?<><label>Published process<select value={draft.process_id||""} onChange={e=>setDraft({...draft,process_id:e.target.value})}><option value="">No linked process</option>{data.processes.filter(p=>p.status==="PUBLISHED").map(p=><option key={p.id} value={p.id}>{p.process_code} · {p.title}</option>)}</select></label><div className={styles.two}><label>Source<select value={draft.source||"OTHER"} onChange={e=>setDraft({...draft,source:e.target.value})}>{["PROCESS","AUDIT","CUSTOMER","INCIDENT","SECURITY","SUPPLIER","PRODUCT","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Severity<select value={draft.severity||"MEDIUM"} onChange={e=>setDraft({...draft,severity:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Evidence reference<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="MANAGE_NC"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{ncNext(modal.nc).map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Keep current</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label>{draft.status==="CONTAINED"?<label>Containment summary<textarea required minLength={3} value={draft.containment||""} onChange={e=>setDraft({...draft,containment:e.target.value})}/></label>:null}<label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="CLOSE_NC"?<><label>Closure evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="CAPA"?<><label>Action type<select value={draft.action_type||"CORRECTIVE"} onChange={e=>setDraft({...draft,action_type:e.target.value})}><option>CORRECTIVE</option><option>PREVENTIVE</option><option>BOTH</option></select></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select CAPA owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Root cause<textarea required minLength={3} value={draft.root_cause||""} onChange={e=>setDraft({...draft,root_cause:e.target.value})}/></label><label>Action plan<textarea required minLength={3} value={draft.action_plan||""} onChange={e=>setDraft({...draft,action_plan:e.target.value})}/></label><label>Due date<input type="date" value={draft.due_on||""} onChange={e=>setDraft({...draft,due_on:e.target.value})}/></label></>
   :<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{capaNext(modal.capa,data.capabilities.capa_review).map(v=><option key={v}>{v}</option>)}</select></label>{draft.status==="AWAITING_VERIFICATION"?<label>Completion evidence<input required minLength={3} value={draft.completion_evidence||""} onChange={e=>setDraft({...draft,completion_evidence:e.target.value})}/></label>:null}{["VERIFIED_EFFECTIVE","VERIFIED_INEFFECTIVE"].includes(draft.status)?<label>Effectiveness evidence<input required minLength={3} value={draft.effectiveness_evidence||""} onChange={e=>setDraft({...draft,effectiveness_evidence:e.target.value})}/></label>:null}<label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}

function ProcessFields({draft,setDraft,people,includeDepartment=false}:{draft:Record<string,string>;setDraft:(v:Record<string,string>)=>void;people:Person[];includeDepartment?:boolean}){
 return <>{includeDepartment?<><label>Process title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Department<input required minLength={2} value={draft.department||""} onChange={e=>setDraft({...draft,department:e.target.value.toUpperCase()})}/></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div></>:null}<label>Purpose<textarea required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><label>Scope<textarea required minLength={3} value={draft.scope||""} onChange={e=>setDraft({...draft,scope:e.target.value})}/></label><label>Procedure<textarea required minLength={10} value={draft.procedure||""} onChange={e=>setDraft({...draft,procedure:e.target.value})}/></label><label>Control points — one per line<textarea value={draft.controls||""} onChange={e=>setDraft({...draft,controls:e.target.value})}/></label><label>Evidence requirements — one per line<textarea value={draft.evidence_requirements||""} onChange={e=>setDraft({...draft,evidence_requirements:e.target.value})}/></label><label>Standard reference<input value={draft.standard_reference||""} onChange={e=>setDraft({...draft,standard_reference:e.target.value})}/></label>{includeDepartment?<label>Next review<input type="date" value={draft.next_review_on||""} onChange={e=>setDraft({...draft,next_review_on:e.target.value})}/></label>:<label>Change summary<input value={draft.change_summary||""} onChange={e=>setDraft({...draft,change_summary:e.target.value})}/></label>}</>
}
