"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, FileCheck2, LoaderCircle, RefreshCw, Scale, ShieldCheck, UserRoundCog, UsersRound, X } from "lucide-react";
import styles from "./office-ownership.module.css";

type ShareClass={id:string;code:string;name:string;face_value:string;authorised_shares:number;voting_rights_per_share:number;status:string;source_document_ref?:string|null;issued_shares?:number};
type Shareholder={id:string;shareholder_no:string;legal_name:string;folio_no?:string|null;email?:string|null;status:string;source_document_ref?:string|null};
type CapRow={shareholder:Shareholder;shares:number;ownership_percent:string;by_class:Record<string,number>};
type OwnershipSummary={total_issued_shares:number;classes:ShareClass[];cap_table:CapRow[];source:string};
type LedgerRow={id:string;shareholder_id:string;share_class_id:string;entry_type:string;quantity_delta:number;instrument_date:string;certificate_no?:string|null;counterparty_ref?:string|null;source_document_ref:string;posted_by:string};
type ShareChange={id:string;shareholder_id:string;share_class_id:string;entry_type:string;quantity_delta:number;instrument_date:string;status:string;approval_request_id?:string|null;posted_ledger_entry_id?:string|null};
type ShareTransfer={id:string;from_shareholder_id:string;to_shareholder_id:string;share_class_id:string;quantity:number;instrument_date:string;status:string;approval_request_id?:string|null;out_ledger_entry_id?:string|null;in_ledger_entry_id?:string|null};
type Approval={id:string;action_type:string;entity_type:string;entity_id:string;requested_by:string;required_role:string;status:"PENDING"|"APPROVED"|"REJECTED";decided_by?:string|null;decision_reason?:string|null};
type Dialog={kind:"CHANGE"}|{kind:"TRANSFER"}|{kind:"DECIDE";approval:Approval;decision:"approve"|"reject"}|{kind:"POST_CHANGE";change:ShareChange}|{kind:"POST_TRANSFER";transfer:ShareTransfer};
type Draft=Record<string,string>;

async function runtime<T>(path:string,options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-runtime/"+path,{...options,credentials:"same-origin",cache:"no-store"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Ownership runtime request failed");
 return body as T;
}
function headers(){return {"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()}}
function date(value?:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(d)}
function signed(value:number){return value>0?"+"+value:String(value)}

export function OfficeOwnershipWorkspace({canStage,canDecide,canPost}:{canStage:boolean;canDecide:boolean;canPost:boolean}){
 const[summary,setSummary]=useState<OwnershipSummary>();const[ledger,setLedger]=useState<LedgerRow[]>([]);const[changes,setChanges]=useState<ShareChange[]>([]);const[transfers,setTransfers]=useState<ShareTransfer[]>([]);const[holders,setHolders]=useState<Shareholder[]>([]);const[classes,setClasses]=useState<ShareClass[]>([]);const[approvals,setApprovals]=useState<Approval[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[dialog,setDialog]=useState<Dialog>();const[draft,setDraft]=useState<Draft>({});const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 const fetchRecords=useCallback(()=>Promise.all([runtime<OwnershipSummary>("ownership/summary"),runtime<LedgerRow[]>("ownership/ledger"),runtime<ShareChange[]>("ownership/share-changes"),runtime<ShareTransfer[]>("ownership/transfers"),runtime<Shareholder[]>("ownership/shareholders"),runtime<ShareClass[]>("ownership/share-classes"),runtime<Approval[]>("approvals")]),[]);
 const apply=useCallback(([s,l,c,t,h,cl,a]:[OwnershipSummary,LedgerRow[],ShareChange[],ShareTransfer[],Shareholder[],ShareClass[],Approval[]])=>{setSummary(s);setLedger(l);setChanges(c);setTransfers(t);setHolders(h);setClasses(cl);setApprovals(a)},[]);
 const load=useCallback(async()=>{setLoading(true);setError(undefined);try{apply(await fetchRecords())}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load ownership records")}finally{setLoading(false)}},[apply,fetchRecords]);
 useEffect(()=>{let active=true;void fetchRecords().then(records=>{if(active)apply(records)}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:"Unable to load ownership records")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[apply,fetchRecords]);

 const holderMap=useMemo(()=>new Map(holders.map(h=>[h.id,h])),[holders]);const classMap=useMemo(()=>new Map(classes.map(c=>[c.id,c])),[classes]);const approvalMap=useMemo(()=>new Map(approvals.filter(a=>["SHARE_CHANGE_POST","SHARE_TRANSFER_POST"].includes(a.action_type)).map(a=>[a.entity_type+":"+a.entity_id,a])),[approvals]);

 async function refresh(message:string){setNotice(message);setDialog(undefined);setDraft({});await load()}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!dialog)return;setBusy(true);setError(undefined);try{
  if(dialog.kind==="CHANGE"){
   const outbound=["CANCEL","ADJUSTMENT_OUT"].includes(draft.entry_type);const quantity=Math.abs(Number(draft.quantity||"0"));
   await runtime("ownership/share-changes",{method:"POST",headers:headers(),body:JSON.stringify({shareholder_id:draft.shareholder_id,share_class_id:draft.share_class_id,entry_type:draft.entry_type,quantity_delta:outbound?-quantity:quantity,instrument_date:draft.instrument_date,source_document_ref:draft.source_document_ref,certificate_no:draft.certificate_no||undefined,counterparty_ref:draft.counterparty_ref||undefined,note:draft.note||undefined})});
   await refresh("Share change staged. Legal ownership has not changed; independent approval and posting are still required.");
  }else if(dialog.kind==="TRANSFER"){
   await runtime("ownership/transfers",{method:"POST",headers:headers(),body:JSON.stringify({from_shareholder_id:draft.from_shareholder_id,to_shareholder_id:draft.to_shareholder_id,share_class_id:draft.share_class_id,quantity:Number(draft.quantity||"0"),instrument_date:draft.instrument_date,source_document_ref:draft.source_document_ref,note:draft.note||undefined})});
   await refresh("Share transfer staged. No ledger movement has occurred until approval and posting.");
  }else if(dialog.kind==="DECIDE"){
   await runtime("approvals/"+encodeURIComponent(dialog.approval.id)+"/"+dialog.decision,{method:"POST",headers:headers(),body:JSON.stringify({reason:draft.reason||undefined})});
   await refresh("Ownership approval decision recorded through maker-checker controls.");
  }else{
   if((draft.confirmation||"").trim().toUpperCase()!=="POST OWNERSHIP")throw new Error("Type POST OWNERSHIP to confirm ledger posting");
   const path=dialog.kind==="POST_CHANGE"?"ownership/share-changes/"+encodeURIComponent(dialog.change.id)+"/post":"ownership/transfers/"+encodeURIComponent(dialog.transfer.id)+"/post";
   await runtime(path,{method:"POST",headers:headers(),body:"{}"});
   await refresh("Approved ownership instrument posted to the append-only share ledger.");
  }
 }catch(caught){setError(caught instanceof Error?caught.message:"Ownership action failed")}finally{setBusy(false)}}

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>OWNERSHIP · CAP TABLE · FUNDING</p><h2>Keep legal ownership append-only, evidence-backed, and separated from expense funding.</h2><span>Share issues, cancellations, adjustments and transfers are staged first, independently approved, then explicitly posted. Expense funding never edits the cap table.</span></div><div className={styles.guard}><Scale/><span>Ledger model</span><b>Append-only ownership evidence</b></div></header>
  <div className={styles.toolbar}><button type="button" onClick={()=>void load()} disabled={loading||busy}><RefreshCw/>Refresh</button>{canStage?<><button type="button" disabled={busy||!holders.length||!classes.length} onClick={()=>{setDraft({entry_type:"ISSUE",instrument_date:new Date().toISOString().slice(0,10)});setDialog({kind:"CHANGE"})}}><UserRoundCog/>Stage share change</button><button type="button" disabled={busy||holders.length<2||!classes.length} onClick={()=>{setDraft({instrument_date:new Date().toISOString().slice(0,10)});setDialog({kind:"TRANSFER"})}}><UsersRound/>Stage transfer</button></>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}
  {loading?<div className={styles.state}><LoaderCircle className={styles.spin}/>Loading canonical ownership ledger…</div>:<>
   <div className={styles.metrics}><article><span>Issued shares</span><b>{summary?.total_issued_shares||0}</b></article><article><span>Active shareholders</span><b>{summary?.cap_table.length||0}</b></article><article><span>Share classes</span><b>{summary?.classes.length||0}</b></article><article><span>Ledger entries</span><b>{ledger.length}</b></article></div>
   <section className={styles.panel}><header className={styles.panelHead}><div><p>CAP TABLE</p><h3>Current holdings derived from the ledger</h3></div><span>{summary?.source||"append-only share ledger"}</span></header><div className={styles.capGrid}>{summary?.cap_table.map(row=><article className={styles.capCard} key={row.shareholder.id}><small>{row.shareholder.shareholder_no}</small><h4>{row.shareholder.legal_name}</h4><b>{row.shares} shares · {row.ownership_percent}%</b><div>{summary.classes.map(c=><span key={c.id}>{c.code}: {row.by_class[c.id]||0}</span>)}</div></article>)}{!summary?.cap_table.length?<div className={styles.empty}>No issued-share ledger balances exist yet.</div>:null}</div></section>
   <section className={styles.panel}><header className={styles.panelHead}><div><p>PENDING INSTRUMENTS</p><h3>Share changes and transfers</h3></div><span>Staging and approval do not alter ownership. Only the final post action writes ledger entries.</span></header><div className={styles.cards}>{changes.map(change=>{const approval=approvalMap.get("share_change:"+change.id);return <article className={styles.card} key={change.id}><header><div><small>SHARE CHANGE · {change.entry_type}</small><h4>{holderMap.get(change.shareholder_id)?.legal_name||change.shareholder_id}</h4></div><em data-status={change.status}>{change.status}</em></header><b>{signed(change.quantity_delta)} {classMap.get(change.share_class_id)?.code||"shares"}</b><span>{date(change.instrument_date)}</span>{approval?<div className={styles.approval}><ShieldCheck/><div><strong>{approval.status}</strong><span>{approval.id} · requires {approval.required_role}</span></div></div>:null}<div className={styles.actions}>{approval?.status==="PENDING"&&canDecide?<><button type="button" disabled={busy} onClick={()=>{setDraft({});setDialog({kind:"DECIDE",approval,decision:"approve"})}}><BadgeCheck/>Approve</button><button type="button" disabled={busy} onClick={()=>{setDraft({});setDialog({kind:"DECIDE",approval,decision:"reject"})}}><CircleAlert/>Reject</button></>:null}{approval?.status==="APPROVED"&&change.status!=="POSTED"&&canPost?<button type="button" disabled={busy} onClick={()=>{setDraft({});setDialog({kind:"POST_CHANGE",change})}}><FileCheck2/>Post approved change</button>:null}</div></article>})}
    {transfers.map(transfer=>{const approval=approvalMap.get("share_transfer:"+transfer.id);return <article className={styles.card} key={transfer.id}><header><div><small>SHARE TRANSFER</small><h4>{holderMap.get(transfer.from_shareholder_id)?.legal_name||transfer.from_shareholder_id} → {holderMap.get(transfer.to_shareholder_id)?.legal_name||transfer.to_shareholder_id}</h4></div><em data-status={transfer.status}>{transfer.status}</em></header><b>{transfer.quantity} {classMap.get(transfer.share_class_id)?.code||"shares"}</b><span>{date(transfer.instrument_date)}</span>{approval?<div className={styles.approval}><ShieldCheck/><div><strong>{approval.status}</strong><span>{approval.id} · requires {approval.required_role}</span></div></div>:null}<div className={styles.actions}>{approval?.status==="PENDING"&&canDecide?<><button type="button" disabled={busy} onClick={()=>{setDraft({});setDialog({kind:"DECIDE",approval,decision:"approve"})}}><BadgeCheck/>Approve</button><button type="button" disabled={busy} onClick={()=>{setDraft({});setDialog({kind:"DECIDE",approval,decision:"reject"})}}><CircleAlert/>Reject</button></>:null}{approval?.status==="APPROVED"&&transfer.status!=="POSTED"&&canPost?<button type="button" disabled={busy} onClick={()=>{setDraft({});setDialog({kind:"POST_TRANSFER",transfer})}}><FileCheck2/>Post approved transfer</button>:null}</div></article>})}{!changes.length&&!transfers.length?<div className={styles.empty}>No staged ownership instruments.</div>:null}</div></section>
   <section className={styles.panel}><header className={styles.panelHead}><div><p>SHARE LEDGER</p><h3>Posted legal ownership evidence</h3></div><span>Historical entries are not edited in place; corrections use new controlled entries.</span></header><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Shareholder</th><th>Class</th><th>Type</th><th>Quantity</th><th>Certificate / counterparty</th><th>Source evidence</th></tr></thead><tbody>{ledger.map(row=><tr key={row.id}><td>{date(row.instrument_date)}</td><td>{holderMap.get(row.shareholder_id)?.legal_name||row.shareholder_id}</td><td>{classMap.get(row.share_class_id)?.code||row.share_class_id}</td><td>{row.entry_type}</td><td>{signed(row.quantity_delta)}</td><td>{row.certificate_no||row.counterparty_ref||"—"}</td><td>{row.source_document_ref}</td></tr>)}{!ledger.length?<tr><td colSpan={7}><div className={styles.empty}>No ownership ledger entries.</div></td></tr>:null}</tbody></table></div></section>
  </>}
  {dialog?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setDialog(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>LEGAL OWNERSHIP CONTROL</small><h3>{dialog.kind==="CHANGE"?"Stage share change":dialog.kind==="TRANSFER"?"Stage share transfer":dialog.kind==="DECIDE"?(dialog.decision==="approve"?"Approve":"Reject")+" ownership request":"Post approved ownership instrument"}</h3></div><button type="button" aria-label="Close" disabled={busy} onClick={()=>setDialog(undefined)}><X/></button></header>
   {dialog.kind==="CHANGE"?<><label>Shareholder<select required value={draft.shareholder_id||""} onChange={e=>setDraft({...draft,shareholder_id:e.target.value})}><option value="">Select shareholder</option>{holders.filter(h=>h.status==="ACTIVE").map(h=><option key={h.id} value={h.id}>{h.shareholder_no} · {h.legal_name}</option>)}</select></label><div className={styles.two}><label>Share class<select required value={draft.share_class_id||""} onChange={e=>setDraft({...draft,share_class_id:e.target.value})}><option value="">Select class</option>{classes.filter(c=>c.status==="ACTIVE").map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label>Entry type<select value={draft.entry_type||"ISSUE"} onChange={e=>setDraft({...draft,entry_type:e.target.value})}><option>ISSUE</option><option>CANCEL</option><option>ADJUSTMENT_IN</option><option>ADJUSTMENT_OUT</option></select></label></div><div className={styles.two}><label>Quantity<input required type="number" min="1" step="1" value={draft.quantity||""} onChange={e=>setDraft({...draft,quantity:e.target.value})}/></label><label>Instrument date<input required type="date" value={draft.instrument_date||""} onChange={e=>setDraft({...draft,instrument_date:e.target.value})}/></label></div><label>Source document reference<input required minLength={2} value={draft.source_document_ref||""} onChange={e=>setDraft({...draft,source_document_ref:e.target.value})}/></label><div className={styles.two}><label>Certificate number<input value={draft.certificate_no||""} onChange={e=>setDraft({...draft,certificate_no:e.target.value})}/></label><label>Counterparty reference<input value={draft.counterparty_ref||""} onChange={e=>setDraft({...draft,counterparty_ref:e.target.value})}/></label></div><label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><p className={styles.warning}>Staging does not alter ownership. The backend also blocks negative holdings and issues beyond authorised shares at post time.</p></>
   :dialog.kind==="TRANSFER"?<><div className={styles.two}><label>From shareholder<select required value={draft.from_shareholder_id||""} onChange={e=>setDraft({...draft,from_shareholder_id:e.target.value})}><option value="">Select source</option>{holders.filter(h=>h.status==="ACTIVE").map(h=><option key={h.id} value={h.id}>{h.legal_name}</option>)}</select></label><label>To shareholder<select required value={draft.to_shareholder_id||""} onChange={e=>setDraft({...draft,to_shareholder_id:e.target.value})}><option value="">Select destination</option>{holders.filter(h=>h.status==="ACTIVE"&&h.id!==draft.from_shareholder_id).map(h=><option key={h.id} value={h.id}>{h.legal_name}</option>)}</select></label></div><label>Share class<select required value={draft.share_class_id||""} onChange={e=>setDraft({...draft,share_class_id:e.target.value})}><option value="">Select class</option>{classes.filter(c=>c.status==="ACTIVE").map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><div className={styles.two}><label>Quantity<input required type="number" min="1" step="1" value={draft.quantity||""} onChange={e=>setDraft({...draft,quantity:e.target.value})}/></label><label>Instrument date<input required type="date" value={draft.instrument_date||""} onChange={e=>setDraft({...draft,instrument_date:e.target.value})}/></label></div><label>Source document reference<input required minLength={2} value={draft.source_document_ref||""} onChange={e=>setDraft({...draft,source_document_ref:e.target.value})}/></label><label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><p className={styles.warning}>The backend rejects self-transfers and transfers exceeding the source holder’s current ledger balance.</p></>
   :dialog.kind==="DECIDE"?<><label>Decision reason<textarea value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><p className={styles.warning}>The requester cannot decide their own approval. Maker-checker separation is enforced by the backend.</p></>
   :<><p>This action writes approved legal ownership evidence into the append-only share ledger.</p><div className={styles.execution}><CircleAlert/><div><b>POST OWNERSHIP</b><span>Posting can change the current cap table. Confirm only after the approved source instrument has been verified.</span></div></div><label>Confirmation<input required autoComplete="off" placeholder="Type POST OWNERSHIP" value={draft.confirmation||""} onChange={e=>setDraft({...draft,confirmation:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setDialog(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<BadgeCheck/>}Confirm</button></footer></form></div>:null}
 </section>
}
