"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, Bot, CircleAlert, FileKey2, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-ai-governance.module.css";

const DATA_CLASSES=["PUBLIC","INTERNAL","CONFIDENTIAL","RESTRICTED","BOARD","FINANCE","HR","LEGAL","SECURITY","CUSTOMER_CONFIDENTIAL"] as const;
type DataClass=(typeof DATA_CLASSES)[number];
type Caps={tool_read:boolean;tool_manage:boolean;tool_review:boolean;use_request:boolean;use_read:boolean;use_review:boolean;usage_audit:boolean};
type Person={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null};
type Tool={id:string;tool_code:string;provider_name:string;tool_name:string;purpose:string;external_service:boolean;allowed_data_classes:DataClass[];prohibited_data_classes:DataClass[];retention_policy:string;provider_training_policy:string;data_residency?:string|null;privacy_security_reference?:string|null;human_review_required:boolean;status:string;owner_user_id:string;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;review_note?:string|null;expires_on?:string|null;created_at:string;updated_at:string};
type UseCase={id:string;use_case_code:string;requester_user_id:string;department_code?:string|null;tool_id:string;title:string;purpose:string;intended_data_classes:DataClass[];action_mode:string;human_review_required:boolean;status:string;reviewer_user_id?:string|null;reviewed_at?:string|null;review_note?:string|null;expires_at?:string|null;created_at:string;updated_at:string};
type Usage={id:number;use_case_id:string;actor_user_id:string;action_kind:string;data_classes:DataClass[];content_sha256?:string|null;provider_reference?:string|null;result_reference?:string|null;human_review_reference?:string|null;created_at:string};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};capabilities:Caps;tools:Tool[];use_cases:UseCase[];usage_events:Usage[];people:Person[];disclaimer:string};
type View="tools"|"uses"|"usage";
type Modal=
 |{kind:"TOOL"}
 |{kind:"TOOL_STATUS";tool:Tool}
 |{kind:"REQUEST_USE";tool?:Tool}
 |{kind:"REVIEW_USE";useCase:UseCase}
 |{kind:"RECORD_USAGE";useCase:UseCase};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-ai-governance",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"AI governance request failed");
 return body as T;
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value.length===10?value+"T00:00:00":value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:value.length>10?"short":undefined}).format(d)}
function toIso(value?:string){if(!value)return undefined;const d=new Date(value);return Number.isNaN(d.getTime())?undefined:d.toISOString()}
function csv(value?:string){return (value||"").split(",").map(v=>v.trim()).filter((v):v is DataClass=>DATA_CLASSES.includes(v as DataClass))}
function toggle(current:string|undefined,value:DataClass){const set=new Set(csv(current));if(set.has(value))set.delete(value);else set.add(value);return [...set].join(",")}
function toolNext(tool:Tool,review:boolean){if(tool.status==="DRAFT")return ["SUBMITTED"];if(tool.status==="SUBMITTED")return review?["APPROVED","REJECTED"]:[];if(tool.status==="APPROVED")return review?["RETIRED"]:[];return []}

export function OfficeAiGovernance(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("tools");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load AI Governance")});return()=>{alive=false}},[]);
 const tools=useMemo(()=>new Map((data?.tools??[]).map(row=>[row.id,row])),[data?.tools]);
 const people=useMemo(()=>new Map((data?.people??[]).map(row=>[row.user_id,row])),[data?.people]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="TOOL")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_TOOL",provider:draft.provider,tool:draft.tool,purpose:draft.purpose,external:draft.external!=="NO",allowed:csv(draft.allowed),prohibited:csv(draft.prohibited),retention:draft.retention,training_policy:draft.training_policy,data_residency:draft.data_residency||undefined,privacy_security_reference:draft.reference||undefined,human_review_required:draft.human_review!=="NO",owner_user_id:draft.owner_user_id,expires_on:draft.expires_on||undefined})});
  else if(modal.kind==="TOOL_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_TOOL",tool_id:modal.tool.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="REQUEST_USE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REQUEST_USE",tool_id:draft.tool_id||modal.tool?.id,title:draft.title,purpose:draft.purpose,data_classes:csv(draft.data_classes),action_mode:draft.action_mode||"DRAFT",human_review_required:draft.human_review!=="NO"})});
  else if(modal.kind==="REVIEW_USE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_USE",use_case_id:modal.useCase.id,status:draft.status,expires_at:draft.status==="APPROVED"?toIso(draft.expires_at):undefined,note:draft.note||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"RECORD_USAGE",use_case_id:modal.useCase.id,action_kind:modal.useCase.action_mode,data_classes:csv(draft.data_classes),content_sha256:draft.content_sha256||undefined,provider_reference:draft.provider_reference||undefined,result_reference:draft.result_reference||undefined,human_review_reference:draft.human_review_reference||undefined})});
  await reload("AI Governance updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"AI governance action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>AI Governance unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading AI Governance</h2><p>Resolving tool and use-case authority.</p></div></section>;
 const approvedTools=data.tools.filter(t=>t.status==="APPROVED").length;
 const pendingUses=data.use_cases.filter(u=>u.status==="REQUESTED").length;
 const activeUses=data.use_cases.filter(u=>u.status==="APPROVED"&&(!u.expires_at||new Date(u.expires_at).getTime()>Date.now())).length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>AI TOOLS · DATA BOUNDARIES · HUMAN REVIEW</p><h2>Approve the use of AI before company data reaches a model provider.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{approvedTools}</b><span>approved tools</span></article><article><b>{pendingUses}</b><span>use cases awaiting review</span></article><article><b>{activeUses}</b><span>approved use cases</span></article></div></header>
  <div className={styles.warning}><Bot/><div><b>No model invocation here</b><span>This workspace governs providers and use cases. It never sends prompts or company data to an AI provider.</span></div></div>
  <div className={styles.toolbar}>{(["tools","uses",...(data.capabilities.usage_audit?["usage" as const]:[])] as View[]).map(item=><button type="button" key={item} data-active={view===item} onClick={()=>setView(item)}>{item==="uses"?"Use cases":item[0].toUpperCase()+item.slice(1)}</button>)}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="tools"&&data.capabilities.tool_manage?<button type="button" onClick={()=>{setDraft({external:"YES",allowed:"PUBLIC,INTERNAL",prohibited:"",human_review:"YES"});setModal({kind:"TOOL"})}}><Plus/>Assess tool</button>:null}{view==="uses"&&data.capabilities.use_request&&data.tools.some(t=>t.status==="APPROVED")?<button type="button" onClick={()=>{setDraft({action_mode:"DRAFT",human_review:"YES"});setModal({kind:"REQUEST_USE"})}}><Plus/>Request use</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="tools"?<div className={styles.grid}>{data.tools.map(tool=>{const next=toolNext(tool,data.capabilities.tool_review);return <article className={styles.card} key={tool.id}><header><div><small>{tool.tool_code} · {tool.provider_name}</small><h3>{tool.tool_name}</h3><span>{tool.external_service?"External provider":"Internal tool"}</span></div><em className={styles.badge} data-status={tool.status}>{tool.status}</em></header><p>{tool.purpose}</p><div className={styles.boundaries}><div><b>Allowed</b>{tool.allowed_data_classes.map(c=><span key={c}>{c}</span>)}</div><div><b>Prohibited</b>{tool.prohibited_data_classes.length?tool.prohibited_data_classes.map(c=><span key={c}>{c}</span>):<span>None listed</span>}</div></div><div className={styles.kv}><span>Retention<b>{tool.retention_policy}</b></span><span>Provider training<b>{tool.provider_training_policy}</b></span><span>Data residency<b>{tool.data_residency||"—"}</b></span><span>Human review<b>{tool.human_review_required?"Required":"Policy-dependent"}</b></span><span>Evidence<b>{tool.privacy_security_reference||"—"}</b></span><span>Expires<b>{date(tool.expires_on)}</b></span></div><div className={styles.actions}>{next.length&&(data.capabilities.tool_manage||data.capabilities.tool_review)&&!(data.capabilities.tool_review&&(tool.owner_user_id===data.actor.user_id||tool.created_by===data.actor.user_id)&&tool.status==="SUBMITTED")?<button type="button" onClick={()=>{setDraft({status:next[0],note:""});setModal({kind:"TOOL_STATUS",tool})}}><ShieldCheck/>Review / advance</button>:null}{tool.status==="APPROVED"&&data.capabilities.use_request?<button type="button" onClick={()=>{setDraft({tool_id:tool.id,action_mode:"DRAFT",human_review:"YES"});setModal({kind:"REQUEST_USE",tool})}}>Request use</button>:null}</div></article>})}{!data.tools.length?<div className={styles.empty}>No approved AI tools are visible in your authority.</div>:null}</div>:null}

  {view==="uses"?<div className={styles.grid}>{data.use_cases.map(useCase=>{const tool=tools.get(useCase.tool_id);return <article className={styles.card} key={useCase.id}><header><div><small>{useCase.use_case_code} · {tool?.tool_name||"AI tool"}</small><h3>{useCase.title}</h3><span>{useCase.action_mode.replaceAll("_"," ")} · {useCase.department_code||"No department"}</span></div><em className={styles.badge} data-status={useCase.status}>{useCase.status}</em></header><p>{useCase.purpose}</p><div className={styles.boundaries}><div><b>Approved/requested data classes</b>{useCase.intended_data_classes.length?useCase.intended_data_classes.map(c=><span key={c}>{c}</span>):<span>No classified company data</span>}</div></div><div className={styles.kv}><span>Requester<b>{people.get(useCase.requester_user_id)?.display_name||(useCase.requester_user_id===data.actor.user_id?"You":useCase.requester_user_id)}</b></span><span>Human review<b>{useCase.human_review_required?"Required":"Not mandated"}</b></span><span>Expires<b>{date(useCase.expires_at)}</b></span><span>Review note<b>{useCase.review_note||"—"}</b></span></div><div className={styles.actions}>{useCase.status==="REQUESTED"&&data.capabilities.use_review&&useCase.requester_user_id!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({status:"APPROVED",note:""});setModal({kind:"REVIEW_USE",useCase})}}><ShieldCheck/>Review request</button>:null}{useCase.status==="APPROVED"&&useCase.requester_user_id===data.actor.user_id?<button type="button" onClick={()=>{setDraft({data_classes:useCase.intended_data_classes.join(",")});setModal({kind:"RECORD_USAGE",useCase})}}><FileKey2/>Record usage metadata</button>:null}</div></article>})}{!data.use_cases.length?<div className={styles.empty}>No AI use cases in your authorised scope.</div>:null}</div>:null}

  {view==="usage"&&data.capabilities.usage_audit?<div className={styles.grid}>{data.usage_events.map(event=><article className={styles.audit} key={event.id}><div><small>{date(event.created_at)}</small><b>{event.action_kind.replaceAll("_"," ")}</b><span>{event.data_classes.join(", ")||"No classified data"}</span></div><div><span>Content hash</span><code>{event.content_sha256||"not recorded"}</code><span>Provider ref</span><code>{event.provider_reference||"—"}</code><span>Result ref</span><code>{event.result_reference||"—"}</code><span>Human review</span><code>{event.human_review_reference||"—"}</code></div></article>)}{!data.usage_events.length?<div className={styles.empty}>No AI usage metadata in your audit scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>AI GOVERNANCE ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="TOOL"?<><div className={styles.two}><label>Provider<input required minLength={2} value={draft.provider||""} onChange={e=>setDraft({...draft,provider:e.target.value})}/></label><label>Tool / model product<input required minLength={2} value={draft.tool||""} onChange={e=>setDraft({...draft,tool:e.target.value})}/></label></div><label>Purpose<textarea required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><ClassPicker label="Allowed data classes" value={draft.allowed} onChange={value=>setDraft({...draft,allowed:value})}/><ClassPicker label="Prohibited data classes" value={draft.prohibited} onChange={value=>setDraft({...draft,prohibited:value})}/><label>Provider retention policy<textarea required minLength={3} value={draft.retention||""} onChange={e=>setDraft({...draft,retention:e.target.value})}/></label><label>Provider training policy<textarea required minLength={3} value={draft.training_policy||""} onChange={e=>setDraft({...draft,training_policy:e.target.value})}/></label><div className={styles.two}><label>Data residency<input value={draft.data_residency||""} onChange={e=>setDraft({...draft,data_residency:e.target.value})}/></label><label>Assessment/evidence reference<input value={draft.reference||""} onChange={e=>setDraft({...draft,reference:e.target.value})}/></label></div><div className={styles.three}><label>External service<select value={draft.external||"YES"} onChange={e=>setDraft({...draft,external:e.target.value})}><option>YES</option><option>NO</option></select></label><label>Human review<select value={draft.human_review||"YES"} onChange={e=>setDraft({...draft,human_review:e.target.value})}><option>YES</option><option>NO</option></select></label><label>Approval expiry<input type="date" value={draft.expires_on||""} onChange={e=>setDraft({...draft,expires_on:e.target.value})}/></label></div></>
   :modal.kind==="TOOL_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{toolNext(modal.tool,data.capabilities.tool_review).map(v=><option key={v}>{v}</option>)}</select></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="REQUEST_USE"?<><label>Approved tool<select required value={draft.tool_id||modal.tool?.id||""} onChange={e=>setDraft({...draft,tool_id:e.target.value})}><option value="">Select approved tool</option>{data.tools.filter(t=>t.status==="APPROVED").map(t=><option key={t.id} value={t.id}>{t.tool_code} · {t.provider_name} · {t.tool_name}</option>)}</select></label><label>Use-case title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Purpose<textarea required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><ClassPicker label="Intended data classes" value={draft.data_classes} onChange={value=>setDraft({...draft,data_classes:value})}/><div className={styles.two}><label>Action mode<select value={draft.action_mode||"DRAFT"} onChange={e=>setDraft({...draft,action_mode:e.target.value})}>{["QUERY","ANALYZE","DRAFT","RECOMMENDATION","ACTION_PROPOSAL"].map(v=><option key={v}>{v}</option>)}</select></label><label>Human review<select value={draft.human_review||"YES"} onChange={e=>setDraft({...draft,human_review:e.target.value})}><option>YES</option><option>NO</option></select></label></div></>
   :modal.kind==="REVIEW_USE"?<><label>Decision<select value={draft.status||"APPROVED"} onChange={e=>setDraft({...draft,status:e.target.value})}><option>APPROVED</option><option>REJECTED</option></select></label>{draft.status!=="REJECTED"?<label>Approval expires<input required type="datetime-local" value={draft.expires_at||""} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></label>:null}<label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :<><ClassPicker label="Data classes actually used" value={draft.data_classes} onChange={value=>setDraft({...draft,data_classes:value})}/><label>Content SHA-256 (optional)<input pattern="[0-9a-fA-F]{64}" value={draft.content_sha256||""} onChange={e=>setDraft({...draft,content_sha256:e.target.value})}/></label><div className={styles.two}><label>Provider reference<input value={draft.provider_reference||""} onChange={e=>setDraft({...draft,provider_reference:e.target.value})}/></label><label>Result reference<input value={draft.result_reference||""} onChange={e=>setDraft({...draft,result_reference:e.target.value})}/></label></div>{modal.useCase.human_review_required&&modal.useCase.action_mode==="ACTION_PROPOSAL"?<label>Human review reference<input required value={draft.human_review_reference||""} onChange={e=>setDraft({...draft,human_review_reference:e.target.value})}/></label>:<label>Human review reference<input value={draft.human_review_reference||""} onChange={e=>setDraft({...draft,human_review_reference:e.target.value})}/></label>}<p className={styles.muted}>Record metadata only. Do not paste the prompt or model output into this governance form.</p></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}

function ClassPicker({label,value,onChange}:{label:string;value?:string;onChange:(value:string)=>void}){
 return <fieldset className={styles.classPicker}><legend>{label}</legend>{DATA_CLASSES.map(item=><label key={item}><input type="checkbox" checked={csv(value).includes(item)} onChange={()=>onChange(toggle(value,item))}/>{item.replaceAll("_"," ")}</label>)}</fieldset>
}
