"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CalendarClock, CircleAlert, LoaderCircle, Plus, RefreshCw, RotateCcw, ShieldCheck, Siren, X } from "lucide-react";
import styles from "./office-engineering-operations.module.css";

type ServiceAccess={
 service:{id:string;service_code:string;name:string;project_key:string;environment:string;owner_team?:string|null;status:string};
 permissions:{oncall_read:boolean;oncall_manage:boolean;maintenance_read:boolean;maintenance_manage:boolean;maintenance_approve:boolean;maintenance_verify:boolean};
};
type Rotation={id:string;rotation_code:string;service_id:string;primary_user_id:string;secondary_user_id?:string|null;starts_at:string;ends_at:string;status:string;note?:string|null;created_by:string;cancelled_by?:string|null;cancelled_at?:string|null;created_at:string;updated_at:string;is_current:boolean};
type Maintenance={id:string;maintenance_code:string;service_id:string;title:string;reason:string;expected_impact:string;implementation_plan:string;rollback_plan:string;owner_user_id:string;starts_at:string;ends_at:string;status:string;approval_reference?:string|null;approved_by?:string|null;approved_at?:string|null;verification_evidence_reference?:string|null;health_reference?:string|null;verified_by?:string|null;verified_at?:string|null;created_by:string;created_at:string;updated_at:string};
type Person={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null};
type Payload={actor:{user_id:string;roles:string[]};generated_at:string;services:ServiceAccess[];rotations:Rotation[];maintenance:Maintenance[];events:unknown[];people:Person[];disclaimer:string};
type View="oncall"|"maintenance";
type Modal=
 |{kind:"ONCALL"}
 |{kind:"CANCEL_ONCALL";rotation:Rotation}
 |{kind:"MAINTENANCE"}
 |{kind:"REVIEW_MAINTENANCE";maintenance:Maintenance}
 |{kind:"EXECUTE_MAINTENANCE";maintenance:Maintenance}
 |{kind:"VERIFY_MAINTENANCE";maintenance:Maintenance};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-engineering-operations",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Engineering operations request failed");
 return body as T;
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function toIso(value?:string){if(!value)return undefined;const d=new Date(value);return Number.isNaN(d.getTime())?undefined:d.toISOString()}

export function OfficeEngineeringOperations(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("oncall");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load engineering operations")});return()=>{alive=false}},[]);
 const services=useMemo(()=>new Map((data?.services??[]).map(row=>[row.service.id,row])),[data?.services]);
 const people=useMemo(()=>new Map((data?.people??[]).map(row=>[row.user_id,row])),[data?.people]);
 const canOncallManage=Boolean(data?.services.some(row=>row.permissions.oncall_manage));
 const canMaintenanceManage=Boolean(data?.services.some(row=>row.permissions.maintenance_manage));

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="ONCALL")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_ONCALL",service_id:draft.service_id,primary_user_id:draft.primary_user_id,secondary_user_id:draft.secondary_user_id||undefined,starts_at:toIso(draft.starts_at),ends_at:toIso(draft.ends_at),note:draft.note||undefined})});
  else if(modal.kind==="CANCEL_ONCALL")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CANCEL_ONCALL",rotation_id:modal.rotation.id,reason:draft.reason})});
  else if(modal.kind==="MAINTENANCE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_MAINTENANCE",service_id:draft.service_id,title:draft.title,reason:draft.reason,expected_impact:draft.expected_impact,implementation_plan:draft.implementation_plan,rollback_plan:draft.rollback_plan,owner_user_id:draft.owner_user_id,starts_at:toIso(draft.starts_at),ends_at:toIso(draft.ends_at)})});
  else if(modal.kind==="REVIEW_MAINTENANCE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_MAINTENANCE",maintenance_id:modal.maintenance.id,decision:draft.decision,approval_reference:draft.approval_reference||undefined,note:draft.note||undefined})});
  else if(modal.kind==="EXECUTE_MAINTENANCE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"EXECUTE_MAINTENANCE",maintenance_id:modal.maintenance.id,status:draft.status,evidence:draft.evidence||undefined,note:draft.note||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"VERIFY_MAINTENANCE",maintenance_id:modal.maintenance.id,evidence:draft.evidence,health_reference:draft.health_reference,note:draft.note||undefined})});
  await reload("Engineering operations updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Engineering operations action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Engineering operations unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading on-call and maintenance</h2></div></section>;
 const current=data.rotations.filter(row=>row.is_current).length;
 const proposed=data.maintenance.filter(row=>row.status==="PROPOSED").length;
 const inProgress=data.maintenance.filter(row=>row.status==="IN_PROGRESS").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>ON-CALL · MAINTENANCE WINDOWS</p><h2>Schedule operational coverage and production change windows without bypassing engineering authority.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{current}</b><span>current on-call rotations</span></article><article><b>{proposed}</b><span>maintenance awaiting review</span></article><article><b>{inProgress}</b><span>maintenance in progress</span></article></div></header>
  <div className={styles.toolbar}><button type="button" data-active={view==="oncall"} onClick={()=>setView("oncall")}>On-call</button><button type="button" data-active={view==="maintenance"} onClick={()=>setView("maintenance")}>Maintenance</button><button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="oncall"&&canOncallManage?<button type="button" onClick={()=>{setDraft({});setModal({kind:"ONCALL"})}}><Plus/>Schedule rotation</button>:null}{view==="maintenance"&&canMaintenanceManage?<button type="button" onClick={()=>{setDraft({});setModal({kind:"MAINTENANCE"})}}><Plus/>Propose maintenance</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="oncall"?<div className={styles.grid}>{data.rotations.map(row=>{const access=services.get(row.service_id);return <article className={styles.card} key={row.id}><header><div><small>{row.rotation_code} · {access?.service.service_code||"SERVICE"}</small><h3>{access?.service.name||"Engineering service"}</h3><span>{access?.service.project_key} · {access?.service.environment}</span></div><em className={styles.badge} data-status={row.is_current?"CURRENT":row.status}>{row.is_current?"CURRENT":row.status}</em></header><div className={styles.kv}><span>Primary<b>{people.get(row.primary_user_id)?.display_name||row.primary_user_id}</b></span><span>Secondary<b>{row.secondary_user_id?people.get(row.secondary_user_id)?.display_name||row.secondary_user_id:"—"}</b></span><span>Starts<b>{date(row.starts_at)}</b></span><span>Ends<b>{date(row.ends_at)}</b></span></div>{row.note?<p>{row.note}</p>:null}{row.status==="SCHEDULED"&&access?.permissions.oncall_manage?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({reason:""});setModal({kind:"CANCEL_ONCALL",rotation:row})}}>Cancel rotation</button></div>:null}</article>})}{!data.rotations.length?<div className={styles.empty}>No on-call rotations are visible in your project scope.</div>:null}</div>:null}

  {view==="maintenance"?<div className={styles.grid}>{data.maintenance.map(row=>{const access=services.get(row.service_id);const ownerOrCreator=row.owner_user_id===data.actor.user_id||row.created_by===data.actor.user_id;return <article className={styles.card} key={row.id}><header><div><small>{row.maintenance_code} · {access?.service.service_code||"SERVICE"}</small><h3>{row.title}</h3><span>{access?.service.name} · {date(row.starts_at)} → {date(row.ends_at)}</span></div><em className={styles.badge} data-status={row.status}>{row.status.replaceAll("_"," ")}</em></header><p>{row.reason}</p><div className={styles.kv}><span>Owner<b>{people.get(row.owner_user_id)?.display_name||row.owner_user_id}</b></span><span>Expected impact<b>{row.expected_impact}</b></span><span>Approval<b>{row.approval_reference||"—"}</b></span><span>Verification<b>{row.verification_evidence_reference||"—"}</b></span></div><details><summary>Implementation and rollback</summary><p><b>Implementation:</b> {row.implementation_plan}</p><p><b>Rollback:</b> {row.rollback_plan}</p>{row.health_reference?<p><b>Health evidence:</b> {row.health_reference}</p>:null}</details><div className={styles.actions}>{row.status==="PROPOSED"&&access?.permissions.maintenance_approve&&!ownerOrCreator?<button type="button" onClick={()=>{setDraft({decision:"APPROVED",approval_reference:"",note:""});setModal({kind:"REVIEW_MAINTENANCE",maintenance:row})}}><ShieldCheck/>Independent review</button>:null}{row.status==="APPROVED"&&access?.permissions.maintenance_manage&&ownerOrCreator?<button type="button" onClick={()=>{setDraft({status:"IN_PROGRESS",note:""});setModal({kind:"EXECUTE_MAINTENANCE",maintenance:row})}}>Start maintenance</button>:null}{row.status==="IN_PROGRESS"&&access?.permissions.maintenance_manage&&ownerOrCreator?<button type="button" onClick={()=>{setDraft({status:"ROLLED_BACK",evidence:"",note:""});setModal({kind:"EXECUTE_MAINTENANCE",maintenance:row})}}><RotateCcw/>Record rollback</button>:null}{row.status==="IN_PROGRESS"&&access?.permissions.maintenance_verify&&!ownerOrCreator?<button type="button" onClick={()=>{setDraft({evidence:"",health_reference:"",note:""});setModal({kind:"VERIFY_MAINTENANCE",maintenance:row})}}><ShieldCheck/>Verify completion</button>:null}</div></article>})}{!data.maintenance.length?<div className={styles.empty}>No maintenance windows are visible in your project scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>ENGINEERING OPERATIONS ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="ONCALL"?<><label>Service<select required value={draft.service_id||""} onChange={e=>setDraft({...draft,service_id:e.target.value})}><option value="">Select managed service</option>{data.services.filter(s=>s.permissions.oncall_manage).map(s=><option key={s.service.id} value={s.service.id}>{s.service.service_code} · {s.service.name}</option>)}</select></label><div className={styles.two}><label>Primary<select required value={draft.primary_user_id||""} onChange={e=>setDraft({...draft,primary_user_id:e.target.value})}><option value="">Select primary</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Secondary<select value={draft.secondary_user_id||""} onChange={e=>setDraft({...draft,secondary_user_id:e.target.value})}><option value="">None</option>{data.people.filter(p=>p.user_id!==draft.primary_user_id).map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><div className={styles.two}><label>Starts<input required type="datetime-local" value={draft.starts_at||""} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={draft.ends_at||""} onChange={e=>setDraft({...draft,ends_at:e.target.value})}/></label></div><label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="CANCEL_ONCALL"?<label>Cancellation reason<textarea required minLength={3} value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>
   :modal.kind==="MAINTENANCE"?<><label>Service<select required value={draft.service_id||""} onChange={e=>setDraft({...draft,service_id:e.target.value})}><option value="">Select change-authorised service</option>{data.services.filter(s=>s.permissions.maintenance_manage).map(s=><option key={s.service.id} value={s.service.id}>{s.service.service_code} · {s.service.name}</option>)}</select></label><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Reason<textarea required minLength={3} value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><label>Expected impact<textarea required minLength={3} value={draft.expected_impact||""} onChange={e=>setDraft({...draft,expected_impact:e.target.value})}/></label><label>Implementation plan<textarea required minLength={3} value={draft.implementation_plan||""} onChange={e=>setDraft({...draft,implementation_plan:e.target.value})}/></label><label>Rollback plan<textarea required minLength={3} value={draft.rollback_plan||""} onChange={e=>setDraft({...draft,rollback_plan:e.target.value})}/></label><div className={styles.two}><label>Starts<input required type="datetime-local" value={draft.starts_at||""} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={draft.ends_at||""} onChange={e=>setDraft({...draft,ends_at:e.target.value})}/></label></div></>
   :modal.kind==="REVIEW_MAINTENANCE"?<><label>Decision<select value={draft.decision||"APPROVED"} onChange={e=>setDraft({...draft,decision:e.target.value})}><option>APPROVED</option><option>REJECTED</option></select></label>{draft.decision!=="REJECTED"?<label>Approval reference<input required minLength={3} value={draft.approval_reference||""} onChange={e=>setDraft({...draft,approval_reference:e.target.value})}/></label>:null}<label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="EXECUTE_MAINTENANCE"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{modal.maintenance.status==="APPROVED"?<><option>IN_PROGRESS</option><option>CANCELLED</option></>:<option>ROLLED_BACK</option>}</select></label>{draft.status==="ROLLED_BACK"?<label>Rollback evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>:null}<label>Execution note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :<><label>Completion evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label><label>Health reference<input required minLength={3} value={draft.health_reference||""} onChange={e=>setDraft({...draft,health_reference:e.target.value})}/></label><label>Verification note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
