"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, HeartPulse, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-resilience.module.css";

type Caps={resilience_read:boolean;plan_manage:boolean;plan_review:boolean;test_manage:boolean;test_review:boolean;incident_report:boolean;incident_read:boolean;incident_manage:boolean;insurance_read:boolean;insurance_manage:boolean;insurance_review:boolean};
type Person={user_id:string;display_name?:string|null;job_title?:string|null};
type Site={id:string;site_code:string;name:string;status:string};
type Plan={id:string;plan_code:string;title:string;plan_type:string;criticality:string;owner_user_id:string;scope_text:string;recovery_order:string;fallback_procedure:string;communication_plan?:string|null;rto_minutes?:number|null;rpo_minutes?:number|null;next_test_on?:string|null;version:number;status:string;created_by:string;review_note?:string|null};
type Test={id:string;test_code:string;plan_id:string;test_type:string;owner_user_id:string;scheduled_on:string;conducted_at?:string|null;status:string;result_summary?:string|null;evidence_reference?:string|null;created_by:string};
type Incident={id:string;incident_code:string;reporter_user_id:string;site_id?:string|null;category:string;severity:string;title:string;description:string;status:string;incident_commander_user_id?:string|null;containment_summary?:string|null;recovery_summary?:string|null;evidence_reference?:string|null;opened_at:string};
type Policy={id:string;policy_code:string;insurance_type:string;provider_name:string;provider_policy_reference:string;coverage_summary:string;premium_paise?:number|null;currency:string;effective_on:string;expires_on:string;owner_user_id:string;document_reference:string;status:string;created_by:string};
type Claim={id:string;claim_code:string;policy_id:string;emergency_incident_id?:string|null;reported_by:string;owner_user_id:string;claim_amount_paise?:number|null;currency:string;description:string;evidence_reference:string;insurer_reference?:string|null;status:string;reviewed_by?:string|null;review_note?:string|null;payment_reference?:string|null;paid_at?:string|null};
type Payload={actor:{user_id:string};capabilities:Caps;plans:Plan[];tests:Test[];incidents:Incident[];policies:Policy[];claims:Claim[];people:Person[];sites:Site[];disclaimer:string};
type View="incidents"|"plans"|"tests"|"insurance";
type Modal={kind:"INCIDENT"}|{kind:"INCIDENT_STATUS";incident:Incident}|{kind:"PLAN"}|{kind:"PLAN_STATUS";plan:Plan}|{kind:"TEST";plan?:Plan}|{kind:"TEST_STATUS";test:Test}|{kind:"POLICY"}|{kind:"CLAIM";policy?:Policy}|{kind:"CLAIM_STATUS";claim:Claim};

async function api<T>(options?:RequestInit):Promise<T>{const r=await fetch("/api/office-resilience",{...options,cache:"no-store",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Resilience operation failed");return b as T}
function date(value?:string|null){if(!value)return "—";const d=new Date(value.length===10?value+"T00:00:00":value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:value.length>10?"short":undefined}).format(d)}
function money(value?:number|null,currency="INR"){if(value==null)return "—";return currency+" "+(value/100).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function planNext(row:Plan,review:boolean){if(row.status==="DRAFT")return ["SUBMITTED"];if(row.status==="SUBMITTED")return review?["APPROVED","REJECTED"]:[];if(row.status==="APPROVED")return ["ACTIVE",...(review?["RETIRED"]:[])];if(row.status==="ACTIVE")return review?["RETIRED"]:[];return []}
function testNext(row:Test,review:boolean){if(row.status==="PLANNED")return ["IN_PROGRESS","CANCELLED"];if(row.status==="IN_PROGRESS")return ["AWAITING_REVIEW"];if(row.status==="AWAITING_REVIEW")return review?["VERIFIED_PASS","VERIFIED_FAIL"]:[];return []}
function claimNext(row:Claim){if(row.status==="SUBMITTED")return ["UNDER_REVIEW","REJECTED"];if(row.status==="UNDER_REVIEW")return ["APPROVED","REJECTED"];if(row.status==="APPROVED")return ["PAID","CLOSED"];if(row.status==="PAID")return ["CLOSED"];return []}

export function OfficeResilienceWorkspace({mode="full"}:{mode?:"full"|"insurance"}){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>(mode==="insurance"?"insurance":"incidents");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive)setData(n)}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load resilience records")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(p=>[p.user_id,p])),[data?.people]);
 const sites=useMemo(()=>new Map((data?.sites??[]).map(s=>[s.id,s])),[data?.sites]);
 const plans=useMemo(()=>new Map((data?.plans??[]).map(p=>[p.id,p])),[data?.plans]);
 const policies=useMemo(()=>new Map((data?.policies??[]).map(p=>[p.id,p])),[data?.policies]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="INCIDENT")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REPORT_INCIDENT",site_id:draft.site_id||undefined,category:draft.category||"OTHER",severity:draft.severity||"MEDIUM",title:draft.title,description:draft.description})});
  else if(modal.kind==="INCIDENT_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_INCIDENT",incident_id:modal.incident.id,status:draft.status,commander_user_id:draft.commander_user_id||undefined,containment:draft.containment||undefined,recovery:draft.recovery||undefined,evidence:draft.evidence||undefined})});
  else if(modal.kind==="PLAN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_PLAN",title:draft.title,plan_type:draft.plan_type||"BUSINESS_CONTINUITY",criticality:draft.criticality||"HIGH",owner_user_id:draft.owner_user_id,scope:draft.scope,recovery_order:draft.recovery_order,fallback_procedure:draft.fallback,communication_plan:draft.communication||undefined,rto_minutes:draft.rto?Number(draft.rto):undefined,rpo_minutes:draft.rpo?Number(draft.rpo):undefined,next_test_on:draft.next_test_on||undefined})});
  else if(modal.kind==="PLAN_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_PLAN",plan_id:modal.plan.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="TEST")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_TEST",plan_id:draft.plan_id||modal.plan?.id,test_type:draft.test_type||"TABLETOP",owner_user_id:draft.owner_user_id,scheduled_on:draft.scheduled_on})});
  else if(modal.kind==="TEST_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_TEST",test_id:modal.test.id,status:draft.status,summary:draft.summary||undefined,evidence:draft.evidence||undefined})});
  else if(modal.kind==="POLICY")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_POLICY",insurance_type:draft.insurance_type||"OTHER",provider:draft.provider,policy_reference:draft.policy_reference,coverage:draft.coverage,premium_paise:draft.premium?Math.round(Number(draft.premium)*100):undefined,currency:draft.currency||"INR",effective_on:draft.effective_on,expires_on:draft.expires_on,owner_user_id:draft.owner_user_id,document_reference:draft.document_reference})});
  else if(modal.kind==="CLAIM")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_CLAIM",policy_id:draft.policy_id||modal.policy?.id,incident_id:draft.incident_id||undefined,owner_user_id:draft.owner_user_id,amount_paise:draft.amount?Math.round(Number(draft.amount)*100):undefined,currency:draft.currency||"INR",description:draft.description,evidence:draft.evidence})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_CLAIM",claim_id:modal.claim.id,status:draft.status,note:draft.note||undefined,insurer_reference:draft.insurer_reference||undefined,payment_reference:draft.payment_reference||undefined})});
  await reload("Resilience record updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Resilience action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Resilience workspace unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading resilience controls</h2></div></section>;
 const tabs:View[]=mode==="insurance"?["insurance"]:[
  ...(data.capabilities.incident_read||data.capabilities.incident_report?["incidents" as const]:[]),
  ...(data.capabilities.resilience_read?["plans" as const,"tests" as const]:[]),
  ...(data.capabilities.insurance_read?["insurance" as const]:[]),
 ];
 const openIncidents=data.incidents.filter(i=>!["RESOLVED","CLOSED","CANCELLED"].includes(i.status)).length;
 const testReview=data.tests.filter(t=>t.status==="AWAITING_REVIEW").length;
 const openClaims=data.claims.filter(c=>!["REJECTED","CLOSED"].includes(c.status)).length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>CONTINUITY · RECOVERY · EMERGENCY · INSURANCE</p><h2>Keep recovery, safety and risk-transfer evidence inside KRAVIA.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{openIncidents}</b><span>open incidents</span></article><article><b>{testReview}</b><span>tests awaiting review</span></article><article><b>{openClaims}</b><span>open claims</span></article></div></header>
  <div className={styles.toolbar}>{tabs.map(t=><button key={t} type="button" data-active={view===t} onClick={()=>setView(t)}>{t==="incidents"?"Emergency":t[0].toUpperCase()+t.slice(1)}</button>)}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="incidents"&&data.capabilities.incident_report?<button type="button" onClick={()=>{setDraft({category:"OTHER",severity:"MEDIUM"});setModal({kind:"INCIDENT"})}}><Plus/>Report incident</button>:null}{view==="plans"&&data.capabilities.plan_manage?<button type="button" onClick={()=>{setDraft({plan_type:"BUSINESS_CONTINUITY",criticality:"HIGH"});setModal({kind:"PLAN"})}}><Plus/>New plan</button>:null}{view==="tests"&&data.capabilities.test_manage?<button type="button" onClick={()=>{setDraft({test_type:"TABLETOP"});setModal({kind:"TEST"})}}><Plus/>Schedule test</button>:null}{view==="insurance"&&data.capabilities.insurance_manage?<button type="button" onClick={()=>{setDraft({insurance_type:"OTHER",currency:"INR"});setModal({kind:"POLICY"})}}><Plus/>New policy</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="incidents"?<div className={styles.grid}>{data.incidents.map(i=><article className={styles.card} key={i.id}><header><div><small>{i.incident_code} · {i.category}</small><h3>{i.title}</h3><span>{sites.get(i.site_id||"")?.name||"No site"} · {date(i.opened_at)}</span></div><em className={styles.badge} data-status={i.severity==="CRITICAL"?"CRITICAL":i.status}>{i.status}</em></header><p>{i.description}</p><div className={styles.kv}><span>Severity<b>{i.severity}</b></span><span>Reporter<b>{people.get(i.reporter_user_id)?.display_name||(i.reporter_user_id===data.actor.user_id?"You":"Employee")}</b></span><span>Commander<b>{i.incident_commander_user_id?people.get(i.incident_commander_user_id)?.display_name||"Assigned":"—"}</b></span><span>Evidence<b>{i.evidence_reference||"—"}</b></span></div>{i.containment_summary?<p><b>Containment:</b> {i.containment_summary}</p>:null}{i.recovery_summary?<p><b>Recovery:</b> {i.recovery_summary}</p>:null}{data.capabilities.incident_manage&&!["CLOSED","CANCELLED"].includes(i.status)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:i.status==="OPEN"?"ACTIVE":i.status,commander_user_id:i.incident_commander_user_id||"",containment:i.containment_summary||"",recovery:i.recovery_summary||"",evidence:i.evidence_reference||""});setModal({kind:"INCIDENT_STATUS",incident:i})}}><HeartPulse/>Manage</button></div>:null}</article>)}{!data.incidents.length?<div className={styles.empty}>No emergency incidents in your authorised scope.</div>:null}</div>:null}

  {view==="plans"?<div className={styles.grid}>{data.plans.map(p=>{const next=planNext(p,data.capabilities.plan_review);return <article className={styles.card} key={p.id}><header><div><small>{p.plan_code} · v{p.version}</small><h3>{p.title}</h3><span>{p.plan_type} · {p.criticality}</span></div><em className={styles.badge} data-status={p.status}>{p.status}</em></header><div className={styles.kv}><span>Owner<b>{people.get(p.owner_user_id)?.display_name||p.owner_user_id}</b></span><span>RTO<b>{p.rto_minutes??"—"} min</b></span><span>RPO<b>{p.rpo_minutes??"—"} min</b></span><span>Next test<b>{date(p.next_test_on)}</b></span></div><details><summary>Recovery design</summary><p><b>Scope:</b> {p.scope_text}</p><p><b>Recovery order:</b> {p.recovery_order}</p><p><b>Fallback:</b> {p.fallback_procedure}</p>{p.communication_plan?<p><b>Communication:</b> {p.communication_plan}</p>:null}</details>{next.length&&(data.capabilities.plan_manage||data.capabilities.plan_review||p.owner_user_id===data.actor.user_id)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:next[0],note:""});setModal({kind:"PLAN_STATUS",plan:p})}}>Advance / review</button>{data.capabilities.test_manage&&["APPROVED","ACTIVE"].includes(p.status)?<button type="button" onClick={()=>{setDraft({test_type:"TABLETOP",plan_id:p.id});setModal({kind:"TEST",plan:p})}}>Schedule test</button>:null}</div>:null}</article>})}{!data.plans.length?<div className={styles.empty}>No continuity or recovery plans recorded.</div>:null}</div>:null}

  {view==="tests"?<div className={styles.grid}>{data.tests.map(t=>{const next=testNext(t,data.capabilities.test_review);return <article className={styles.card} key={t.id}><header><div><small>{t.test_code} · {t.test_type}</small><h3>{plans.get(t.plan_id)?.title||"Resilience test"}</h3><span>Scheduled {date(t.scheduled_on)}</span></div><em className={styles.badge} data-status={t.status}>{t.status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Owner<b>{people.get(t.owner_user_id)?.display_name||t.owner_user_id}</b></span><span>Conducted<b>{date(t.conducted_at)}</b></span><span>Evidence<b>{t.evidence_reference||"—"}</b></span></div>{t.result_summary?<p>{t.result_summary}</p>:null}{next.length&&(t.owner_user_id===data.actor.user_id||data.capabilities.test_manage||data.capabilities.test_review)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:next[0],summary:t.result_summary||"",evidence:t.evidence_reference||""});setModal({kind:"TEST_STATUS",test:t})}}>Update / verify</button></div>:null}</article>})}{!data.tests.length?<div className={styles.empty}>No resilience tests scheduled.</div>:null}</div>:null}

  {view==="insurance"?<div className={styles.grid}>{data.policies.map(p=><article className={styles.card} key={p.id}><header><div><small>{p.policy_code} · {p.insurance_type}</small><h3>{p.provider_name}</h3><span>{p.provider_policy_reference}</span></div><em className={styles.badge} data-status={p.status}>{p.status}</em></header><p>{p.coverage_summary}</p><div className={styles.kv}><span>Effective<b>{date(p.effective_on)}</b></span><span>Expiry<b>{date(p.expires_on)}</b></span><span>Premium<b>{money(p.premium_paise,p.currency)}</b></span><span>Document<b>{p.document_reference}</b></span></div>{data.capabilities.insurance_manage&&p.status==="ACTIVE"?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({policy_id:p.id,currency:p.currency});setModal({kind:"CLAIM",policy:p})}}><Plus/>New claim</button></div>:null}{data.claims.filter(c=>c.policy_id===p.id).map(c=><div className={styles.claim} key={c.id}><div><b>{c.claim_code} · {c.status}</b><span>{c.description}</span><small>{money(c.claim_amount_paise,c.currency)} · evidence {c.evidence_reference}</small></div>{data.capabilities.insurance_review&&c.owner_user_id!==data.actor.user_id&&c.reported_by!==data.actor.user_id&&claimNext(c).length?<button type="button" onClick={()=>{setDraft({status:claimNext(c)[0],insurer_reference:c.insurer_reference||"",payment_reference:c.payment_reference||"",note:c.review_note||""});setModal({kind:"CLAIM_STATUS",claim:c})}}>Review</button>:null}</div>)}</article>)}{!data.policies.length?<div className={styles.empty}>No insurance policies recorded in your authorised scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED RESILIENCE ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="INCIDENT"?<><div className={styles.two}><label>Category<select value={draft.category||"OTHER"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["FIRE","MEDICAL","SECURITY","POWER","NETWORK","WEATHER","SAFETY","FACILITY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Severity<select value={draft.severity||"MEDIUM"} onChange={e=>setDraft({...draft,severity:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Office site<select value={draft.site_id||""} onChange={e=>setDraft({...draft,site_id:e.target.value})}><option value="">No site / remote</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>
   :modal.kind==="INCIDENT_STATUS"?<><div className={styles.two}><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{["ACTIVE","CONTAINED","RECOVERING","RESOLVED","CLOSED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label><label>Commander<select value={draft.commander_user_id||""} onChange={e=>setDraft({...draft,commander_user_id:e.target.value})}><option value="">Keep current</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><label>Containment summary<textarea value={draft.containment||""} onChange={e=>setDraft({...draft,containment:e.target.value})}/></label><label>Recovery summary<textarea required={["RESOLVED","CLOSED"].includes(draft.status)} value={draft.recovery||""} onChange={e=>setDraft({...draft,recovery:e.target.value})}/></label><label>Evidence reference<input required={draft.status==="CLOSED"} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="PLAN"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Plan type<select value={draft.plan_type||"BUSINESS_CONTINUITY"} onChange={e=>setDraft({...draft,plan_type:e.target.value})}>{["BUSINESS_CONTINUITY","DISASTER_RECOVERY","EMERGENCY_RESPONSE","DEPENDENCY_RECOVERY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Criticality<select value={draft.criticality||"HIGH"} onChange={e=>setDraft({...draft,criticality:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Scope<textarea required minLength={3} value={draft.scope||""} onChange={e=>setDraft({...draft,scope:e.target.value})}/></label><label>Recovery order<textarea required minLength={3} value={draft.recovery_order||""} onChange={e=>setDraft({...draft,recovery_order:e.target.value})}/></label><label>Fallback procedure<textarea required minLength={3} value={draft.fallback||""} onChange={e=>setDraft({...draft,fallback:e.target.value})}/></label><label>Communication plan<textarea value={draft.communication||""} onChange={e=>setDraft({...draft,communication:e.target.value})}/></label><div className={styles.three}><label>RTO minutes<input type="number" min="0" value={draft.rto||""} onChange={e=>setDraft({...draft,rto:e.target.value})}/></label><label>RPO minutes<input type="number" min="0" value={draft.rpo||""} onChange={e=>setDraft({...draft,rpo:e.target.value})}/></label><label>Next test<input type="date" value={draft.next_test_on||""} onChange={e=>setDraft({...draft,next_test_on:e.target.value})}/></label></div></>
   :modal.kind==="PLAN_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{planNext(modal.plan,data.capabilities.plan_review).map(v=><option key={v}>{v}</option>)}</select></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="TEST"?<><label>Plan<select required value={draft.plan_id||modal.plan?.id||""} onChange={e=>setDraft({...draft,plan_id:e.target.value})}><option value="">Select approved/active plan</option>{data.plans.filter(p=>["APPROVED","ACTIVE"].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.plan_code} · {p.title}</option>)}</select></label><label>Test type<select value={draft.test_type||"TABLETOP"} onChange={e=>setDraft({...draft,test_type:e.target.value})}>{["TABLETOP","RESTORE","FAILOVER","COMMUNICATION","EVACUATION","BACKUP_RECOVERY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Scheduled date<input required type="date" value={draft.scheduled_on||""} onChange={e=>setDraft({...draft,scheduled_on:e.target.value})}/></label></>
   :modal.kind==="TEST_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{testNext(modal.test,data.capabilities.test_review).map(v=><option key={v}>{v}</option>)}</select></label><label>Result summary<textarea value={draft.summary||""} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><label>Evidence reference<input required={["VERIFIED_PASS","VERIFIED_FAIL"].includes(draft.status)} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="POLICY"?<><label>Insurance type<select value={draft.insurance_type||"OTHER"} onChange={e=>setDraft({...draft,insurance_type:e.target.value})}>{["EMPLOYEE","CYBER","DIRECTORS_OFFICERS","EQUIPMENT","PROPERTY","LIABILITY","TRAVEL","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><div className={styles.two}><label>Provider<input required minLength={2} value={draft.provider||""} onChange={e=>setDraft({...draft,provider:e.target.value})}/></label><label>Policy reference<input required minLength={2} value={draft.policy_reference||""} onChange={e=>setDraft({...draft,policy_reference:e.target.value})}/></label></div><label>Coverage summary<textarea required minLength={3} value={draft.coverage||""} onChange={e=>setDraft({...draft,coverage:e.target.value})}/></label><div className={styles.three}><label>Premium<input inputMode="decimal" value={draft.premium||""} onChange={e=>setDraft({...draft,premium:e.target.value})}/></label><label>Currency<input maxLength={3} value={draft.currency||"INR"} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><div className={styles.two}><label>Effective<input required type="date" value={draft.effective_on||""} onChange={e=>setDraft({...draft,effective_on:e.target.value})}/></label><label>Expiry<input required type="date" value={draft.expires_on||""} onChange={e=>setDraft({...draft,expires_on:e.target.value})}/></label></div><label>Document reference<input required minLength={3} value={draft.document_reference||""} onChange={e=>setDraft({...draft,document_reference:e.target.value})}/></label></>
   :modal.kind==="CLAIM"?<><label>Policy<select required value={draft.policy_id||modal.policy?.id||""} onChange={e=>setDraft({...draft,policy_id:e.target.value})}><option value="">Select active policy</option>{data.policies.filter(p=>p.status==="ACTIVE").map(p=><option key={p.id} value={p.id}>{p.policy_code} · {p.provider_name}</option>)}</select></label><label>Related emergency<select value={draft.incident_id||""} onChange={e=>setDraft({...draft,incident_id:e.target.value})}><option value="">None</option>{data.incidents.map(i=><option key={i.id} value={i.id}>{i.incident_code} · {i.title}</option>)}</select></label><label>Claim owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><div className={styles.two}><label>Claim amount<input inputMode="decimal" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Currency<input maxLength={3} value={draft.currency||"INR"} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label></div><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Evidence reference<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{claimNext(modal.claim).map(v=><option key={v}>{v}</option>)}</select></label><label>Insurer reference<input value={draft.insurer_reference||""} onChange={e=>setDraft({...draft,insurer_reference:e.target.value})}/></label>{draft.status==="PAID"?<label>Payment reference<input required minLength={3} value={draft.payment_reference||""} onChange={e=>setDraft({...draft,payment_reference:e.target.value})}/></label>:null}<label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
