"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, Flag, LoaderCircle, Plus, RefreshCw, ShieldCheck, Target, X } from "lucide-react";
import styles from "./office-strategy.module.css";

type Caps={read:boolean;manage:boolean;review:boolean;progress_update:boolean};
type Person={user_id:string;display_name?:string|null};
type Cycle={id:string;cycle_code:string;title:string;scope_type:string;scope_key?:string|null;period_start:string;period_end:string;owner_user_id:string;status:string;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;review_note?:string|null;closure_evidence_reference?:string|null};
type Objective={id:string;objective_code:string;cycle_id:string;parent_objective_id?:string|null;title:string;description:string;owner_user_id:string;priority:string;status:string;completion_evidence_reference?:string|null;created_by:string};
type KeyResult={id:string;key_result_code:string;objective_id:string;title:string;owner_user_id:string;measurement_kind:string;unit?:string|null;start_value?:number|null;target_value?:number|null;current_value?:number|null;currency?:string|null;reported_status:string;progress_note?:string|null;evidence_reference?:string|null;due_on?:string|null;last_reported_by?:string|null;last_reported_at?:string|null;created_by:string};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};capabilities:Caps;cycles:Cycle[];objectives:Objective[];key_results:KeyResult[];people:Person[];disclaimer:string};
type Modal=
 |{kind:"CYCLE"}
 |{kind:"CYCLE_STATUS";cycle:Cycle}
 |{kind:"OBJECTIVE";cycle:Cycle}
 |{kind:"OBJECTIVE_STATUS";objective:Objective}
 |{kind:"KR";objective:Objective}
 |{kind:"PROGRESS";keyResult:KeyResult};

async function api<T>(options?:RequestInit):Promise<T>{
 const r=await fetch("/api/office-strategy",{...options,cache:"no-store",credentials:"same-origin"});
 const b=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Strategy operation failed");
 return b as T;
}
function date(v?:string|null){if(!v)return "—";const d=new Date(v.length===10?v+"T00:00:00":v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(d)}
function cycleNext(c:Cycle,review:boolean){if(c.status==="DRAFT")return ["SUBMITTED"];if(c.status==="SUBMITTED")return review?["APPROVED","REJECTED"]:[];if(c.status==="APPROVED")return ["ACTIVE",...(review?["CANCELLED"]:[])];if(c.status==="ACTIVE")return review?["CLOSED","CANCELLED"]:[];return []}
function objectiveNext(o:Objective){if(o.status==="DRAFT")return ["ACTIVE","CANCELLED"];if(o.status==="ACTIVE")return ["COMPLETED","CANCELLED"];return []}
function measurement(k:KeyResult){const current=k.current_value==null?"—":String(k.current_value);const target=k.target_value==null?"—":String(k.target_value);const unit=k.currency||k.unit||"";return current+" / "+target+(unit?" "+unit:"")}

export function OfficeStrategyWorkspace(){
 const[data,setData]=useState<Payload>();const[selected,setSelected]=useState<string>();const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);setSelected(current=>current&&next.cycles.some(c=>c.id===current)?current:next.cycles[0]?.id);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive){setData(n);setSelected(n.cycles[0]?.id)}}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load Strategy")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(p=>[p.user_id,p])),[data?.people]);
 const cycle=data?.cycles.find(c=>c.id===selected);
 const objectives=data?.objectives.filter(o=>o.cycle_id===selected)||[];
 const objectiveMap=useMemo(()=>new Map((data?.objectives??[]).map(o=>[o.id,o])),[data?.objectives]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="CYCLE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_CYCLE",title:draft.title,scope_type:draft.scope_type||"DEPARTMENT",scope_key:draft.scope_type==="COMPANY"?undefined:draft.scope_key||data?.actor.department||undefined,period_start:draft.period_start,period_end:draft.period_end,owner_user_id:draft.owner_user_id})});
  else if(modal.kind==="CYCLE_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_CYCLE",cycle_id:modal.cycle.id,status:draft.status,evidence:draft.evidence||undefined,note:draft.note||undefined})});
  else if(modal.kind==="OBJECTIVE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_OBJECTIVE",cycle_id:modal.cycle.id,parent_objective_id:draft.parent_objective_id||undefined,title:draft.title,description:draft.description,owner_user_id:draft.owner_user_id,priority:draft.priority||"MEDIUM"})});
  else if(modal.kind==="OBJECTIVE_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_OBJECTIVE",objective_id:modal.objective.id,status:draft.status,evidence:draft.evidence||undefined,note:draft.note||undefined})});
  else if(modal.kind==="KR")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_KEY_RESULT",objective_id:modal.objective.id,title:draft.title,owner_user_id:draft.owner_user_id,measurement_kind:draft.measurement_kind||"NUMBER",unit:draft.unit||undefined,start_value:draft.start_value?Number(draft.start_value):undefined,target_value:draft.target_value?Number(draft.target_value):undefined,currency:draft.currency||undefined,due_on:draft.due_on||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REPORT_PROGRESS",key_result_id:modal.keyResult.id,current_value:draft.current_value?Number(draft.current_value):undefined,status:draft.status,note:draft.note||undefined,evidence:draft.evidence||undefined})});
  await reload("Strategy record updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Strategy action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Strategy unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading Strategy & OKRs</h2></div></section>;
 const activeCycles=data.cycles.filter(c=>["APPROVED","ACTIVE"].includes(c.status)).length;
 const atRisk=data.key_results.filter(k=>["AT_RISK","OFF_TRACK"].includes(k.reported_status)).length;
 const achieved=data.key_results.filter(k=>k.reported_status==="ACHIEVED").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>STRATEGY · OBJECTIVES · KEY RESULTS</p><h2>Align company work through human-reported outcomes, not activity-derived scores.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{activeCycles}</b><span>active/approved cycles</span></article><article><b>{atRisk}</b><span>key results at risk</span></article><article><b>{achieved}</b><span>key results achieved</span></article></div></header>
  <div className={styles.toolbar}><button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{data.capabilities.manage?<button type="button" onClick={()=>{setDraft({scope_type:"DEPARTMENT",scope_key:data.actor.department||""});setModal({kind:"CYCLE"})}}><Plus/>New strategy cycle</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  <div className={styles.cycleTabs}>{data.cycles.map(c=><button type="button" key={c.id} data-active={selected===c.id} onClick={()=>setSelected(c.id)}><small>{c.cycle_code} · {c.scope_type}</small><b>{c.title}</b><span>{c.status} · {date(c.period_start)} → {date(c.period_end)}</span></button>)}{!data.cycles.length?<div className={styles.empty}>No strategy cycles recorded.</div>:null}</div>

  {cycle?<div className={styles.grid}>
    <article className={styles.card}><header><div><small>{cycle.cycle_code} · {cycle.scope_type}{cycle.scope_key?" · "+cycle.scope_key:""}</small><h3>{cycle.title}</h3><span>{date(cycle.period_start)} → {date(cycle.period_end)}</span></div><em className={styles.badge} data-status={cycle.status}>{cycle.status}</em></header><div className={styles.kv}><span>Owner<b>{people.get(cycle.owner_user_id)?.display_name||cycle.owner_user_id}</b></span><span>Review note<b>{cycle.review_note||"—"}</b></span><span>Closure evidence<b>{cycle.closure_evidence_reference||"—"}</b></span></div><div className={styles.actions}>{cycleNext(cycle,data.capabilities.review).length&&(data.capabilities.manage||data.capabilities.review||cycle.owner_user_id===data.actor.user_id)?<button type="button" onClick={()=>{setDraft({status:cycleNext(cycle,data.capabilities.review)[0],evidence:cycle.closure_evidence_reference||"",note:cycle.review_note||""});setModal({kind:"CYCLE_STATUS",cycle})}}><ShieldCheck/>Advance / review</button>:null}{data.capabilities.manage&&!["CLOSED","REJECTED","CANCELLED"].includes(cycle.status)?<button type="button" onClick={()=>{setDraft({priority:"MEDIUM"});setModal({kind:"OBJECTIVE",cycle})}}><Plus/>Add objective</button>:null}</div></article>

    {objectives.map(o=>{const results=data.key_results.filter(k=>k.objective_id===o.id);return <article className={styles.objective} key={o.id}><header><div><small>{o.objective_code} · {o.priority}</small><h3>{o.title}</h3><span>Owner: {people.get(o.owner_user_id)?.display_name||o.owner_user_id}{o.parent_objective_id?" · aligned to "+(objectiveMap.get(o.parent_objective_id)?.objective_code||"parent"):""}</span></div><em className={styles.badge} data-status={o.status}>{o.status}</em></header><p>{o.description}</p><div className={styles.actions}>{objectiveNext(o).length&&(data.capabilities.manage||o.owner_user_id===data.actor.user_id)?<button type="button" onClick={()=>{setDraft({status:objectiveNext(o)[0],evidence:o.completion_evidence_reference||"",note:""});setModal({kind:"OBJECTIVE_STATUS",objective:o})}}>Update objective</button>:null}{data.capabilities.manage&&!["COMPLETED","CANCELLED"].includes(o.status)?<button type="button" onClick={()=>{setDraft({measurement_kind:"NUMBER"});setModal({kind:"KR",objective:o})}}><Plus/>Key result</button>:null}</div><div className={styles.results}>{results.map(k=><div className={styles.kr} key={k.id}><div><small>{k.key_result_code} · {k.measurement_kind}</small><b>{k.title}</b><span>{people.get(k.owner_user_id)?.display_name||k.owner_user_id} · due {date(k.due_on)}</span></div><div className={styles.measure}><b>{measurement(k)}</b><em className={styles.badge} data-status={k.reported_status}>{k.reported_status.replaceAll("_"," ")}</em></div>{k.progress_note?<p>{k.progress_note}</p>:null}{k.evidence_reference?<small>Evidence: {k.evidence_reference}</small>:null}{!["ACHIEVED","CANCELLED"].includes(k.reported_status)&&(k.owner_user_id===data.actor.user_id||data.capabilities.progress_update)?<button type="button" onClick={()=>{setDraft({current_value:k.current_value==null?"":String(k.current_value),status:k.reported_status,note:k.progress_note||"",evidence:k.evidence_reference||""});setModal({kind:"PROGRESS",keyResult:k})}}><Flag/>Report progress</button>:null}</div>)}</div></article>})}
    {!objectives.length?<div className={styles.empty}>No objectives in this strategy cycle.</div>:null}
  </div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>GOVERNED STRATEGY ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="CYCLE"?<><label>Cycle title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Scope<select value={draft.scope_type||"DEPARTMENT"} onChange={e=>setDraft({...draft,scope_type:e.target.value})}><option>DEPARTMENT</option><option>COMPANY</option></select></label>{draft.scope_type!=="COMPANY"?<label>Department<input required value={draft.scope_key||""} onChange={e=>setDraft({...draft,scope_key:e.target.value.toUpperCase()})}/></label>:<span/>}</div><div className={styles.two}><label>Period start<input required type="date" value={draft.period_start||""} onChange={e=>setDraft({...draft,period_start:e.target.value})}/></label><label>Period end<input required type="date" value={draft.period_end||""} onChange={e=>setDraft({...draft,period_end:e.target.value})}/></label></div><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></>
   :modal.kind==="CYCLE_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{cycleNext(modal.cycle,data.capabilities.review).map(v=><option key={v}>{v}</option>)}</select></label>{draft.status==="CLOSED"?<label>Closure evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>:null}<label>Review / transition note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="OBJECTIVE"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className={styles.two}><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Priority<select value={draft.priority||"MEDIUM"} onChange={e=>setDraft({...draft,priority:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Parent objective<select value={draft.parent_objective_id||""} onChange={e=>setDraft({...draft,parent_objective_id:e.target.value})}><option value="">None</option>{objectives.map(o=><option key={o.id} value={o.id}>{o.objective_code} · {o.title}</option>)}</select></label></>
   :modal.kind==="OBJECTIVE_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{objectiveNext(modal.objective).map(v=><option key={v}>{v}</option>)}</select></label>{draft.status==="COMPLETED"?<label>Completion evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>:null}<label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="KR"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><div className={styles.two}><label>Measurement<select value={draft.measurement_kind||"NUMBER"} onChange={e=>setDraft({...draft,measurement_kind:e.target.value})}>{["PERCENT","NUMBER","CURRENCY","BOOLEAN","MILESTONE"].map(v=><option key={v}>{v}</option>)}</select></label><label>Unit<input value={draft.unit||""} onChange={e=>setDraft({...draft,unit:e.target.value})}/></label></div><div className={styles.three}><label>Start value<input type="number" step="any" value={draft.start_value||""} onChange={e=>setDraft({...draft,start_value:e.target.value})}/></label><label>Target value<input type="number" step="any" value={draft.target_value||""} onChange={e=>setDraft({...draft,target_value:e.target.value})}/></label><label>Due on<input type="date" value={draft.due_on||""} onChange={e=>setDraft({...draft,due_on:e.target.value})}/></label></div>{draft.measurement_kind==="CURRENCY"?<label>Currency<input required maxLength={3} value={draft.currency||""} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label>:null}</>
   :<><label>Human-reported status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{["NOT_STARTED","ON_TRACK","AT_RISK","OFF_TRACK","ACHIEVED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label><label>Current value<input type="number" step="any" value={draft.current_value||""} onChange={e=>setDraft({...draft,current_value:e.target.value})}/></label><label>Progress note<textarea required={["AT_RISK","OFF_TRACK"].includes(draft.status)} value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>{draft.status==="ACHIEVED"?<label>Achievement evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>:null}</>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<Target/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
