"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, FileCheck2, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-trust-center.module.css";

type Caps={vendor_read:boolean;vendor_manage:boolean;vendor_review:boolean;customer_read:boolean;customer_manage:boolean;customer_review:boolean};
type Vendor={id:string;legal_name:string;category?:string|null;gstin?:string|null;status:string;risk?:string|null};
type Assessment={id:string;assessment_code:string;vendor_id:string;assessment_type:string;scope_summary:string;risk_level:string;evidence_reference?:string|null;remediation_summary?:string|null;owner_user_id:string;status:string;expires_on?:string|null;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;review_note?:string|null;created_at:string;updated_at:string};
type Customer={id:string;legal_name:string;display_name:string;country?:string|null;email?:string|null;status:string};
type TrustRequest={id:string;trust_code:string;customer_id:string;request_type:string;title:string;request_summary:string;owner_user_id:string;due_at?:string|null;status:string;response_reference?:string|null;evidence_reference?:string|null;sent_reference?:string|null;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;review_note?:string|null;sent_at?:string|null;closed_at?:string|null;created_at:string;updated_at:string};
type Person={user_id:string;display_name?:string|null;job_title?:string|null};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};capabilities:Caps;vendors:Vendor[];vendor_assessments:Assessment[];customers:Customer[];customer_trust_requests:TrustRequest[];people:Person[];disclaimer:string};
type View="vendors"|"customers";
type Modal=
 |{kind:"ASSESS";vendor?:Vendor}
 |{kind:"ASSESS_STATUS";assessment:Assessment}
 |{kind:"TRUST";customer?:Customer}
 |{kind:"TRUST_PREPARE";trust:TrustRequest}
 |{kind:"TRUST_REVIEW";trust:TrustRequest}
 |{kind:"TRUST_SEND";trust:TrustRequest}
 |{kind:"TRUST_CLOSE";trust:TrustRequest};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-trust-center",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Trust Center request failed");
 return body as T;
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value.length===10?value+"T00:00:00":value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:value.length>10?"short":undefined}).format(d)}
function toIso(value?:string){if(!value)return undefined;const d=new Date(value);return Number.isNaN(d.getTime())?undefined:d.toISOString()}
function assessmentNext(row:Assessment,review:boolean){
 if(row.status==="DRAFT")return ["SUBMITTED"];
 if(row.status==="SUBMITTED")return review?["APPROVED","REJECTED"]:[];
 if(row.status==="APPROVED")return ["EXPIRED"];
 return [];
}
function trustPrepareNext(row:TrustRequest){
 if(row.status==="OPEN")return ["IN_PROGRESS","CANCELLED"];
 if(row.status==="IN_PROGRESS")return ["AWAITING_REVIEW"];
 return [];
}

export function OfficeTrustCenter(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("vendors");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load Trust Center")});return()=>{alive=false}},[]);
 const vendorMap=useMemo(()=>new Map((data?.vendors??[]).map(v=>[v.id,v])),[data?.vendors]);
 const customerMap=useMemo(()=>new Map((data?.customers??[]).map(v=>[v.id,v])),[data?.customers]);
 const people=useMemo(()=>new Map((data?.people??[]).map(v=>[v.user_id,v])),[data?.people]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="ASSESS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_VENDOR_ASSESSMENT",vendor_id:draft.vendor_id||modal.vendor?.id,assessment_type:draft.assessment_type||"SECURITY",scope_summary:draft.scope_summary,risk_level:draft.risk_level||"MEDIUM",evidence_reference:draft.evidence_reference||undefined,remediation_summary:draft.remediation_summary||undefined,owner_user_id:draft.owner_user_id,expires_on:draft.expires_on||undefined})});
  else if(modal.kind==="ASSESS_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_VENDOR_ASSESSMENT",assessment_id:modal.assessment.id,status:draft.status,evidence_reference:draft.evidence_reference||undefined,remediation_summary:draft.remediation_summary||undefined,expires_on:draft.expires_on||undefined,note:draft.note||undefined})});
  else if(modal.kind==="TRUST")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_CUSTOMER_TRUST",customer_id:draft.customer_id||modal.customer?.id,request_type:draft.request_type||"SECURITY_QUESTIONNAIRE",title:draft.title,request_summary:draft.request_summary,owner_user_id:draft.owner_user_id,due_at:toIso(draft.due_at)})});
  else if(modal.kind==="TRUST_PREPARE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"PREPARE_CUSTOMER_TRUST",trust_id:modal.trust.id,status:draft.status,response_reference:draft.response_reference||undefined,evidence_reference:draft.evidence_reference||undefined,note:draft.note||undefined})});
  else if(modal.kind==="TRUST_REVIEW")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_CUSTOMER_TRUST",trust_id:modal.trust.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="TRUST_SEND")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"SEND_CUSTOMER_TRUST",trust_id:modal.trust.id,sent_reference:draft.sent_reference})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CLOSE_CUSTOMER_TRUST",trust_id:modal.trust.id,note:draft.note||undefined})});
  await reload("Trust Center updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Trust Center action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Trust Center unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading Trust Center</h2><p>Resolving vendor and customer assurance authority.</p></div></section>;

 const pendingAssess=data.vendor_assessments.filter(a=>a.status==="SUBMITTED").length;
 const trustReview=data.customer_trust_requests.filter(t=>t.status==="AWAITING_REVIEW").length;
 const openTrust=data.customer_trust_requests.filter(t=>!["CLOSED","REJECTED","CANCELLED"].includes(t.status)).length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>VENDOR ASSURANCE · CUSTOMER TRUST</p><h2>Keep due diligence and customer security evidence inside KRAVIA.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{pendingAssess}</b><span>vendor reviews waiting</span></article><article><b>{trustReview}</b><span>trust reviews waiting</span></article><article><b>{openTrust}</b><span>open customer requests</span></article></div></header>
  <div className={styles.toolbar}>{data.capabilities.vendor_read?<button type="button" data-active={view==="vendors"} onClick={()=>setView("vendors")}>Vendor assurance</button>:null}{data.capabilities.customer_read?<button type="button" data-active={view==="customers"} onClick={()=>setView("customers")}>Customer trust</button>:null}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="vendors"&&data.capabilities.vendor_manage&&data.vendors.length?<button type="button" onClick={()=>{setDraft({assessment_type:"SECURITY",risk_level:"MEDIUM"});setModal({kind:"ASSESS"})}}><Plus/>New assessment</button>:null}{view==="customers"&&data.capabilities.customer_manage&&data.customers.length?<button type="button" onClick={()=>{setDraft({request_type:"SECURITY_QUESTIONNAIRE"});setModal({kind:"TRUST"})}}><Plus/>New trust request</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="vendors"&&data.capabilities.vendor_read?<div className={styles.grid}>{data.vendor_assessments.map(a=>{const vendor=vendorMap.get(a.vendor_id);const next=assessmentNext(a,data.capabilities.vendor_review);return <article className={styles.card} key={a.id}><header><div><small>{a.assessment_code} · {a.assessment_type}</small><h3>{vendor?.legal_name||a.vendor_id}</h3><span>{vendor?.category||"Vendor"} · risk {a.risk_level}</span></div><em className={styles.badge} data-status={a.status}>{a.status}</em></header><p>{a.scope_summary}</p><div className={styles.kv}><span>Owner<b>{people.get(a.owner_user_id)?.display_name||a.owner_user_id}</b></span><span>Evidence<b>{a.evidence_reference||"—"}</b></span><span>Expires<b>{date(a.expires_on)}</b></span><span>Remediation<b>{a.remediation_summary||"—"}</b></span></div>{a.review_note?<p><b>Review:</b> {a.review_note}</p>:null}{next.length&&((a.status==="DRAFT"&&(data.capabilities.vendor_manage||a.owner_user_id===data.actor.user_id))||(a.status==="SUBMITTED"&&data.capabilities.vendor_review&&a.owner_user_id!==data.actor.user_id&&a.created_by!==data.actor.user_id)||(a.status==="APPROVED"&&data.capabilities.vendor_manage))?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:next[0],evidence_reference:a.evidence_reference||"",remediation_summary:a.remediation_summary||"",expires_on:a.expires_on||"",note:""});setModal({kind:"ASSESS_STATUS",assessment:a})}}><ShieldCheck/>Review / advance</button></div>:null}</article>})}{data.capabilities.vendor_manage?data.vendors.filter(v=>!data.vendor_assessments.some(a=>a.vendor_id===v.id)).map(v=><article className={styles.catalog} key={v.id}><div><small>{v.category||"Vendor"} · {v.status}</small><b>{v.legal_name}</b><span>Canonical risk: {v.risk||"not set"}</span></div><button type="button" onClick={()=>{setDraft({vendor_id:v.id,assessment_type:"SECURITY",risk_level:"MEDIUM"});setModal({kind:"ASSESS",vendor:v})}}>Assess</button></article>):null}{!data.vendor_assessments.length&&!data.vendors.length?<div className={styles.empty}>No vendor assurance records are available.</div>:null}</div>:null}

  {view==="customers"&&data.capabilities.customer_read?<div className={styles.grid}>{data.customer_trust_requests.map(t=>{const customer=customerMap.get(t.customer_id);const prep=trustPrepareNext(t);return <article className={styles.card} key={t.id}><header><div><small>{t.trust_code} · {t.request_type}</small><h3>{t.title}</h3><span>{customer?.display_name||customer?.legal_name||t.customer_id}</span></div><em className={styles.badge} data-status={t.status}>{t.status.replaceAll("_"," ")}</em></header><p>{t.request_summary}</p><div className={styles.kv}><span>Owner<b>{people.get(t.owner_user_id)?.display_name||t.owner_user_id}</b></span><span>Due<b>{date(t.due_at)}</b></span><span>Response<b>{t.response_reference||"—"}</b></span><span>Evidence<b>{t.evidence_reference||"—"}</b></span><span>Sent reference<b>{t.sent_reference||"—"}</b></span></div>{t.review_note?<p><b>Review:</b> {t.review_note}</p>:null}<div className={styles.actions}>{prep.length&&data.capabilities.customer_manage&&(t.owner_user_id===data.actor.user_id||data.capabilities.customer_manage)?<button type="button" onClick={()=>{setDraft({status:prep[0],response_reference:t.response_reference||"",evidence_reference:t.evidence_reference||"",note:""});setModal({kind:"TRUST_PREPARE",trust:t})}}>Prepare / advance</button>:null}{t.status==="AWAITING_REVIEW"&&data.capabilities.customer_review&&t.owner_user_id!==data.actor.user_id&&t.created_by!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({status:"READY",note:""});setModal({kind:"TRUST_REVIEW",trust:t})}}><FileCheck2/>Independent review</button>:null}{t.status==="READY"&&data.capabilities.customer_manage?<button type="button" onClick={()=>{setDraft({sent_reference:""});setModal({kind:"TRUST_SEND",trust:t})}}>Record delivery</button>:null}{t.status==="SENT"&&data.capabilities.customer_manage?<button type="button" onClick={()=>{setDraft({note:""});setModal({kind:"TRUST_CLOSE",trust:t})}}>Close</button>:null}</div></article>})}{data.capabilities.customer_manage?data.customers.filter(c=>!data.customer_trust_requests.some(t=>t.customer_id===c.id&&!["CLOSED","REJECTED","CANCELLED"].includes(t.status))).map(c=><article className={styles.catalog} key={c.id}><div><small>{c.country||"Customer"} · {c.status}</small><b>{c.display_name||c.legal_name}</b><span>{c.email||"No contact email recorded"}</span></div><button type="button" onClick={()=>{setDraft({customer_id:c.id,request_type:"SECURITY_QUESTIONNAIRE"});setModal({kind:"TRUST",customer:c})}}>New request</button></article>):null}{!data.customer_trust_requests.length&&!data.customers.length?<div className={styles.empty}>No customer trust records are available.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>TRUST CENTER ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="ASSESS"?<><label>Vendor<select required value={draft.vendor_id||modal.vendor?.id||""} onChange={e=>setDraft({...draft,vendor_id:e.target.value})}><option value="">Select vendor</option>{data.vendors.map(v=><option key={v.id} value={v.id}>{v.legal_name}</option>)}</select></label><div className={styles.two}><label>Assessment type<select value={draft.assessment_type||"SECURITY"} onChange={e=>setDraft({...draft,assessment_type:e.target.value})}>{["SECURITY","PRIVACY","LEGAL","FINANCIAL","BUSINESS_CONTINUITY","AI","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Risk level<select value={draft.risk_level||"MEDIUM"} onChange={e=>setDraft({...draft,risk_level:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Scope summary<textarea required minLength={3} value={draft.scope_summary||""} onChange={e=>setDraft({...draft,scope_summary:e.target.value})}/></label><label>Evidence reference<input value={draft.evidence_reference||""} onChange={e=>setDraft({...draft,evidence_reference:e.target.value})}/></label><label>Remediation summary<textarea value={draft.remediation_summary||""} onChange={e=>setDraft({...draft,remediation_summary:e.target.value})}/></label></>
   :modal.kind==="ASSESS_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{assessmentNext(modal.assessment,data.capabilities.vendor_review).map(v=><option key={v}>{v}</option>)}</select></label><label>Evidence reference<input required={draft.status==="APPROVED"} value={draft.evidence_reference||""} onChange={e=>setDraft({...draft,evidence_reference:e.target.value})}/></label><label>Remediation summary<textarea value={draft.remediation_summary||""} onChange={e=>setDraft({...draft,remediation_summary:e.target.value})}/></label>{draft.status==="APPROVED"?<label>Assessment expiry<input required type="date" value={draft.expires_on||""} onChange={e=>setDraft({...draft,expires_on:e.target.value})}/></label>:null}<label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="TRUST"?<><label>Customer<select required value={draft.customer_id||modal.customer?.id||""} onChange={e=>setDraft({...draft,customer_id:e.target.value})}><option value="">Select customer</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.display_name||c.legal_name}</option>)}</select></label><label>Request type<select value={draft.request_type||"SECURITY_QUESTIONNAIRE"} onChange={e=>setDraft({...draft,request_type:e.target.value})}>{["SECURITY_QUESTIONNAIRE","DPA","COMPLIANCE_EVIDENCE","PEN_TEST","SLA","SUBPROCESSOR","ARCHITECTURE","PRIVACY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Request summary<textarea required minLength={3} value={draft.request_summary||""} onChange={e=>setDraft({...draft,request_summary:e.target.value})}/></label><label>Due time<input type="datetime-local" value={draft.due_at||""} onChange={e=>setDraft({...draft,due_at:e.target.value})}/></label></>
   :modal.kind==="TRUST_PREPARE"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{trustPrepareNext(modal.trust).map(v=><option key={v}>{v}</option>)}</select></label>{draft.status==="AWAITING_REVIEW"?<><label>Response reference<input required minLength={3} value={draft.response_reference||""} onChange={e=>setDraft({...draft,response_reference:e.target.value})}/></label><label>Evidence reference<input required minLength={3} value={draft.evidence_reference||""} onChange={e=>setDraft({...draft,evidence_reference:e.target.value})}/></label></>:null}<label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="TRUST_REVIEW"?<><label>Decision<select value={draft.status||"READY"} onChange={e=>setDraft({...draft,status:e.target.value})}><option>READY</option><option>REJECTED</option></select></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="TRUST_SEND"?<><p>Record the external delivery/provider/mail reference for <b>{modal.trust.trust_code}</b>.</p><label>Delivery reference<input required minLength={3} value={draft.sent_reference||""} onChange={e=>setDraft({...draft,sent_reference:e.target.value})}/></label></>
   :<label>Closure note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
