"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, KeyRound, LoaderCircle, PackageCheck, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-secure-custody.module.css";

type Caps={read:boolean;manage:boolean;checkout:boolean;review:boolean};
type Person={user_id:string;display_name?:string|null;job_title?:string|null};
type Asset={id:string;asset_no:string;name:string;category:string;serial_no?:string|null;status:string};
type Item={id:string;custody_code:string;item_type:string;title:string;reference_no?:string|null;linked_asset_id?:string|null;document_reference?:string|null;current_custodian_user_id?:string|null;storage_location:string;classification:string;status:string;notes?:string|null;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;created_at:string;updated_at:string};
type Checkout={id:string;checkout_code:string;item_id:string;checked_out_to_user_id:string;purpose:string;related_reference?:string|null;checked_out_by:string;checked_out_at:string;due_back_at?:string|null;status:string;returned_at?:string|null;return_evidence_reference?:string|null;return_verified_by?:string|null;return_verified_at?:string|null;loss_evidence_reference?:string|null;created_at:string;updated_at:string};
type Payload={generated_at:string;actor:{user_id:string;roles:string[]};capabilities:Caps;items:Item[];checkouts:Checkout[];people:Person[];assets:Asset[];disclaimer:string};
type View="items"|"checkouts";
type Modal={kind:"ITEM"}|{kind:"CHECKOUT";item:Item}|{kind:"RETURN";checkout:Checkout}|{kind:"VERIFY";checkout:Checkout}|{kind:"LOST";checkout:Checkout};

async function api<T>(options?:RequestInit):Promise<T>{
 const r=await fetch("/api/office-custody",{...options,cache:"no-store",credentials:"same-origin"});
 const b=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Secure-custody operation failed");
 return b as T;
}
function date(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function toIso(v?:string){if(!v)return undefined;const d=new Date(v);return Number.isNaN(d.getTime())?undefined:d.toISOString()}

export function OfficeSecureCustody(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("items");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive)setData(n)}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load secure custody")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(p=>[p.user_id,p])),[data?.people]);
 const assets=useMemo(()=>new Map((data?.assets??[]).map(a=>[a.id,a])),[data?.assets]);
 const items=useMemo(()=>new Map((data?.items??[]).map(i=>[i.id,i])),[data?.items]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="ITEM")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_ITEM",item_type:draft.item_type||"ORIGINAL_DOCUMENT",title:draft.title,reference_no:draft.reference_no||undefined,asset_id:draft.asset_id||undefined,document_reference:draft.document_reference||undefined,custodian_user_id:draft.custodian_user_id||undefined,storage_location:draft.storage_location,classification:draft.classification||"RESTRICTED",notes:draft.notes||undefined})});
  else if(modal.kind==="CHECKOUT")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CHECKOUT",item_id:modal.item.id,to_user_id:draft.to_user_id,purpose:draft.purpose,related_reference:draft.related_reference||undefined,due_back_at:toIso(draft.due_back_at)})});
  else if(modal.kind==="RETURN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"RETURN",checkout_id:modal.checkout.id,evidence:draft.evidence})});
  else if(modal.kind==="VERIFY")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"VERIFY_RETURN",checkout_id:modal.checkout.id,evidence:draft.evidence})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"MARK_LOST",checkout_id:modal.checkout.id,evidence:draft.evidence,note:draft.note||undefined})});
  await reload("Secure-custody record updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Secure-custody action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Secure custody unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading secure custody</h2></div></section>;
 const nowMs=Date.parse(data.generated_at);
 const overdue=data.checkouts.filter(c=>c.status==="OPEN"&&c.due_back_at&&Date.parse(c.due_back_at)<nowMs).length;
 const checkedOut=data.items.filter(i=>i.status==="CHECKED_OUT").length;
 const unverified=data.checkouts.filter(c=>c.status==="RETURNED"&&!c.return_verified_at).length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>SECURE CUSTODY · ORIGINALS · DSC TOKENS</p><h2>Track physical possession of restricted company items without storing their secrets.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{checkedOut}</b><span>checked out</span></article><article><b>{overdue}</b><span>overdue returns</span></article><article><b>{unverified}</b><span>returns awaiting review</span></article></div></header>
  <div className={styles.warning}><KeyRound/><div><b>Custody metadata only</b><span>Never enter a DSC/signing PIN, private key, token secret, recovery phrase or password into this module.</span></div></div>
  <div className={styles.toolbar}><button type="button" data-active={view==="items"} onClick={()=>setView("items")}>Items</button><button type="button" data-active={view==="checkouts"} onClick={()=>setView("checkouts")}>Checkouts</button><button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="items"&&data.capabilities.manage?<button type="button" onClick={()=>{setDraft({item_type:"ORIGINAL_DOCUMENT",classification:"RESTRICTED"});setModal({kind:"ITEM"})}}><Plus/>Register item</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="items"?<div className={styles.grid}>{data.items.map(item=><article className={styles.card} key={item.id}><header><div><small>{item.custody_code} · {item.item_type.replaceAll("_"," ")}</small><h3>{item.title}</h3><span>{item.classification} · {item.storage_location}</span></div><em className={styles.badge} data-status={item.status}>{item.status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Reference<b>{item.reference_no||"—"}</b></span><span>Document ref<b>{item.document_reference||"—"}</b></span><span>Linked asset<b>{item.linked_asset_id?assets.get(item.linked_asset_id)?.asset_no||item.linked_asset_id:"—"}</b></span><span>Custodian<b>{item.current_custodian_user_id?people.get(item.current_custodian_user_id)?.display_name||item.current_custodian_user_id:"Secure storage"}</b></span></div>{item.notes?<p>{item.notes}</p>:null}{item.status==="IN_CUSTODY"&&data.capabilities.checkout?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({});setModal({kind:"CHECKOUT",item})}}><PackageCheck/>Checkout</button></div>:null}</article>)}{!data.items.length?<div className={styles.empty}>No secure-custody items recorded.</div>:null}</div>:null}

  {view==="checkouts"?<div className={styles.grid}>{data.checkouts.map(c=>{const item=items.get(c.item_id);const isOverdue=c.status==="OPEN"&&!!c.due_back_at&&Date.parse(c.due_back_at)<nowMs;return <article className={styles.card} key={c.id}><header><div><small>{c.checkout_code} · {item?.custody_code||"Item"}</small><h3>{item?.title||"Secure item checkout"}</h3><span>{c.purpose}</span></div><em className={styles.badge} data-status={isOverdue?"OVERDUE":c.status}>{isOverdue?"OVERDUE":c.status}</em></header><div className={styles.kv}><span>Recipient<b>{people.get(c.checked_out_to_user_id)?.display_name||(c.checked_out_to_user_id===data.actor.user_id?"You":c.checked_out_to_user_id)}</b></span><span>Checked out<b>{date(c.checked_out_at)}</b></span><span>Due back<b>{date(c.due_back_at)}</b></span><span>Related ref<b>{c.related_reference||"—"}</b></span><span>Return evidence<b>{c.return_evidence_reference||"—"}</b></span><span>Verified<b>{date(c.return_verified_at)}</b></span><span>Loss evidence<b>{c.loss_evidence_reference||"—"}</b></span></div><div className={styles.actions}>{["OPEN","OVERDUE"].includes(c.status)&&c.checked_out_to_user_id===data.actor.user_id?<button type="button" onClick={()=>{setDraft({evidence:""});setModal({kind:"RETURN",checkout:c})}}>Record return</button>:null}{c.status==="RETURNED"&&!c.return_verified_at&&data.capabilities.review&&c.checked_out_to_user_id!==data.actor.user_id&&c.checked_out_by!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({evidence:""});setModal({kind:"VERIFY",checkout:c})}}><ShieldCheck/>Verify return</button>:null}{["OPEN","OVERDUE"].includes(c.status)&&data.capabilities.review&&c.checked_out_to_user_id!==data.actor.user_id&&c.checked_out_by!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({evidence:"",note:""});setModal({kind:"LOST",checkout:c})}}>Declare lost</button>:null}</div></article>})}{!data.checkouts.length?<div className={styles.empty}>No secure-item checkout history.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>RESTRICTED PHYSICAL-CUSTODY ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="ITEM"?<><label>Item type<select value={draft.item_type||"ORIGINAL_DOCUMENT"} onChange={e=>setDraft({...draft,item_type:e.target.value})}>{["DSC_TOKEN","ORIGINAL_DOCUMENT","SHARE_CERTIFICATE","BANK_DOCUMENT","GOVERNMENT_CERTIFICATE","SECURITY_TOKEN","BACKUP_MEDIA","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Reference number<input value={draft.reference_no||""} onChange={e=>setDraft({...draft,reference_no:e.target.value})}/></label><label>Document reference<input value={draft.document_reference||""} onChange={e=>setDraft({...draft,document_reference:e.target.value})}/></label></div><label>Linked normal asset<select value={draft.asset_id||""} onChange={e=>setDraft({...draft,asset_id:e.target.value})}><option value="">No asset link</option>{data.assets.map(a=><option key={a.id} value={a.id}>{a.asset_no} · {a.name}</option>)}</select></label><div className={styles.two}><label>Initial custodian<select value={draft.custodian_user_id||""} onChange={e=>setDraft({...draft,custodian_user_id:e.target.value})}><option value="">Secure storage</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Classification<select value={draft.classification||"RESTRICTED"} onChange={e=>setDraft({...draft,classification:e.target.value})}>{["CONFIDENTIAL","RESTRICTED","LEGAL","BOARD","SECURITY"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Storage location<input required minLength={2} value={draft.storage_location||""} onChange={e=>setDraft({...draft,storage_location:e.target.value})}/></label><label>Notes<textarea value={draft.notes||""} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><p className={styles.muted}>Do not enter any PIN, private key, password or token secret.</p></>
   :modal.kind==="CHECKOUT"?<><label>Recipient<select required value={draft.to_user_id||""} onChange={e=>setDraft({...draft,to_user_id:e.target.value})}><option value="">Select recipient</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Purpose<textarea required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><div className={styles.two}><label>Related reference<input value={draft.related_reference||""} onChange={e=>setDraft({...draft,related_reference:e.target.value})}/></label><label>Due back<input type="datetime-local" value={draft.due_back_at||""} onChange={e=>setDraft({...draft,due_back_at:e.target.value})}/></label></div></>
   :modal.kind==="RETURN"?<label>Return evidence reference<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>
   :modal.kind==="VERIFY"?<label>Independent return-verification evidence<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>
   :<><label>Loss evidence/reference<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
