"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CircleAlert, Laptop, LifeBuoy, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-it-service.module.css";

type Ticket={id:string;ticket_code:string;requester_user_id:string;owner_user_id?:string|null;category:string;priority:string;title:string;description:string;status:string;related_device_id?:string|null;resolution?:string|null;due_at?:string|null;created_at:string;updated_at:string};
type Device={id:string;user_id:string;device_label:string;device_kind:string;platform?:string|null;trust_state:string};
type Identity={user_id:string;display_name?:string|null;job_title?:string|null};
type License={id:string;license_code:string;vendor_name:string;product_name:string;plan_name?:string|null;billing_cycle?:string|null;total_seats?:number|null;currency?:string|null;cost_minor?:number|null;renewal_at?:string|null;auto_renew:boolean;status:string;owner_user_id:string};
type Assignment={id:string;license_id:string;user_id:string;assigned_at:string;expires_at?:string|null;status:string;external_seat_reference?:string|null};
type Payload={actor:{user_id:string};capabilities:{manage:boolean;read_company:boolean;license_read:boolean;license_manage:boolean};tickets:Ticket[];devices:Device[];identities:Identity[];licenses:License[];assignments:Assignment[];disclaimer:string};
type View="tickets"|"licenses";
type Modal={kind:"TICKET"}|{kind:"TRANSITION";ticket:Ticket}|{kind:"LICENSE"}|{kind:"ASSIGN";license:License}|{kind:"REVOKE";assignment:Assignment};

async function api<T>(options?:RequestInit):Promise<T>{const response=await fetch("/api/office-it",{...options,cache:"no-store",credentials:"same-origin"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"IT service request failed");return body as T}
function date(value?:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function money(value?:number|null,currency?:string|null){if(value==null)return "—";return `${currency||"INR"} ${(value/100).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`}

export function OfficeItService(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("tickets");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load IT service desk")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.identities??[]).map(row=>[row.user_id,row])),[data?.identities]);
 const devices=useMemo(()=>new Map((data?.devices??[]).map(row=>[row.id,row])),[data?.devices]);
 const usedSeats=useMemo(()=>{const map=new Map<string,number>();for(const row of data?.assignments??[])if(row.status==="ACTIVE")map.set(row.license_id,(map.get(row.license_id)||0)+1);return map},[data?.assignments]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="TICKET")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_TICKET",category:draft.category||"OTHER",priority:draft.priority||"NORMAL",title:draft.title,description:draft.description,device_id:draft.device_id||undefined})});
  else if(modal.kind==="TRANSITION")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_TICKET",ticket_id:modal.ticket.id,status:draft.status,owner_user_id:draft.owner_user_id||undefined,note:draft.note||undefined})});
  else if(modal.kind==="LICENSE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_LICENSE",owner_user_id:draft.owner_user_id,vendor:draft.vendor,product:draft.product,plan:draft.plan||undefined,cycle:draft.cycle||undefined,seats:draft.seats?Number(draft.seats):undefined,currency:draft.currency||undefined,cost_minor:draft.cost?Math.round(Number(draft.cost)*100):undefined,renewal_at:draft.renewal_at?new Date(draft.renewal_at).toISOString():undefined,auto_renew:draft.auto_renew==="YES"})});
  else if(modal.kind==="ASSIGN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ASSIGN_LICENSE",license_id:modal.license.id,user_id:draft.user_id,external_reference:draft.external_reference||undefined,expires_at:draft.expires_at?new Date(draft.expires_at).toISOString():undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVOKE_LICENSE",assignment_id:modal.assignment.id,reason:draft.reason})});
  await reload("IT service control updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"IT service action failed")}finally{setBusy(false)}}
 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>IT service unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading IT service desk</h2></div></section>;
 const open=data.tickets.filter(t=>!["RESOLVED","CLOSED","CANCELLED"].includes(t.status)).length;
 const seats=data.assignments.filter(a=>a.status==="ACTIVE").length;
 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>IT SERVICE DESK · SOFTWARE LICENCES</p><h2>Request, resolve and provision company technology inside KRAVIA Office.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{open}</b><span>open tickets</span></article><article><b>{data.licenses.length}</b><span>licences</span></article><article><b>{seats}</b><span>assigned seats</span></article></div></header>
  <div className={styles.toolbar}><button type="button" data-active={view==="tickets"} onClick={()=>setView("tickets")}>Service desk</button><button type="button" data-active={view==="licenses"} onClick={()=>setView("licenses")}>Licences</button><button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="tickets"?<button type="button" onClick={()=>{setDraft({category:"OTHER",priority:"NORMAL"});setModal({kind:"TICKET"})}}><Plus/>New request</button>:data.capabilities.license_manage?<button type="button" onClick={()=>{setDraft({currency:"INR",cycle:"ANNUAL",auto_renew:"NO"});setModal({kind:"LICENSE"})}}><Plus/>New licence</button>:null}</div>
  {notice?<div className={styles.notice}><ShieldCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}
  {view==="tickets"?<div className={styles.list}>{data.tickets.map(t=><article className={styles.card} key={t.id}><header><div><code>{t.ticket_code}</code><h3>{t.title}</h3><span>{t.category} · {t.priority}</span></div><em className={styles.badge} data-status={t.status}>{t.status.replaceAll("_"," ")}</em></header><p>{t.description}</p><div className={styles.meta}><span>Requester<b>{people.get(t.requester_user_id)?.display_name|| (t.requester_user_id===data.actor.user_id?"You":"Employee")}</b></span><span>Owner<b>{t.owner_user_id?people.get(t.owner_user_id)?.display_name||"Assigned":"Unassigned"}</b></span><span>Device<b>{t.related_device_id?devices.get(t.related_device_id)?.device_label||"Linked device":"—"}</b></span><span>Created<b>{date(t.created_at)}</b></span></div>{t.resolution?<p><b>Resolution:</b> {t.resolution}</p>:null}{data.capabilities.manage&&!["CLOSED","CANCELLED"].includes(t.status)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:t.status,owner_user_id:t.owner_user_id||"",note:""});setModal({kind:"TRANSITION",ticket:t})}}><LifeBuoy/>Update</button></div>:null}</article>)}{!data.tickets.length?<div className={styles.empty}>No IT requests in your scope.</div>:null}</div>:null}
  {view==="licenses"?<div className={styles.list}>{data.licenses.map(l=><article className={styles.card} key={l.id}><header><div><code>{l.license_code}</code><h3>{l.product_name}</h3><span>{l.vendor_name}{l.plan_name?` · ${l.plan_name}`:""}</span></div><em className={styles.badge} data-status={l.status}>{l.status}</em></header><div className={styles.meta}><span>Seats<b>{usedSeats.get(l.id)||0} / {l.total_seats??"Unlimited"}</b></span><span>Cost<b>{money(l.cost_minor,l.currency)}</b></span><span>Renewal<b>{date(l.renewal_at)}</b></span><span>Auto-renew<b>{l.auto_renew?"Yes":"No"}</b></span></div>{data.capabilities.license_manage?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({});setModal({kind:"ASSIGN",license:l})}}>Assign seat</button></div>:null}{data.assignments.filter(a=>a.license_id===l.id&&a.status==="ACTIVE").map(a=><div className={styles.meta} key={a.id}><span>User<b>{people.get(a.user_id)?.display_name||a.user_id}</b></span><span>Assigned<b>{date(a.assigned_at)}</b></span><span>Expires<b>{date(a.expires_at)}</b></span>{data.capabilities.license_manage?<span><button type="button" onClick={()=>{setDraft({reason:""});setModal({kind:"REVOKE",assignment:a})}}>Revoke</button></span>:<span/>}</div>)}</article>)}{!data.licenses.length?<div className={styles.empty}>No software licences in your authorised scope.</div>:null}</div>:null}
  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED IT ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="TICKET"?<><div className={styles.two}><label>Category<select value={draft.category||"OTHER"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["DEVICE","SOFTWARE","ACCESS","EMAIL","MFA","NETWORK","VPN","PRINTER","SECURITY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select value={draft.priority||"NORMAL"} onChange={e=>setDraft({...draft,priority:e.target.value})}>{["LOW","NORMAL","HIGH","URGENT"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Related device<select value={draft.device_id||""} onChange={e=>setDraft({...draft,device_id:e.target.value})}><option value="">None</option>{data.devices.filter(d=>d.user_id===data.actor.user_id).map(d=><option key={d.id} value={d.id}>{d.device_label}</option>)}</select></label></>
   :modal.kind==="TRANSITION"?<><div className={styles.two}><label>Status<select value={draft.status||modal.ticket.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{["OPEN","TRIAGED","IN_PROGRESS","WAITING_USER","WAITING_VENDOR","RESOLVED","CLOSED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Keep current</option>{data.identities.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><label>Note / resolution<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="LICENSE"?<><div className={styles.two}><label>Vendor<input required value={draft.vendor||""} onChange={e=>setDraft({...draft,vendor:e.target.value})}/></label><label>Product<input required value={draft.product||""} onChange={e=>setDraft({...draft,product:e.target.value})}/></label></div><div className={styles.two}><label>Plan<input value={draft.plan||""} onChange={e=>setDraft({...draft,plan:e.target.value})}/></label><label>Billing cycle<select value={draft.cycle||"ANNUAL"} onChange={e=>setDraft({...draft,cycle:e.target.value})}>{["MONTHLY","ANNUAL","MULTI_YEAR","PERPETUAL","USAGE"].map(v=><option key={v}>{v}</option>)}</select></label></div><div className={styles.two}><label>Seats<input type="number" min="0" value={draft.seats||""} onChange={e=>setDraft({...draft,seats:e.target.value})}/></label><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.identities.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label></div><div className={styles.two}><label>Cost<input inputMode="decimal" value={draft.cost||""} onChange={e=>setDraft({...draft,cost:e.target.value})}/></label><label>Currency<input maxLength={3} value={draft.currency||"INR"} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label></div><div className={styles.two}><label>Renewal<input type="datetime-local" value={draft.renewal_at||""} onChange={e=>setDraft({...draft,renewal_at:e.target.value})}/></label><label>Auto-renew<select value={draft.auto_renew||"NO"} onChange={e=>setDraft({...draft,auto_renew:e.target.value})}><option>NO</option><option>YES</option></select></label></div></>
   :modal.kind==="ASSIGN"?<><label>User<select required value={draft.user_id||""} onChange={e=>setDraft({...draft,user_id:e.target.value})}><option value="">Select user</option>{data.identities.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>External seat reference<input value={draft.external_reference||""} onChange={e=>setDraft({...draft,external_reference:e.target.value})}/></label><label>Expiry<input type="datetime-local" value={draft.expires_at||""} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></label></>
   :<label>Reason<textarea required minLength={3} value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>
}
