"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, LoaderCircle, LockKeyhole, MessageSquareMore, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-ethics.module.css";

type Caps={report:boolean;case_read:boolean;case_manage:boolean;case_review:boolean};
type Case={id:string;case_code:string;reporter_user_id:string;category:string;severity:string;title:string;report_text:string;reporter_evidence_reference?:string|null;confidentiality_notice:string;status:string;investigator_user_id?:string|null;reviewer_user_id?:string|null;outcome_summary?:string|null;reporter_safe_outcome?:string|null;created_at:string;updated_at:string;closed_at?:string|null};
type Note={id:number;case_id:string;author_user_id:string;visibility:string;note_text:string;evidence_reference?:string|null;created_at:string};
type Investigator={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null};
type Payload={actor:{user_id:string;roles:string[]};capabilities:Caps;my_cases:Case[];investigation_cases:Case[];notes:Note[];investigators:Investigator[];disclaimer:string};
type View="mine"|"investigations";
type Modal={kind:"REPORT"}|{kind:"NOTE";item:Case;visibility:"REPORTER"|"INVESTIGATOR"}|{kind:"ASSIGN";item:Case}|{kind:"TRANSITION";item:Case}|{kind:"WITHDRAW";item:Case};

async function api<T>(options?:RequestInit):Promise<T>{const r=await fetch("/api/office-ethics",{...options,cache:"no-store",credentials:"same-origin"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.detail==="string"?b.detail:"Ethics operation failed");return b as T}
function date(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function investigatorNext(row:Case){if(row.status==="SUBMITTED"||row.status==="TRIAGE")return "INVESTIGATING";if(row.status==="INVESTIGATING")return "ACTION_PENDING";if(row.status==="ACTION_PENDING")return "AWAITING_REVIEW";return row.status}

export function OfficeEthicsChannel(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("mine");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(n=>{if(alive)setData(n)}).catch((e:unknown)=>{if(alive)setError(e instanceof Error?e.message:"Unable to load Ethics channel")});return()=>{alive=false}},[]);
 const notes=useMemo(()=>{const map=new Map<string,Note[]>();for(const n of data?.notes??[]){const a=map.get(n.case_id)||[];a.push(n);map.set(n.case_id,a)}return map},[data?.notes]);
 const investigatorNames=useMemo(()=>new Map((data?.investigators??[]).map(i=>[i.user_id,i.display_name||i.user_id])),[data?.investigators]);

 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="REPORT")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REPORT",category:draft.category||"OTHER",severity:draft.severity||"MEDIUM",title:draft.title,report:draft.report,evidence:draft.evidence||undefined})});
  else if(modal.kind==="NOTE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"NOTE",case_id:modal.item.id,visibility:modal.visibility,note:draft.note,evidence:draft.evidence||undefined})});
  else if(modal.kind==="ASSIGN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ASSIGN",case_id:modal.item.id,investigator_user_id:draft.investigator_user_id})});
  else if(modal.kind==="WITHDRAW")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION",case_id:modal.item.id,status:"WITHDRAWN"})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION",case_id:modal.item.id,status:draft.status,outcome:draft.outcome||undefined,reporter_outcome:draft.reporter_outcome||undefined})});
  await reload("Ethics case updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Ethics action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Ethics channel unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading confidential ethics channel</h2></div></section>;
 const openMine=data.my_cases.filter(c=>!["CLOSED","UNSUBSTANTIATED","WITHDRAWN"].includes(c.status)).length;
 const reviewQueue=data.investigation_cases.filter(c=>c.status==="AWAITING_REVIEW").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>CONFIDENTIAL ETHICS CHANNEL</p><h2>Report and investigate concerns outside normal manager and HR visibility.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{openMine}</b><span>your open reports</span></article>{data.capabilities.case_read?<article><b>{reviewQueue}</b><span>awaiting independent review</span></article>:null}</div></header>
  <div className={styles.warning}><LockKeyhole/><div><b>Confidential, not technically anonymous</b><span>Reporter identity is retained in the restricted case system. Normal managers, HR workspaces and global Office search do not receive this case content.</span></div></div>
  <div className={styles.toolbar}><button type="button" data-active={view==="mine"} onClick={()=>setView("mine")}>My reports</button>{data.capabilities.case_read?<button type="button" data-active={view==="investigations"} onClick={()=>setView("investigations")}>Investigation queue</button>:null}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{data.capabilities.report&&view==="mine"?<button type="button" onClick={()=>{setDraft({category:"OTHER",severity:"MEDIUM"});setModal({kind:"REPORT"})}}><Plus/>Report concern</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="mine"?<div className={styles.grid}>{data.my_cases.map(c=><article className={styles.card} key={c.id}><header><div><small>{c.case_code} · {c.category}</small><h3>{c.title}</h3><span>{date(c.created_at)} · {c.severity}</span></div><em className={styles.badge} data-status={c.status}>{c.status.replaceAll("_"," ")}</em></header><p className={styles.report}>{c.report_text}</p>{c.reporter_safe_outcome?<div className={styles.outcome}><b>Case outcome</b><p>{c.reporter_safe_outcome}</p></div>:null}<div className={styles.thread}>{(notes.get(c.id)||[]).filter(n=>n.visibility==="REPORTER").map(n=><div key={n.id}><MessageSquareMore/><span><b>{n.author_user_id===data.actor.user_id?"You":"Investigation team"}</b>{n.note_text}<small>{date(n.created_at)}{n.evidence_reference?" · evidence "+n.evidence_reference:""}</small></span></div>)}</div>{!["CLOSED","UNSUBSTANTIATED","WITHDRAWN"].includes(c.status)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({note:"",evidence:""});setModal({kind:"NOTE",item:c,visibility:"REPORTER"})}}><MessageSquareMore/>Add confidential note</button>{["SUBMITTED","TRIAGE"].includes(c.status)?<button type="button" onClick={()=>setModal({kind:"WITHDRAW",item:c})}>Withdraw report</button>:null}</div>:null}</article>)}{!data.my_cases.length?<div className={styles.empty}>You have not submitted an ethics report.</div>:null}</div>:null}

  {view==="investigations"&&data.capabilities.case_read?<div className={styles.grid}>{data.investigation_cases.map(c=>{const assignedToMe=c.investigator_user_id===data.actor.user_id;const canReview=data.capabilities.case_review&&c.status==="AWAITING_REVIEW"&&c.investigator_user_id!==data.actor.user_id&&c.reporter_user_id!==data.actor.user_id;return <article className={styles.card} key={c.id}><header><div><small>{c.case_code} · {c.category}</small><h3>{c.title}</h3><span>Reporter identity protected in list · {c.severity}</span></div><em className={styles.badge} data-status={c.status}>{c.status.replaceAll("_"," ")}</em></header><p className={styles.report}>{c.report_text}</p><div className={styles.kv}><span>Investigator<b>{c.investigator_user_id?investigatorNames.get(c.investigator_user_id)||"Restricted investigator":"Unassigned"}</b></span><span>Evidence<b>{c.reporter_evidence_reference||"—"}</b></span><span>Created<b>{date(c.created_at)}</b></span></div><div className={styles.thread}>{(notes.get(c.id)||[]).map(n=><div key={n.id}><MessageSquareMore/><span><b>{n.visibility==="REPORTER"?"Reporter-visible":"Investigator-only"}</b>{n.note_text}<small>{date(n.created_at)}</small></span></div>)}</div><div className={styles.actions}>{data.capabilities.case_manage&&!c.investigator_user_id?<button type="button" onClick={()=>{setDraft({investigator_user_id:""});setModal({kind:"ASSIGN",item:c})}}>Assign investigator</button>:null}{data.capabilities.case_manage&&assignedToMe&&!["AWAITING_REVIEW","CLOSED","UNSUBSTANTIATED","WITHDRAWN"].includes(c.status)?<><button type="button" onClick={()=>{setDraft({note:"",evidence:""});setModal({kind:"NOTE",item:c,visibility:"INVESTIGATOR"})}}>Add investigator note</button><button type="button" onClick={()=>{setDraft({status:investigatorNext(c)});setModal({kind:"TRANSITION",item:c})}}>Advance investigation</button></>:null}{canReview?<button type="button" onClick={()=>{setDraft({status:"CLOSED",outcome:"",reporter_outcome:""});setModal({kind:"TRANSITION",item:c})}}><ShieldCheck/>Independent closure review</button>:null}</div></article>})}{!data.investigation_cases.length?<div className={styles.empty}>No restricted ethics cases in the investigator queue.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>RESTRICTED ETHICS ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="REPORT"?<><div className={styles.two}><label>Category<select value={draft.category||"OTHER"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["CODE_OF_CONDUCT","HARASSMENT","DISCRIMINATION","FRAUD","BRIBERY","CONFLICT_OF_INTEREST","DATA_MISUSE","SECURITY","RETALIATION","SAFETY","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Severity<select value={draft.severity||"MEDIUM"} onChange={e=>setDraft({...draft,severity:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Report<textarea required minLength={10} value={draft.report||""} onChange={e=>setDraft({...draft,report:e.target.value})}/></label><label>Evidence reference<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="NOTE"?<><label>Note<textarea required minLength={1} value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><label>Evidence reference<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label><small>Visibility: {modal.visibility==="REPORTER"?"Reporter and investigation team":"Investigation team only"}</small></>
   :modal.kind==="ASSIGN"?<label>Investigator<select required value={draft.investigator_user_id||""} onChange={e=>setDraft({...draft,investigator_user_id:e.target.value})}><option value="">Select explicitly authorised investigator</option>{data.investigators.filter(i=>i.user_id!==modal.item.reporter_user_id).map(i=><option key={i.user_id} value={i.user_id}>{i.display_name||i.user_id}</option>)}</select></label>
   :modal.kind==="WITHDRAW"?<p>Withdraw <b>{modal.item.case_code}</b>? The historical record remains retained.</p>
   :<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{modal.item.status==="AWAITING_REVIEW"?<><option>CLOSED</option><option>UNSUBSTANTIATED</option></>:<option>{investigatorNext(modal.item)}</option>}</select></label>{["CLOSED","UNSUBSTANTIATED"].includes(draft.status)?<><label>Restricted outcome summary<textarea required minLength={3} value={draft.outcome||""} onChange={e=>setDraft({...draft,outcome:e.target.value})}/></label><label>Reporter-safe outcome<textarea required minLength={3} value={draft.reporter_outcome||""} onChange={e=>setDraft({...draft,reporter_outcome:e.target.value})}/></label></>:null}</>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
