"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, FilePlus2, LoaderCircle, RefreshCw, ReceiptIndianRupee, X } from "lucide-react";
import styles from "./office-billing.module.css";

type Invoice={id:string;invoice_no:string;status:string;issued_at:string;due_date?:string|null;customer_id:string;product_id:string;description:string;sac?:string|null;taxable_value:number;discount:number;net_taxable:number;gst_rate:string;cgst:number;sgst:number;igst:number;total:number;paid:number;balance:number;currency:string;document_hash:string};
type Customer={id:string;legal_name:string;display_name:string;gstin?:string|null;state:string;state_code:string;country:string;status:string};
type Product={id:string;code:string;name:string;category:string;status:string};
type Modal={kind:"INVOICE"}|{kind:"RECEIPT";invoice:Invoice};

async function runtime<T>(path:string,options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-runtime/"+path,{...options,credentials:"same-origin",cache:"no-store"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Finance runtime request failed");
 return body as T;
}
function key(){return crypto.randomUUID()}
function money(value:number,currency="INR"){return currency+" "+Number(value||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function date(value?:string|null){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(d)}

export function OfficeBillingWorkspace({canCreateInvoice,canRecordReceipt}:{canCreateInvoice:boolean;canRecordReceipt:boolean}){
 const[invoices,setInvoices]=useState<Invoice[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[products,setProducts]=useState<Product[]>([]);const[loading,setLoading]=useState(true);const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 const load=useCallback(async()=>{setLoading(true);setError(undefined);try{const [i,c,p]=await Promise.all([runtime<Invoice[]>("invoices"),runtime<Customer[]>("customers"),runtime<Product[]>("products")]);setInvoices(i);setCustomers(c);setProducts(p)}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load billing records")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const customerMap=useMemo(()=>new Map(customers.map(c=>[c.id,c])),[customers]);const productMap=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="INVOICE"){
   const payload={customer_id:draft.customer_id,product_id:draft.product_id,description:draft.description,sac:draft.sac||undefined,qty:Number(draft.qty||"1"),taxable_value:Number(draft.taxable_value||"0"),discount:Number(draft.discount||"0"),gst_rate:Number(draft.gst_rate||"18"),due_date:draft.due_date||undefined,notes:draft.notes||undefined};
   await runtime("invoices",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key()},body:JSON.stringify(payload)});
   setNotice("Invoice issued through the canonical Finance runtime.");
  }else{
   const payload={amount:Number(draft.amount||"0"),method:draft.method||"BANK_TRANSFER",external_reference:draft.external_reference||undefined,received_date:draft.received_date};
   await runtime("invoices/"+encodeURIComponent(modal.invoice.id)+"/payments",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key()},body:JSON.stringify(payload)});
   setNotice("Received payment recorded and receipt generated by the canonical Finance runtime.");
  }
  setModal(undefined);setDraft({});await load();
 }catch(caught){setError(caught instanceof Error?caught.message:"Billing action failed")}finally{setBusy(false)}}

 const receivables=invoices.reduce((sum,i)=>sum+Number(i.balance||0),0);
 const issued=invoices.reduce((sum,i)=>sum+Number(i.total||0),0);
 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>BILLING · TAX · RECEIPTS</p><h2>Issue canonical invoices and record externally received payments inside KRAVIA.</h2><span>Production GST invoicing remains blocked by the backend until GSTIN and approved tax configuration are locked. Recording a receipt never initiates a bank payment.</span></div><div className={styles.metrics}><article><b>{money(issued)}</b><span>issued value</span></article><article><b>{money(receivables)}</b><span>receivables</span></article><article><b>{invoices.length}</b><span>invoices</span></article></div></header>
  <div className={styles.toolbar}><button type="button" onClick={()=>void load()}><RefreshCw/>Refresh</button>{canCreateInvoice?<button type="button" onClick={()=>{setDraft({qty:"1",discount:"0",gst_rate:"18"});setModal({kind:"INVOICE"})}}><FilePlus2/>Issue invoice</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}
  {loading?<div className={styles.state}><LoaderCircle className={styles.spin}/>Loading canonical invoices…</div>:<div className={styles.grid}>{invoices.map(i=><article className={styles.card} key={i.id}><header><div><small>{i.invoice_no} · {date(i.issued_at)}</small><h3>{customerMap.get(i.customer_id)?.display_name||customerMap.get(i.customer_id)?.legal_name||i.customer_id}</h3><span>{productMap.get(i.product_id)?.name||i.product_id} · {i.description}</span></div><em data-status={i.status}>{i.status}</em></header><div className={styles.kv}><span>Total<b>{money(i.total,i.currency)}</b></span><span>Paid<b>{money(i.paid,i.currency)}</b></span><span>Balance<b>{money(i.balance,i.currency)}</b></span><span>GST<b>{i.gst_rate}%</b></span><span>CGST / SGST / IGST<b>{money(i.cgst)} / {money(i.sgst)} / {money(i.igst)}</b></span><span>Due<b>{date(i.due_date)}</b></span></div><details><summary>Invoice integrity</summary><code>{i.document_hash}</code></details>{canRecordReceipt&&Number(i.balance)>0?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({amount:String(i.balance),method:"BANK_TRANSFER",received_date:new Date().toISOString().slice(0,10)});setModal({kind:"RECEIPT",invoice:i})}}><ReceiptIndianRupee/>Record received payment</button></div>:null}</article>)}{!invoices.length?<div className={styles.empty}>No canonical invoices yet.</div>:null}</div>}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CANONICAL FINANCE ACTION</small><h3>{modal.kind==="INVOICE"?"Issue invoice":"Record received payment"}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="INVOICE"?<><label>Customer<select required value={draft.customer_id||""} onChange={e=>setDraft({...draft,customer_id:e.target.value})}><option value="">Select customer</option>{customers.filter(c=>c.status==="ACTIVE").map(c=><option key={c.id} value={c.id}>{c.display_name||c.legal_name} · {c.state}</option>)}</select></label><label>Product<select required value={draft.product_id||""} onChange={e=>setDraft({...draft,product_id:e.target.value})}><option value="">Select product</option>{products.filter(p=>p.status==="ACTIVE").map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>Description<textarea required minLength={2} maxLength={1000} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className={styles.three}><label>Quantity<input required type="number" min="0.001" step="0.001" value={draft.qty||"1"} onChange={e=>setDraft({...draft,qty:e.target.value})}/></label><label>Taxable value<input required type="number" min="0.01" step="0.01" value={draft.taxable_value||""} onChange={e=>setDraft({...draft,taxable_value:e.target.value})}/></label><label>Discount<input type="number" min="0" step="0.01" value={draft.discount||"0"} onChange={e=>setDraft({...draft,discount:e.target.value})}/></label></div><div className={styles.three}><label>GST rate %<input required type="number" min="0" max="100" step="0.01" value={draft.gst_rate||"18"} onChange={e=>setDraft({...draft,gst_rate:e.target.value})}/></label><label>SAC<input value={draft.sac||""} onChange={e=>setDraft({...draft,sac:e.target.value})}/></label><label>Due date<input type="date" value={draft.due_date||""} onChange={e=>setDraft({...draft,due_date:e.target.value})}/></label></div><label>Notes<textarea value={draft.notes||""} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><p className={styles.warning}>The backend computes tax from canonical company/customer state. Production issuance is fail-closed until controlled GST configuration is approved.</p></>
   :<><p>Invoice <b>{modal.invoice.invoice_no}</b> · outstanding {money(modal.invoice.balance,modal.invoice.currency)}.</p><label>Amount received<input required type="number" min="0.01" max={modal.invoice.balance} step="0.01" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><div className={styles.two}><label>Method<input required minLength={2} maxLength={80} value={draft.method||""} onChange={e=>setDraft({...draft,method:e.target.value})}/></label><label>Received date<input required type="date" value={draft.received_date||""} onChange={e=>setDraft({...draft,received_date:e.target.value})}/></label></div><label>External/bank reference<input maxLength={160} value={draft.external_reference||""} onChange={e=>setDraft({...draft,external_reference:e.target.value})}/></label><p className={styles.warning}>This records money already received. It does not initiate a transfer.</p></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<BadgeCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>
}
