"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, Globe2, KeyRound, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-domain-control.module.css";

type Caps={read:boolean;manage:boolean;dns_propose:boolean;dns_review:boolean;dns_verify:boolean};
type Domain={id:string;domain_code:string;domain_name:string;registrar_name?:string|null;dns_provider_name?:string|null;registered_on?:string|null;expires_on?:string|null;auto_renew:boolean;owner_user_id:string;renewal_reference?:string|null;status:string;created_by:string};
type DnsChange={id:string;change_code:string;domain_id:string;record_name:string;record_type:string;expected_value_sha256:string;ttl_seconds?:number|null;provider_record_reference?:string|null;purpose:string;status:string;proposed_by:string;approved_by?:string|null;approved_at?:string|null;applied_by?:string|null;applied_at?:string|null;apply_evidence_reference?:string|null;verified_by?:string|null;verified_at?:string|null;observed_value_sha256?:string|null;verification_evidence_reference?:string|null;created_at:string};
type Cert={id:string;certificate_code:string;domain_id:string;service_id?:string|null;hostname_pattern:string;issuer_name:string;fingerprint_sha256:string;provider_reference?:string|null;issued_at?:string|null;expires_at:string;auto_managed:boolean;status:string;created_by:string};
type Person={user_id:string;display_name?:string|null;job_title?:string|null};
type Service={id:string;service_code:string;name:string;project_key:string;environment:string;status:string};
type Payload={actor:{user_id:string;roles:string[]};capabilities:Caps;domains:Domain[];dns_changes:DnsChange[];certificates:Cert[];people:Person[];services:Service[];disclaimer:string};
type View="domains"|"dns"|"certificates";
type Modal=
 |{kind:"DOMAIN"}
 |{kind:"EDIT_DOMAIN";domain:Domain}
 |{kind:"DNS"}
 |{kind:"REVIEW_DNS";change:DnsChange}
 |{kind:"APPLY_DNS";change:DnsChange}
 |{kind:"VERIFY_DNS";change:DnsChange}
 |{kind:"CERT"};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-domains",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Domain control request failed");
 return body as T;
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value.length===10?value+"T00:00:00":value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:value.length>10?"short":undefined}).format(d)}
function toIso(value?:string){if(!value)return undefined;const d=new Date(value);return Number.isNaN(d.getTime())?undefined:d.toISOString()}
async function sha256(value:string){
 const bytes=new TextEncoder().encode(value);
 const digest=await crypto.subtle.digest("SHA-256",bytes);
 return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("");
}
function shortHash(value?:string|null){return value?value.slice(0,10)+"…"+value.slice(-8):"—"}

export function OfficeDomainControl(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("domains");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load domain controls")});return()=>{alive=false}},[]);
 const domains=useMemo(()=>new Map((data?.domains??[]).map(row=>[row.id,row])),[data?.domains]);
 const people=useMemo(()=>new Map((data?.people??[]).map(row=>[row.user_id,row])),[data?.people]);
 const services=useMemo(()=>new Map((data?.services??[]).map(row=>[row.id,row])),[data?.services]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="DOMAIN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_DOMAIN",domain:draft.domain,registrar:draft.registrar||undefined,dns_provider:draft.dns_provider||undefined,registered_on:draft.registered_on||undefined,expires_on:draft.expires_on||undefined,auto_renew:draft.auto_renew==="YES",owner_user_id:draft.owner_user_id,renewal_reference:draft.renewal_reference||undefined})});
  else if(modal.kind==="EDIT_DOMAIN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"UPDATE_DOMAIN",domain_id:modal.domain.id,registrar:draft.registrar||undefined,dns_provider:draft.dns_provider||undefined,expires_on:draft.expires_on||undefined,auto_renew:draft.auto_renew==="YES",owner_user_id:draft.owner_user_id,renewal_reference:draft.renewal_reference||undefined,status:draft.status})});
  else if(modal.kind==="DNS"){const expected=await sha256(draft.expected_value||"");await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"PROPOSE_DNS",domain_id:draft.domain_id,record_name:draft.record_name,record_type:draft.record_type||"CNAME",expected_value_sha256:expected,ttl_seconds:draft.ttl?Number(draft.ttl):undefined,provider_record_reference:draft.provider_reference||undefined,purpose:draft.purpose})})}
  else if(modal.kind==="REVIEW_DNS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_DNS",change_id:modal.change.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="APPLY_DNS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"MARK_DNS_APPLIED",change_id:modal.change.id,evidence_reference:draft.evidence})});
  else if(modal.kind==="VERIFY_DNS"){const observed=await sha256(draft.observed_value||"");await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"VERIFY_DNS",change_id:modal.change.id,observed_value_sha256:observed,evidence_reference:draft.evidence})})}
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"RECORD_CERT",domain_id:draft.domain_id,service_id:draft.service_id||undefined,hostname:draft.hostname,issuer:draft.issuer,fingerprint:draft.fingerprint,provider_reference:draft.provider_reference||undefined,issued_at:toIso(draft.issued_at),expires_at:toIso(draft.expires_at),auto_managed:draft.auto_managed!=="NO"})});
  await reload("Domain control updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Domain control action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Domains & certificates unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading domains & certificates</h2></div></section>;
 const activeDomains=data.domains.filter(d=>d.status==="ACTIVE").length;
 const pendingDns=data.dns_changes.filter(d=>!["VERIFIED","REJECTED","ROLLED_BACK","CANCELLED"].includes(d.status)).length;
 const activeCerts=data.certificates.filter(c=>c.status==="ACTIVE").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>DOMAINS · DNS · TLS</p><h2>Track internet identity and certificate lifecycle without storing provider secrets.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{activeDomains}</b><span>active domains</span></article><article><b>{pendingDns}</b><span>DNS changes open</span></article><article><b>{activeCerts}</b><span>active certificates</span></article></div></header>
  <div className={styles.toolbar}>{(["domains","dns","certificates"] as View[]).map(item=><button type="button" key={item} data-active={view===item} onClick={()=>setView(item)}>{item==="dns"?"DNS":item[0].toUpperCase()+item.slice(1)}</button>)}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="domains"&&data.capabilities.manage?<button type="button" onClick={()=>{setDraft({auto_renew:"NO"});setModal({kind:"DOMAIN"})}}><Plus/>Add domain</button>:null}{view==="dns"&&data.capabilities.dns_propose&&data.domains.length?<button type="button" onClick={()=>{setDraft({record_type:"CNAME",ttl:"300"});setModal({kind:"DNS"})}}><Plus/>Propose DNS</button>:null}{view==="certificates"&&data.capabilities.manage&&data.domains.length?<button type="button" onClick={()=>{setDraft({auto_managed:"YES"});setModal({kind:"CERT"})}}><Plus/>Record certificate</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="domains"?<div className={styles.grid}>{data.domains.map(domain=><article className={styles.card} key={domain.id}><header><div><small>{domain.domain_code}</small><h3>{domain.domain_name}</h3><span>{domain.registrar_name||"Registrar not recorded"} · DNS {domain.dns_provider_name||"not recorded"}</span></div><em className={styles.badge} data-status={domain.status}>{domain.status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Owner<b>{people.get(domain.owner_user_id)?.display_name||domain.owner_user_id}</b></span><span>Registered<b>{date(domain.registered_on)}</b></span><span>Expires<b>{date(domain.expires_on)}</b></span><span>Auto-renew<b>{domain.auto_renew?"Enabled":"Disabled"}</b></span><span>Renewal reference<b>{domain.renewal_reference||"—"}</b></span></div>{data.capabilities.manage?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({registrar:domain.registrar_name||"",dns_provider:domain.dns_provider_name||"",expires_on:domain.expires_on||"",auto_renew:domain.auto_renew?"YES":"NO",owner_user_id:domain.owner_user_id,renewal_reference:domain.renewal_reference||"",status:domain.status});setModal({kind:"EDIT_DOMAIN",domain})}}>Edit metadata</button></div>:null}</article>)}{!data.domains.length?<div className={styles.empty}>No corporate domains recorded.</div>:null}</div>:null}

  {view==="dns"?<div className={styles.grid}>{data.dns_changes.map(change=><article className={styles.card} key={change.id}><header><div><small>{change.change_code} · {domains.get(change.domain_id)?.domain_name||"Domain"}</small><h3>{change.record_type} · {change.record_name}</h3><span>{change.purpose}</span></div><em className={styles.badge} data-status={change.status}>{change.status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Expected SHA-256<b>{shortHash(change.expected_value_sha256)}</b></span><span>Observed SHA-256<b>{shortHash(change.observed_value_sha256)}</b></span><span>TTL<b>{change.ttl_seconds??"—"} sec</b></span><span>Provider ref<b>{change.provider_record_reference||"—"}</b></span><span>Apply evidence<b>{change.apply_evidence_reference||"—"}</b></span><span>Verify evidence<b>{change.verification_evidence_reference||"—"}</b></span></div><div className={styles.actions}>{change.status==="PROPOSED"&&data.capabilities.dns_review&&change.proposed_by!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({status:"APPROVED",note:""});setModal({kind:"REVIEW_DNS",change})}}><ShieldCheck/>Independent review</button>:null}{change.status==="APPROVED"&&data.capabilities.dns_propose?<button type="button" onClick={()=>{setDraft({evidence:""});setModal({kind:"APPLY_DNS",change})}}>Record provider application</button>:null}{change.status==="PROVIDER_APPLIED"&&data.capabilities.dns_verify&&change.proposed_by!==data.actor.user_id&&change.applied_by!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({observed_value:"",evidence:""});setModal({kind:"VERIFY_DNS",change})}}>Verify observed DNS</button>:null}</div></article>)}{!data.dns_changes.length?<div className={styles.empty}>No DNS changes recorded.</div>:null}</div>:null}

  {view==="certificates"?<div className={styles.grid}>{data.certificates.map(cert=><article className={styles.card} key={cert.id}><header><div><small>{cert.certificate_code} · {domains.get(cert.domain_id)?.domain_name||"Domain"}</small><h3>{cert.hostname_pattern}</h3><span>{cert.issuer_name} · {cert.auto_managed?"Auto-managed":"Manual lifecycle"}</span></div><em className={styles.badge} data-status={cert.status}>{cert.status}</em></header><div className={styles.kv}><span>Fingerprint<b>{shortHash(cert.fingerprint_sha256)}</b></span><span>Issued<b>{date(cert.issued_at)}</b></span><span>Expires<b>{date(cert.expires_at)}</b></span><span>Service<b>{cert.service_id?services.get(cert.service_id)?.name||cert.service_id:"—"}</b></span><span>Provider ref<b>{cert.provider_reference||"—"}</b></span></div></article>)}{!data.certificates.length?<div className={styles.empty}>No TLS certificate metadata recorded.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED INTERNET-ID ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="DOMAIN"?<><label>Domain name<input required minLength={3} value={draft.domain||""} onChange={e=>setDraft({...draft,domain:e.target.value.toLowerCase()})}/></label><div className={styles.two}><label>Registrar<input value={draft.registrar||""} onChange={e=>setDraft({...draft,registrar:e.target.value})}/></label><label>DNS provider<input value={draft.dns_provider||""} onChange={e=>setDraft({...draft,dns_provider:e.target.value})}/></label></div><div className={styles.two}><label>Registered on<input type="date" value={draft.registered_on||""} onChange={e=>setDraft({...draft,registered_on:e.target.value})}/></label><label>Expires on<input type="date" value={draft.expires_on||""} onChange={e=>setDraft({...draft,expires_on:e.target.value})}/></label></div><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}><option value="">Select owner</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><div className={styles.two}><label>Auto-renew<select value={draft.auto_renew||"NO"} onChange={e=>setDraft({...draft,auto_renew:e.target.value})}><option>YES</option><option>NO</option></select></label><label>Renewal reference<input value={draft.renewal_reference||""} onChange={e=>setDraft({...draft,renewal_reference:e.target.value})}/></label></div></>
   :modal.kind==="EDIT_DOMAIN"?<><label>Domain<input readOnly value={modal.domain.domain_name}/></label><div className={styles.two}><label>Registrar<input value={draft.registrar||""} onChange={e=>setDraft({...draft,registrar:e.target.value})}/></label><label>DNS provider<input value={draft.dns_provider||""} onChange={e=>setDraft({...draft,dns_provider:e.target.value})}/></label></div><div className={styles.two}><label>Expires on<input type="date" value={draft.expires_on||""} onChange={e=>setDraft({...draft,expires_on:e.target.value})}/></label><label>Status<select value={draft.status||"ACTIVE"} onChange={e=>setDraft({...draft,status:e.target.value})}>{["ACTIVE","TRANSFER_PENDING","EXPIRING","EXPIRED","RETIRED"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Owner<select required value={draft.owner_user_id||""} onChange={e=>setDraft({...draft,owner_user_id:e.target.value})}>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><div className={styles.two}><label>Auto-renew<select value={draft.auto_renew||"NO"} onChange={e=>setDraft({...draft,auto_renew:e.target.value})}><option>YES</option><option>NO</option></select></label><label>Renewal reference<input value={draft.renewal_reference||""} onChange={e=>setDraft({...draft,renewal_reference:e.target.value})}/></label></div></>
   :modal.kind==="DNS"?<><label>Domain<select required value={draft.domain_id||""} onChange={e=>setDraft({...draft,domain_id:e.target.value})}><option value="">Select domain</option>{data.domains.filter(d=>["ACTIVE","EXPIRING","TRANSFER_PENDING"].includes(d.status)).map(d=><option key={d.id} value={d.id}>{d.domain_name}</option>)}</select></label><div className={styles.two}><label>Record type<select value={draft.record_type||"CNAME"} onChange={e=>setDraft({...draft,record_type:e.target.value})}>{["A","AAAA","CNAME","MX","TXT","SRV","CAA","NS","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Record name<input required value={draft.record_name||""} onChange={e=>setDraft({...draft,record_name:e.target.value})}/></label></div><label>Expected DNS value<input required value={draft.expected_value||""} onChange={e=>setDraft({...draft,expected_value:e.target.value})}/><small>Hashed locally in your browser. Raw value is not sent to KRAVIA.</small></label><div className={styles.two}><label>TTL seconds<input type="number" min="30" max="604800" value={draft.ttl||"300"} onChange={e=>setDraft({...draft,ttl:e.target.value})}/></label><label>Provider record reference<input value={draft.provider_reference||""} onChange={e=>setDraft({...draft,provider_reference:e.target.value})}/></label></div><label>Purpose<textarea required minLength={3} value={draft.purpose||""} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label></>
   :modal.kind==="REVIEW_DNS"?<><label>Decision<select value={draft.status||"APPROVED"} onChange={e=>setDraft({...draft,status:e.target.value})}><option>APPROVED</option><option>REJECTED</option></select></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="APPLY_DNS"?<><p>Record provider-side application for <b>{modal.change.change_code}</b>. This does not claim KRAVIA changed DNS automatically.</p><label>Provider/application evidence reference<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="VERIFY_DNS"?<><label>Observed DNS value<input required value={draft.observed_value||""} onChange={e=>setDraft({...draft,observed_value:e.target.value})}/><small>Hashed locally. Only the observed SHA-256 is submitted.</small></label><label>Verification evidence reference<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :<><label>Domain<select required value={draft.domain_id||""} onChange={e=>setDraft({...draft,domain_id:e.target.value})}><option value="">Select domain</option>{data.domains.map(d=><option key={d.id} value={d.id}>{d.domain_name}</option>)}</select></label><label>Hostname / pattern<input required value={draft.hostname||""} onChange={e=>setDraft({...draft,hostname:e.target.value})}/></label><div className={styles.two}><label>Issuer<input required minLength={2} value={draft.issuer||""} onChange={e=>setDraft({...draft,issuer:e.target.value})}/></label><label>Engineering service<select value={draft.service_id||""} onChange={e=>setDraft({...draft,service_id:e.target.value})}><option value="">No service link</option>{data.services.map(s=><option key={s.id} value={s.id}>{s.service_code} · {s.name} · {s.environment}</option>)}</select></label></div><label>SHA-256 certificate fingerprint<input required minLength={64} value={draft.fingerprint||""} onChange={e=>setDraft({...draft,fingerprint:e.target.value})}/><small>Certificate fingerprint only. Never paste a private key.</small></label><label>Provider reference<input value={draft.provider_reference||""} onChange={e=>setDraft({...draft,provider_reference:e.target.value})}/></label><div className={styles.three}><label>Issued at<input type="datetime-local" value={draft.issued_at||""} onChange={e=>setDraft({...draft,issued_at:e.target.value})}/></label><label>Expires at<input required type="datetime-local" value={draft.expires_at||""} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></label><label>Auto-managed<select value={draft.auto_managed||"YES"} onChange={e=>setDraft({...draft,auto_managed:e.target.value})}><option>YES</option><option>NO</option></select></label></div></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
