"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, GraduationCap, LoaderCircle, Plus, RefreshCw, ShieldCheck, X } from "lucide-react";
import styles from "./office-people-development.module.css";

type Caps={skills_read:boolean;skills_declare:boolean;skills_verify:boolean;training_read:boolean;training_manage:boolean;training_assign:boolean;performance_read:boolean;performance_manage:boolean;performance_review:boolean;plan_read:boolean;plan_manage:boolean;plan_review:boolean};
type Person={user_id:string;display_name?:string|null;job_title?:string|null;primary_department?:string|null};
type Skill={id:string;user_id:string;skill_name:string;level:string;verification_status:string;evidence_reference?:string|null;verified_by?:string|null;last_validated_on?:string|null};
type Training={id:string;training_code:string;title:string;category:string;description:string;validity_months?:number|null;evidence_required:boolean};
type Assignment={id:string;training_id:string;user_id:string;assigned_by:string;due_on?:string|null;status:string;completion_evidence_reference?:string|null;completed_at?:string|null;expires_on?:string|null;note?:string|null};
type Review={id:string;review_code:string;user_id:string;reviewer_user_id:string;department_code?:string|null;period_start:string;period_end:string;goals:unknown;employee_summary?:string|null;reviewer_summary?:string|null;outcome?:string|null;development_plan?:string|null;status:string};
type Plan={id:string;plan_code:string;department_code:string;period_start:string;period_end:string;current_headcount:number;target_headcount:number;approved_headcount?:number|null;rationale:string;budget_reference?:string|null;status:string;created_by:string;reviewed_by?:string|null;review_note?:string|null};
type Payload={actor:{user_id:string;department?:string|null};capabilities:Caps;people:Person[];skills:Skill[];training_catalog:Training[];training_assignments:Assignment[];performance_reviews:Review[];workforce_plans:Plan[];disclaimer:string};
type View="skills"|"training"|"performance"|"planning";
type Modal={kind:"SKILL"}|{kind:"VERIFY";skill:Skill}|{kind:"TRAINING"}|{kind:"ASSIGN"}|{kind:"TRAINING_STATUS";assignment:Assignment}|{kind:"PERFORMANCE"}|{kind:"PERFORMANCE_STATUS";review:Review}|{kind:"PLAN"}|{kind:"PLAN_STATUS";plan:Plan};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-people-development",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"People Development request failed");
 return body as T;
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value.length===10?value+"T00:00:00":value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(d)}
function goalList(goals:unknown){return Array.isArray(goals)?goals.map(String):[]}

export function OfficePeopleDevelopment(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("skills");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load People Development")});return()=>{alive=false}},[]);
 const people=useMemo(()=>new Map((data?.people??[]).map(row=>[row.user_id,row])),[data?.people]);
 const training=useMemo(()=>new Map((data?.training_catalog??[]).map(row=>[row.id,row])),[data?.training_catalog]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="SKILL")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"DECLARE_SKILL",skill:draft.skill,level:draft.level||"FOUNDATIONAL",evidence:draft.evidence||undefined})});
  else if(modal.kind==="VERIFY")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"VERIFY_SKILL",skill_id:modal.skill.id,status:draft.status||"VERIFIED",evidence:draft.evidence||undefined})});
  else if(modal.kind==="TRAINING")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_TRAINING",title:draft.title,category:draft.category||"OTHER",description:draft.description,validity_months:draft.validity_months?Number(draft.validity_months):undefined,evidence_required:draft.evidence_required!=="NO"})});
  else if(modal.kind==="ASSIGN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"ASSIGN_TRAINING",training_id:draft.training_id,user_id:draft.user_id,due_on:draft.due_on||undefined,note:draft.note||undefined})});
  else if(modal.kind==="TRAINING_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_TRAINING",assignment_id:modal.assignment.id,status:draft.status,evidence:draft.evidence||undefined,note:draft.note||undefined})});
  else if(modal.kind==="PERFORMANCE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_PERFORMANCE",user_id:draft.user_id,reviewer_user_id:draft.reviewer_user_id,period_start:draft.period_start,period_end:draft.period_end,goals:(draft.goals||"").split("\n").map(v=>v.trim()).filter(Boolean)})});
  else if(modal.kind==="PERFORMANCE_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_PERFORMANCE",review_id:modal.review.id,status:draft.status,employee_summary:draft.employee_summary||undefined,reviewer_summary:draft.reviewer_summary||undefined,outcome:draft.outcome||undefined,development_plan:draft.development_plan||undefined})});
  else if(modal.kind==="PLAN")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_WORKFORCE_PLAN",department:draft.department,period_start:draft.period_start,period_end:draft.period_end,current_headcount:Number(draft.current_headcount||0),target_headcount:Number(draft.target_headcount||0),rationale:draft.rationale,budget_reference:draft.budget_reference||undefined})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_WORKFORCE_PLAN",plan_id:modal.plan.id,status:draft.status,approved_headcount:draft.approved_headcount?Number(draft.approved_headcount):undefined,note:draft.note||undefined})});
  await reload("People Development updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"People Development action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>People Development unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading People Development</h2></div></section>;
 const overdue=data.training_assignments.filter(row=>row.due_on&&["ASSIGNED","IN_PROGRESS"].includes(row.status)).length;
 const openReviews=data.performance_reviews.filter(row=>!["FINAL","CANCELLED"].includes(row.status)).length;
 const pendingPlans=data.workforce_plans.filter(row=>row.status==="SUBMITTED").length;

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>SKILLS · TRAINING · PERFORMANCE · WORKFORCE</p><h2>Develop people with explicit evidence and human judgement.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{data.skills.length}</b><span>skills</span></article><article><b>{overdue}</b><span>training open</span></article><article><b>{openReviews+pendingPlans}</b><span>reviews / plans</span></article></div></header>
  <div className={styles.toolbar}>{(["skills","training","performance","planning"] as View[]).map(item=><button type="button" key={item} data-active={view===item} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="skills"&&data.capabilities.skills_declare?<button type="button" onClick={()=>{setDraft({level:"FOUNDATIONAL"});setModal({kind:"SKILL"})}}><Plus/>Declare skill</button>:null}{view==="training"&&data.capabilities.training_manage?<button type="button" onClick={()=>{setDraft({category:"OTHER",evidence_required:"YES"});setModal({kind:"TRAINING"})}}><Plus/>New training</button>:null}{view==="training"&&data.capabilities.training_assign?<button type="button" onClick={()=>{setDraft({});setModal({kind:"ASSIGN"})}}><Plus/>Assign</button>:null}{view==="performance"&&data.capabilities.performance_manage?<button type="button" onClick={()=>{setDraft({});setModal({kind:"PERFORMANCE"})}}><Plus/>New review</button>:null}{view==="planning"&&data.capabilities.plan_manage?<button type="button" onClick={()=>{setDraft({department:data.actor.department||""});setModal({kind:"PLAN"})}}><Plus/>New plan</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="skills"?<div className={styles.grid}>{data.skills.map(row=><article className={styles.card} key={row.id}><header><div><small>{people.get(row.user_id)?.display_name||"You"}</small><h3>{row.skill_name}</h3><span>{row.level}</span></div><em className={styles.badge} data-status={row.verification_status}>{row.verification_status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Evidence<b>{row.evidence_reference||"—"}</b></span><span>Validated<b>{date(row.last_validated_on)}</b></span></div>{data.capabilities.skills_verify&&row.user_id!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({status:"VERIFIED",evidence:row.evidence_reference||""});setModal({kind:"VERIFY",skill:row})}}>Verify / expire</button>:null}</article>)}{!data.skills.length?<div className={styles.empty}>No skills recorded in your scope.</div>:null}</div>:null}

  {view==="training"?<div className={styles.grid}>{data.training_assignments.map(row=><article className={styles.card} key={row.id}><header><div><small>{training.get(row.training_id)?.training_code||"TRAINING"}</small><h3>{training.get(row.training_id)?.title||"Assigned training"}</h3><span>{people.get(row.user_id)?.display_name||"You"}</span></div><em className={styles.badge} data-status={row.status}>{row.status.replaceAll("_"," ")}</em></header><div className={styles.kv}><span>Due<b>{date(row.due_on)}</b></span><span>Expires<b>{date(row.expires_on)}</b></span><span>Evidence<b>{row.completion_evidence_reference||"—"}</b></span></div>{!["COMPLETED","WAIVED","EXPIRED"].includes(row.status)?<button type="button" onClick={()=>{setDraft({status:row.status==="ASSIGNED"?"IN_PROGRESS":"COMPLETED",evidence:row.completion_evidence_reference||"",note:row.note||""});setModal({kind:"TRAINING_STATUS",assignment:row})}}>Update</button>:null}</article>)}{!data.training_assignments.length?<div className={styles.empty}>No training assignments in your scope.</div>:null}</div>:null}

  {view==="performance"?<div className={styles.grid}>{data.performance_reviews.map(row=><article className={styles.card} key={row.id}><header><div><small>{row.review_code}</small><h3>{people.get(row.user_id)?.display_name||"Review subject"}</h3><span>{date(row.period_start)} → {date(row.period_end)}</span></div><em className={styles.badge} data-status={row.status}>{row.status.replaceAll("_"," ")}</em></header><p><b>Reviewer:</b> {people.get(row.reviewer_user_id)?.display_name||row.reviewer_user_id}</p><ul>{goalList(row.goals).map((goal,index)=><li key={index}>{goal}</li>)}</ul>{row.outcome?<p><b>Human outcome:</b> {row.outcome.replaceAll("_"," ")}</p>:null}{row.development_plan?<p><b>Development plan:</b> {row.development_plan}</p>:null}{row.status!=="FINAL"&&row.status!=="CANCELLED"?<button type="button" onClick={()=>{const own=row.user_id===data.actor.user_id;setDraft({status:own?"EMPLOYEE_INPUT":row.status==="EMPLOYEE_INPUT"?"MANAGER_REVIEW":"FINAL",employee_summary:row.employee_summary||"",reviewer_summary:row.reviewer_summary||"",outcome:row.outcome||"MEETS_EXPECTATIONS",development_plan:row.development_plan||""});setModal({kind:"PERFORMANCE_STATUS",review:row})}}>Continue review</button>:null}</article>)}{!data.performance_reviews.length?<div className={styles.empty}>No performance cycle in your scope.</div>:null}</div>:null}

  {view==="planning"?<div className={styles.grid}>{data.workforce_plans.map(row=><article className={styles.card} key={row.id}><header><div><small>{row.plan_code}</small><h3>{row.department_code}</h3><span>{date(row.period_start)} → {date(row.period_end)}</span></div><em className={styles.badge} data-status={row.status}>{row.status}</em></header><div className={styles.kv}><span>Current<b>{row.current_headcount}</b></span><span>Target<b>{row.target_headcount}</b></span><span>Approved<b>{row.approved_headcount??"—"}</b></span><span>Budget ref<b>{row.budget_reference||"—"}</b></span></div><p>{row.rationale}</p>{!["REJECTED","CLOSED"].includes(row.status)?<button type="button" onClick={()=>{const next=row.status==="DRAFT"?"SUBMITTED":row.status==="SUBMITTED"?(data.capabilities.plan_review?"APPROVED":"SUBMITTED"):"CLOSED";setDraft({status:next,approved_headcount:row.approved_headcount!=null?String(row.approved_headcount):String(row.target_headcount),note:row.review_note||""});setModal({kind:"PLAN_STATUS",plan:row})}}>Advance / review</button>:null}</article>)}{!data.workforce_plans.length?<div className={styles.empty}>No workforce plans in your scope.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED PEOPLE ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" onClick={()=>setModal(undefined)} aria-label="Close"><X/></button></header>
   {modal.kind==="SKILL"?<><label>Skill<input required minLength={2} value={draft.skill||""} onChange={e=>setDraft({...draft,skill:e.target.value})}/></label><label>Level<select value={draft.level||"FOUNDATIONAL"} onChange={e=>setDraft({...draft,level:e.target.value})}>{["AWARENESS","FOUNDATIONAL","INTERMEDIATE","ADVANCED","EXPERT"].map(v=><option key={v}>{v}</option>)}</select></label><label>Evidence reference<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="VERIFY"?<><label>Status<select value={draft.status||"VERIFIED"} onChange={e=>setDraft({...draft,status:e.target.value})}><option>VERIFIED</option><option>EXPIRED</option></select></label><label>Evidence reference<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="TRAINING"?<><label>Title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Category<select value={draft.category||"OTHER"} onChange={e=>setDraft({...draft,category:e.target.value})}>{["SECURITY","PRIVACY","COMPLIANCE","TECHNICAL","PRODUCT","LEADERSHIP","SAFETY","HR","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className={styles.two}><label>Validity months<input type="number" min="1" max="120" value={draft.validity_months||""} onChange={e=>setDraft({...draft,validity_months:e.target.value})}/></label><label>Evidence required<select value={draft.evidence_required||"YES"} onChange={e=>setDraft({...draft,evidence_required:e.target.value})}><option>YES</option><option>NO</option></select></label></div></>
   :modal.kind==="ASSIGN"?<><label>Training<select required value={draft.training_id||""} onChange={e=>setDraft({...draft,training_id:e.target.value})}><option value="">Select training</option>{data.training_catalog.map(t=><option key={t.id} value={t.id}>{t.training_code} · {t.title}</option>)}</select></label><label>Person<select required value={draft.user_id||""} onChange={e=>setDraft({...draft,user_id:e.target.value})}><option value="">Select person</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Due date<input type="date" value={draft.due_on||""} onChange={e=>setDraft({...draft,due_on:e.target.value})}/></label><label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="TRAINING_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{["IN_PROGRESS","COMPLETED","WAIVED","EXPIRED"].map(v=><option key={v}>{v}</option>)}</select></label>{draft.status==="COMPLETED"?<label>Completion evidence<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label>:null}<label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="PERFORMANCE"?<><label>Person<select required value={draft.user_id||""} onChange={e=>setDraft({...draft,user_id:e.target.value})}><option value="">Select review subject</option>{data.people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><label>Human reviewer<select required value={draft.reviewer_user_id||""} onChange={e=>setDraft({...draft,reviewer_user_id:e.target.value})}><option value="">Select reviewer</option>{data.people.filter(p=>p.user_id!==draft.user_id).map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.user_id}</option>)}</select></label><div className={styles.two}><label>Period start<input required type="date" value={draft.period_start||""} onChange={e=>setDraft({...draft,period_start:e.target.value})}/></label><label>Period end<input required type="date" value={draft.period_end||""} onChange={e=>setDraft({...draft,period_end:e.target.value})}/></label></div><label>Goals · one per line<textarea value={draft.goals||""} onChange={e=>setDraft({...draft,goals:e.target.value})}/></label></>
   :modal.kind==="PERFORMANCE_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{(modal.review.user_id===data.actor.user_id?["EMPLOYEE_INPUT"]:["MANAGER_REVIEW","FINAL"]).map(v=><option key={v}>{v}</option>)}</select></label>{modal.review.user_id===data.actor.user_id?<label>Employee summary<textarea required minLength={3} value={draft.employee_summary||""} onChange={e=>setDraft({...draft,employee_summary:e.target.value})}/></label>:<div><label>Reviewer summary<textarea value={draft.reviewer_summary||""} onChange={e=>setDraft({...draft,reviewer_summary:e.target.value})}/></label>{draft.status==="FINAL"?<label>Human outcome<select value={draft.outcome||"MEETS_EXPECTATIONS"} onChange={e=>setDraft({...draft,outcome:e.target.value})}>{["EXCEEDS_EXPECTATIONS","MEETS_EXPECTATIONS","DEVELOPMENT_REQUIRED","NOT_RATED"].map(v=><option key={v}>{v}</option>)}</select></label>:null}<label>Development plan<textarea value={draft.development_plan||""} onChange={e=>setDraft({...draft,development_plan:e.target.value})}/></label></div>}</>
   :modal.kind==="PLAN"?<><label>Department<input required minLength={2} value={draft.department||""} onChange={e=>setDraft({...draft,department:e.target.value.toUpperCase()})}/></label><div className={styles.two}><label>Period start<input required type="date" value={draft.period_start||""} onChange={e=>setDraft({...draft,period_start:e.target.value})}/></label><label>Period end<input required type="date" value={draft.period_end||""} onChange={e=>setDraft({...draft,period_end:e.target.value})}/></label></div><div className={styles.two}><label>Current headcount<input required type="number" min="0" value={draft.current_headcount||"0"} onChange={e=>setDraft({...draft,current_headcount:e.target.value})}/></label><label>Target headcount<input required type="number" min="0" value={draft.target_headcount||"0"} onChange={e=>setDraft({...draft,target_headcount:e.target.value})}/></label></div><label>Rationale<textarea required minLength={3} value={draft.rationale||""} onChange={e=>setDraft({...draft,rationale:e.target.value})}/></label><label>Budget reference<input value={draft.budget_reference||""} onChange={e=>setDraft({...draft,budget_reference:e.target.value})}/></label></>
   :<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{(modal.plan.status==="DRAFT"?["SUBMITTED"]:modal.plan.status==="SUBMITTED"?["APPROVED","REJECTED"]:["CLOSED"]).map(v=><option key={v}>{v}</option>)}</select></label>{draft.status==="APPROVED"?<label>Approved headcount<input required type="number" min="0" value={draft.approved_headcount||""} onChange={e=>setDraft({...draft,approved_headcount:e.target.value})}/></label>:null}<label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
