"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleAlert, Coins, LoaderCircle, Plus, RefreshCw, ShieldCheck, WalletCards, X } from "lucide-react";
import styles from "./office-budget.module.css";

type Caps={read:boolean;manage:boolean;review:boolean;commit:boolean;actual:boolean};
type Cycle={id:string;cycle_code:string;title:string;period_start:string;period_end:string;status:string;created_by:string;reviewed_by?:string|null;reviewed_at?:string|null;review_note?:string|null};
type Budget={id:string;budget_code:string;cycle_id:string;scope_type:string;scope_key?:string|null;category:string;currency:string;allocation_minor:number;available_minor?:number|null;status:string;created_by:string;reviewed_by?:string|null;review_note?:string|null};
type Adjustment={id:string;adjustment_code:string;budget_id:string;delta_minor:number;reason:string;evidence_reference?:string|null;status:string;requested_by:string;reviewed_by?:string|null;review_note?:string|null;created_at:string};
type Commitment={id:string;commitment_code:string;budget_id:string;source_type:string;source_reference:string;description:string;amount_minor:number;currency:string;approval_reference:string;status:string;created_by:string;released_by?:string|null;release_reason?:string|null;created_at:string};
type Actual={id:string;actual_code:string;budget_id:string;commitment_id?:string|null;source_type:string;source_reference:string;description:string;amount_minor:number;currency:string;evidence_reference:string;recorded_by:string;recorded_at:string};
type Payload={actor:{user_id:string;roles:string[];department?:string|null};scope:{type?:string|null;key?:string|null};capabilities:Caps;cycles:Cycle[];budgets:Budget[];adjustments:Adjustment[];commitments:Commitment[];actuals:Actual[];disclaimer:string};
type View="cycles"|"budgets"|"commitments"|"actuals";
type Modal=
 |{kind:"CYCLE"}
 |{kind:"CYCLE_STATUS";cycle:Cycle}
 |{kind:"BUDGET";cycle?:Cycle}
 |{kind:"BUDGET_STATUS";budget:Budget}
 |{kind:"ADJUST";budget:Budget}
 |{kind:"ADJUST_REVIEW";adjustment:Adjustment}
 |{kind:"COMMIT";budget:Budget}
 |{kind:"RELEASE";commitment:Commitment}
 |{kind:"ACTUAL";budget:Budget;commitment?:Commitment};

async function api<T>(options?:RequestInit):Promise<T>{
 const response=await fetch("/api/office-budget",{...options,cache:"no-store",credentials:"same-origin"});
 const body=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(typeof body.detail==="string"?body.detail:"Budget request failed");
 return body as T;
}
function money(minor?:number|null,currency="INR"){
 if(minor==null)return "—";
 return currency+" "+(minor/100).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
}
function date(value?:string|null){if(!value)return "—";const d=new Date(value.length===10?value+"T00:00:00":value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(d)}
function toMinor(value?:string){const n=Number(value||"0");return Number.isFinite(n)?Math.round(n*100):0}
function cycleNext(row:Cycle,review:boolean){if(row.status==="DRAFT")return ["SUBMITTED"];if(row.status==="SUBMITTED")return review?["APPROVED","REJECTED"]:[];if(row.status==="APPROVED")return ["ACTIVE",...(review?["CLOSED"]:[])];if(row.status==="ACTIVE")return review?["CLOSED"]:[];return []}
function budgetNext(row:Budget,review:boolean){if(row.status==="DRAFT")return ["SUBMITTED"];if(row.status==="SUBMITTED")return review?["APPROVED","REJECTED"]:[];if(row.status==="APPROVED")return review?["CLOSED"]:[];return []}

export function OfficeBudgetWorkspace(){
 const[data,setData]=useState<Payload>();const[view,setView]=useState<View>("budgets");const[modal,setModal]=useState<Modal>();const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();const[notice,setNotice]=useState<string>();
 async function reload(message?:string){const next=await api<Payload>();setData(next);if(message)setNotice(message)}
 useEffect(()=>{let alive=true;void api<Payload>().then(next=>{if(alive)setData(next)}).catch((caught:unknown)=>{if(alive)setError(caught instanceof Error?caught.message:"Unable to load budgets")});return()=>{alive=false}},[]);
 const budgets=useMemo(()=>new Map((data?.budgets??[]).map(row=>[row.id,row])),[data?.budgets]);
 const commitmentsByBudget=useMemo(()=>{const map=new Map<string,Commitment[]>();for(const row of data?.commitments??[]){const list=map.get(row.budget_id)||[];list.push(row);map.set(row.budget_id,list)}return map},[data?.commitments]);
 const actualsByBudget=useMemo(()=>{const map=new Map<string,Actual[]>();for(const row of data?.actuals??[]){const list=map.get(row.budget_id)||[];list.push(row);map.set(row.budget_id,list)}return map},[data?.actuals]);

 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!modal)return;setBusy(true);setError(undefined);try{
  if(modal.kind==="CYCLE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_CYCLE",title:draft.title,period_start:draft.period_start,period_end:draft.period_end})});
  else if(modal.kind==="CYCLE_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_CYCLE",cycle_id:modal.cycle.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="BUDGET")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"CREATE_BUDGET",cycle_id:draft.cycle_id||modal.cycle?.id,scope_type:draft.scope_type||"COMPANY",scope_key:draft.scope_type==="COMPANY"?undefined:draft.scope_key,category:draft.category,currency:draft.currency||"INR",allocation_minor:toMinor(draft.allocation)})});
  else if(modal.kind==="BUDGET_STATUS")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TRANSITION_BUDGET",budget_id:modal.budget.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="ADJUST")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REQUEST_ADJUSTMENT",budget_id:modal.budget.id,delta_minor:toMinor(draft.delta),reason:draft.reason,evidence:draft.evidence||undefined})});
  else if(modal.kind==="ADJUST_REVIEW")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REVIEW_ADJUSTMENT",adjustment_id:modal.adjustment.id,status:draft.status,note:draft.note||undefined})});
  else if(modal.kind==="COMMIT")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"COMMIT",budget_id:modal.budget.id,source_type:draft.source_type||"OTHER",source_reference:draft.source_reference,description:draft.description,amount_minor:toMinor(draft.amount),currency:modal.budget.currency,approval_reference:draft.approval_reference})});
  else if(modal.kind==="RELEASE")await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"RELEASE_COMMITMENT",commitment_id:modal.commitment.id,reason:draft.reason})});
  else await api({method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"RECORD_ACTUAL",budget_id:modal.budget.id,commitment_id:modal.commitment?.id,source_type:draft.source_type||modal.commitment?.source_type||"OTHER",source_reference:draft.source_reference||modal.commitment?.source_reference,description:draft.description,amount_minor:toMinor(draft.amount),currency:modal.budget.currency,evidence:draft.evidence})});
  await reload("Budget control updated.");setModal(undefined);setDraft({});
 }catch(caught){setError(caught instanceof Error?caught.message:"Budget action failed")}finally{setBusy(false)}}

 if(error&&!data)return <section className={styles.state}><CircleAlert/><div><h2>Budget control unavailable</h2><p>{error}</p></div></section>;
 if(!data)return <section className={styles.state}><LoaderCircle className={styles.spin}/><div><h2>Loading budget controls</h2><p>Resolving company and department budget authority.</p></div></section>;

 const approved=data.budgets.filter(b=>b.status==="APPROVED");
 const allocated=approved.reduce((sum,b)=>sum+b.allocation_minor,0);
 const committed=data.commitments.filter(c=>c.status==="ACTIVE").reduce((sum,c)=>sum+c.amount_minor,0);
 const actual=data.actuals.reduce((sum,a)=>sum+a.amount_minor,0);
 const displayCurrency=approved[0]?.currency||"INR";

 return <section className={styles.shell}>
  <header className={styles.hero}><div><p>BUDGET · COMMITMENTS · ACTUALS</p><h2>Reserve approved spend before work begins and reconcile it to evidence-backed actuals.</h2><span>{data.disclaimer}</span></div><div className={styles.metrics}><article><b>{money(allocated,displayCurrency)}</b><span>approved allocation</span></article><article><b>{money(committed,displayCurrency)}</b><span>active commitments</span></article><article><b>{money(actual,displayCurrency)}</b><span>recorded actuals</span></article></div></header>
  <div className={styles.toolbar}>{(["cycles","budgets","commitments","actuals"] as View[]).map(item=><button type="button" key={item} data-active={view===item} onClick={()=>setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}<button type="button" onClick={()=>void reload()}><RefreshCw/>Refresh</button>{view==="cycles"&&data.capabilities.manage?<button type="button" onClick={()=>{setDraft({});setModal({kind:"CYCLE"})}}><Plus/>New cycle</button>:null}{view==="budgets"&&data.capabilities.manage&&data.cycles.some(c=>["APPROVED","ACTIVE"].includes(c.status))?<button type="button" onClick={()=>{setDraft({scope_type:"COMPANY",currency:"INR"});setModal({kind:"BUDGET"})}}><Plus/>New allocation</button>:null}</div>
  {notice?<div className={styles.notice}><BadgeCheck/>{notice}</div>:null}{error?<div className={styles.error}><CircleAlert/>{error}</div>:null}

  {view==="cycles"?<div className={styles.grid}>{data.cycles.map(c=>{const next=cycleNext(c,data.capabilities.review);return <article className={styles.card} key={c.id}><header><div><small>{c.cycle_code}</small><h3>{c.title}</h3><span>{date(c.period_start)} → {date(c.period_end)}</span></div><em className={styles.badge} data-status={c.status}>{c.status}</em></header>{c.review_note?<p><b>Review:</b> {c.review_note}</p>:null}{next.length&&(data.capabilities.manage||data.capabilities.review)?<div className={styles.actions}><button type="button" onClick={()=>{setDraft({status:next[0],note:""});setModal({kind:"CYCLE_STATUS",cycle:c})}}><ShieldCheck/>Review / advance</button>{data.capabilities.manage&&["APPROVED","ACTIVE"].includes(c.status)?<button type="button" onClick={()=>{setDraft({cycle_id:c.id,scope_type:"COMPANY",currency:"INR"});setModal({kind:"BUDGET",cycle:c})}}>Add allocation</button>:null}</div>:null}</article>})}{!data.cycles.length?<div className={styles.empty}>No budget cycles recorded.</div>:null}</div>:null}

  {view==="budgets"?<div className={styles.grid}>{data.budgets.map(b=>{const cs=commitmentsByBudget.get(b.id)||[];const xs=actualsByBudget.get(b.id)||[];const activeCommit=cs.filter(c=>c.status==="ACTIVE").reduce((sum,c)=>sum+c.amount_minor,0);const actualSum=xs.reduce((sum,x)=>sum+x.amount_minor,0);const next=budgetNext(b,data.capabilities.review);return <article className={styles.card} key={b.id}><header><div><small>{b.budget_code} · {b.category}</small><h3>{b.scope_type}{b.scope_key?" · "+b.scope_key:""}</h3><span>{b.currency}</span></div><em className={styles.badge} data-status={b.status}>{b.status}</em></header><div className={styles.kv}><span>Base allocation<b>{money(b.allocation_minor,b.currency)}</b></span><span>Committed<b>{money(activeCommit,b.currency)}</b></span><span>Actual<b>{money(actualSum,b.currency)}</b></span><span>Available<b>{money(b.available_minor,b.currency)}</b></span></div>{b.review_note?<p><b>Review:</b> {b.review_note}</p>:null}<div className={styles.actions}>{next.length&&(data.capabilities.manage||data.capabilities.review)?<button type="button" onClick={()=>{setDraft({status:next[0],note:""});setModal({kind:"BUDGET_STATUS",budget:b})}}>Review / advance</button>:null}{b.status==="APPROVED"&&data.capabilities.manage?<button type="button" onClick={()=>{setDraft({delta:"0"});setModal({kind:"ADJUST",budget:b})}}>Request adjustment</button>:null}{b.status==="APPROVED"&&data.capabilities.commit?<button type="button" onClick={()=>{setDraft({source_type:"OTHER"});setModal({kind:"COMMIT",budget:b})}}><Coins/>Reserve budget</button>:null}{b.status==="APPROVED"&&data.capabilities.actual?<button type="button" onClick={()=>{setDraft({source_type:"OTHER"});setModal({kind:"ACTUAL",budget:b})}}><WalletCards/>Record actual</button>:null}</div>{data.adjustments.filter(a=>a.budget_id===b.id).map(a=><div className={styles.subrow} key={a.id}><div><b>{a.adjustment_code} · {money(a.delta_minor,b.currency)}</b><span>{a.reason}</span></div><em className={styles.badge} data-status={a.status}>{a.status}</em>{a.status==="REQUESTED"&&data.capabilities.review&&a.requested_by!==data.actor.user_id?<button type="button" onClick={()=>{setDraft({status:"APPROVED",note:""});setModal({kind:"ADJUST_REVIEW",adjustment:a})}}>Review</button>:null}</div>)}</article>})}{!data.budgets.length?<div className={styles.empty}>No budget allocations in your authorised scope.</div>:null}</div>:null}

  {view==="commitments"?<div className={styles.grid}>{data.commitments.map(c=>{const b=budgets.get(c.budget_id);return <article className={styles.card} key={c.id}><header><div><small>{c.commitment_code} · {c.source_type}</small><h3>{c.description}</h3><span>{c.source_reference}</span></div><em className={styles.badge} data-status={c.status}>{c.status}</em></header><div className={styles.kv}><span>Amount<b>{money(c.amount_minor,c.currency)}</b></span><span>Budget<b>{b?.budget_code||c.budget_id}</b></span><span>Approval reference<b>{c.approval_reference}</b></span><span>Release reason<b>{c.release_reason||"—"}</b></span></div>{c.status==="ACTIVE"?<div className={styles.actions}>{data.capabilities.commit?<button type="button" onClick={()=>{setDraft({reason:""});setModal({kind:"RELEASE",commitment:c})}}>Release</button>:null}{data.capabilities.actual&&b?<button type="button" onClick={()=>{setDraft({source_type:c.source_type,source_reference:c.source_reference,amount:String(c.amount_minor/100),description:c.description});setModal({kind:"ACTUAL",budget:b,commitment:c})}}>Convert to actual</button>:null}</div>:null}</article>})}{!data.commitments.length?<div className={styles.empty}>No budget commitments in your authorised scope.</div>:null}</div>:null}

  {view==="actuals"?<div className={styles.grid}>{data.actuals.map(a=><article className={styles.card} key={a.id}><header><div><small>{a.actual_code} · {a.source_type}</small><h3>{a.description}</h3><span>{a.source_reference}</span></div><em className={styles.badge} data-status="POSTED">POSTED</em></header><div className={styles.kv}><span>Amount<b>{money(a.amount_minor,a.currency)}</b></span><span>Budget<b>{budgets.get(a.budget_id)?.budget_code||a.budget_id}</b></span><span>Evidence<b>{a.evidence_reference}</b></span><span>Recorded<b>{date(a.recorded_at)}</b></span></div></article>)}{!data.actuals.length?<div className={styles.empty}>No budget actuals recorded.</div>:null}</div>:null}

  {modal?<div className={styles.backdrop} role="presentation" onMouseDown={()=>!busy&&setModal(undefined)}><form className={styles.dialog} onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><header><div><small>CONTROLLED BUDGET ACTION</small><h3>{modal.kind.replaceAll("_"," ")}</h3></div><button type="button" aria-label="Close" onClick={()=>setModal(undefined)}><X/></button></header>
   {modal.kind==="CYCLE"?<><label>Cycle title<input required minLength={3} value={draft.title||""} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className={styles.two}><label>Period start<input required type="date" value={draft.period_start||""} onChange={e=>setDraft({...draft,period_start:e.target.value})}/></label><label>Period end<input required type="date" value={draft.period_end||""} onChange={e=>setDraft({...draft,period_end:e.target.value})}/></label></div></>
   :modal.kind==="CYCLE_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{cycleNext(modal.cycle,data.capabilities.review).map(v=><option key={v}>{v}</option>)}</select></label><label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="BUDGET"?<><label>Cycle<select required value={draft.cycle_id||modal.cycle?.id||""} onChange={e=>setDraft({...draft,cycle_id:e.target.value})}><option value="">Select approved/active cycle</option>{data.cycles.filter(c=>["APPROVED","ACTIVE"].includes(c.status)).map(c=><option key={c.id} value={c.id}>{c.cycle_code} · {c.title}</option>)}</select></label><div className={styles.two}><label>Scope<select value={draft.scope_type||"COMPANY"} onChange={e=>setDraft({...draft,scope_type:e.target.value,scope_key:""})}>{["COMPANY","DEPARTMENT","PRODUCT","PROJECT","COST_CENTER"].map(v=><option key={v}>{v}</option>)}</select></label>{draft.scope_type!=="COMPANY"?<label>Scope key<input required value={draft.scope_key||""} onChange={e=>setDraft({...draft,scope_key:e.target.value.toUpperCase()})}/></label>:null}</div><div className={styles.two}><label>Category<input required minLength={2} value={draft.category||""} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Currency<input required maxLength={3} value={draft.currency||"INR"} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label></div><label>Allocation<input required inputMode="decimal" value={draft.allocation||""} onChange={e=>setDraft({...draft,allocation:e.target.value})}/></label></>
   :modal.kind==="BUDGET_STATUS"?<><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{budgetNext(modal.budget,data.capabilities.review).map(v=><option key={v}>{v}</option>)}</select></label><label>Note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="ADJUST"?<><label>Adjustment amount (+ / -)<input required inputMode="decimal" value={draft.delta||""} onChange={e=>setDraft({...draft,delta:e.target.value})}/></label><label>Reason<textarea required minLength={3} value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><label>Evidence reference<input value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label></>
   :modal.kind==="ADJUST_REVIEW"?<><label>Decision<select value={draft.status||"APPROVED"} onChange={e=>setDraft({...draft,status:e.target.value})}><option>APPROVED</option><option>REJECTED</option></select></label><label>Review note<textarea value={draft.note||""} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>
   :modal.kind==="COMMIT"?<><label>Source type<select value={draft.source_type||"OTHER"} onChange={e=>setDraft({...draft,source_type:e.target.value})}>{["PROCUREMENT","TRAVEL","HIRING","SOFTWARE","PROJECT","CONTRACT","CARD","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label><label>Source reference<input required minLength={2} value={draft.source_reference||""} onChange={e=>setDraft({...draft,source_reference:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Amount<input required inputMode="decimal" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Upstream approval reference<input required minLength={2} value={draft.approval_reference||""} onChange={e=>setDraft({...draft,approval_reference:e.target.value})}/></label></>
   :modal.kind==="RELEASE"?<label>Release reason<textarea required minLength={3} value={draft.reason||""} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>
   :<><label>Source type<input required value={draft.source_type||"OTHER"} onChange={e=>setDraft({...draft,source_type:e.target.value.toUpperCase()})}/></label><label>Source reference<input required minLength={2} value={draft.source_reference||""} onChange={e=>setDraft({...draft,source_reference:e.target.value})}/></label><label>Description<textarea required minLength={3} value={draft.description||""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Actual amount<input required inputMode="decimal" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Evidence reference<input required minLength={3} value={draft.evidence||""} onChange={e=>setDraft({...draft,evidence:e.target.value})}/></label><p className={styles.muted}>Recording an actual does not execute a payment. It links an already-authorised source transaction/evidence to the budget ledger.</p></>}
   <footer><button type="button" disabled={busy} onClick={()=>setModal(undefined)}>Cancel</button><button type="submit" disabled={busy}>{busy?<LoaderCircle className={styles.spin}/>:<ShieldCheck/>}Confirm</button></footer>
  </form></div>:null}
 </section>;
}
