import Link from "next/link";
import { publicResearchMetrics, formatResearchValue, yuktaSources, researchCheckedAt } from "@/lib/products/yukta-research";
import { YuktaResearchCharts } from "./yukta-research-charts";
import styles from "./yukta-research.module.css";

export function YuktaProblem() {
  return <section id="problem" className={`shell yukta-section ${styles.section}`}><header className="yukta-section-head"><div><p className="eyebrow">THE OUTPATIENT WORKDAY</p><h2>Better handoffs, <em>less chasing.</em></h2></div><p>YUKTA focuses on the administrative moments around care: who has arrived, which doctor is available, what needs review and which payment still needs reconciliation.</p></header><div className={styles.grid}>{[
    ["Reception", "A schedule changes. The queue changes with it.", "The design connects appointments, walk-ins, arrival and doctor availability so staff can coordinate the next step."],
    ["Doctors & assistants", "A report being ready is not a clinical review.", "Separate report receipt from doctor review, and keep doctor instructions distinct from administrative entry."],
    ["Owners & accounts", "A payment screenshot is not reconciliation.", "Keep billing, collections and settlement status distinguishable, with authorised correction and a traceable record."],
  ].map(([role, title, body]) => <article key={role}><span className="eyebrow">{role}</span><h3>{title}</h3><p>{body}</p></article>)}</div><aside className={styles.note}><strong>What external evidence tells us</strong><p>A small time-motion study at S.N. Medical College, Agra examined registration steps and waiting as distinct sources of friction. Its single-centre sample is useful process context, not a national benchmark or a YUKTA result. The national Scan and Register programme also demonstrates practical demand for easier OPD registration.</p><a href="https://assets.cureus.com/uploads/original_article/pdf/351844/20250405-27095-aj5o4n.pdf" target="_blank" rel="noreferrer">Read the registration study ↗</a><span> · </span><a href={yuktaSources[2].url} target="_blank" rel="noreferrer">Read the MoHFW release ↗</a></aside></section>;
}

export function YuktaResearch() {
  const metrics = publicResearchMetrics(new Date().toISOString().slice(0, 10));
  return <>
    <section id="value" className={`shell yukta-section ${styles.section}`}><header className="yukta-section-head"><div><p className="eyebrow">EXPECTED OPERATIONAL VALUE</p><h2>Measure the work, <em>not the promise.</em></h2></div><p>No YUKTA pilot outcome dataset has been verified for this page. These are intended mechanisms and future measurement areas.</p></header><div className={styles.grid}>{[["Registration", "Reuse returning-patient context; measure time from registration start to a valid visit record."], ["Patient flow", "Coordinate doctor availability and arrivals; measure median and tail waiting times with documented exclusions."], ["Continuity & finance", "Track doctor-defined follow-up and unresolved payments; measure completion and reconciliation age."]].map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="market" className={`shell yukta-section ${styles.section}`}><header className="yukta-section-head"><div><p className="eyebrow">MARKET CONTEXT</p><h2>Healthcare administration <em>is becoming connected.</em></h2></div><p>Practice-management systems are the closest researched category to this outpatient workflow direction. They include software and services beyond YUKTA V1. These are market forecasts, not YUKTA revenue or valuation.</p></header>
      {metrics.length > 0 && <YuktaResearchCharts metrics={metrics} />}
      <div className={styles.note}><h3>Read the figures in context</h3><p>India and global figures come from independent publishers with different scopes and periods. They must not be added or treated as a single addressable-market model. The India report’s stated CAGR does not exactly reconcile to its published endpoints, so this page shows endpoints only.</p><p>Research checked <time dateTime={researchCheckedAt}>{researchCheckedAt}</time>. Data periods and source dates are listed separately below.</p></div>
      <details className={styles.table} open><summary>Source data, dates and evidence types</summary><div><table><caption>Reviewed public metrics; USD values retain their source currency and scale.</caption><thead><tr><th scope="col">Metric</th><th scope="col">Value</th><th scope="col">Period</th><th scope="col">Classification</th><th scope="col">Source</th></tr></thead><tbody>{metrics.map(metric => <tr key={metric.id}><th scope="row">{metric.label}</th><td>{formatResearchValue(metric)}</td><td>{metric.period}</td><td>{metric.kind.replaceAll("_", " ")}</td><td><a href={yuktaSources.find(source => source.id === metric.sourceIds[0])!.url} target="_blank" rel="noreferrer">{yuktaSources.find(source => source.id === metric.sourceIds[0])!.publisher} ↗</a></td></tr>)}</tbody></table></div></details>
      <div id="research-sources" className={styles.sources}>{yuktaSources.map(source => <article key={source.id}><h3><a href={source.url} target="_blank" rel="noreferrer">{source.publisher} ↗</a></h3><p>{source.title}</p><small>Published: {source.publishedAt ?? "not stated"} · Updated: {source.updatedAt ?? "not stated"} · Checked: {source.checkedAt}</small><p>{source.methodology}</p></article>)}</div>
    </section>
    <section className={`shell yukta-section ${styles.section}`}><header className="yukta-section-head"><div><p className="eyebrow">CHOOSING A PLATFORM</p><h2>Start with your <em>actual clinic workflow.</em></h2></div><p>Practice-management, EMR and hospital systems overlap, but have different starting points. This is a dated description of official product materials, not a ranking or endorsement.</p></header><div className={styles.grid}>{[
      ["Practo Ray", "Practice management for doctors and clinics.", "https://help.practo.com/practo-ray/getting-started/getting-started-with-ray/"],
      ["Eka Care", "Clinic management alongside digital prescriptions and patient engagement.", "https://www.eka.care/s/for-doctors"],
      ["Bahmni", "Open-source EMR and hospital system with clinical, laboratory and billing components.", "https://www.bahmni.org/feature-list/"],
      ["Clinicea", "Clinic workflows with patient portal, staff management and CRM guidance.", "https://help.clinicea.com/en/category/getting-started-1yzgs8f/"],
    ].map(([name, body, url]) => <article key={name}><h3>{name}</h3><p>{body}</p><a href={url} target="_blank" rel="noreferrer">Official product information ↗</a></article>)}</div><p className={styles.note}>Reviewed 6 September 2026. YUKTA’s documented focus is a doctor-centred outpatient timeline, support for handwritten consultation sheets, and administrative coordination in English and Telugu. Deployment, pricing, migrations and support must be evaluated for each product; absence from a page does not establish absence of a feature.</p></section>
    <section id="adoption" className={`shell yukta-section ${styles.section}`}><header className="yukta-section-head"><div><p className="eyebrow">DISCUSS YOUR OPERATING CONTEXT</p><h2>A considered start, <em>before activation.</em></h2></div><p>Discuss facility fit, staff responsibilities, doctor schedules, printing, patient pricing and data-migration requirements. Release readiness, integration activation and terms must be confirmed before use.</p></header><p>YUKTA is in development. No public launch date, price, migration duration or support SLA is promised here. Please do not send patient records, prescriptions or medical details in a sales enquiry.</p><Link href="/contact?product=yukta#enquiry-form" className="button button-dark">Discuss YUKTA</Link><p><Link href="/products">Kravia products</Link> · <Link href="/company/about">About Kravia</Link> · <Link href="/trust">Trust Centre</Link> · <Link href="/legal">Legal information</Link></p></section>
  </>;
}
