-- Kravia Corporate Office: private by default. Apply only to the intended Supabase project.
create type public.corporate_role as enum ('DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR','LEGAL_REVIEWER','READ_ONLY_ADVISOR');
create type public.visibility_level as enum ('PRIVATE','DIRECTORS','ADVISORS','PUBLIC_APPROVED');
create type public.record_status as enum ('DRAFT','REVIEW_REQUESTED','CORPORATE_REVIEW','LEGAL_REVIEW','APPROVED_FOR_PUBLICATION','PUBLISHED','ARCHIVED','FINAL');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text, role public.corporate_role not null default 'READ_ONLY_ADVISOR', mfa_verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.corporate_documents (id uuid primary key default gen_random_uuid(), document_type text not null, title text not null, financial_year text, authority text, registration_number_masked text, issue_date date, expiry_date date, status public.record_status not null default 'DRAFT', visibility public.visibility_level not null default 'PRIVATE', storage_path text not null unique, version integer not null default 1, checksum text, created_by uuid not null references public.profiles(id), reviewed_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);
create table public.board_meetings (id uuid primary key default gen_random_uuid(), meeting_number text not null, financial_year text not null, meeting_type text not null, scheduled_at timestamptz, location text, status public.record_status not null default 'DRAFT', chairperson_id uuid references public.profiles(id), draft_minutes text, approved_minutes_document_id uuid references public.corporate_documents(id), finalised_at timestamptz, finalised_by uuid references public.profiles(id), created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(meeting_number, financial_year));
create table public.meeting_agenda_items (id uuid primary key default gen_random_uuid(), meeting_id uuid not null references public.board_meetings(id) on delete cascade, ordinal integer not null, title text not null, detail text, created_at timestamptz not null default now(), unique(meeting_id, ordinal));
create table public.resolutions (id uuid primary key default gen_random_uuid(), meeting_id uuid references public.board_meetings(id), reference text not null unique, title text not null, body text not null, status public.record_status not null default 'DRAFT', finalised_at timestamptz, finalised_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.compliance_items (id uuid primary key default gen_random_uuid(), category text not null, title text not null, due_date date, owner_id uuid references public.profiles(id), legal_source text, rule_reference text, applicability text, calculation_rule text, last_reviewed_at timestamptz, status public.record_status not null default 'DRAFT', override_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.publications (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.corporate_documents(id), slug text not null unique, title text not null, financial_year text, published_at timestamptz, status public.record_status not null default 'DRAFT', approved_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.privacy_requests (id uuid primary key default gen_random_uuid(), reference text not null unique, category text not null, email text not null, name text, message text not null, status text not null default 'RECEIVED', retention_review_at date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_events (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, context jsonb not null default '{}'::jsonb, previous_state jsonb, new_state jsonb, created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.corporate_documents enable row level security; alter table public.board_meetings enable row level security; alter table public.meeting_agenda_items enable row level security; alter table public.resolutions enable row level security; alter table public.compliance_items enable row level security; alter table public.publications enable row level security; alter table public.privacy_requests enable row level security; alter table public.audit_events enable row level security;

create function public.has_corporate_role(roles public.corporate_role[]) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = any(roles)) $$;
create function public.is_corporate_member() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid()) $$;
revoke all on function public.has_corporate_role(public.corporate_role[]) from public; grant execute on function public.has_corporate_role(public.corporate_role[]) to authenticated;
revoke all on function public.is_corporate_member() from public; grant execute on function public.is_corporate_member() to authenticated;

create policy "profiles: self read" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles: admin manage" on public.profiles for all to authenticated using (public.has_corporate_role(array['CORPORATE_ADMIN']::public.corporate_role[])) with check (public.has_corporate_role(array['CORPORATE_ADMIN']::public.corporate_role[]));
create policy "documents: corporate members read permitted records" on public.corporate_documents for select to authenticated using (public.is_corporate_member() and (visibility = 'PRIVATE' or visibility = 'DIRECTORS' or visibility = 'ADVISORS'));
create policy "documents: privileged write" on public.corporate_documents for insert to authenticated with check (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR','LEGAL_REVIEWER']::public.corporate_role[]));
create policy "documents: privileged update" on public.corporate_documents for update to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR','LEGAL_REVIEWER']::public.corporate_role[]));
create policy "board: directors and secretaries" on public.board_meetings for all to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR','LEGAL_REVIEWER']::public.corporate_role[])) with check (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY']::public.corporate_role[]));
create policy "agenda: board access" on public.meeting_agenda_items for all to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR','LEGAL_REVIEWER']::public.corporate_role[])) with check (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY']::public.corporate_role[]));
create policy "resolutions: board access" on public.resolutions for all to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','LEGAL_REVIEWER']::public.corporate_role[])) with check (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY']::public.corporate_role[]));
create policy "compliance: authorised read" on public.compliance_items for select to authenticated using (public.is_corporate_member());
create policy "compliance: privileged write" on public.compliance_items for all to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR']::public.corporate_role[])) with check (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR']::public.corporate_role[]));
create policy "publications: published publicly readable" on public.publications for select using (status = 'PUBLISHED');
create policy "publications: reviewers manage" on public.publications for all to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','LEGAL_REVIEWER']::public.corporate_role[])) with check (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','LEGAL_REVIEWER']::public.corporate_role[]));
create policy "privacy: admin handling" on public.privacy_requests for all to authenticated using (public.has_corporate_role(array['CORPORATE_ADMIN','LEGAL_REVIEWER']::public.corporate_role[])) with check (public.has_corporate_role(array['CORPORATE_ADMIN','LEGAL_REVIEWER']::public.corporate_role[]));
create policy "audit: privileged read" on public.audit_events for select to authenticated using (public.has_corporate_role(array['DIRECTOR','CORPORATE_ADMIN','COMPANY_SECRETARY','CA_AUDITOR','LEGAL_REVIEWER']::public.corporate_role[]));
-- No INSERT/UPDATE/DELETE policy exists for audit_events: application mutations go through controlled server functions.
