import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Building2, Fingerprint, ShieldCheck, Waypoints } from "lucide-react";
import { Footer } from "@/components/footer";
import { KLine } from "@/components/k-line";
import { SiteNav } from "@/components/site-nav";
import { HeroMotion, Reveal } from "@/components/motion";

const principles = [["Clarity", "Complexity should become comprehensible."], ["Responsibility", "Technology should make accountability stronger."], ["Continuity", "We build for the long term, not the next release."]];
export default function Home() { return <><SiteNav /><main><section className="hero shell"><div className="hero-meta"><span>INDIA</span><span>SOFTWARE</span><span>AI</span><span>INFRASTRUCTURE</span></div><HeroMotion /><div className="hero-foot"><p>Kravia builds software products, intelligent systems and digital infrastructure designed to make complex work simpler, safer and more connected.</p><div><Link className="button button-light" href="/products">Explore our products <ArrowUpRight /></Link><Link className="text-link" href="/company">About Kravia</Link></div></div><KLine className="hero-line" /></section>
<section className="intro shell grid-12"><Reveal className="intro-kicker span-3"><p className="eyebrow">01 / COMPANY</p></Reveal><Reveal className="span-8"><h2>A corporate identity that gives serious work <em>room to grow.</em></h2><p>Kravia is the company layer behind a portfolio of products and systems—designed to hold product ambition, engineering discipline and corporate responsibility together.</p><Link href="/company" className="text-link">Meet Kravia <ArrowDownRight /></Link></Reveal></section>
<section className="dark-section"><div className="shell"><div className="section-head"><p className="eyebrow">02 / WHAT WE BUILD</p><h2>Systems with a<br /><em>useful point of view.</em></h2></div><div className="build-grid"><article><Building2 /><h3>Software products</h3><p>Clear, focused products that help people work with more confidence.</p></article><article><Fingerprint /><h3>Intelligent systems</h3><p>Practical intelligence designed with human judgement in view.</p></article><article><Waypoints /><h3>Digital infrastructure</h3><p>Connected foundations for work that needs to remain reliable.</p></article></div></div></section>
<section className="principles shell"><div className="section-head"><p className="eyebrow">03 / PRINCIPLES</p><h2>Made to hold up.</h2></div><div>{principles.map(([title, body], i) => <Reveal key={title} className="principle"><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></Reveal>)}</div></section>
<section className="trust-band"><div className="shell trust-inner"><ShieldCheck size={36}/><div><p className="eyebrow">04 / TRUST</p><h2>Private records stay private.<br />Public commitments stay clear.</h2></div><Link className="button button-dark" href="/trust">Explore Trust Center <ArrowUpRight /></Link></div></section>
<section className="shell final"><p className="eyebrow">KRAVIA PRIVATE LIMITED</p><h2>Building what<br /><em>comes next.</em></h2><div><Link className="button button-dark" href="/products">Explore our products <ArrowUpRight /></Link><Link className="text-link" href="/contact">Talk to Kravia</Link></div></section></main><Footer /></>; }
