import Link from "next/link";
import { ArrowUpRight, Blocks, BrainCircuit, CheckCircle2, CircleAlert, ExternalLink, FileText, Landmark, LockKeyhole, Network, ShieldCheck, UsersRound } from "lucide-react";
import { companyProfile, officialLinks } from "@/lib/site";
import { TrustRequestPortal } from "@/components/trust-request-portal";

const areas = [{ icon: Blocks, title: "Software Products", copy: "Products designed around real organisational workflows." }, { icon: BrainCircuit, title: "Intelligent Systems", copy: "Applied AI and automation that improve decisions and reduce repetitive work." }, { icon: Network, title: "Digital Infrastructure", copy: "Reliable systems, APIs and infrastructure supporting modern software products." }];
function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="detail-section"><span>{number}</span><div><h2>{title}</h2>{children}</div></section>; }
function CorporateInformation() { const fields = [["Legal name", companyProfile.legalName], ["Entity type", companyProfile.companyType], ["Country", companyProfile.country], ["CIN", companyProfile.cin], ["Incorporated", companyProfile.incorporationDate], ["Registered office", companyProfile.registeredOffice], ["GST status", companyProfile.gst.registered === null ? null : companyProfile.gst.registered ? "Registered" : "Not registered"], ["GSTIN", companyProfile.gst.gstin]]; return <dl className="facts-grid">{fields.filter(([, value]) => value).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>; }
export function PublicPageContent({ slug }: { slug: string }) {
  if (slug === "company") return <div className="detail-shell shell"><Section number="01" title="Technology should remove complexity, not create more of it."><p>Kravia is building a long-term technology company around useful products, intelligent systems and connected infrastructure. We take a considered approach: clear purpose, dependable engineering and responsible operation.</p></Section><Section number="02" title="What we build"><div className="capability-list">{areas.map(({ icon: Icon, title, copy }) => <article key={title}><Icon /><h3>{title}</h3><p>{copy}</p></article>)}</div></Section><Section number="03" title="Corporate information"><p>Only verified and approved statutory company information is published. Sensitive corporate records remain inside the Corporate Office.</p><CorporateInformation /></Section></div>;
  if (slug === "products") return <div className="detail-shell shell"><Section number="01" title="A focused product portfolio"><p>Kravia communicates ownership and direction at the corporate level. Individual product sites explain their own detailed offering.</p></Section><section className="product-feature"><div><p className="eyebrow">PUBLIC PRODUCT / EDUCATION</p><h2>VidyaLuma</h2><p>AI-powered school and academic intelligence platform.</p><span className="product-note">Official product URL pending owner configuration.</span></div><div className="product-mark"><span>V</span><i /></div></section><Section number="02" title="Portfolio discipline"><p>We publish products only when their identity, positioning and public information are approved. Product roadmaps and unreleased systems are not marketing material.</p></Section></div>;
  if (slug === "technology") return <div className="detail-shell shell"><Section number="01" title="Engineering from the experience down"><p>Kravia approaches technology as a connected system: the experience people use, the application logic behind it, secure services and data, and the infrastructure that supports dependable operation.</p><div className="architecture-flow">{["Experience", "Application", "Services", "Data", "Infrastructure"].map((label, index) => <div key={label}><span>0{index + 1}</span><b>{label}</b></div>)}</div></Section><Section number="02" title="Responsible applied AI"><p>We focus on appropriate automation, human oversight, privacy-aware data use, security, evaluation and safe failure modes. Tools should make accountability clearer—not harder to find.</p></Section></div>;
  if (slug === "governance") return <div className="detail-shell shell"><Section number="01" title="Mature conduct, kept private where it should be"><p>Kravia maintains appropriate governance processes and corporate records. Board materials, director communications, agendas, minutes, attendance and private resolutions are not public content.</p></Section><Section number="02" title="Public governance commitments"><div className="governance-grid">{[[UsersRound,"Leadership & accountability"],[Landmark,"Corporate governance"],[ShieldCheck,"Privacy & security governance"],[CircleAlert,"Risk & controls"]].map(([Icon, label]) => { const Item = Icon as typeof UsersRound; return <div key={label as string}><Item /><p>{label as string}</p></div>; })}</div></Section><Section number="03" title="Public disclosures"><p>Approved statutory notices and public corporate records belong in the Disclosure Register, never in general content or private storage.</p><Link href="/disclosures" className="text-link">View disclosures <ArrowUpRight /></Link></Section></div>;
  if (slug === "disclosures") return <div className="detail-shell shell"><Section number="01" title="Controlled disclosure register"><p>Each document requires private review and approval before publication. There are no approved public records currently available.</p></Section><div className="document-empty"><FileText /><div><h2>Disclosure register is ready</h2><p>Financial-year document rows will appear here only when a corporate record is verified and approved for public disclosure.</p></div></div></div>;
  if (slug === "trust") return <div className="detail-shell shell"><Section number="01" title="Trust should be designed in"><p>Kravia’s public Trust Center explains our approach to personal information, security, responsible AI and accessible technology without overstating what has not been verified.</p></Section><div className="trust-grid">{[["Privacy","How personal information collected through public forms is handled.","/trust/privacy"],["Data protection","Plain-language DPDP information and official references.","/trust/data-protection"],["Security","Verified security information and responsible reporting.","/trust/security"],["Responsible AI","Human oversight and appropriate automation.","/trust/responsible-ai"]].map(([title, copy, href]) => <Link href={href} key={title}><h2>{title}</h2><p>{copy}</p><ArrowUpRight /></Link>)}</div></div>;
  if (slug === "trust/data-protection") return <div className="detail-shell shell legal-reading"><Section number="01" title="Personal information, handled with care"><p>Kravia collects the limited information people choose to provide through enquiry and privacy-request forms so it can respond to the request, operate authorised services and meet applicable obligations. Detailed retention periods, processor arrangements and grievance contact information require owner and legal approval before production publication.</p></Section><Section number="02" title="Your choices"><p>Where applicable, you may ask a question, seek access or correction, request erasure, withdraw consent, raise a grievance or report a security concern through the private request route.</p><TrustRequestPortal /></Section><section className="official-resources"><p className="eyebrow">Official Government Resources</p>{officialLinks.map(link => <a key={link.href} href={link.href} target="_blank" rel="noreferrer">{link.label}<ExternalLink size={16} /></a>)}</section></div>;
  if (slug === "trust/security") return <div className="detail-shell shell"><Section number="01" title="Security is operational"><p>Public security statements are limited to controls that can be verified at production launch. The system design supports authenticated access, data isolation, controlled server-side actions and private corporate storage.</p></Section><Section number="02" title="Status before claim"><div className="status-list"><p><CheckCircle2 /> Verified: production configuration only</p><p><CircleAlert /> Partial: security operations require final deployment setup</p><p><LockKeyhole /> Planned: public security contact and vulnerability process require owner approval</p></div><Link href="/trust/security-reporting" className="button button-dark">Report a security concern <ArrowUpRight /></Link></Section></div>;
  if (slug === "trust/security-reporting") return <div className="detail-shell shell"><Section number="01" title="Responsible security reporting"><p>Use this restricted channel to report a potential Kravia security issue. Do not send credentials, private keys, production data or harmful payloads.</p></Section><TrustRequestPortal securityOnly /></div>;
  if (slug === "careers") return <div className="detail-shell shell"><Section number="01" title="A company built with care"><p>Kravia is for people who value useful technology, careful engineering and clear responsibility. Future roles will be published only when they are approved and active.</p></Section><Section number="02" title="Open roles"><div className="document-empty"><UsersRound /><div><h2>No open roles</h2><p>There are no approved vacancies at this time. We do not publish speculative job listings.</p></div></div></Section></div>;
  if (slug === "updates") return <div className="detail-shell shell"><Section number="01" title="Official company updates"><p>Company news, product launches, public notices and engineering updates will be managed as structured, approved content. Statutory documents remain in the Disclosure Register.</p></Section><div className="document-empty"><FileText /><div><h2>No updates published</h2><p>There are no approved updates at this time.</p></div></div></div>;
  if (slug === "legal") return <div className="detail-shell shell legal-reading"><Section number="01" title="Clear terms, clear responsibilities"><p>Legal notices and policies are published when reviewed and approved for the applicable service or public use. This page does not substitute for a legally reviewed terms-of-use document.</p></Section><Section number="02" title="Trust documents"><div className="inline-links"><Link href="/trust/privacy">Privacy</Link><Link href="/trust/data-protection">Data protection</Link><Link href="/trust/security">Security</Link><Link href="/trust/responsible-ai">Responsible AI</Link></div></Section></div>;
  return null;
}
