"use client";

import { useId, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { buildVidyaLumaForecastSeries, formatVidyaLumaUsdBn, vidyaLumaMarketEstimates, vidyaLumaMarketResearchReviewedAt } from "@/lib/products/vidyaluma-market";
import styles from "./vorio-market-chart.module.css";

export function VidyaLumaMarketChart() {
  const [region, setRegion] = useState<"global" | "india">("global");
  const estimate = vidyaLumaMarketEstimates[region];
  const data = buildVidyaLumaForecastSeries(estimate);
  const gradientId = useId().replace(/:/g, "");
  const ceiling = region === "global" ? 400 : 20;
  const growth = Math.round((estimate.forecastValueUsdBn / estimate.baseValueUsdBn - 1) * 100);
  return <div className={styles.panel}>
    <div className={styles.toolbar}><div><span className={styles.kicker}>EDUCATION TECHNOLOGY</span><h3>{region === "global" ? "Global" : "India"} market outlook</h3><p>{estimate.baseYear}–{estimate.forecastYear} · USD billions</p></div><div className={styles.switcher} role="group" aria-label="Market geography"><button type="button" aria-pressed={region === "global"} onClick={() => setRegion("global")}>Global</button><button type="button" aria-pressed={region === "india"} onClick={() => setRegion("india")}>India</button></div></div>
    <div className={styles.metrics} aria-live="polite"><div><span>{estimate.baseYear} estimate</span><strong>{formatVidyaLumaUsdBn(estimate.baseValueUsdBn)}</strong></div><div><span>{estimate.forecastYear} forecast</span><strong>{formatVidyaLumaUsdBn(estimate.forecastValueUsdBn)}</strong></div><div><span>Annual growth</span><strong>{estimate.cagr}<small>% CAGR</small></strong></div></div>
    <figure className={styles.figure}><figcaption className={styles.chartCaption}><span><i aria-hidden="true" />Market size forecast</span><span>Zero-based scale · USD B</span></figcaption><div className={styles.plot}><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{ top: 16, right: 14, bottom: 8, left: 0 }} accessibilityLayer><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--green)" stopOpacity={.2} /><stop offset="100%" stopColor="var(--green)" stopOpacity={.015} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="3 5" /><XAxis dataKey="year" axisLine={false} tickLine={false} minTickGap={16} tickMargin={14} tick={{ fill: "var(--ink-2)", fontSize: 12 }} /><YAxis domain={[0, ceiling]} width={52} axisLine={false} tickLine={false} tick={{ fill: "var(--ink-2)", fontSize: 12 }} tickFormatter={(value: number) => `$${value}`} /><Tooltip cursor={{ stroke: "var(--green)", strokeDasharray: "4 4" }} content={({ active, payload }) => { const point = payload?.[0]?.payload as (typeof data)[number] | undefined; return active && point ? <div className={styles.tooltip}><span>{point.year} {point.year === estimate.baseYear ? "estimate" : "forecast"}</span><strong>{formatVidyaLumaUsdBn(point.valueUsdBn)}</strong><small>{point.derived ? "Calculated from published CAGR" : point.year === estimate.baseYear ? "Published base estimate" : "Published forecast endpoint"}</small></div> : null; }} /><Area type="linear" dataKey="valueUsdBn" stroke="var(--green)" strokeWidth={3} strokeDasharray="6 4" fill={`url(#${gradientId})`} dot={{ r: 4, fill: "var(--paper)", strokeWidth: 2 }} activeDot={{ r: 6, strokeWidth: 3, stroke: "var(--paper)" }} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div><p className={styles.summary}>{formatVidyaLumaUsdBn(estimate.baseValueUsdBn)} in {estimate.baseYear} → {formatVidyaLumaUsdBn(estimate.forecastValueUsdBn)} forecast for {estimate.forecastYear}. Intermediate years are calculated from the published {estimate.cagr}% CAGR.</p></figure>
    <div className={styles.bottom}><div className={styles.comparison}><span>Projected change</span><strong>+{growth}%</strong><div className={styles.barRow}><span>{estimate.baseYear}</span><div><i style={{ width: `${estimate.baseValueUsdBn / estimate.forecastValueUsdBn * 100}%` }} /></div><span>100</span></div><div className={styles.barRow}><span>{estimate.forecastYear}</span><div><i /></div><span>{100 + growth}</span></div><small>Index: base year = 100. Derived from published endpoints.</small></div><div className={styles.source}><span className={styles.kicker}>SOURCE & METHODOLOGY</span><a href={estimate.url} target="_blank" rel="noreferrer">{estimate.source} ↗</a><p>{estimate.reportTitle}. This broader market category is industry context, not VidyaLuma revenue, market share or a guarantee of demand.</p><small>Research reviewed {vidyaLumaMarketResearchReviewedAt}</small></div></div>
    <details className={styles.table}><summary>View forecast data and method</summary><div><table><caption>{region === "global" ? "Global" : "India"} education technology market · USD billions</caption><thead><tr><th scope="col">Year</th><th scope="col">Value</th><th scope="col">Method</th></tr></thead><tbody>{data.map(point => <tr key={point.year}><td>{point.year}</td><td>{formatVidyaLumaUsdBn(point.valueUsdBn)}</td><td>{point.derived ? "CAGR-derived" : "Published endpoint"}</td></tr>)}</tbody></table></div></details>
  </div>;
}
