import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, BadgeCheck, BellRing, Camera, CheckCircle2, ClipboardCheck, Clock3, MapPinned, MessageSquareMore, Network, Route, ShieldCheck, Smartphone, Sparkles, UsersRound, Video, Wrench } from "lucide-react";
import { Accordion } from "@/components/ui";
import { ProductAnalytics, ProductTrackedLink } from "@/components/product-interactions";
import { formatUsdBn, selectedApacMarketEstimate, selectedGlobalGrowthIndex, selectedGlobalMarketEstimate, selectedGlobalMarketSeries, selectedUsMarketEstimate, vorioMarketEstimates, vorioMarketResearchReviewedAt } from "@/lib/products/vorio-market";
import { vorioProduct } from "@/lib/products/vorio";

const contactHref = "/contact?product=vorio#enquiry-form";
const icons = [BellRing, Clock3, UsersRound, Route, CheckCircle2, MapPinned, MapPinned, ClipboardCheck, BadgeCheck, Sparkles] as const;
const capabilityGroups = [
  ["Dispatch with operational context", "Bring requests, priority, SLA context and eligible workforce choices into one clear operating view.", ["Intelligent dispatch", "Technician eligibility", "Service-region management"], Route],
  ["Match work to the right capability", "Make skills and certification controls visible before work is assigned, so operations can act with clearer context.", ["Skills and certification controls", "Plan-controlled capabilities", "Human operational control"], BadgeCheck],
  ["Keep service commitments in view", "Design the work around live status, priority, acceptance and SLA attention - not status chasing across calls and messages.", ["SLA-aware operations", "Secure realtime updates", "Notifications"], Clock3],
  ["Make mobile execution legible", "Give technicians a workflow for work updates, checklists and completion evidence while teams retain a clear operational picture.", ["Technician mobile workflow", "Job checklists", "Evidence collection"], Smartphone],
  ["Keep customers appropriately informed", "Share service progress through customer-safe tracking without exposing internal operations.", ["Customer tracking", "Controlled progress updates", "Completion communication"], MessageSquareMore],
  ["Support the work when context matters", "Prepare a governed path for remote operational assistance through audio and video, subject to approved release scope.", ["WebRTC assistance", "Operational communications", "Product intelligence / automation"], Video],
] as const;
const impactItems = ["Faster dispatch decisions", "Fewer coordination steps", "More consistent technician selection", "Better SLA visibility", "Fewer status calls", "Clearer accountability", "Stronger completion documentation", "More useful operational reporting"] as const;
const personas = [
  ["Operations owner", "Needs a reliable operating picture across requests, teams, territories and service outcomes.", "A connected view of the work and its handoffs."],
  ["Dispatcher", "Needs to make fast, defensible assignments without chasing separate sources of status.", "Eligible choices, priority context and a clear response path."],
  ["Service manager", "Needs to understand whether commitments, capacity and field execution are holding together.", "SLA visibility, accountable workflow and operational reporting."],
  ["Field technician", "Needs the next job, the relevant context and a clean way to record progress.", "A focused mobile execution workflow."],
  ["Service recipient", "Needs to know what is happening without repeated calls for an update.", "Appropriate service-status visibility from request to completion."],
] as const;
const useCases = [
  ["Priority commercial service", "A private commercial service organisation responds to a priority HVAC, electrical or equipment request with a clear SLA and dispatch path."],
  ["Multi-site maintenance", "A facilities team coordinates technicians across several locations while retaining service-region and work-status visibility."],
  ["Field repair operations", "An appliance or equipment service business connects intake, technician work, evidence and customer updates in one operational lifecycle."],
  ["Distributed team coordination", "A service organisation operating across India or US time zones configures local conventions without splitting the platform story."],
] as const;
const trust = [
  ["Tenant isolation", "Design the platform so one organisation's operational data stays separated from another's."],
  ["Role-aware access", "Make access and capabilities match the responsibility of the person using the system."],
  ["Traceable actions", "Keep material dispatch and execution actions understandable and auditable."],
  ["Controlled data lifecycle", "Treat service, location and evidence data as governed information rather than incidental exhaust."],
] as const;

function MarketChart() {
  const series = selectedGlobalMarketSeries;
  const max = Math.max(...series.map((point) => point.valueUsdBn));
  const points = series.map((point, index) => `${58 + index * 126},${198 - (point.valueUsdBn / max) * 146}`).join(" ");
  return <figure className="vorio-chart">
    <figcaption id="vorio-chart-title"><span className="eyebrow">GLOBAL FIELD SERVICE MANAGEMENT MARKET</span><strong>2025-2030 forecast</strong><p>USD billions. Endpoints are published by MarketsandMarkets; 2026-2029 are CAGR-derived estimates.</p></figcaption>
    <svg viewBox="0 0 720 260" role="img" aria-labelledby="vorio-chart-title vorio-chart-summary">
      <desc id="vorio-chart-summary">MarketsandMarkets estimates the global field service management market grows from 5.10 billion US dollars in 2025 to 9.17 billion US dollars in 2030 at a 12.5 percent compound annual growth rate. Intermediate values are derived from that published CAGR.</desc>
      <line x1="58" x2="690" y1="198" y2="198" /><line x1="58" x2="690" y1="125" y2="125" /><line x1="58" x2="690" y1="52" y2="52" />
      <polyline points={points} />
      {series.map((point, index) => { const x = 58 + index * 126; const y = 198 - (point.valueUsdBn / max) * 146; return <g key={point.year}><circle cx={x} cy={y} r={point.derived ? 4 : 6} data-derived={point.derived || undefined} /><text x={x} y={y - 13} textAnchor="middle">{formatUsdBn(point.valueUsdBn)}</text><text x={x} y="226" textAnchor="middle">{point.year}</text></g>; })}
    </svg>
    <details><summary>View the market-data table</summary><table><caption>Global field service management forecast, USD billions</caption><thead><tr><th scope="col">Year</th><th scope="col">Market value</th><th scope="col">Method</th></tr></thead><tbody>{series.map((point) => <tr key={point.year}><td>{point.year}</td><td>{formatUsdBn(point.valueUsdBn)}</td><td>{point.derived ? "Derived from published CAGR" : "Published source endpoint"}</td></tr>)}</tbody></table></details>
  </figure>;
}

export function VorioProductPage() {
  return <main id="main-content" className="vorio-page">
    <ProductAnalytics event="vorio_product_view" product="vorio" />
    <section className="vorio-hero"><div className="shell vorio-hero-grid">
      <div><p className="eyebrow">{vorioProduct.hero.eyebrow}</p><p className="vorio-wordmark" aria-label="VORIO">VORIO<span aria-hidden="true">.</span></p><h1>{vorioProduct.hero.title}</h1><p className="vorio-lede">{vorioProduct.hero.intro}</p><div className="vorio-actions"><ProductTrackedLink product="vorio" event="vorio_explore_clicked" href="#how-it-works" className="button button-dark">Explore the operating flow <ArrowDownRight aria-hidden="true" /></ProductTrackedLink><ProductTrackedLink product="vorio" event="vorio_contact_clicked" href={contactHref} className="text-link">Talk to Kravia <ArrowUpRight aria-hidden="true" /></ProductTrackedLink></div></div>
      <aside className="vorio-signal-board" aria-label="VORIO operational lifecycle preview"><div><span>VORIO / FIELD OPERATIONS</span><strong>In development</strong></div><div className="vorio-route-map" aria-hidden="true"><i /><i /><i /><i /><i /><b /></div><p><span>Request</span><span>Dispatch</span><span>Execute</span></p></aside>
    </div></section>

    <section className="shell vorio-overview" aria-labelledby="vorio-overview-title"><div><p className="eyebrow">WHAT IS VORIO?</p><h2 id="vorio-overview-title">A field-service operating layer for the work that happens <em>away from the desk.</em></h2></div><div><p>VORIO helps service businesses coordinate field technicians faster, assign work with clearer qualification and service context, maintain live operational visibility and keep customers informed from request through completion.</p><p>It is being developed for organisations that operate their own field workforce - not public emergency response.</p></div></section>

    <section id="how-it-works" className="vorio-section vorio-lifecycle"><div className="shell"><header className="vorio-section-head"><div><p className="eyebrow">01 / HOW VORIO WORKS</p><h2>One operational thread, <em>from request to continuity.</em></h2></div><p>VORIO is designed to replace fragmented calls, messages and spreadsheets with a coordinated service lifecycle.</p></header><ol className="vorio-lifecycle-grid">{vorioProduct.lifecycle.map((step, index) => { const Icon = icons[index]; return <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><Icon aria-hidden="true" /><strong>{step}</strong></li>; })}</ol></div></section>

    <section className="vorio-section shell"><header className="vorio-section-head"><div><p className="eyebrow">02 / PRODUCT CAPABILITIES</p><h2>Built for operations that need a clearer <em>next move.</em></h2></div><p>These are capability directions for VORIO's in-development product scope. Public availability is confirmed only when a release is approved.</p></header><div className="vorio-capability-grid">{capabilityGroups.map(([title, copy, items, Icon], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><Icon aria-hidden="true" /><h3>{title}</h3><p>{copy}</p><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section className="vorio-section vorio-dispatch"><div className="shell vorio-dispatch-grid"><div><p className="eyebrow">03 / DISPATCH, ELIGIBILITY & SLA</p><h2>A fast dispatch decision should still be a <em>considered one.</em></h2><p>VORIO is being shaped around who is available, who is eligible, what the service commitment requires and how the work responds when the first path changes.</p></div><div className="vorio-operating-signals"><article><span>01</span><h3>Eligibility before ranking</h3><p>Start with technicians who can do the work in the relevant service context before a dispatch choice is made.</p></article><article><span>02</span><h3>A visible SLA clock</h3><p>Make the commitments and priority surrounding a request easier for operations teams to see and manage.</p></article><article><span>03</span><h3>An explicit response path</h3><p>Design for accept, decline, timeout and reassignment so operational recovery is not an afterthought.</p></article></div></div></section>

    <section className="vorio-section shell"><header className="vorio-section-head"><div><p className="eyebrow">04 / FIELD EXECUTION</p><h2>The field team gets a workflow, not another <em>message thread.</em></h2></div><p>Keep the work readable for the technician and accountable for the operations team.</p></header><div className="vorio-execution-grid"><article><Smartphone aria-hidden="true" /><h3>Technician mobile workflow</h3><p>Receive the next assigned job, understand service context and update the work from the field.</p></article><article><ClipboardCheck aria-hidden="true" /><h3>Checklists and evidence</h3><p>Use job-specific checklists and completion evidence to make handoffs and records clearer.</p></article><article><MapPinned aria-hidden="true" /><h3>Live status and route context</h3><p>Keep a usable view of assignment, progress and route status as the day changes.</p></article><article><Video aria-hidden="true" /><h3>Remote operational support</h3><p>Prepare a controlled path for audio/video assistance when a job needs more context.</p></article></div></section>

    <section className="vorio-section vorio-customers"><div className="shell vorio-customer-grid"><div><p className="eyebrow">05 / CUSTOMER STATUS</p><h2>Clear service progress - without turning customers into <em>dispatchers.</em></h2></div><p>Customer-safe tracking is designed to answer the practical question: what is happening with my request? Internal location, assignment and operations data remain governed by appropriate permissions.</p></div></section>

    <section className="vorio-section shell"><header className="vorio-section-head"><div><p className="eyebrow">06 / INDIA + UNITED STATES</p><h2>One platform direction, <em>country-aware configuration.</em></h2></div><p>VORIO is being developed for India and the United States without claiming every provider integration is already production-enabled.</p></header><div className="vorio-region-grid"><article><p className="eyebrow">INDIA</p><h3>Local operating conventions, considered.</h3><ul><li>INR and Indian address / phone conventions</li><li>Asia/Kolkata and metric units</li><li>MSG91 and Razorpay integration readiness, subject to scope and credentials</li></ul></article><article><p className="eyebrow">UNITED STATES</p><h3>Multi-timezone operations, designed in.</h3><ul><li>USD and US address / phone conventions</li><li>Multiple time zones, daylight-saving time and imperial presentation options</li><li>Twilio and Stripe integration readiness, subject to scope, credentials and merchant eligibility</li></ul></article></div></section>

    <section className="vorio-section vorio-impact"><div className="shell"><header className="vorio-section-head"><div><p className="eyebrow">07 / EXPECTED OPERATIONAL IMPACT</p><h2>Designed to improve the economics of <em>field operations.</em></h2></div><p>No performance percentage is claimed before deployment evidence exists. These are the operating outcomes VORIO is being designed to support.</p></header><div className="vorio-impact-grid">{impactItems.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></article>)}</div></div></section>

    <section className="vorio-section shell vorio-market"><header className="vorio-section-head"><div><p className="eyebrow">08 / MARKET OPPORTUNITY</p><h2>A growing category, with definitions that deserve <em>care.</em></h2></div><p>Market research firms measure the broader field-service-management category differently. VORIO keeps the source, period and definition next to every number.</p></header><div className="vorio-market-metrics"><article><span>Global FSM market</span><strong>{formatUsdBn(selectedGlobalMarketEstimate.baseValueUsdBn)}</strong><p>{selectedGlobalMarketEstimate.baseYear} published estimate</p></article><article><span>Global forecast</span><strong>{formatUsdBn(selectedGlobalMarketEstimate.forecastValueUsdBn)}</strong><p>{selectedGlobalMarketEstimate.forecastYear} / MarketsandMarkets</p></article><article><span>Global CAGR</span><strong>{selectedGlobalMarketEstimate.cagr}%</strong><p>{selectedGlobalMarketEstimate.baseYear}-{selectedGlobalMarketEstimate.forecastYear}</p></article><article><span>US FSM forecast</span><strong>{formatUsdBn(selectedUsMarketEstimate.baseValueUsdBn)} to {formatUsdBn(selectedUsMarketEstimate.forecastValueUsdBn)}</strong><p>{selectedUsMarketEstimate.baseYear}-{selectedUsMarketEstimate.forecastYear} / {selectedUsMarketEstimate.cagr}% CAGR</p></article></div><MarketChart /><div className="vorio-growth-index"><div><span className="eyebrow">MARKET GROWTH INDEX</span><strong>100</strong><p>{selectedGlobalMarketEstimate.baseYear} baseline</p></div><i aria-hidden="true" /><div><span className="eyebrow">PUBLISHED-ENDPOINT INDEX</span><strong>{selectedGlobalGrowthIndex}</strong><p>{selectedGlobalMarketEstimate.forecastYear}, derived from published endpoints</p></div></div><div className="vorio-market-context"><p>Other current research illustrates the range: Grand View Research reports a global forecast of $13.8B by 2033 from a $6.7B 2026 estimate, while Mordor Intelligence estimates Asia Pacific at $2.61B in 2025 and $6.41B in 2030. These values are not directly interchangeable because periods, regional scopes and market definitions differ.</p><p>Market research reviewed: <time dateTime={vorioMarketResearchReviewedAt}>{vorioMarketResearchReviewedAt}</time>.</p></div></section>

    <section className="vorio-section vorio-landscape"><div className="shell"><header className="vorio-section-head"><div><p className="eyebrow">09 / CATEGORY LANDSCAPE</p><h2>Positioned by operating intent, <em>not unsupported superlatives.</em></h2></div><p>VORIO is being developed in a mature field-service category with enterprise suites and industry-focused products.</p></header><div className="vorio-landscape-grid"><article><h3>Enterprise suites</h3><p>Salesforce Field Service, Microsoft Dynamics 365 Field Service, Oracle Field Service, IFS and ServiceNow serve the broader enterprise field-service category.</p></article><article><h3>Field-service specialists</h3><p>Jobber, Housecall Pro, ServiceTitan and Zoho FSM are examples of product-focused field-service platforms in the category.</p></article><article><h3>VORIO's product intent</h3><p>VORIO is being shaped around dispatch-first workflows, eligibility before ranking, SLA visibility, integrated execution, bounded automation and India + US configuration.</p></article></div></div></section>

    <section className="vorio-section shell"><header className="vorio-section-head"><div><p className="eyebrow">10 / WHO VORIO IS FOR</p><h2>A shared operating picture for the people who keep service <em>moving.</em></h2></div></header><div className="vorio-persona-grid">{personas.map(([role, challenge, benefit]) => <article key={role}><p className="eyebrow">{role}</p><h3>{challenge}</h3><p><strong>Designed to provide:</strong> {benefit}</p></article>)}</div></section>

    <section className="vorio-section vorio-use-cases"><div className="shell"><header className="vorio-section-head"><div><p className="eyebrow">11 / ILLUSTRATIVE USE CASES</p><h2>Operational scenarios, not <em>customer case studies.</em></h2></div><p>These examples are hypothetical and do not represent named VORIO customers or measured outcomes.</p></header><div className="vorio-use-case-grid">{useCases.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="vorio-section shell"><header className="vorio-section-head"><div><p className="eyebrow">12 / ONE CONNECTED OPERATING LAYER</p><h2>Customer-facing architecture, <em>without exposing infrastructure.</em></h2></div><p>VORIO is designed to coordinate visible operating layers without publishing private implementation, security or scoring details.</p></header><div className="vorio-architecture-stack"><article><Wrench aria-hidden="true" /><span>Operations web</span></article><article><Smartphone aria-hidden="true" /><span>Technician mobile</span></article><article><Network aria-hidden="true" /><span>Realtime dispatch</span></article><article><Route aria-hidden="true" /><span>Location + routing</span></article><article><MessageSquareMore aria-hidden="true" /><span>Customer tracking</span></article><article><Camera aria-hidden="true" /><span>Evidence</span></article><article><BellRing aria-hidden="true" /><span>Communications</span></article><article><ClipboardCheck aria-hidden="true" /><span>Operational reports</span></article></div></section>

    <section className="vorio-section vorio-trust"><div className="shell"><header className="vorio-section-head"><div><p className="eyebrow">13 / TRUST & CONTROL</p><h2>Operational visibility needs <em>clear boundaries.</em></h2></div><p>VORIO is being designed with privacy and security controls at the platform foundation. Certifications are not claimed unless independently verified.</p></header><div className="vorio-trust-grid">{trust.map(([title, copy]) => <article key={title}><ShieldCheck aria-hidden="true" /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="vorio-section shell vorio-faq"><header className="vorio-section-head"><div><p className="eyebrow">14 / FAQ</p><h2>Direct answers for the operational questions that <em>matter first.</em></h2></div></header><Accordion label="VORIO frequently asked questions" entries={vorioProduct.faqs.map(([title, content]) => ({ title, content: <p>{content}</p> }))} /></section>

    <section className="vorio-section vorio-sources"><div className="shell"><header className="vorio-section-head"><div><p className="eyebrow">MARKET RESEARCH REFERENCES</p><h2>Source-led context, with <em>scope kept visible.</em></h2></div><p>External sources are provided for market context. Kravia does not endorse a provider's methodology beyond identifying the cited report.</p></header><ol>{vorioMarketEstimates.map((source) => <li key={source.id}><div><strong>{source.source}</strong><span>{source.publishedAt} / accessed {source.accessedAt}</span></div><a href={source.url} target="_blank" rel="noreferrer">{source.reportTitle} <ArrowUpRight aria-hidden="true" /></a><p>{source.notes}</p></li>)}</ol></div></section>

    <section className="vorio-early-access"><div className="shell vorio-early-access-inner"><div><p className="eyebrow">VORIO / EARLY ACCESS</p><h2>Shape the field-service operating context <em>before launch.</em></h2><p>VORIO is currently being developed by Kravia for field-service organisations in India and the United States. Discuss workflow and product-fit questions through the existing corporate enquiry route.</p></div><ProductTrackedLink product="vorio" event="vorio_early_access_clicked" href={contactHref} className="button button-light">Discuss VORIO <ArrowUpRight aria-hidden="true" /></ProductTrackedLink></div></section>
    <section className="vorio-final"><div className="shell vorio-final-inner"><div><p className="eyebrow">VORIO / A KRAVIA PRODUCT</p><h2>Dispatch with context.<br /><em>Execute with clarity.</em></h2></div><Link href="/products" className="text-link">Explore Kravia products <ArrowUpRight aria-hidden="true" /></Link></div></section>
  </main>;
}
