import "server-only";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { requireOfficeAdminEnvironment } from "@/lib/env/office";
import { getOfficeSessionContext, officeIdentityIsProvisioned } from "@/lib/office/auth-server";
import { canAdministerAccess,canInviteRoles,canManageTarget,isOfficeDepartment,type OfficeDepartment,type OfficeIdentityStatus } from "@/lib/office/access-policy";
import { isOfficeRole, type OfficeRole } from "@/lib/office/workspaces";
import { OfficeAccessError } from "@/lib/office/access-admin";
type Actor={userId:string;email?:string;roles:OfficeRole[]}; type Target={userId:string;email?:string;roles:OfficeRole[];status:OfficeIdentityStatus};
function adminClient(){const e=requireOfficeAdminEnvironment();return createClient(e.OFFICE_SUPABASE_URL,e.OFFICE_SUPABASE_SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})}
async function authority():Promise<{admin:SupabaseClient;actor:Actor}>{const context=await getOfficeSessionContext();if(!context||!officeIdentityIsProvisioned(context.identity))throw new OfficeAccessError(401,"Office sign-in required");if(context.identity.aal!=="aal2")throw new OfficeAccessError(403,"AAL2 verification is required");if(!canAdministerAccess(context.identity.roles))throw new OfficeAccessError(403,"OWNER or ADMIN authority is required");try{return{admin:adminClient(),actor:{userId:context.identity.userId,email:context.identity.email,roles:context.identity.roles}}}catch{throw new OfficeAccessError(503,"Trusted Office access administration is not configured")}}
async function target(admin:SupabaseClient,userId:string):Promise<Target>{const[identityResult,roleResult,authResult]=await Promise.all([admin.from("office_identity_users").select("status").eq("user_id",userId).maybeSingle(),admin.from("office_user_roles").select("role,expires_at").eq("user_id",userId),admin.auth.admin.getUserById(userId)]);if(identityResult.error||roleResult.error||authResult.error||!identityResult.data||!authResult.data.user)throw new OfficeAccessError(404,"Office identity not found");const status=identityResult.data.status as OfficeIdentityStatus;if(!(["INVITED","ACTIVE","SUSPENDED","REVOKED"] as const).includes(status))throw new OfficeAccessError(409,"Office identity state is invalid");const now=Date.now();const roles=((roleResult.data??[]) as Array<{role:unknown;expires_at?:unknown}>).filter((row)=>{if(typeof row.expires_at!=="string"||!row.expires_at)return true;const expiry=Date.parse(row.expires_at);return Number.isFinite(expiry)&&expiry>now}).map((row)=>row.role).filter(isOfficeRole);return{userId,email:authResult.data.user.email,roles:Array.from(new Set(roles)),status}}
async function audit(admin:SupabaseClient,actor:Actor,input:{targetUserId?:string;targetEmail?:string;action:string;department?:string;reason?:string;metadata?:Record<string,unknown>}){const{error}=await admin.from("office_access_audit").insert({actor_user_id:actor.userId,actor_roles:actor.roles,target_user_id:input.targetUserId??null,target_email:input.targetEmail??null,action:input.action,department:input.department??null,reason:input.reason??null,metadata:input.metadata??{}});if(error)throw new OfficeAccessError(500,"Access audit write failed")}
export async function acceptOfficeInvitation(userId:string){let admin:SupabaseClient;try{admin=adminClient()}catch{return false}const{data,error}=await admin.rpc("office_accept_invitation",{p_user_id:userId});if(error)return false;return data===true}
export async function revokeOfficeInvitation(input:{invitationId:string;reason:string}){const{admin,actor}=await authority();const{data:invitation,error}=await admin.from("office_access_invitations").select("id,email,requested_roles,auth_user_id,status").eq("id",input.invitationId).maybeSingle();if(error||!invitation)throw new OfficeAccessError(404,"Invitation not found");if(invitation.status!=="PENDING")throw new OfficeAccessError(409,"Only pending invitations can be revoked");const requestedRoles=(Array.isArray(invitation.requested_roles)?invitation.requested_roles:[]).filter(isOfficeRole);const decision=canInviteRoles(actor.roles,requestedRoles);if(!decision.allowed)throw new OfficeAccessError(403,decision.reason);const now=new Date().toISOString();const{error:revokeError}=await admin.from("office_access_invitations").update({status:"REVOKED",revoked_at:now,updated_at:now}).eq("id",invitation.id).eq("status","PENDING");if(revokeError)throw new OfficeAccessError(500,"Unable to revoke invitation");if(typeof invitation.auth_user_id==="string"){await admin.from("office_identity_users").update({status:"REVOKED"}).eq("user_id",invitation.auth_user_id).eq("status","INVITED");try{await admin.auth.admin.deleteUser(invitation.auth_user_id)}catch{/* Identity remains fail-closed if provider cleanup is unavailable. */}}await audit(admin,actor,{targetUserId:typeof invitation.auth_user_id==="string"?invitation.auth_user_id:undefined,targetEmail:invitation.email,action:"INVITE_REVOKED",reason:input.reason,metadata:{requested_roles:requestedRoles}});return{revoked:true,invitation_id:invitation.id}}
export async function changeOfficeDepartment(input:{targetUserId:string;department:OfficeDepartment;reason:string}){const{admin,actor}=await authority();if(!isOfficeDepartment(input.department))throw new OfficeAccessError(400,"Invalid Office department");const targetIdentity=await target(admin,input.targetUserId);if(targetIdentity.status==="INVITED"||targetIdentity.status==="REVOKED")throw new OfficeAccessError(409,"Department changes require an active or suspended identity");const decision=canManageTarget(actor.userId,actor.roles,targetIdentity.userId,targetIdentity.roles);if(!decision.allowed)throw new OfficeAccessError(403,decision.reason);const{error}=await admin.from("office_identity_users").update({primary_department:input.department}).eq("user_id",targetIdentity.userId);if(error)throw new OfficeAccessError(500,"Department update failed");await audit(admin,actor,{targetUserId:targetIdentity.userId,targetEmail:targetIdentity.email,action:"DEPARTMENT_CHANGED",department:input.department,reason:input.reason});return{updated:true,target_user_id:targetIdentity.userId,department:input.department}}
export async function resetOfficeMfa(input:{targetUserId:string;reason:string}){const{admin,actor}=await authority();const targetIdentity=await target(admin,input.targetUserId);if(targetIdentity.status==="INVITED"||targetIdentity.status==="REVOKED")throw new OfficeAccessError(409,"MFA reset requires an active or suspended identity");const decision=canManageTarget(actor.userId,actor.roles,targetIdentity.userId,targetIdentity.roles);if(!decision.allowed)throw new OfficeAccessError(403,decision.reason);const{data,error}=await admin.auth.admin.getUserById(targetIdentity.userId);if(error||!data.user)throw new OfficeAccessError(404,"Office identity not found");const factors=(data.user.factors??[]).filter((factor)=>factor.factor_type==="totp");if(!factors.length)throw new OfficeAccessError(409,"No TOTP factor is enrolled for this identity");for(const factor of factors){const{error:deleteError}=await admin.auth.admin.mfa.deleteFactor({id:factor.id,userId:targetIdentity.userId});if(deleteError)throw new OfficeAccessError(502,"Unable to reset the authenticator factor")}await audit(admin,actor,{targetUserId:targetIdentity.userId,targetEmail:targetIdentity.email,action:"MFA_RESET",reason:input.reason,metadata:{factor_count:factors.length}});return{reset:true,factor_count:factors.length,target_user_id:targetIdentity.userId}}
