"""v3 tamper evident audit chain

Revision ID: 7908cb4588e7
Revises: eadfbcc35b0f
Create Date: 2026-09-12 10:58:56.830798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7908cb4588e7'
down_revision: Union[str, Sequence[str], None] = 'eadfbcc35b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('event_hash', sa.String(length=64), nullable=True))
    op.create_index('ux_audit_event_hash', 'audit_events', ['event_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_audit_event_hash', table_name='audit_events')
    op.drop_column('audit_events', 'event_hash')
    op.drop_column('audit_events', 'previous_hash')
    # ### end Alembic commands ###
