const NAV=[
  ['Operate',[['command-center','Command Center','◈'],['products','Products','◫'],['customers','Customers','◎'],['commercial/plans','Commercial','◧']]],
  ['Money',[['invoices','Billing','▤'],['tax/gst/summary','GST & Tax','%'],['accounting/trial-balance','Accounting','▥'],['banking/transactions','Banking','⌁']]],
  ['Govern',[['governance/meetings','Governance','◇'],['compliance','Compliance','✓'],['contracts','Contracts','▧'],['vendors','Vendors','◩']]],
  ['Office',[['people','People','◉'],['assets','Assets','▦'],['documents','Documents','▤']]],
  ['Assure',[['notices','Notices','!'],['inspections','Audit & Inspection','◌'],['approvals','Approvals','✓'],['integrations','Integrations','⌘'],['audit','Audit Trail','≡']]]
];
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let route=(location.hash||'#command-center').slice(1), products=[], customers=[];
const session=()=>({actor:sessionStorage.getItem('ko_actor')||'Office Owner',role:sessionStorage.getItem('ko_role')||'OWNER',key:sessionStorage.getItem('ko_key')||''});
function headers(extra={}){const s=session(),h={'Content-Type':'application/json','X-Office-Actor':s.actor,'X-Office-Role':s.role,...extra};if(s.key)h['X-Kravia-Office-Key']=s.key;return h}
async function api(path,opts={}){const r=await fetch('/api/v1/'+path,{...opts,headers:{...headers(opts.headers||{})}});let body=null;const ct=r.headers.get('content-type')||'';if(ct.includes('application/json'))body=await r.json();else body=await r.text();if(!r.ok)throw new Error(body?.detail||body||`HTTP ${r.status}`);return body}
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;$('#toast').append(e);setTimeout(()=>e.remove(),3500)}
function badge(v){const s=String(v||'').toUpperCase();let c=/ACTIVE|PAID|MATCHED|SUCCESS|READY|LOCKED|ISSUED|APPROVED/.test(s)?'good':/OVERDUE|FAILED|CRITICAL|REJECTED/.test(s)?'bad':/PENDING|REVIEW|UNMATCHED|OPEN|CANCELLING/.test(s)?'warn':'info';return `<span class="badge ${c}">${esc(s.replaceAll('_',' '))}</span>`}
function table(headers,rows){return `<div class="tableWrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}"><div class="empty"><b>No records yet</b>Nothing is fabricated. Create/connect a source to populate this area.</div></td></tr>`}</tbody></table></div>`}
function card(title,sub,body,action=''){return `<section class="card"><div class="cardHead"><div><h2>${esc(title)}</h2><p>${esc(sub||'')}</p></div>${action}</div><div class="cardBody">${body}</div></section>`}
function metric(l,v,m){return `<div class="metric"><label>${esc(l)}</label><strong>${esc(v)}</strong><small>${esc(m||'')}</small></div>`}
function renderNav(){$('#nav').innerHTML=NAV.map(([g,items])=>`<div class="navGroup"><div class="navLabel">${g}</div>${items.map(([id,l,i])=>`<button class="navBtn ${route===id?'active':''}" data-route="${id}"><span class="ico">${i}</span>${l}</button>`).join('')}</div>`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;location.hash=route;renderNav();render()})}
async function init(){renderNav();$('#refresh').onclick=render;$('#sessionBtn').onclick=sessionModal;$('#modalClose').onclick=closeModal;$('#drawerClose').onclick=closeDrawer;$('#createBtn').onclick=createForRoute;window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();commandModal()}});$('#commandBtn').onclick=commandModal;await health();await preload();render()}
async function health(){try{const r=await fetch('/health');const j=await r.json();$('#apiState').textContent=`API ${j.version} · ${j.status}`;$('#apiState').className='health ok'}catch(e){$('#apiState').textContent='API unavailable';$('#apiState').className='health bad'}}
async function preload(){try{[products,customers]=await Promise.all([api('products'),api('customers')])}catch(e){}}
function setTitle(t){$('#title').textContent=t;$('#crumb').textContent='KRAVIA PRIVATE LIMITED'}
function banner(){return `<div class="banner"><b>Evidence-first operating mode</b><span>Values shown here come from KRAVIA Office records. Missing external sources remain explicitly unavailable.</span></div>`}
async function render(){const c=$('#content');c.innerHTML=banner()+card('Loading','Reading canonical records','<div class="empty">Loading…</div>');try{if(route==='command-center')return renderCommand();if(route==='products')return renderProducts();if(route==='customers')return renderCustomers();if(route==='commercial/plans')return renderPlans();if(route==='invoices')return renderInvoices();if(route==='tax/gst/summary')return renderTax();if(route==='accounting/trial-balance')return renderAccounting();if(route==='banking/transactions')return renderBanking();if(route==='governance/meetings')return renderGovernance();if(route==='documents')return renderDocuments();if(route==='notices')return renderNotices();if(route==='inspections')return renderInspections();if(route==='approvals')return renderApprovals();if(route==='integrations')return renderIntegrations();return renderGeneric(route)}catch(e){c.innerHTML=banner()+card('Unable to load','The source returned an error',`<div class="empty"><b>${esc(e.message)}</b>Check access/session or the source connection and retry.</div>`)} }
async function renderCommand(){setTitle('Command Center');const d=await api('command-center');$('#content').innerHTML=banner()+`<div class="metrics">${metric('Issued invoice value','₹'+d.financial.issued_invoice_value,'Canonical invoice ledger')}${metric('Collected','₹'+d.financial.collected,'Successful recorded payments')}${metric('Receivables','₹'+d.financial.receivables,'Open invoice balances')}${metric('Needs attention',String(Object.values(d.attention).reduce((a,b)=>a+Number(b||0),0)),'Exceptions requiring review')}</div><div class="grid2">${card('Attention','Exception-driven administration',`<div class="list">${Object.entries(d.attention).map(([k,v])=>`<div class="item"><div><b>${esc(k.replaceAll('_',' '))}</b><small>Canonical exception count</small></div>${badge(v? 'ACTION_REQUIRED':'CLEAR')}</div>`).join('')}</div>`)}${card('Record coverage','Current authoritative Office records',`<div class="list">${Object.entries(d.records).map(([k,v])=>`<div class="item"><div><b>${esc(k)}</b><small>Canonical record count</small></div><strong>${v}</strong></div>`).join('')}</div>`)}</div>`}
async function renderProducts(){setTitle('Products');products=await api('products');$('#content').innerHTML=banner()+card('Product Registry','All products use shared corporate/commercial controls',table(['Code','Product','Category','Status'],products.map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${badge(x.status)}</td></tr>`)),'<button class="primary" onclick="window.KO.createProduct()">+ Product</button>')}
async function renderCustomers(){setTitle('Customers');customers=await api('customers');$('#content').innerHTML=banner()+card('Customer Master','Canonical legal/commercial identity across products',table(['Customer','GSTIN','State','Country','Status'],customers.map(x=>`<tr><td><b>${esc(x.legal_name)}</b><br><small>${esc(x.id)}</small></td><td>${esc(x.gstin||'—')}</td><td>${esc(x.state)} (${esc(x.state_code)})</td><td>${esc(x.country)}</td><td>${badge(x.status)}</td></tr>`)),'<button class="primary" onclick="window.KO.createCustomer()">+ Customer</button>')}
async function renderPlans(){setTitle('Commercial');const rows=await api('commercial/plans');$('#content').innerHTML=banner()+card('Plans & price versions','Shared commercial catalog; historical versions remain explicit',table(['Plan','Product','Cycle','Price','GST','Effective','Status'],rows.map(x=>`<tr><td><b>${esc(x.code)}</b><br>${esc(x.name)}</td><td>${esc(products.find(p=>p.id===x.product_id)?.name||x.product_id)}</td><td>${esc(x.billing_cycle)}</td><td>₹${esc(x.price)}</td><td>${esc(x.gst_rate)}%</td><td>${esc(x.effective_from)}</td><td>${badge(x.status)}</td></tr>`)),'<button class="primary" onclick="window.KO.createPlan()">+ Plan</button>')}
async function renderInvoices(){setTitle('Billing');const rows=await api('invoices');$('#content').innerHTML=banner()+card('Invoices','Immutable billing snapshots with tax and verification hash',table(['Invoice','Customer','Product','Taxable','Tax','Total','Balance','Status'],rows.map(x=>`<tr class="clickable" onclick="window.KO.invoice('${x.id}')"><td><b>${esc(x.invoice_no)}</b><br><small>${esc(x.issued_at.slice(0,10))}</small></td><td>${esc(customers.find(c=>c.id===x.customer_id)?.legal_name||x.customer_id)}</td><td>${esc(products.find(p=>p.id===x.product_id)?.name||x.product_id)}</td><td>₹${esc(x.net_taxable)}</td><td>₹${(Number(x.cgst)+Number(x.sgst)+Number(x.igst)).toFixed(2)}</td><td><b>₹${esc(x.total)}</b></td><td>₹${esc(x.balance)}</td><td>${badge(x.status)}</td></tr>`)),'<button class="primary" onclick="window.KO.createInvoice()">+ Invoice</button>')}
async function renderTax(){setTitle('GST & Tax');const x=await api('tax/gst/summary');$('#content').innerHTML=banner()+`<div class="metrics">${metric('Taxable','₹'+x.taxable_value,'Issued invoices')}${metric('CGST','₹'+x.cgst,'Working register')}${metric('SGST','₹'+x.sgst,'Working register')}${metric('IGST','₹'+x.igst,'Working register')}</div>`+card('Control state','Tax filings remain a review/filing workflow',`<div class="empty"><b>Working summary only</b>Production GST filing is not marked complete unless actual filing evidence is ingested and locked.</div>`)}
async function renderAccounting(){setTitle('Accounting');const x=await api('accounting/trial-balance');$('#content').innerHTML=banner()+`<div class="metrics">${metric('Total debit','₹'+x.total_debit,'Operational ledger')}${metric('Total credit','₹'+x.total_credit,'Operational ledger')}${metric('Balance',x.balanced?'Balanced':'Out of balance','Control check')}${metric('Accounts',String(x.accounts.length),'Active ledger accounts')}</div>`+card('Trial Balance','Every number drills to source journals in the API',table(['Code','Account','Debit','Credit','Net'],x.accounts.map(a=>`<tr><td>${esc(a.code)}</td><td>${esc(a.name)}</td><td>₹${esc(a.debit)}</td><td>₹${esc(a.credit)}</td><td>₹${esc(a.net)}</td></tr>`)))}
async function renderBanking(){setTitle('Banking');const rows=await api('banking/transactions');$('#content').innerHTML=banner()+card('Bank Transactions','Imported/source transactions and reconciliation state',table(['Date','Direction','Amount','Reference','Source','Match'],rows.map(x=>`<tr><td>${esc(x.transaction_date)}</td><td>${badge(x.direction)}</td><td>₹${esc(x.amount)}</td><td>${esc(x.reference)}</td><td>${esc(x.source)}</td><td>${badge(x.match_status)}</td></tr>`)))}
async function renderGovernance(){setTitle('Governance');const rows=await api('governance/meetings');$('#content').innerHTML=banner()+card('Board Meetings','Meeting → resolution → CTC → authority → audit',table(['Meeting','Date','Title','Status'],rows.map(x=>`<tr><td><b>${esc(x.meeting_no)}</b></td><td>${esc(x.meeting_date)}</td><td>${esc(x.title)}</td><td>${badge(x.status)}</td></tr>`)))}
async function renderDocuments(){setTitle('Documents');const rows=await api('documents');$('#content').innerHTML=banner()+card('Controlled Document Vault','Versioned, hashed and lockable evidence',table(['Document','Type','Area','Version','SHA-256','Status'],rows.map(x=>`<tr><td><b>${esc(x.title)}</b><br><small>${esc(x.filename||'')}</small></td><td>${esc(x.document_type)}</td><td>${esc(x.area)}</td><td>v${x.current_version}</td><td><code>${esc((x.sha256||'').slice(0,18))}${x.sha256?'…':''}</code></td><td>${badge(x.locked?'LOCKED':x.status)}</td></tr>`)))}
async function renderNotices(){setTitle('Notices');const rows=await api('notices');$('#content').innerHTML=banner()+card('Authority / Government Notices','Deadline-driven controlled response cases',table(['Authority','Reference','Title','Received','Due','Risk','Status'],rows.map(x=>`<tr><td>${esc(x.authority)}</td><td><b>${esc(x.reference_no)}</b></td><td>${esc(x.title)}</td><td>${esc(x.received_date)}</td><td>${esc(x.response_due_date||'—')}</td><td>${badge(x.risk)}</td><td>${badge(x.status)}</td></tr>`)),'<button class="primary" onclick="window.KO.createNotice()">+ Notice</button>')}
async function renderInspections(){setTitle('Audit & Inspection');const rows=await api('inspections');$('#content').innerHTML=banner()+card('Inspection Rooms','Scope-limited evidence workspaces; never general admin access',table(['Authority','Reference','Scope','Period','Status','Readiness'],rows.map(x=>`<tr><td>${esc(x.authority)}</td><td>${esc(x.reference_no||'—')}</td><td>${esc(x.scope_text)}</td><td>${esc(x.period_start||'—')} → ${esc(x.period_end||'—')}</td><td>${badge(x.status)}</td><td>${badge(x.manifest?.readiness||'NOT_BUILT')}</td></tr>`)))}
async function renderApprovals(){setTitle('Approvals');const rows=await api('approvals');$('#content').innerHTML=banner()+card('Maker-Checker Approvals','High-risk actions require independent approval',table(['Action','Entity','Requested By','Required Role','Status','Decision'],rows.map(x=>`<tr><td><b>${esc(x.action_type)}</b></td><td>${esc(x.entity_type)} · ${esc(x.entity_id)}</td><td>${esc(x.requested_by)}</td><td>${esc(x.required_role)}</td><td>${badge(x.status)}</td><td>${esc(x.decided_by||'—')}</td></tr>`)))}
async function renderIntegrations(){setTitle('Integrations');const rows=await api('integrations');$('#content').innerHTML=banner()+card('Integration Registry','Registry stores references/status; raw secrets are rejected',table(['Provider','Type','Environment','Owner','Status'],rows.map(x=>`<tr><td><b>${esc(x.provider)}</b></td><td>${esc(x.integration_type)}</td><td>${esc(x.environment)}</td><td>${esc(x.owner||'—')}</td><td>${badge(x.status)}</td></tr>`)))}
async function renderGeneric(path){const names={compliance:'Compliance',contracts:'Contracts',vendors:'Vendors',people:'People',assets:'Assets',audit:'Audit Trail'};setTitle(names[path]||'KRAVIA Office');const rows=await api(path);const keys=rows[0]?Object.keys(rows[0]).filter(k=>!['created_at'].includes(k)).slice(0,7):[];$('#content').innerHTML=banner()+card(names[path]||path,'Canonical records',table(keys.map(k=>k.replaceAll('_',' ')),rows.map(x=>`<tr>${keys.map(k=>`<td>${typeof x[k]==='object'?esc(JSON.stringify(x[k])):esc(x[k]??'—')}</td>`).join('')}</tr>`)))}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalWrap').hidden=false}function closeModal(){$('#modalWrap').hidden=true}function closeDrawer(){$('#drawerWrap').hidden=true;if(window._blob)URL.revokeObjectURL(window._blob)}
function form(fields,submit){return `<form id="actionForm"><div class="formGrid">${fields.join('')}</div><div class="formActions"><button type="button" class="ghost" onclick="document.querySelector('#modalClose').click()">Cancel</button><button class="primary">${submit}</button></div></form>`}function fld(name,label,type='text',extra='',full=false){return `<div class="field ${full?'full':''}"><label>${label}</label><input name="${name}" type="${type}" ${extra}></div>`}function sel(name,label,opts){return `<div class="field"><label>${label}</label><select name="${name}">${opts.map(o=>`<option value="${esc(o[0])}">${esc(o[1])}</option>`).join('')}</select></div>`}
function wire(handler){$('#actionForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());try{await handler(d);closeModal();await preload();await render();toast('Completed and recorded in KRAVIA Office')}catch(err){toast(err.message)}}}
function sessionModal(){const s=session();openModal('Session & access',form([fld('actor','Actor','text',`value="${esc(s.actor)}"`),sel('role','Role',['OWNER','DIRECTOR','FINANCE','CA','CS','LEGAL','HR','OPERATIONS','AUDITOR','PRODUCT_ADMIN'].map(x=>[x,x])),fld('key','Development bootstrap key','password','autocomplete="off"')],'Save session'));document.querySelector('[name=role]').value=s.role;wire(async d=>{sessionStorage.setItem('ko_actor',d.actor);sessionStorage.setItem('ko_role',d.role);sessionStorage.setItem('ko_key',d.key||'')})}
function commandModal(){openModal('Command palette',form([fld('query','Go to module','text','placeholder="billing, governance, documents…"',true)],'Open'));wire(async d=>{const q=d.query.toLowerCase();const hit=NAV.flatMap(x=>x[1]).find(x=>x[1].toLowerCase().includes(q)||x[0].includes(q));if(!hit)throw new Error('No matching module');route=hit[0];location.hash=route;renderNav()})}
function createForRoute(){({products:createProduct,customers:createCustomer,'commercial/plans':createPlan,invoices:createInvoice,notices:createNotice}[route]||(()=>toast('Use the module-specific controlled workflow for this record.')))()}
function createProduct(){openModal('Add product',form([fld('code','Product code','text','required maxlength="5"'),fld('name','Product name','text','required'),fld('category','Category','text','required',true)],'Create product'));wire(d=>api('products',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(d)}))}
function createCustomer(){openModal('Add customer',form([fld('legal_name','Legal name','text','required',true),fld('state','State','text','required'),fld('state_code','State code','text','required pattern="[0-9]{2}"'),fld('gstin','GSTIN','text','maxlength="15"'),fld('billing_address','Billing address','text','',true)],'Create customer'));wire(d=>api('customers',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({...d,gstin:d.gstin||null})}))}
function createPlan(){openModal('Create plan',form([sel('product_id','Product',products.map(x=>[x.id,`${x.code} — ${x.name}`])),fld('code','Plan code','text','required'),fld('name','Plan name','text','required'),sel('billing_cycle','Billing cycle',[['MONTHLY','Monthly'],['ANNUAL','Annual'],['ONE_TIME','One-time'],['USAGE','Usage']]),fld('price','Price','number','required min="0" step="0.01"'),fld('gst_rate','GST rate %','number','value="18" min="0" max="100" step="0.01"'),fld('sac','SAC','text'),fld('effective_from','Effective from','date','required')],'Create plan'));wire(d=>api('commercial/plans',{method:'POST',body:JSON.stringify(d)}))}
function createInvoice(){openModal('Issue invoice',form([sel('customer_id','Customer',customers.map(x=>[x.id,x.legal_name])),sel('product_id','Product',products.map(x=>[x.id,`${x.code} — ${x.name}`])),fld('description','Description','text','required',true),fld('sac','SAC','text'),fld('taxable_value','Taxable value','number','required min="0.01" step="0.01"'),fld('discount','Discount','number','value="0" min="0" step="0.01"'),fld('gst_rate','GST rate %','number','value="18" min="0" max="100" step="0.01"'),fld('due_date','Due date','date')],'Issue invoice'));wire(d=>api('invoices',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({...d,qty:'1'})}))}
function createNotice(){openModal('Register notice',form([fld('authority','Authority','text','required'),fld('reference_no','Reference number','text','required'),fld('title','Title','text','required',true),fld('received_date','Received date','date','required'),fld('response_due_date','Response due','date'),sel('risk','Risk',[['HIGH','High'],['CRITICAL','Critical'],['MEDIUM','Medium'],['LOW','Low']]),fld('owner','Owner','text')],'Register notice'));wire(d=>api('notices',{method:'POST',body:JSON.stringify(d)}))}
async function invoice(id){const inv=(await api('invoices')).find(x=>x.id===id);if(!inv)return;$('#drawerTitle').textContent=inv.invoice_no;$('#drawerKicker').textContent='Tax invoice';$('#drawerBody').innerHTML=`${Object.entries(inv).filter(([k])=>!['snapshot'].includes(k)).map(([k,v])=>`<div class="kv"><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}<div class="formActions"><button id="pdfBtn" class="primary">Preview PDF</button></div><div id="pdfMount"></div>`;$('#drawerWrap').hidden=false;$('#pdfBtn').onclick=async()=>{try{const r=await fetch(`/api/v1/invoices/${id}/pdf`,{headers:headers()});if(!r.ok)throw new Error('Unable to load PDF');const b=await r.blob();window._blob=URL.createObjectURL(b);$('#pdfMount').innerHTML=`<iframe class="docFrame" sandbox="allow-downloads" src="${window._blob}"></iframe>`}catch(e){toast(e.message)}}}
window.KO={createProduct,createCustomer,createPlan,createInvoice,createNotice,invoice};
init();
