const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const session=()=>({actor:sessionStorage.getItem('ko_actor')||'Office Owner',role:sessionStorage.getItem('ko_role')||'OWNER',key:sessionStorage.getItem('ko_key')||''});
const idem=()=>`ko-${Date.now()}-${Array.from(crypto.getRandomValues(new Uint32Array(2))).map(x=>x.toString(16)).join('')}`;
let view='overview',state={summary:null,classes:[],holders:[],policies:[],expenses:[],mandates:[],calls:[],instructions:[],approvals:[],vendors:[],readiness:null};
function headers(extra={}){const s=session(),h={'Content-Type':'application/json','X-Office-Actor':s.actor,'X-Office-Role':s.role,...extra};if(s.key)h['X-Kravia-Office-Key']=s.key;return h}
async function api(path,opts={}){const r=await fetch('/api/v1/'+path,{...opts,headers:headers(opts.headers||{})});const ct=r.headers.get('content-type')||'';const body=ct.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(body?.detail||body||`HTTP ${r.status}`);return body}
function toast(message){const e=document.createElement('div');e.className='toast';e.textContent=message;$('#toast').append(e);setTimeout(()=>e.remove(),3800)}
function badge(value){const s=String(value||'').toUpperCase(),c=/ACTIVE|APPROVED|POSTED|PAID|SUCCEEDED|FUNDED|READY|CONNECTED/.test(s)?'good':/FAILED|REJECTED|CANCELLED|EXPIRED/.test(s)?'bad':/PENDING|DRAFT|PROCESSING|PARTIAL|SCHEDULED|ISSUED/.test(s)?'warn':'info';return `<span class="badge ${c}">${esc(s.replaceAll('_',' '))}</span>`}
function table(headers,rows){return `<div class="tableWrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}"><div class="empty"><b>No records yet</b>Only canonical Office records are shown.</div></td></tr>`}</tbody></table></div>`}
function card(title,sub,body,action=''){return `<section class="card"><div class="cardHead"><div><h2>${esc(title)}</h2><p>${esc(sub||'')}</p></div>${action}</div><div class="cardBody">${body}</div></section>`}
function metric(label,value,detail){return `<div class="metric"><label>${esc(label)}</label><strong>${esc(value)}</strong><small>${esc(detail||'')}</small></div>`}
function holderName(id){return state.holders.find(x=>x.id===id)?.legal_name||id||'—'}
function className(id){return state.classes.find(x=>x.id===id)?.code||id||'—'}
function vendorName(id){return state.vendors.find(x=>x.id===id)?.legal_name||id||'—'}
function field(label,name,type='text',value='',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" ${extra}></label>`}
function selectField(label,name,items,required=true){return `<label class="field"><span>${esc(label)}</span><select name="${esc(name)}" ${required?'required':''}><option value="">Select…</option>${items.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`}
function dialog(title,body,onSubmit){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;const form=$('#dialogForm');form.onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(form));$('#dialog').close();await refresh();toast('Saved')}catch(err){toast(err.message)}};$('#dialog').showModal()}
function jsonForm(fd){return Object.fromEntries([...fd.entries()].filter(([,v])=>v!==''))}
function post(path,body,withIdem=false){const opts={method:'POST',body:JSON.stringify(body)};if(withIdem)opts.headers={'Idempotency-Key':idem()};return api(path,opts)}
async function load(path,fallback){try{return await api(path)}catch(e){console.warn(path,e);return fallback}}
async function refresh(){
  const [summary,classes,holders,policies,expenses,mandates,calls,instructions,approvals,vendors,readiness]=await Promise.all([
    load('ownership/summary',null),load('ownership/share-classes',[]),load('ownership/shareholders',[]),load('finance/funding-policies',[]),load('finance/expenses',[]),load('finance/mandates',[]),load('finance/contribution-calls',[]),load('finance/payment-instructions',[]),load('approvals',[]),load('vendors',[]),load('finance/readiness',null)
  ]);
  Object.assign(state,{summary,classes,holders,policies,expenses,mandates,calls,instructions,approvals,vendors,readiness});render()
}
function readinessPanel(){const r=state.readiness;if(!r)return '<div class="dangerNote">Finance readiness endpoint is unavailable. Payment execution remains unverified.</div>';return `<div class="statusBlock">
  <div class="statusRow"><div><b>Execution mode</b><small>Production defaults to disabled until external configuration is complete.</small></div>${badge(r.execution_mode)}</div>
  <div class="statusRow"><div><b>Sandbox</b><small>Deterministic QA payment execution.</small></div>${badge(r.sandbox_ready?'READY':'OFF')}</div>
  <div class="statusRow"><div><b>Live payout credentials</b><small>Only presence is reported; secret values are never returned.</small></div>${badge(r.live_payout_credentials_configured?'CONFIGURED':'NOT_CONFIGURED')}</div>
  <div class="statusRow"><div><b>RazorpayX registry</b><small>Live execution also requires an operational integration record.</small></div>${badge(r.live_payout_registry_ready?'READY':'NOT_READY')}</div>
  <div class="statusRow"><div><b>Variable recurring collection</b><small>Fail-closed until merchant use-case/provider adapter approval.</small></div>${badge(r.live_variable_collection)}</div>
</div>`}
function renderOverview(){const s=state.summary||{total_issued_shares:0,cap_table:[]};const outstanding=state.expenses.filter(x=>!['PAID','CANCELLED'].includes(x.status)).reduce((a,x)=>a+Number(x.amount||0),0);const pending=state.approvals.filter(x=>x.status==='PENDING').length;const paymentAttention=state.instructions.filter(x=>['PENDING_APPROVAL','APPROVED','PROCESSING','FAILED'].includes(x.status)).length;$('#content').innerHTML=`<div class="banner"><b>Ownership ≠ funding ≠ payments</b><span>Each ledger is controlled independently and reconciles through evidence and approvals.</span></div><div class="metrics">${metric('Issued shares',String(s.total_issued_shares),'Append-only ownership ledger')}${metric('Open expenses',money(outstanding),'Approved/pending corporate obligations')}${metric('Pending approvals',String(pending),'Independent maker-checker queue')}${metric('Payment attention',String(paymentAttention),'Instructions not in final success state')}</div><div class="grid2">${card('Finance readiness','Live execution stays fail-closed',readinessPanel())}${card('Cap table','Derived only from posted share ledger',table(['Shareholder','Shares','Ownership'],s.cap_table.map(x=>`<tr><td><b>${esc(x.shareholder.legal_name)}</b><br><small>${esc(x.shareholder.shareholder_no)}</small></td><td>${esc(x.shares)}</td><td>${esc(x.ownership_percent)}%</td></tr>`)))}</div>`}
function renderOwnership(){const s=state.summary||{classes:[],cap_table:[]};$('#content').innerHTML=`<div class="controlStrip"><button class="primary" data-create="shareholder">+ Shareholder</button><button class="ghost" data-create="shareclass">+ Share class</button><button class="ghost" data-create="sharechange">Stage issue/adjustment</button><button class="ghost" data-create="transfer">Stage transfer</button></div>${card('Cap table','Computed from immutable posted ledger entries',table(['Shareholder','Shares','Ownership','Class balances'],s.cap_table.map(x=>`<tr><td><b>${esc(x.shareholder.legal_name)}</b><br><small>${esc(x.shareholder.shareholder_no)}</small></td><td>${esc(x.shares)}</td><td>${esc(x.ownership_percent)}%</td><td class="mono">${esc(JSON.stringify(x.by_class))}</td></tr>`)))}${card('Share classes','Authorised versus issued shares',table(['Code','Name','Face value','Authorised','Issued','Status'],(s.classes||[]).map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${money(x.face_value)}</td><td>${esc(x.authorised_shares)}</td><td>${esc(x.issued_shares)}</td><td>${badge(x.status)}</td></tr>`)))}<div class="twoCol">${card('Pending share changes','Approval then posting',table(['Type','Holder','Quantity','Status','Action'],state.approvals.filter(x=>x.entity_type==='share_change').slice(0,20).map(x=>`<tr><td>${esc(x.action_type)}</td><td>${esc(x.entity_id)}</td><td>—</td><td>${badge(x.status)}</td><td>${x.status==='APPROVED'?`<button class="ghost" data-post-share="${esc(x.entity_id)}">Post</button>`:'—'}</td></tr>`)))}${card('Transfers','Atomic debit + credit after approval',table(['Transfer','Status','Action'],state.approvals.filter(x=>x.entity_type==='share_transfer').slice(0,20).map(x=>`<tr><td>${esc(x.entity_id)}</td><td>${badge(x.status)}</td><td>${x.status==='APPROVED'?`<button class="ghost" data-post-transfer="${esc(x.entity_id)}">Post</button>`:'—'}</td></tr>`)))}</div>`}
function renderFunding(){const allocationRows=state.calls.flatMap(call=>call.allocations.map(a=>`<tr><td><b>${esc(call.id)}</b><br><small>${badge(call.status)}</small></td><td>${esc(holderName(a.shareholder_id))}</td><td>${money(a.amount)}</td><td>${money(a.collected)}</td><td>${badge(a.status)}</td><td>${a.status!=='COLLECTED'?`<button class="ghost" data-schedule="${esc(a.id)}">Schedule</button>`:'—'}</td></tr>`));$('#content').innerHTML=`<div class="controlStrip"><button class="primary" data-create="policy">+ Funding policy</button><button class="ghost" data-create="call">+ Contribution call</button></div>${card('Funding policies','Separate from legal ownership; custom weights require exactly 10,000 bps',table(['Policy','Basis','Frequency','Maximum call','Status'],state.policies.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.allocation_basis)}</td><td>${esc(x.frequency)}</td><td>${x.max_call?money(x.max_call):'—'}</td><td>${badge(x.status)}</td></tr>`)))}${card('Contribution allocations','Exact paise allocation and collection state',table(['Call','Shareholder','Allocated','Collected','Status','Action'],allocationRows))}`}
function renderExpenses(){const rows=state.expenses.map(x=>`<tr><td><b>${esc(x.reference)}</b><br><small>${esc(x.title)}</small></td><td>${esc(vendorName(x.vendor_id))}</td><td>${esc(x.category)}</td><td>${money(x.amount)}</td><td>${esc(x.funding_mode)}</td><td>${badge(x.status)}</td><td>${x.status==='PENDING_APPROVAL'?'<span class="muted">Approve in queue</span>':x.status==='APPROVED'&&x.vendor_id?`<button class="ghost" data-create-payout="${esc(x.id)}">Payout</button>`:'—'}</td></tr>`);$('#content').innerHTML=`<div class="controlStrip"><button class="primary" data-create="expense">+ Expense</button></div>${card('Expense obligations','Bills and obligations require evidence and independent approval before payment',table(['Reference','Vendor','Category','Amount','Funding','Status','Next'],rows))}`}
function renderMandates(){const rows=state.mandates.map(x=>`<tr><td>${esc(holderName(x.shareholder_id))}</td><td><b>${esc(x.provider)}</b></td><td>${esc(x.purpose)}</td><td>${money(x.max_amount)}</td><td>${esc(x.frequency)}</td><td>${badge(x.status)}</td><td class="miniActions">${x.status==='DRAFT'?`<button class="ghost" data-activate-mandate="${esc(x.id)}">Activate</button>`:''}${x.status==='ACTIVE'?`<button class="ghost" data-cancel-mandate="${esc(x.id)}">Cancel</button>`:''}</td></tr>`);$('#content').innerHTML=`<div class="controlStrip"><button class="primary" data-create="mandate">+ Mandate</button></div><div class="dangerNote">KRAVIA Office never asks for or stores a bank password, OTP or UPI PIN. Mandates store provider references and consent state only.</div><br>${card('Authorised mandates','Limits and validity are rechecked immediately before execution',table(['Shareholder','Provider','Purpose','Maximum','Frequency','Status','Action'],rows))}`}
function renderPayments(){const rows=state.instructions.map(x=>`<tr><td><b>${esc(x.direction)}</b><br><small>${esc(x.id)}</small></td><td>${money(x.amount)}</td><td>${esc(x.provider)}</td><td>${badge(x.status)}</td><td>${esc(x.provider_reference||'—')}</td><td class="miniActions">${x.status==='PENDING_APPROVAL'?'<span class="muted">Approval required</span>':''}${x.status==='APPROVED'?`<button class="primary" data-execute="${esc(x.id)}">Execute</button>`:''}</td></tr>`);$('#content').innerHTML=`<div class="controlStrip"><button class="primary" data-create="payout">+ Vendor payout</button><button class="ghost" id="runDue">Run due approved</button></div>${card('Payment instructions','Idempotent controlled collections and payouts',table(['Direction','Amount','Provider','Status','Provider ref','Action'],rows))}`}
function renderApprovals(){const rows=state.approvals.map(x=>`<tr><td><b>${esc(x.action_type)}</b><br><small>${esc(x.entity_type)} · ${esc(x.entity_id)}</small></td><td>${esc(x.requested_by)}</td><td>${esc(x.required_role)}</td><td>${badge(x.status)}</td><td class="miniActions">${x.status==='PENDING'?`<button class="primary" data-approve="${esc(x.id)}">Approve</button><button class="ghost" data-reject="${esc(x.id)}">Reject</button>`:esc(x.decided_by||'—')}</td></tr>`);$('#content').innerHTML=card('Maker-checker approvals','Requester cannot approve their own high-risk action',table(['Action','Requested by','Required role','Status','Decision'],rows))}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#title').textContent=({overview:'Finance & Ownership',ownership:'Ownership register',funding:'Expense funding',expenses:'Company expenses',mandates:'Mandates',payments:'Payments',approvals:'Approvals'})[view]||'Finance & Ownership';if(view==='overview')renderOverview();if(view==='ownership')renderOwnership();if(view==='funding')renderFunding();if(view==='expenses')renderExpenses();if(view==='mandates')renderMandates();if(view==='payments')renderPayments();if(view==='approvals')renderApprovals();bindActions()}
function formActions(){return `<div class="formActions"><button type="button" class="ghost" id="dialogCancel">Cancel</button><button class="primary" type="submit">Save</button></div>`}
function create(kind){
  if(kind==='shareholder')return dialog('Create shareholder',`<div class="formGrid">${field('Shareholder no','shareholder_no')}${field('Legal name','legal_name')}${field('Folio no','folio_no')}${field('Email','email','email')}${field('Evidence reference','source_document_ref')}</div>${formActions()}`,fd=>post('ownership/shareholders',jsonForm(fd)));
  if(kind==='shareclass')return dialog('Create share class',`<div class="formGrid">${field('Code','code')}${field('Name','name')}${field('Face value ₹','face_value','number','10','step="0.01" min="0.01" required')}${field('Authorised shares','authorised_shares','number','','min="0" required')}${field('Evidence reference','source_document_ref')}</div>${formActions()}`,fd=>{const o=jsonForm(fd);o.authorised_shares=Number(o.authorised_shares);return post('ownership/share-classes',o)});
  if(kind==='sharechange')return dialog('Stage share issue / adjustment',`<div class="formGrid">${selectField('Shareholder','shareholder_id',state.holders.map(x=>[x.id,x.legal_name]))}${selectField('Share class','share_class_id',state.classes.map(x=>[x.id,`${x.code} · ${x.name}`]))}${selectField('Entry type','entry_type',[['ISSUE','Issue'],['CANCEL','Cancel'],['ADJUSTMENT_IN','Adjustment in'],['ADJUSTMENT_OUT','Adjustment out']])}${field('Quantity delta','quantity_delta','number','','required')}${field('Instrument date','instrument_date','date','','required')}${field('Certificate no','certificate_no')}${field('Evidence reference','source_document_ref')}${field('Note','note')}</div>${formActions()}`,fd=>{const o=jsonForm(fd);o.quantity_delta=Number(o.quantity_delta);return post('ownership/share-changes',o,true)});
  if(kind==='transfer')return dialog('Stage share transfer',`<div class="formGrid">${selectField('From shareholder','from_shareholder_id',state.holders.map(x=>[x.id,x.legal_name]))}${selectField('To shareholder','to_shareholder_id',state.holders.map(x=>[x.id,x.legal_name]))}${selectField('Share class','share_class_id',state.classes.map(x=>[x.id,`${x.code} · ${x.name}`]))}${field('Quantity','quantity','number','','min="1" required')}${field('Instrument date','instrument_date','date','','required')}${field('Evidence reference','source_document_ref')}${field('Note','note')}</div>${formActions()}`,fd=>{const o=jsonForm(fd);o.quantity=Number(o.quantity);return post('ownership/transfers',o,true)});
  if(kind==='policy')return dialog('Create funding policy',`<div class="formGrid">${field('Policy name','name')}${selectField('Allocation basis','allocation_basis',[['OWNERSHIP','Current ownership'],['CUSTOM_WEIGHTS','Custom weights']])}${field('Frequency','frequency','text','AS_NEEDED')}${field('Maximum call ₹','max_call','number','','step="0.01" min="0.01"')}${field('Custom weights JSON','custom_weights','text','{}')}${field('Evidence reference','source_document_ref')}</div><div class="goodNote">Custom weights use shareholder IDs mapped to basis points and must total exactly 10,000.</div>${formActions()}`,fd=>{const o=jsonForm(fd);try{o.custom_weights=JSON.parse(o.custom_weights||'{}')}catch{throw new Error('Custom weights must be valid JSON')}delete o.custom_weights_json;return post('finance/funding-policies',o)});
  if(kind==='expense')return dialog('Create expense',`<div class="formGrid">${selectField('Vendor','vendor_id',state.vendors.map(x=>[x.id,x.legal_name]),false)}${field('Reference','reference')}${field('Title','title')}${field('Category','category')}${field('Amount ₹','amount','number','','step="0.01" min="0.01" required')}${field('Due date','due_date','date')}${selectField('Funding mode','funding_mode',[['COMPANY_FUNDS','Company funds'],['SHAREHOLDER_CONTRIBUTION','Shareholder contribution']])}${selectField('Funding policy','funding_policy_id',state.policies.filter(x=>x.status==='ACTIVE').map(x=>[x.id,x.name]),false)}${field('Evidence reference','source_document_ref')}${field('Note','note')}</div>${formActions()}`,fd=>post('finance/expenses',jsonForm(fd),true));
  if(kind==='mandate')return dialog('Create mandate',`<div class="formGrid">${selectField('Shareholder','shareholder_id',state.holders.map(x=>[x.id,x.legal_name]))}${field('Provider','provider','text','SANDBOX')}${field('Purpose','purpose','text','Approved KRAVIA expense contribution')}${field('Maximum amount ₹','max_amount','number','','step="0.01" min="0.01" required')}${field('Frequency','frequency','text','AS_NEEDED')}${field('Valid from','valid_from','date')}${field('Valid until','valid_until','date')}${field('Evidence reference','source_document_ref')}</div>${formActions()}`,fd=>post('finance/mandates',jsonForm(fd)));
  if(kind==='call')return dialog('Issue contribution call',`<div class="formGrid">${selectField('Approved shareholder-funded expense','expense_id',state.expenses.filter(x=>x.status==='APPROVED'&&x.funding_mode==='SHAREHOLDER_CONTRIBUTION').map(x=>[x.id,`${x.reference} · ${money(x.amount)}`]))}${field('Due date','due_date','date')}</div>${formActions()}`,fd=>post('finance/contribution-calls',jsonForm(fd)));
  if(kind==='payout')return openPayout();
}
function openPayout(expenseId=''){dialog('Stage vendor payout',`<div class="formGrid">${selectField('Approved vendor expense','expense_id',state.expenses.filter(x=>x.status==='APPROVED'&&x.vendor_id).map(x=>[x.id,`${x.reference} · ${money(x.amount)}`]))}${field('Provider','provider','text','SANDBOX')}${field('Provider destination reference','provider_destination_ref')}${field('Amount ₹ (optional)','amount','number','','step="0.01" min="0.01"')}${field('Schedule (optional)','scheduled_for','datetime-local')}</div><div class="dangerNote">Use only provider fund-account / destination references. Never enter bank passwords, OTPs or UPI PINs.</div>${formActions()}`,fd=>{const o=jsonForm(fd);if(expenseId)o.expense_id=expenseId;if(o.scheduled_for)o.scheduled_for=new Date(o.scheduled_for).toISOString();return post('finance/payouts',o,true)});if(expenseId){const sel=$('#dialogBody select[name="expense_id"]');if(sel)sel.value=expenseId}}
function openSchedule(allocationId){dialog('Schedule authorised collection',`<div class="formGrid">${selectField('Active mandate','mandate_id',state.mandates.filter(x=>x.status==='ACTIVE').map(x=>[x.id,`${holderName(x.shareholder_id)} · ${x.provider} · ${money(x.max_amount)}`]))}${field('Schedule (optional)','scheduled_for','datetime-local')}</div>${formActions()}`,fd=>{const o=jsonForm(fd);if(o.scheduled_for)o.scheduled_for=new Date(o.scheduled_for).toISOString();return post(`finance/contribution-allocations/${allocationId}/schedule`,o,true)})}
function sessionDialog(){const s=session();dialog('Session & access',`<div class="formGrid">${field('Actor','actor','text',s.actor)}${selectField('Role','role',['OWNER','DIRECTOR','FINANCE','CA','CS','LEGAL','HR','OPERATIONS','AUDITOR','PRODUCT_ADMIN'].map(x=>[x,x]))}${field('Development bootstrap key','key','password',s.key)}</div><div class="dangerNote">Bootstrap authentication is development-only. Production startup requires OIDC.</div>${formActions()}`,async fd=>{const o=jsonForm(fd);sessionStorage.setItem('ko_actor',o.actor||'Office Owner');sessionStorage.setItem('ko_role',o.role||'OWNER');sessionStorage.setItem('ko_key',o.key||'')});setTimeout(()=>{const sel=$('#dialogBody select[name="role"]');if(sel)sel.value=s.role},0)}
function bindActions(){document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>create(b.dataset.create));document.querySelectorAll('[data-create-payout]').forEach(b=>b.onclick=()=>openPayout(b.dataset.createPayout));document.querySelectorAll('[data-schedule]').forEach(b=>b.onclick=()=>openSchedule(b.dataset.schedule));document.querySelectorAll('[data-post-share]').forEach(b=>b.onclick=()=>act(`ownership/share-changes/${b.dataset.postShare}/post`));document.querySelectorAll('[data-post-transfer]').forEach(b=>b.onclick=()=>act(`ownership/transfers/${b.dataset.postTransfer}/post`));document.querySelectorAll('[data-execute]').forEach(b=>b.onclick=()=>act(`finance/payment-instructions/${b.dataset.execute}/execute`));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>decision(b.dataset.approve,'approve'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>decision(b.dataset.reject,'reject'));document.querySelectorAll('[data-activate-mandate]').forEach(b=>b.onclick=()=>act(`finance/mandates/${b.dataset.activateMandate}/activate`,{}));document.querySelectorAll('[data-cancel-mandate]').forEach(b=>b.onclick=()=>act(`finance/mandates/${b.dataset.cancelMandate}/cancel`));const run=$('#runDue');if(run)run.onclick=()=>act('finance/payment-instructions/run-due')}
async function act(path,body=null){try{await api(path,{method:'POST',body:body===null?undefined:JSON.stringify(body)});toast('Action completed');await refresh()}catch(e){toast(e.message)}}
async function decision(id,verb){try{await post(`approvals/${id}/${verb}`,{reason:`${verb==='approve'?'Approved':'Rejected'} in KRAVIA Office Finance & Ownership`});toast(`Approval ${verb}d`);await refresh()}catch(e){toast(e.message)}}
function init(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#refresh').onclick=refresh;$('#sessionBtn').onclick=sessionDialog;$('#createBtn').onclick=()=>create(({ownership:'shareholder',funding:'policy',expenses:'expense',mandates:'mandate',payments:'payout'})[view]||'expense');$('#dialogClose').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close()});document.addEventListener('click',e=>{if(e.target?.id==='dialogCancel')$('#dialog').close()});fetch('/health').then(r=>r.json()).then(j=>{$('#apiState').textContent=`API ${j.version} · ${j.status}`;$('#apiState').className='health ok'}).catch(()=>{$('#apiState').textContent='API unavailable';$('#apiState').className='health bad'});refresh()}
init();
