export const recruitFlowProduct = {
  id: "recruitflow",
  slug: "nicerole",
  name: "Nice Role",
  category: "Recruitment technology",
  description: "An accountable recruitment workspace for jobs, applications, candidate review, interviews, hiring decisions and recruiter analytics.",
  status: "BETA",
  public: true,
  href: "/products/nicerole",
  website: "https://nicerole.vmnexa.co.in",
  enquiryCategory: "Product enquiry · Nice Role — Recruitment operations platform",
  order: 2,
  seo: {
    title: "Nice Role | Recruitment Operations Platform by Kravia",
    description: "Nice Role is Kravia's recruitment operations platform for structured jobs, applications, candidate review, interviews, scorecards, human hiring decisions and analytics.",
  },
  hero: {
    eyebrow: "A PRODUCT BY KRAVIA PRIVATE LIMITED / RECRUITMENT TECHNOLOGY",
    title: "One accountable flow for modern hiring.",
    intro: "Nice Role brings jobs, applications, candidate evidence, interviews, scorecards, hiring outcomes and recruiter analytics into one structured workspace while keeping consequential decisions with authorised people.",
  },
  workflow: [
    "Create the company workspace",
    "Publish a structured role",
    "Receive candidate applications",
    "Review evidence and candidate history",
    "Move through hiring stages",
    "Schedule interviews and scorecards",
    "Record the human hiring decision",
    "Publish the candidate-facing outcome",
  ],
  capabilityGroups: [
    {
      title: "Jobs, applications and pipeline",
      summary: "Run the hiring lifecycle from structured role setup through application intake and configurable ATS stages.",
      capabilities: ["Job publishing", "Application questions", "ATS pipeline", "Bounded bulk actions"],
    },
    {
      title: "Candidate 360",
      summary: "Give recruiters one private view of candidate identity, application history, tags, notes, assignments and submitted evidence.",
      capabilities: ["Candidate directory", "Candidate 360", "Private notes", "Tags and assignment"],
    },
    {
      title: "Interview operations",
      summary: "Coordinate interview scheduling, updates, cancellations and structured scorecards without losing decision history.",
      capabilities: ["Interview scheduling", "Scorecards", "Rescheduling", "Cancellation history"],
    },
    {
      title: "Evidence-assisted matching",
      summary: "Use deterministic resume extraction and matching to organise evidence while keeping automated assistance separate from hiring authority.",
      capabilities: ["Resume extraction", "Structured matching", "Evidence display", "Human-decision boundary"],
    },
    {
      title: "Candidate experience",
      summary: "Support candidate job discovery, applications, interview visibility, notifications, privacy choices and account support across web and mobile.",
      capabilities: ["Candidate mobile", "Application status", "Notifications", "Privacy and deletion"],
    },
    {
      title: "Recruiter analytics and operations",
      summary: "Track hiring activity, funnel movement, interviews, outcomes and platform usage from recorded product events and authoritative data.",
      capabilities: ["Hiring analytics", "Funnel reporting", "Operational visibility", "Subscription state"],
    },
  ],
  audiences: [
    "Growing companies",
    "Recruitment teams",
    "Talent acquisition teams",
    "HR teams",
    "Recruitment agencies",
    "Multi-location hiring operations",
  ],
  principles: [
    ["Private candidate records", "Candidate profiles and reusable resumes stay private by default and are shared through supported recruitment flows."],
    ["Human-controlled decisions", "Extraction and matching can organise evidence, but Nice Role does not independently hire, reject or disqualify a candidate."],
    ["Tenant-aware access", "Company data and recruiter actions are governed by server-side tenancy, roles and permissions rather than browser visibility."],
    ["Application snapshots", "An application preserves the submitted candidate and resume context so later profile edits do not silently rewrite history."],
  ],
  faqs: [
    ["What is Nice Role?", "Nice Role is a recruitment operations platform from Kravia for managing jobs, applications, candidate review, interview workflows, hiring decisions and recruiter analytics in one structured system."],
    ["Does Nice Role make hiring decisions automatically?", "No. Resume extraction and matching can assist authorised users with evidence organisation, but consequential hiring decisions remain human-controlled."],
    ["Are candidate resumes public?", "No. Candidate profile and resume information is private by default and is shared only through supported recruitment workflows and authorised access."],
    ["Does Nice Role support interview workflows?", "Yes. The implemented product includes interview scheduling, updates, cancellation and structured scorecards."],
    ["Can candidates use Nice Role?", "Nice Role includes candidate-facing job discovery, applications, interviews, notifications, profile, privacy and support workflows, including a candidate mobile application direction."],
    ["Where can I open Nice Role?", "Use the official Nice Role application link from this page. Product availability and live external services remain subject to the production environment and approved provider configuration."],
  ],
} as const;
