import type { Capability } from "@/lib/corporate/permissions";

type SectionDefinition = { title: string; eyebrow: string; capability: Capability; description: string; empty: string };
export const officeSections = {
  dashboard: { title: "Corporate overview", eyebrow: "EXECUTIVE WORKSPACE", capability: "decision.view", description: "A decision-oriented view of approved records, attention items and active operational queues.", empty: "No attention items are available for the selected financial year." },
  decisions: { title: "Decision Inbox", eyebrow: "DIRECTOR ACTIONS", capability: "decision.view", description: "One controlled queue for reviews and decisions. High-risk approvals retain independent workflow and AAL2 requirements.", empty: "No decisions are assigned to your role." },
  support: { title: "Support Operations", eyebrow: "CUSTOMER CASE MANAGEMENT", capability: "support.view", description: "Customer cases are tracked through controlled status transitions, scoped ownership and separately marked customer-visible updates.", empty: "No support cases are currently in your authorised queue." },
  automations: { title: "Automations", eyebrow: "CONTROLLED OPERATIONS", capability: "automation.view", description: "Reusable triggers create safe tasks, reminders and evidence requests. Automation never completes a legal or financial approval.", empty: "No automation definitions are active for this environment." },
  calendar: { title: "Corporate calendar", eyebrow: "FORWARD VIEW", capability: "calendar.view", description: "Board, compliance, registration, contract and renewal items use Asia/Kolkata business-time semantics.", empty: "No upcoming corporate events are available to this role." },
  board: { title: "Board Room", eyebrow: "GOVERNANCE WORKSPACE", capability: "meeting.view", description: "Controlled meetings, notices, agendas, minutes, resolutions and action items.", empty: "No Board meetings have been scheduled for this financial year." },
  meetings: { title: "Board meetings", eyebrow: "GOVERNANCE RECORDS", capability: "meeting.view", description: "Meeting lifecycles are controlled. Formal records are versioned and final records are locked.", empty: "No meeting records match this view." },
  resolutions: { title: "Resolution register", eyebrow: "GOVERNANCE RECORDS", capability: "meeting.view", description: "Final resolution references are immutable. Circulation responses remain attributable.", empty: "No resolutions have been recorded." },
  compliance: { title: "Compliance", eyebrow: "REVIEW-LED ENGINE", capability: "compliance.view", description: "Recommendations remain linked to versioned official sources and professional review; the system never declares compliance by assumption.", empty: "No active compliance obligations are configured." },
  registrations: { title: "Company registrations", eyebrow: "CONTROLLED REGISTRY", capability: "registration.view", description: "Registration metadata, expiry information and evidence are held privately with masked identifiers by default.", empty: "No registration records are available to this role." },
  documents: { title: "Document Vault", eyebrow: "PRIVATE RECORDS", capability: "document.view", description: "Private-by-default documents use classification, versions, checksums, retention metadata and controlled delivery.", empty: "No documents are available to this role." },
  finance: { title: "Finance operations", eyebrow: "EVIDENCE & RECONCILIATION", capability: "finance.view", description: "Administrative finance evidence, staged imports and human-confirmed reconciliation. This is not a payment-execution or accounting system.", empty: "No financial records are assigned to your role." },
  assets: { title: "Corporate assets", eyebrow: "ASSET & RENEWAL REGISTER", capability: "asset.view", description: "Company assets, SaaS subscriptions and renewal dates remain controlled operational records.", empty: "No corporate assets are available to this role." },
  "data-migration": { title: "Real data migration", eyebrow: "PRODUCTION ONBOARDING", capability: "data.import", description: "Real records are inventoried, classified, staged, validated and owner-approved before commit. No production record is created from an unreviewed upload.", empty: "No real-data migration batches have been created." },
  data: { title: "Import & export center", eyebrow: "CONTROLLED DATA MOVEMENT", capability: "data.import", description: "Imports stage, validate and require confirmation before records change. Sensitive exports remain role-restricted and audited.", empty: "No imports or exports require attention." },
  "statutory-registers": { title: "Statutory registers", eyebrow: "CONTROLLED REGISTERS", capability: "registration.view", description: "Enable each register definition only after professional confirmation of its applicability.", empty: "No statutory register definitions are enabled." },
  gst: { title: "GST workspace", eyebrow: "RESTRICTED WORKSPACE", capability: "compliance.view", description: "Registration, return periods, review status and filing evidence remain internal. Filed status requires evidence.", empty: "No GST records are configured." },
  auditor: { title: "Professional workspace", eyebrow: "ASSIGNED ACCESS", capability: "document.view", description: "CA, CS, auditor and legal work is assigned by scope and expiry—not by blanket access.", empty: "No professional requests are assigned to you." },
  ip: { title: "Intellectual property", eyebrow: "ASSET REGISTER", capability: "registration.view", description: "Trademarks, domains and other assets are tracked with evidence and renewal reminders.", empty: "No intellectual-property records are configured." },
  contracts: { title: "Contracts", eyebrow: "CONTROLLED REPOSITORY", capability: "document.view", description: "Agreements retain owner, dates, renewal timing, classification and signed evidence.", empty: "No contracts are available to this role." },
  disclosures: { title: "Public disclosure workflow", eyebrow: "PUBLICATION GATE", capability: "disclosure.review", description: "A public artifact is reviewed and approved separately; a private bucket is never made public by a status switch.", empty: "No disclosure publication requests are awaiting review." },
  privacy: { title: "Privacy governance", eyebrow: "DATA GOVERNANCE", capability: "compliance.view", description: "Data inventory, retention, legal holds and privacy requests support governed handling—not automated deletion.", empty: "No privacy governance records require attention." },
  security: { title: "Security administration", eyebrow: "RESTRICTED ADMINISTRATION", capability: "security.manage", description: "Access review, security events and high-risk controls are available only to authorised administrators.", empty: "No security events require action." },
  integrations: { title: "Integrations", eyebrow: "CONTROLLED PROVIDERS", capability: "integration.view", description: "Provider health and credential references are visible without exposing secrets or credentials.", empty: "No external integrations are configured." },
  readiness: { title: "Production readiness", eyebrow: "LAUNCH CONTROL", capability: "readiness.view", description: "Readiness reflects only verified configuration and evidence. It is never a legal-compliance score.", empty: "No verified launch-readiness checks are configured." },
  audit: { title: "Audit trail", eyebrow: "APPEND-ORIENTED EVIDENCE", capability: "audit.view", description: "Significant business actions are recorded without copying sensitive document content into audit metadata.", empty: "No audit events are available to this role." },
  content: { title: "Content governance", eyebrow: "PUBLICATION CONTROL", capability: "content.view", description: "Public content is versioned, reviewed by domain, SEO-checked and published from approved records only. Drafts and evidence stay private.", empty: "No governed public content records are available to this role." },
  settings: { title: "Corporate settings", eyebrow: "CONTROLLED CONFIGURATION", capability: "access.manage", description: "Company applicability, rule-review cadence, roles and retention policies require controlled changes and audit evidence.", empty: "No settings are available to this role." },
} as const satisfies Record<string, SectionDefinition>;
export type OfficeSection = keyof typeof officeSections;
export const officeNavigation = Object.entries(officeSections).map(([slug, item]) => ({ slug, title: item.title }));
