const SEED = window.KRAVIA_SEED;
const ENG = window.KRAVIA_ENGINE;
let state = ENG.getState();
let page = (location.hash || '#overview').slice(1);
let activeTab = {};

const NAV = [
  {section:'Operate',items:[['overview','Command Center','◈'],['company','Company','◆'],['products','Products','◫'],['customers','Customers','◎'],['commercial','Commercial','◧']]},
  {section:'Money',items:[['billing','Billing','▤'],['payments','Payments','₹'],['tax','GST & Tax','%'],['accounting','Accounting','▥'],['banking','Banking','⌁']]},
  {section:'Govern',items:[['governance','Governance','◇'],['compliance','Compliance','✓'],['contracts','Contracts','▧'],['vendors','Vendors','◩']]},
  {section:'Office',items:[['people','People','◉'],['assets','Assets','▦'],['communications','Communications','✉'],['documents','Documents','▤']]},
  {section:'Assure',items:[['inspection','Audit & Inspection','◌'],['automations','Automations','↻'],['integrations','Integrations','⌘'],['security','Security','◐'],['audit','Audit Trail','≡'],['reports','Reports','▨'],['settings','Settings','⚙']]}
];
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money = v => `₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dt = v => v ? new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle: v.includes?.('T')?'short':undefined}) : '—';
const idShort = v => String(v||'').slice(0,18);
function badge(text,cls){ cls=cls||badgeClass(text); return `<span class="badge ${cls}">${esc(String(text).replaceAll('_',' '))}</span>`; }
function badgeClass(s){ s=String(s||'').toUpperCase(); if(/VERIFIED|READY|SUCCESS|ACTIVE|PAID|CONNECTED|AVAILABLE/.test(s))return'ready'; if(/CRITICAL|FAILED|ACTION_REQUIRED|OVERDUE/.test(s))return'critical'; if(/REVIEW|WAITING|PARTIAL|IN_PROGRESS|REQUIRES/.test(s))return'review'; if(/ISSUED|SOURCE|EVIDENCE|FILED/.test(s))return'source'; return'pending'; }
function card(title,sub,body,actions='',cls=''){ return `<article class="card ${cls}"><div class="card-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${actions?`<div class="card-actions">${actions}</div>`:''}</div>${body}</article>`; }
function metric(label,value,meta,unavailable=false){ return `<article class="card metric ${unavailable?'unavailable':''}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-meta">${meta}</div></article>`; }
function table(headers,rows,classes=''){ return `<div class="table-wrap"><table class="data-table ${classes}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}"><div class="empty"><strong>No records yet</strong><span>The system will show records here when created or ingested.</span></div></td></tr>`}</tbody></table></div>`; }
function banner(type,title,text){ return `<div class="banner ${type||''}"><span>${type==='critical'?'!':'✓'}</span><div><strong>${title}</strong> ${text}</div></div>`; }
function kv(k,v){ return `<div class="kv"><div class="k">${k}</div><div class="v">${v}</div></div>`; }
function toast(title,message,type='success'){ const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<strong>${esc(title)}</strong>${esc(message)}`;$('#toastStack').appendChild(el);setTimeout(()=>el.remove(),4200); }
function download(filename,content,type='application/json'){ const blob=new Blob([content],{type});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),500); }

function renderNav(){ $('#nav').innerHTML=NAV.map(g=>`<div class="nav-section">${g.section}</div>${g.items.map(([id,label,icon])=>`<button class="${page===id?'active':''}" data-nav="${id}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span></button>`).join('')}`).join(''); $$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav)); }
function navigate(id){ page=id; location.hash=id; renderNav(); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function setHead(title,eyebrow=SEED.company.legalName){ $('#pageTitle').textContent=title;$('#eyebrow').textContent=eyebrow; }
function refresh(){ state=ENG.getState(); render(); }

function sourceBanner(){return banner('', 'No fabricated operating data.', 'Live financial, tax and banking values appear only after a verified source exists. This foundation uses source-backed corporate records plus records actually created inside this build.');}
function attentionItems(){
  const c=SEED.compliance.filter(x=>!['COMPLETE','VERIFIED'].includes(x.status));
  const ints=SEED.integrations.filter(x=>x.health!=='READY');
  return [...c.slice(0,5).map(x=>({name:x.requirement,purpose:`${x.domain} · ${x.owner}`,status:x.status,severity:x.severity})),...ints.slice(0,3).map(x=>({name:x.name,purpose:x.purpose,status:x.status,severity:'MEDIUM'}))];
}
function pageOverview(){
  setHead('Command Center');
  const tax=ENG.getTaxSummary(), rec=ENG.getReceivables(), rev=ENG.getIssuedRevenue(), exceptions=attentionItems();
  const haveInvoices=state.invoices.length>0;
  return `${sourceBanner()}<div class="section-gap"></div>
  <div class="grid grid-5">
    ${metric('Issued revenue',haveInvoices?money(rev):'No issued invoices',haveInvoices?`${state.invoices.length} invoice(s) in local ledger`:'Billing engine is ready; no transaction invented',!haveInvoices)}
    ${metric('Receivables',haveInvoices?money(rec):'No source',haveInvoices?'Open invoice balance':'No issued invoice balance',!haveInvoices)}
    ${metric('Output GST',haveInvoices?money(tax.cgst+tax.sgst+tax.igst):'No source',haveInvoices?'Derived from issued local invoices':'Tax engine has no financial source yet',!haveInvoices)}
    ${metric('Controlled records',String(SEED.documents.length+state.invoices.length+state.receipts.length),`${SEED.documents.length} source/workspace documents`)}
    ${metric('Needs attention',String(exceptions.length),`${SEED.compliance.filter(x=>x.severity==='CRITICAL').length} critical setup control(s)`)}
  </div><div class="section-gap"></div>
  <div class="split">
    ${card('Portfolio','One company operating layer for every KRAVIA product.',`<div class="grid grid-3">${state.products.map(p=>`<div class="product-card"><div class="product-code">${esc(p.code)}</div><h3>${esc(p.name)}</h3><p>${esc(p.category)}</p><div class="product-foot">${badge(p.status)}<span class="subtle">${state.invoices.filter(i=>i.productId===p.id).length} invoices</span></div></div>`).join('')}</div>`)}
    ${card('Needs attention','Exceptions, verification gaps and disconnected source systems.',exceptions.map(x=>`<div class="attention-row"><div><div class="name">${esc(x.name)}</div><div class="purpose">${esc(x.purpose)}</div></div>${badge(x.status,x.severity==='CRITICAL'?'critical':undefined)}</div>`).join(''))}
  </div><div class="section-gap"></div>
  ${card('Quick actions','Normal work should start from controlled commands, not scattered documents.',`<div class="quick-grid"><button class="quick-tile" data-create="customer"><strong>New customer</strong><small>Create canonical billing identity</small></button><button class="quick-tile" data-create="invoice"><strong>Issue invoice</strong><small>Snapshot customer, product and GST</small></button><button class="quick-tile" data-create="payment"><strong>Record payment</strong><small>Match invoice and issue receipt</small></button><button class="quick-tile" data-navx="inspection"><strong>Inspection room</strong><small>Build controlled evidence manifest</small></button></div>`)}
  <div class="section-gap"></div>
  ${card('Automation spine','The local foundation executes safe, deterministic billing and evidence flows; external API steps remain visibly disconnected until real credentials/providers are authorized.',`<div class="flow"><span class="flow-step">Product event</span><span class="flow-arrow">→</span><span class="flow-step">Commercial context</span><span class="flow-arrow">→</span><span class="flow-step">Billing snapshot</span><span class="flow-arrow">→</span><span class="flow-step">GST calculation</span><span class="flow-arrow">→</span><span class="flow-step">Payment</span><span class="flow-arrow">→</span><span class="flow-step">Receipt</span><span class="flow-arrow">→</span><span class="flow-step">Evidence</span></div>`)}
  `;
}
function pageCompany(){
  setHead('Company','Verified master & legal identity');
  const directors=table(['Director','Designation','DIN','Source date','Status'],SEED.directors.map(d=>`<tr><td><div class="row-title">${esc(d.name)}</div></td><td>${esc(d.designation)}</td><td class="mono">${esc(d.din)}</td><td>${esc(d.sourceDate)}</td><td>${badge(d.status)}</td></tr>`));
  const regs=table(['Registration','Authority','Identifier','Status','Evidence'],SEED.registrations.map(r=>`<tr><td><div class="row-title">${esc(r.name)}</div></td><td>${esc(r.authority)}</td><td class="mono">${esc(r.number)}</td><td>${badge(r.status,r.risk==='HIGH'?'review':r.risk==='CRITICAL'?'critical':undefined)}</td><td>${esc(r.evidence)}</td></tr>`));
  return `${banner('warning','Production lock is intentionally blocked.', 'Registered office and each statutory registration should be linked to current authoritative evidence before production master lock.')}<div class="section-gap"></div><div class="grid grid-2">${card('Legal entity','Current working source of truth.',kv('Legal name',`<strong>${esc(SEED.company.legalName)}</strong>`)+kv('CIN',`<span class="mono">${esc(SEED.company.cin)}</span>`)+kv('Registered office',esc(SEED.company.registeredOffice))+kv('Financial year',esc(SEED.company.financialYear))+kv('Master status',badge(SEED.company.verification)))}${card('Master-data controls','Critical identity changes require evidence and maker-checker in production.',`<div class="timeline"><div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-copy"><strong>Evidence linked</strong><p>Every statutory identifier and address should point to its source document.</p></div></div><div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-copy"><strong>Effective dated</strong><p>Historical invoices and resolutions keep the identity snapshot that existed when issued.</p></div></div><div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-copy"><strong>Protected values</strong><p>PAN/TAN/secrets are not exposed in general administration views.</p></div></div></div>`)}</div><div class="section-gap"></div>${card('Directors','Authorized director evidence is required before records appear here.',directors)}<div class="section-gap"></div>${card('Registrations','Evidence and current status must be independently linked before Office treats a registration as production-verified.',regs)}`;
}
function pageProducts(){
  setHead('Products','Global product registry');
  const rows=state.products.map(p=>`<tr><td><div class="row-title">${esc(p.name)}</div><div class="row-sub">${esc(p.id)}</div></td><td><span class="mono">${esc(p.code)}</span></td><td>${esc(p.category)}</td><td>${esc((p.countries||[]).join(', '))}</td><td>${badge(p.status)}</td><td>${state.invoices.filter(i=>i.productId===p.id).length}</td></tr>`);
  return `${card('Product Registry','New KRAVIA products inherit the central commercial, billing, tax, document and audit platform.',table(['Product','Code','Category','Countries','Status','Invoices'],rows),`<button class="button" data-create="product">+ Add product</button>`)}<div class="section-gap"></div>${card('Product onboarding contract','Adding a product should be configuration, not a new back office.',`<div class="flow"><span class="flow-step">Identity</span><span class="flow-arrow">→</span><span class="flow-step">Country</span><span class="flow-arrow">→</span><span class="flow-step">Pricing</span><span class="flow-arrow">→</span><span class="flow-step">Tax</span><span class="flow-arrow">→</span><span class="flow-step">Payment</span><span class="flow-arrow">→</span><span class="flow-step">Documents</span><span class="flow-arrow">→</span><span class="flow-step">Compliance</span></div>`)}`;
}
function pageCustomers(){
  setHead('Customers','Canonical legal & billing identity');
  const rows=state.customers.map(c=>`<tr><td><div class="row-title">${esc(c.legalName)}</div><div class="row-sub">${esc(c.id)}</div></td><td>${esc(c.gstin||'Unregistered / not captured')}</td><td>${esc(c.state)} ${c.stateCode?`(${esc(c.stateCode)})`:''}</td><td>${esc(c.email||'—')}</td><td>${state.invoices.filter(i=>i.customerId===c.id).length}</td><td>${badge(c.status)}</td></tr>`);
  return `${banner('', 'One customer identity across products.', 'Operational product profiles may differ, but KRAVIA Office owns the canonical legal and billing identity used for contracts, invoices, tax and collections.')}<div class="section-gap"></div>${card('Customer Master',`${state.customers.length} canonical customer record(s).`,table(['Customer','GSTIN','State','Billing contact','Invoices','Status'],rows),`<button class="button" data-create="customer">+ New customer</button>`)}`;
}
function pageCommercial(){
  setHead('Commercial','Catalog, pricing & entitlements');
  return `${banner('warning','Commercial catalog is not yet source-connected.', 'No plan prices are invented here. The engine structure is ready; approved product pricing should be imported from source-of-truth product/commercial records.')}<div class="section-gap"></div><div class="grid grid-3">${card('Product catalog','Company-wide product registry.',`<div class="metric-value">${state.products.length}</div><div class="metric-meta">configured products</div>`)}${card('Price versions','Effective-dated pricing control.',`<div class="metric-value">0</div><div class="metric-meta">approved catalog versions imported</div>`)}${card('Entitlements','Subscription/usage rights.',`<div class="metric-value">0</div><div class="metric-meta">live entitlement sources connected</div>`)}</div><div class="section-gap"></div>${card('Commercial engine contract','Products request a commercial decision; they should not calculate final prices/taxes independently.',`<div class="flow"><span class="flow-step">Customer</span><span class="flow-arrow">→</span><span class="flow-step">Product</span><span class="flow-arrow">→</span><span class="flow-step">Plan</span><span class="flow-arrow">→</span><span class="flow-step">Price version</span><span class="flow-arrow">→</span><span class="flow-step">Discount</span><span class="flow-arrow">→</span><span class="flow-step">Tax</span><span class="flow-arrow">→</span><span class="flow-step">Order</span></div>`)}`;
}
function pageBilling(){
  setHead('Billing','Central invoice engine');
  const rows=state.invoices.slice().reverse().map(i=>{const c=i.snapshot.customer,p=i.snapshot.product;return `<tr><td><button class="button ghost" data-invoice="${i.id}">${esc(i.invoiceNo)}</button><div class="row-sub">${dt(i.issuedAt)}</div></td><td><div class="row-title">${esc(c.legalName)}</div><div class="row-sub">${esc(p.name)}</div></td><td class="text-right money">${money(i.netTaxable)}</td><td class="text-right money">${money(i.cgst+i.sgst+i.igst)}</td><td class="text-right money"><strong>${money(i.total)}</strong></td><td>${badge(i.status)}</td></tr>`});
  return `${banner('', 'Immutable billing snapshots are implemented locally.', 'Every issued invoice preserves the company/customer/product/tax snapshot used at issuance. Historical values are not recomputed from current master data.')}<div class="section-gap"></div><div class="grid grid-4">${metric('Invoices',state.invoices.length,'issued in this local foundation')}${metric('Taxable value',money(ENG.getIssuedRevenue()),'derived from issued records')}${metric('Open balance',money(ENG.getReceivables()),'local receivables')}${metric('Sequence',`*/${ENG.financialYear()}/######`,'atomic production sequence required')}</div><div class="section-gap"></div>${card('Invoices','Issue, inspect and print canonical invoices.',table(['Invoice','Customer / Product','Taxable','GST','Total','Status'],rows),`<button class="button" data-create="invoice">+ Issue invoice</button>`)}`;
}
function pagePayments(){
  setHead('Payments','Collections, receipts & reconciliation');
  const rows=state.payments.slice().reverse().map(p=>{const i=state.invoices.find(x=>x.id===p.invoiceId);return `<tr><td><div class="row-title">${esc(p.id)}</div><div class="row-sub">${esc(p.receivedAt)}</div></td><td>${esc(i?.invoiceNo||'—')}</td><td>${esc(p.method)}</td><td class="mono">${esc(p.reference||'—')}</td><td class="text-right money"><strong>${money(p.amount)}</strong></td><td>${badge(p.status)}</td></tr>`});
  const receipts=state.receipts.map(r=>`<tr><td><button class="button ghost" data-receipt="${r.id}">${esc(r.receiptNo)}</button></td><td>${esc(state.invoices.find(i=>i.id===r.invoiceId)?.invoiceNo||'—')}</td><td class="text-right">${money(r.amount)}</td><td>${dt(r.issuedAt)}</td></tr>`);
  return `${banner('warning','Provider and bank feeds are not connected to this build.', 'Manual payment capture works and produces receipts, but settlement/bank matching remains visibly pending instead of being fabricated.')}<div class="section-gap"></div>${card('Payments','Source-linked collections.',table(['Payment','Invoice','Method','Reference','Amount','Status'],rows),`<button class="button" data-create="payment">+ Record payment</button>`)}<div class="section-gap"></div>${card('Receipts','Generated from recorded payments.',table(['Receipt','Invoice','Amount','Issued'],receipts))}`;
}
function pageTax(){
  setHead('GST & Tax','Tax control center');
  const t=ENG.getTaxSummary();
  const rows=state.invoices.map(i=>`<tr><td>${esc(i.invoiceNo)}</td><td>${esc(i.snapshot.customer.legalName)}</td><td>${esc(i.snapshot.customer.gstin||'—')}</td><td>${esc(i.snapshot.customer.state||'—')}</td><td class="text-right">${money(i.netTaxable)}</td><td class="text-right">${money(i.cgst)}</td><td class="text-right">${money(i.sgst)}</td><td class="text-right">${money(i.igst)}</td></tr>`);
  return `${banner('critical','GST production lock is not complete.', 'Current GST registration status, GSTIN, invoice sequence, SAC mappings and CA-reviewed rules must be verified before production tax invoices are issued.')}<div class="section-gap"></div><div class="grid grid-4">${metric('Taxable value',money(t.taxable),`${state.invoices.length} issued local invoices`)}${metric('CGST',money(t.cgst),'derived locally')}${metric('SGST',money(t.sgst),'derived locally')}${metric('IGST',money(t.igst),'derived locally')}</div><div class="section-gap"></div>${card('Sales Register','Generated directly from invoice snapshots.',table(['Invoice','Customer','GSTIN','Place of supply','Taxable','CGST','SGST','IGST'],rows))}<div class="section-gap"></div>${card('Period controls','Returns remain human-reviewed.',`<div class="flow"><span class="flow-step">Sales register</span><span class="flow-arrow">→</span><span class="flow-step">Reconcile</span><span class="flow-arrow">→</span><span class="flow-step">GSTR-1 working</span><span class="flow-arrow">→</span><span class="flow-step">CA review</span><span class="flow-arrow">→</span><span class="flow-step">Director approval</span><span class="flow-arrow">→</span><span class="flow-step">File</span><span class="flow-arrow">→</span><span class="flow-step">Ack + lock</span></div>`)}`;
}
function pageAccounting(){
  setHead('Accounting','Double-entry control plane');
  const invRows=state.invoices.map(i=>`<tr><td>${esc(i.invoiceNo)}</td><td>Accounts Receivable</td><td>Software / SaaS Revenue + Output GST</td><td class="text-right">${money(i.total)}</td><td>${badge('DEMO_POSTING_MODEL','review')}</td></tr>`);
  return `${banner('warning','Accounting ledger adapter is not yet connected.', 'This page derives control views from the local invoice engine but does not pretend that a statutory accounting book has been posted. A production ledger or approved accounting integration is required.')}<div class="section-gap"></div><div class="grid grid-3">${metric('Journal source records',state.invoices.length,'invoice-origin candidates')}${metric('Manual journals','0','none created in this foundation')}${metric('Period state','OPEN','no production accounting close')}</div><div class="section-gap"></div>${card('Posting candidates','Every production posting must link back to source_event_id and source_document_id.',table(['Source','Debit','Credit','Amount','Status'],invRows))}`;
}
function pageBanking(){
  setHead('Banking','Accounts & reconciliation');
  const rows=SEED.banking.map(b=>`<tr><td><div class="row-title">${esc(b.bank)}</div><div class="row-sub">${esc(b.type)}</div></td><td class="mono">${esc(b.maskedAccount)}</td><td>${badge(b.status)}</td><td>${esc(b.lastEvidence)}</td><td>${b.balance==null?'<span class="subtle">No bank feed</span>':money(b.balance)}</td></tr>`);
  return `${banner('', 'No bank-account evidence is embedded in this source package.', 'Attach authorized bank evidence in the private vault. Live balances and transactions remain unavailable until an approved integration is configured.')}<div class="section-gap"></div>${card('Bank Registry','Sensitive values are masked in general Office views.',table(['Bank','Account','Status','Last evidence','Live balance'],rows))}<div class="section-gap"></div>${card('Reconciliation target','Production flow.',`<div class="flow"><span class="flow-step">Gateway payment</span><span class="flow-arrow">→</span><span class="flow-step">Settlement</span><span class="flow-arrow">→</span><span class="flow-step">Bank credit</span><span class="flow-arrow">→</span><span class="flow-step">Match</span><span class="flow-arrow">→</span><span class="flow-step">Ledger</span></div>`)}`;
}
function pageGovernance(){
  setHead('Governance','Board, resolutions & authorities');
  const meetings=table(['Meeting / Record','Date','Status','Evidence','Attention'],SEED.governance.meetings.map(m=>`<tr><td><div class="row-title">${esc(m.id)} · ${esc(m.title)}</div></td><td>${esc(m.date)}</td><td>${badge(m.status)}</td><td><button class="button ghost" data-doc="${m.documentId}">Open source</button></td><td>${esc(m.attention)}</td></tr>`));
  const auth=table(['Authority','Subject','Granted to','Source','Effective','Status'],SEED.governance.authorities.map(a=>`<tr><td class="mono">${esc(a.id)}</td><td>${esc(a.subject)}</td><td>${esc(a.grantee)}</td><td><button class="button ghost" data-doc="${a.source}">${esc(a.source)}</button></td><td>${esc(a.effective)}</td><td>${badge(a.status)}</td></tr>`));
  return `${banner('warning','Governance records need controlled statutory review.', 'The system preserves source documents and does not infer that a drafted or uploaded file proves a statutory action was completed.')}<div class="section-gap"></div>${card('Board records','Trace meeting → resolution → CTC → authority → action.',meetings)}<div class="section-gap"></div>${card('Authority Register','Authority must never exceed its source resolution.',auth)}`;
}
function pageCompliance(){
  setHead('Compliance','Company & product obligations');
  const rows=SEED.compliance.map(c=>`<tr><td class="mono">${esc(c.id)}</td><td><div class="row-title">${esc(c.requirement)}</div><div class="row-sub">${esc(c.domain)}</div></td><td>${esc(c.owner)}</td><td>${esc(c.due)}</td><td>${badge(c.status,c.severity==='CRITICAL'?'critical':undefined)}</td><td>${badge(c.severity,c.severity==='CRITICAL'?'critical':c.severity==='HIGH'?'review':'pending')}</td></tr>`);
  return `${card('Compliance Register','Evidence-first status. A document existing does not automatically mean the obligation is complete.',table(['ID','Requirement','Owner','Due / Trigger','Status','Severity'],rows))}`;
}
function pageContracts(){
  setHead('Contracts','Master agreements & obligations');
  return `${banner('', 'Contract engine foundation.', 'The controlled client agreement template is available; executed counterparty contracts should be ingested as real records with effective/expiry/renewal metadata.')}<div class="section-gap"></div>${card('Contract Library','No executed customer/vendor contract is invented in this build.',table(['Contract','Counterparty','Products','Effective','Renewal','Status'],[]),`<button class="button ghost" data-doc="DOC-LEG-001">Open client agreement template</button>`)}`;
}
function pageVendors(){
  setHead('Vendors','Provider registry & risk');
  const rows=SEED.vendors.map(v=>`<tr><td><div class="row-title">${esc(v.name)}</div><div class="row-sub">${esc(v.id)}</div></td><td>${esc(v.category)}</td><td>${esc(v.products.join(', '))}</td><td>${badge(v.risk,v.risk==='CRITICAL'?'critical':v.risk==='HIGH'?'review':undefined)}</td><td>${badge(v.status)}</td><td>${esc(v.evidence)}</td></tr>`);
  return `${card('Vendor Master','Source-backed providers already visible from corporate correspondence and current infrastructure.',table(['Vendor','Category','Used by','Risk','Status','Evidence'],rows))}`;
}
function pagePeople(){
  setHead('People','Directors & workforce controls');
  const rows=SEED.directors.map(d=>`<tr><td><div class="row-title">${esc(d.name)}</div><div class="row-sub">${esc(d.id)}</div></td><td>${esc(d.designation)}</td><td class="mono">${esc(d.din)}</td><td>${badge(d.status)}</td></tr>`);
  return `${banner('', 'Sensitive personal data is deliberately minimized.', 'The Office foundation includes only corporate-role details needed for administration; PAN, personal addresses and phone numbers are not exposed here.')}<div class="section-gap"></div>${card('Corporate people','Current source-backed director records.',table(['Person','Role','DIN','Source status'],rows))}<div class="section-gap"></div>${card('Employee lifecycle','Ready for future staff.',`<div class="flow"><span class="flow-step">Offer</span><span class="flow-arrow">→</span><span class="flow-step">Joining</span><span class="flow-arrow">→</span><span class="flow-step">Access + Asset</span><span class="flow-arrow">→</span><span class="flow-step">Payroll</span><span class="flow-arrow">→</span><span class="flow-step">Performance</span><span class="flow-arrow">→</span><span class="flow-step">Exit</span></div>`)}`;
}
function pageAssets(){
  setHead('Assets','Company property & custody');
  const rows=state.assets.map(a=>`<tr><td><div class="row-title">${esc(a.name)}</div><div class="row-sub">${esc(a.id)}</div></td><td>${esc(a.category)}</td><td class="mono">${esc(a.serial||'—')}</td><td>${esc(a.assignedTo||'Unassigned')}</td><td>${esc(a.location||'—')}</td><td>${badge(a.status)}</td></tr>`);
  return `${card('Asset Register','Track laptops, DSC tokens, phones, network equipment and other company property without fabricating inventory.',table(['Asset','Category','Serial','Custodian','Location','Status'],rows),`<button class="button" data-create="asset">+ Add asset</button>`)}`;
}
function pageCommunications(){
  setHead('Communications','Corporate inbox intelligence');
  const rows=SEED.communications.map(m=>`<tr><td>${esc(m.at)}</td><td><div class="row-title">${esc(m.from)}</div><div class="row-sub">${esc(m.id)}</div></td><td>${esc(m.subject)}</td><td>${badge(m.classification,'source')}</td><td>${esc(m.action.replaceAll('_',' '))}</td><td>${badge(m.status)}</td></tr>`);
  return `${banner('', 'No corporate-mail snapshot is embedded in this source package.', 'The deployed Office application needs its own authorized email integration, approved retention policy and least-privilege scopes before ingestion is enabled.')}<div class="section-gap"></div>${card('Ingestion snapshot','Banking, payment, vendor and compliance correspondence is classified into records instead of disappearing in email.',table(['When','Source','Subject','Class','Suggested action','Status'],rows))}`;
}
function allDocuments(){
  const generated=state.invoices.map(i=>({id:i.id,title:`Tax Invoice ${i.invoiceNo}`,type:'Generated Invoice',area:'Billing',format:'HTML',status:i.status,source:'KRAVIA Office local engine',generated:true,record:i}));
  const receipts=state.receipts.map(r=>({id:r.id,title:`Payment Receipt ${r.receiptNo}`,type:'Generated Receipt',area:'Payments',format:'HTML',status:'ISSUED',source:'KRAVIA Office local engine',generated:true,receipt:r}));
  return [...SEED.documents,...generated,...receipts];
}
function pageDocuments(){
  setHead('Documents','Controlled vault & verification');
  const docs=allDocuments(); const rows=docs.map(d=>`<tr><td><button class="button ghost" data-doc="${d.id}">${esc(d.title)}</button><div class="row-sub">${esc(d.id)}</div></td><td>${esc(d.type)}</td><td>${esc(d.area)}</td><td>${esc(d.format)}</td><td>${badge(d.status)}</td><td>${esc(d.source)}</td></tr>`);
  return `${banner('', 'Controlled document model.', 'PDFs use a sandboxed iframe preview. Generated financial documents are rendered from immutable snapshots, not the current customer master.')}<div class="section-gap"></div>${card('Document Vault',`${docs.length} controlled or working record(s).`,table(['Document','Type','Area','Format','Status','Source'],rows))}`;
}
function pageInspection(){
  setHead('Audit & Inspection','Controlled evidence disclosure');
  const docs=allDocuments();
  return `${banner('warning','Inspection mode is scope-limited.', 'Do not give an officer, auditor or counterparty general Office admin access. Select only records relevant to the authorized request.')}<div class="section-gap"></div><div class="split">${card('Inspection request','Create a manifest from selected evidence.',`<div class="form-grid"><div class="field"><label>Authority</label><select id="inspAuthority"><option>GST</option><option>MCA / ROC</option><option>Income Tax</option><option>Statutory Auditor</option><option>Bank</option><option>Other</option></select></div><div class="field"><label>Reference / Notice</label><input id="inspRef" placeholder="Enter actual reference if available"></div><div class="field"><label>Period</label><input id="inspPeriod" placeholder="e.g. FY 2026-27 / Aug 2026"></div><div class="field"><label>Purpose</label><input id="inspPurpose" placeholder="Inspection / scrutiny / audit"></div></div><div class="section-gap"></div><div class="inspection-panel">${docs.map(d=>`<label class="stat-line"><span><input type="checkbox" class="inspection-doc" value="${d.id}"> ${esc(d.title)}</span><span>${badge(d.status)}</span></label>`).join('')}</div><div class="form-actions"><button class="button secondary" id="previewManifest">Preview manifest</button><button class="button" id="generateManifest">Download manifest</button></div>`)}${card('Manifest preview','Every disclosure is explicit and traceable.',`<div class="manifest-box" id="manifestPreview">Select evidence and preview the manifest. No authority reference will be invented.</div>`)}</div>`;
}
function pageAutomations(){
  setHead('Automations','Event-driven workflow control');
  const runs=ENG.getRuns();
  const wfRows=SEED.workflows.map(w=>`<tr><td><div class="row-title">${esc(w.name)}</div><div class="row-sub">${esc(w.id)}</div></td><td class="mono">${esc(w.trigger)}</td><td>${esc(w.domain)}</td><td>${badge(w.status)}</td><td>${badge(w.automation,'source')}</td></tr>`);
  const runHtml=runs.length?runs.slice(0,10).map(r=>`<div class="workflow-run ${r.status==='SUCCESS'?'success':'partial'}"><strong>${esc(r.workflow)} · ${esc(r.status)}</strong><br><small>${dt(r.at)} · ${esc(r.id)} · ${r.durationMs}ms</small><div class="run-steps">${r.steps.map(s=>`<div class="run-step">${badge(s.status)}<br>${esc(s.name)}</div>`).join('')}</div></div>`).join(''):`<div class="empty"><strong>No workflow runs yet</strong><span>Issue an invoice or record a payment to generate real local workflow traces.</span></div>`;
  return `${card('Workflow Registry','Normal operations become deterministic workflows; human intervention is reserved for approvals and exceptions.',table(['Workflow','Trigger','Domain','Status','Mode'],wfRows))}<div class="section-gap"></div>${card('Recent run traces','No silent automation. Each step is observable.',runHtml)}`;
}
function pageIntegrations(){
  setHead('Integrations','Source systems & provider health');
  const rows=SEED.integrations.map(i=>`<tr><td><div class="row-title">${esc(i.name)}</div><div class="row-sub">${esc(i.id)}</div></td><td>${esc(i.category)}</td><td>${esc(i.purpose)}</td><td>${badge(i.status)}</td><td>${badge(i.health,i.health==='READY'?'ready':'review')}</td></tr>`);
  return `${banner('', 'Connection truth is explicit.', 'A provider being evidenced in email is not the same thing as Office having live API access. The UI preserves that distinction.')}<div class="section-gap"></div>${card('Integration Registry','Every production connector needs scoped credentials, health, owner, sync history and failure visibility.',table(['Integration','Category','Purpose','Status','Health'],rows))}`;
}
function pageSecurity(){
  setHead('Security','Identity, roles & audit controls');
  const rows=SEED.roles.map(r=>`<tr><td><strong>${esc(r.role)}</strong></td><td>${esc(r.company)}</td><td>${esc(r.finance)}</td><td>${esc(r.governance)}</td><td>${esc(r.people)}</td><td>${esc(r.audit)}</td></tr>`);
  return `${banner('critical','Production authentication is not yet implemented.', 'This local foundation demonstrates control design only. Production requires real identity, MFA, server-side RBAC/ABAC, protected sessions, encrypted secrets and tamper-resistant audit storage.')}<div class="section-gap"></div>${card('Role model','Least privilege; deny by default.',table(['Role','Company','Finance','Governance','People','Audit'],rows))}<div class="section-gap"></div>${card('Production security gates','Must pass before internet deployment.',`<div class="grid grid-3"><div class="record-card"><h3>MFA + Sessions</h3><p>Strong sign-in, session rotation, device/session review.</p>${badge('BUILD_REQUIRED','critical')}</div><div class="record-card"><h3>Server-side authorization</h3><p>Every API/query enforces company/product/role scope.</p>${badge('BUILD_REQUIRED','critical')}</div><div class="record-card"><h3>Immutable audit</h3><p>Client-side local audit is not sufficient for production evidence.</p>${badge('BUILD_REQUIRED','critical')}</div></div>`)}`;
}
function pageAudit(){
  setHead('Audit Trail','Append-only operating evidence');
  const rows=ENG.getAudit().map(a=>`<tr><td>${dt(a.at)}</td><td><div class="row-title">${esc(a.event)}</div><div class="row-sub">${esc(a.id)}</div></td><td>${esc(a.entity)} · ${esc(a.entityId)}</td><td>${esc(a.actor)}</td><td>${esc(a.detail)}</td><td>${badge(a.severity,a.severity==='FINANCIAL'?'purple':undefined)}</td></tr>`);
  return `${banner('warning','Local audit is demonstrative, not legally immutable.', 'Production will move audit events to protected server-side append-only storage. No clear/delete action is exposed in this interface.')}<div class="section-gap"></div>${card('Audit events',`${rows.length} event(s) retained locally.`,table(['When','Event','Entity','Actor','Detail','Class'],rows))}`;
}
function pageReports(){
  setHead('Reports','Company & product intelligence');
  const byProduct=state.products.map(p=>{const inv=state.invoices.filter(i=>i.productId===p.id);return {name:p.name,revenue:inv.reduce((s,i)=>s+i.netTaxable,0),count:inv.length}}).sort((a,b)=>b.revenue-a.revenue);
  const max=Math.max(1,...byProduct.map(x=>x.revenue));
  return `${banner('', 'Reports derive from canonical Office records.', 'No headline revenue, tax or cash number is manually typed into reporting.')}<div class="section-gap"></div><div class="grid grid-4">${metric('Issued revenue',money(ENG.getIssuedRevenue()),`${state.invoices.length} invoice(s)`)}${metric('Collections',money(state.payments.reduce((s,p)=>s+p.amount,0)),`${state.payments.length} payment(s)`)}${metric('Receivables',money(ENG.getReceivables()),'open local balance')}${metric('Products',state.products.length,'registered')}</div><div class="section-gap"></div>${card('Revenue by product','Based only on invoices created in this Office foundation.',`<div class="chart-bars">${byProduct.map(x=>`<div class="bar" style="height:${Math.max(4,(x.revenue/max)*100)}%" title="${esc(x.name)} ${money(x.revenue)}"><span>${esc(x.name)}</span></div>`).join('')}</div><div class="section-gap"></div>${table(['Product','Invoices','Taxable revenue'],byProduct.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.count}</td><td class="text-right">${money(x.revenue)}</td></tr>`))}`)}`;
}
function pageSettings(){
  setHead('Settings','Office configuration');
  return `${card('Billing configuration','Local foundation settings. Production changes require controlled approval.',kv('Supplier state code',`<span class="mono">${esc(state.settings.supplierStateCode)}</span>`)+kv('Default GST rate',`${esc(state.settings.defaultGstRate)}%`)+kv('Invoice prefix',esc(state.settings.invoicePrefix))+kv('Financial year',ENG.financialYear()))}<div class="section-gap"></div>${card('Build information','Current enterprise foundation.',kv('Version',esc(SEED.build.version))+kv('Target domain',`<span class="mono">${esc(SEED.build.domainTarget)}</span>`)+kv('Mode',badge(SEED.build.mode,'source'))+kv('Generated',esc(SEED.build.generatedAt)))}`;
}

const PAGES={overview:pageOverview,company:pageCompany,products:pageProducts,customers:pageCustomers,commercial:pageCommercial,billing:pageBilling,payments:pagePayments,tax:pageTax,accounting:pageAccounting,banking:pageBanking,governance:pageGovernance,compliance:pageCompliance,contracts:pageContracts,vendors:pageVendors,people:pagePeople,assets:pageAssets,communications:pageCommunications,documents:pageDocuments,inspection:pageInspection,automations:pageAutomations,integrations:pageIntegrations,security:pageSecurity,audit:pageAudit,reports:pageReports,settings:pageSettings};
function render(){ state=ENG.getState(); if(!PAGES[page])page='overview'; $('#content').innerHTML=PAGES[page](); bind(); updateNotification(); }

function bind(){
  $$('[data-navx]').forEach(b=>b.onclick=()=>navigate(b.dataset.navx));
  $$('[data-create]').forEach(b=>b.onclick=()=>openCreate(b.dataset.create));
  $$('[data-doc]').forEach(b=>b.onclick=()=>openDocument(b.dataset.doc));
  $$('[data-invoice]').forEach(b=>b.onclick=()=>openInvoice(b.dataset.invoice));
  $$('[data-receipt]').forEach(b=>b.onclick=()=>openReceipt(b.dataset.receipt));
  $('#previewManifest') && ($('#previewManifest').onclick=()=>previewManifest(false));
  $('#generateManifest') && ($('#generateManifest').onclick=()=>previewManifest(true));
}
function updateNotification(){ const n=SEED.compliance.filter(x=>x.severity==='CRITICAL'&&x.status!=='COMPLETE').length; $('#notificationCount').textContent=n; $('#notificationCount').style.display=n?'grid':'none'; }

function openDocument(id){
  const d=allDocuments().find(x=>x.id===id); if(!d)return;
  $('#drawerEyebrow').textContent=d.type;$('#drawerTitle').textContent=d.title;const dl=$('#drawerDownload');dl.hidden=true;
  if(d.generated && d.record){ openInvoice(d.record.id); return; }
  if(d.generated && d.receipt){ openReceipt(d.receipt.id); return; }
  if(d.format==='PDF'){
    dl.hidden=false;dl.href=d.file;dl.download=d.file.split('/').pop();
    $('#drawerBody').innerHTML=`<div class="record-meta">${badge(d.status)}${badge(d.area,'source')}<span class="pill">${esc(d.id)}</span></div><div class="section-gap"></div><iframe class="document-frame" sandbox="allow-same-origin allow-downloads" src="${esc(d.file)}#view=FitH" title="${esc(d.title)}"></iframe>`;
  } else {
    dl.hidden=false;dl.href=d.file;dl.download=d.file.split('/').pop();
    $('#drawerBody').innerHTML=`${banner('', 'Preview not embedded for this file format.', 'Download the controlled file to open it in the appropriate application.')}<div class="section-gap"></div>${kv('Document ID',esc(d.id))+kv('Status',badge(d.status))+kv('Source',esc(d.source))}`;
  }
  $('#drawerOverlay').hidden=false;document.body.style.overflow='hidden';ENG.audit('document.opened','document',d.id,d.title);
}
function openInvoice(id){ const inv=state.invoices.find(x=>x.id===id);if(!inv)return;$('#drawerEyebrow').textContent='Immutable invoice snapshot';$('#drawerTitle').textContent=inv.invoiceNo;$('#drawerDownload').hidden=true;const html=ENG.htmlInvoice(inv);$('#drawerBody').innerHTML=`<div class="toolbar"><div class="record-meta">${badge(inv.status)}<span class="pill">${esc(inv.id)}</span></div><div><button class="button secondary" id="printInvoice">Print / Save PDF</button></div></div><iframe id="htmlDocFrame" class="document-frame" sandbox="allow-same-origin" title="Invoice preview"></iframe>`;$('#drawerOverlay').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>{const f=$('#htmlDocFrame');f.srcdoc=html;$('#printInvoice').onclick=()=>f.contentWindow.print();},0);ENG.audit('invoice.viewed','invoice',inv.id,inv.invoiceNo); }
function openReceipt(id){ const r=state.receipts.find(x=>x.id===id);if(!r)return;$('#drawerEyebrow').textContent='Payment receipt';$('#drawerTitle').textContent=r.receiptNo;$('#drawerDownload').hidden=true;const html=ENG.htmlReceipt(r);$('#drawerBody').innerHTML=`<div class="toolbar"><div class="record-meta">${badge('ISSUED')}</div><button class="button secondary" id="printReceipt">Print / Save PDF</button></div><iframe id="htmlDocFrame" class="document-frame" sandbox="allow-same-origin" title="Receipt preview"></iframe>`;$('#drawerOverlay').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>{const f=$('#htmlDocFrame');f.srcdoc=html;$('#printReceipt').onclick=()=>f.contentWindow.print();},0);ENG.audit('receipt.viewed','receipt',r.id,r.receiptNo); }
function closeDrawer(){ $('#drawerOverlay').hidden=true;$('#drawerBody').innerHTML='';document.body.style.overflow=''; }

function openModal(title,eyebrow,body){ $('#modalTitle').textContent=title;$('#modalEyebrow').textContent=eyebrow;$('#modalBody').innerHTML=body;$('#modalOverlay').hidden=false;document.body.style.overflow='hidden'; }
function closeModal(){ $('#modalOverlay').hidden=true;$('#modalBody').innerHTML='';document.body.style.overflow=''; }
function val(id){ return document.getElementById(id)?.value||''; }
function openCreate(type){
  if(type==='customer'){
    openModal('New customer','Customer Master',`<form id="customerForm"><div class="form-grid"><div class="field"><label>Legal name *</label><input id="cLegal" required></div><div class="field"><label>Display name</label><input id="cDisplay"></div><div class="field"><label>GSTIN</label><input id="cGstin" maxlength="15" placeholder="Leave blank if not captured"></div><div class="field"><label>State code</label><input id="cStateCode" maxlength="2" placeholder="e.g. 37"></div><div class="field"><label>State *</label><input id="cState" required></div><div class="field"><label>Country</label><input id="cCountry" value="India"></div><div class="field"><label>Billing email</label><input id="cEmail" type="email"></div><div class="field"><label>Phone</label><input id="cPhone"></div><div class="field full"><label>Billing address</label><textarea id="cAddress"></textarea></div></div><div class="form-note">This creates the canonical legal/billing identity. Product-specific operational profiles should reference this customer instead of duplicating tax/legal data.</div><div class="form-actions"><button type="button" class="button secondary" data-cancel>Cancel</button><button class="button" type="submit">Create customer</button></div></form>`);
    $('#customerForm').onsubmit=e=>{e.preventDefault();try{const c=ENG.addCustomer({legalName:val('cLegal'),displayName:val('cDisplay'),gstin:val('cGstin'),stateCode:val('cStateCode'),state:val('cState'),country:val('cCountry'),email:val('cEmail'),phone:val('cPhone'),billingAddress:val('cAddress')});closeModal();toast('Customer created',c.legalName);page='customers';location.hash=page;renderNav();refresh();}catch(err){toast('Could not create customer',err.message,'error')}};
  } else if(type==='product'){
    openModal('Add product','Product Registry',`<form id="productForm"><div class="form-grid"><div class="field"><label>Product code *</label><input id="pCode" maxlength="5" placeholder="2–5 letters/numbers" required></div><div class="field"><label>Brand name *</label><input id="pName" required></div><div class="field"><label>Category *</label><input id="pCategory" required></div><div class="field"><label>Initial country</label><select id="pCountry"><option value="IN">India</option><option value="US">United States</option></select></div></div><div class="form-note">A product registry record inherits company identity, billing mode and platform services. Pricing, tax mappings and contracts remain separate versioned configuration.</div><div class="form-actions"><button type="button" class="button secondary" data-cancel>Cancel</button><button class="button" type="submit">Add product</button></div></form>`);
    $('#productForm').onsubmit=e=>{e.preventDefault();try{const p=ENG.addProduct({code:val('pCode'),name:val('pName'),category:val('pCategory'),country:val('pCountry')});closeModal();toast('Product added',`${p.code} · ${p.name}`);page='products';location.hash=page;renderNav();refresh();}catch(err){toast('Could not add product',err.message,'error')}};
  } else if(type==='invoice'){
    if(!state.customers.length){toast('Create a customer first','Invoices require a canonical customer identity.','error');openCreate('customer');return;}
    openModal('Issue tax invoice','Billing Engine',`<form id="invoiceForm"><div class="form-grid"><div class="field"><label>Customer *</label><select id="iCustomer">${state.customers.map(c=>`<option value="${c.id}">${esc(c.legalName)} · ${esc(c.stateCode||'no state code')}</option>`).join('')}</select></div><div class="field"><label>Product *</label><select id="iProduct">${state.products.map(p=>`<option value="${p.id}">${esc(p.code)} · ${esc(p.name)}</option>`).join('')}</select></div><div class="field full"><label>Description *</label><input id="iDescription" value="Software development / SaaS services"></div><div class="field"><label>SAC</label><input id="iSac" placeholder="Verify approved SAC before production"></div><div class="field"><label>Quantity</label><input id="iQty" type="number" min="1" value="1"></div><div class="field"><label>Taxable value *</label><input id="iTaxable" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Discount</label><input id="iDiscount" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>GST rate %</label><input id="iGst" type="number" min="0" step="0.01" value="${state.settings.defaultGstRate}"></div><div class="field"><label>Due date</label><input id="iDue" type="date"></div><div class="field full"><label>Notes</label><textarea id="iNotes" placeholder="Optional controlled note"></textarea></div></div><div class="form-note">GST type is determined from supplier state code ${esc(state.settings.supplierStateCode)} and the customer's state code. Production issue remains blocked until GST registration, sequence, SAC and tax mappings are formally verified.</div><div class="form-actions"><button type="button" class="button secondary" data-cancel>Cancel</button><button class="button" type="submit">Issue immutable invoice</button></div></form>`);
    $('#invoiceForm').onsubmit=e=>{e.preventDefault();try{const inv=ENG.createInvoice({customerId:val('iCustomer'),productId:val('iProduct'),description:val('iDescription'),sac:val('iSac'),qty:val('iQty'),taxableValue:val('iTaxable'),discount:val('iDiscount'),gstRate:val('iGst'),dueDate:val('iDue'),notes:val('iNotes')});closeModal();toast('Invoice issued',`${inv.invoiceNo} · ${money(inv.total)}`);page='billing';location.hash=page;renderNav();refresh();setTimeout(()=>openInvoice(inv.id),80);}catch(err){toast('Invoice not issued',err.message,'error')}};
  } else if(type==='payment'){
    const open=state.invoices.filter(i=>i.balance>0.01);if(!open.length){toast('No open invoices','Issue an invoice or all local invoices are already paid.','error');return;}
    openModal('Record payment','Payments',`<form id="paymentForm"><div class="form-grid"><div class="field full"><label>Invoice *</label><select id="payInvoice">${open.map(i=>`<option value="${i.id}">${esc(i.invoiceNo)} · ${esc(i.snapshot.customer.legalName)} · balance ${money(i.balance)}</option>`).join('')}</select></div><div class="field"><label>Amount *</label><input id="payAmount" type="number" min="0.01" step="0.01" value="${open[0]?.balance||''}" required></div><div class="field"><label>Method</label><select id="payMethod"><option>Bank Transfer</option><option>UPI</option><option>Razorpay</option><option>Cheque</option><option>Cash</option><option>Other</option></select></div><div class="field"><label>Reference / UTR</label><input id="payRef"></div><div class="field"><label>Received date</label><input id="payDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><div class="form-note">Manual capture is an exception path. In production, successful provider/bank events should create this record automatically with idempotency and settlement reconciliation.</div><div class="form-actions"><button type="button" class="button secondary" data-cancel>Cancel</button><button class="button" type="submit">Record & issue receipt</button></div></form>`);
    $('#payInvoice').onchange=()=>{const inv=state.invoices.find(i=>i.id===val('payInvoice'));$('#payAmount').value=inv?.balance||'';};
    $('#paymentForm').onsubmit=e=>{e.preventDefault();try{const x=ENG.recordPayment({invoiceId:val('payInvoice'),amount:val('payAmount'),method:val('payMethod'),reference:val('payRef'),receivedAt:val('payDate')});closeModal();toast('Payment recorded',`${money(x.payment.amount)} · ${x.receipt.receiptNo}`);page='payments';location.hash=page;renderNav();refresh();setTimeout(()=>openReceipt(x.receipt.id),80);}catch(err){toast('Payment not recorded',err.message,'error')}};
  } else if(type==='asset'){
    openModal('Add asset','Asset Register',`<form id="assetForm"><div class="form-grid"><div class="field"><label>Asset name *</label><input id="aName" required></div><div class="field"><label>Category *</label><input id="aCategory" required placeholder="Laptop / DSC Token / Network"></div><div class="field"><label>Serial / Identifier</label><input id="aSerial"></div><div class="field"><label>Custodian</label><input id="aOwner"></div><div class="field full"><label>Location</label><input id="aLocation"></div></div><div class="form-actions"><button type="button" class="button secondary" data-cancel>Cancel</button><button class="button" type="submit">Add asset</button></div></form>`);
    $('#assetForm').onsubmit=e=>{e.preventDefault();try{const a=ENG.addAsset({name:val('aName'),category:val('aCategory'),serial:val('aSerial'),assignedTo:val('aOwner'),location:val('aLocation')});closeModal();toast('Asset added',a.name);page='assets';location.hash=page;renderNav();refresh();}catch(err){toast('Asset not added',err.message,'error')}};
  }
  $$('[data-cancel]').forEach(b=>b.onclick=closeModal);
}

function buildManifest(){ const selected=$$('.inspection-doc:checked').map(x=>x.value); const docs=allDocuments().filter(d=>selected.includes(d.id)); return {manifest_id:ENG.uid('INSP'),generated_at:new Date().toISOString(),legal_entity:{name:SEED.company.legalName,cin:SEED.company.cin},request:{authority:val('inspAuthority'),reference:val('inspRef')||null,period:val('inspPeriod')||null,purpose:val('inspPurpose')||null},mode:'READ_ONLY_SCOPE_LIMITED_DISCLOSURE',record_count:docs.length,records:docs.map(d=>({document_id:d.id,title:d.title,type:d.type,area:d.area,format:d.format,status:d.status,source:d.source,file:d.file||null}))}; }
function previewManifest(downloadIt){ const m=buildManifest();$('#manifestPreview').textContent=JSON.stringify(m,null,2);ENG.audit(downloadIt?'inspection.manifest.downloaded':'inspection.manifest.previewed','inspection',m.manifest_id,`${m.request.authority} · ${m.record_count} records`,'AUDIT');if(downloadIt){download(`KRAVIA_${m.request.authority.replaceAll(/[^A-Za-z0-9]+/g,'_')}_Inspection_Manifest_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(m,null,2));toast('Inspection manifest generated',`${m.record_count} controlled record(s) selected.`);} }

function buildCommands(){ const arr=[];NAV.forEach(g=>g.items.forEach(([id,label])=>arr.push({type:'Module',title:label,detail:g.section,act:()=>navigate(id)})));allDocuments().forEach(d=>arr.push({type:'Document',title:d.title,detail:`${d.id} · ${d.area}`,act:()=>openDocument(d.id)}));state.customers.forEach(c=>arr.push({type:'Customer',title:c.legalName,detail:c.id,act:()=>navigate('customers')}));state.products.forEach(p=>arr.push({type:'Product',title:p.name,detail:`${p.code} · ${p.category}`,act:()=>navigate('products')}));state.invoices.forEach(i=>arr.push({type:'Invoice',title:i.invoiceNo,detail:`${i.snapshot.customer.legalName} · ${money(i.total)}`,act:()=>openInvoice(i.id)}));return arr; }
function openCommand(){ $('#commandOverlay').hidden=false;$('#commandInput').value='';renderCommands('');setTimeout(()=>$('#commandInput').focus(),20); }
function closeCommand(){ $('#commandOverlay').hidden=true; }
function renderCommands(q){const cmds=buildCommands();const s=q.toLowerCase().trim();const list=cmds.filter(c=>!s||`${c.type} ${c.title} ${c.detail}`.toLowerCase().includes(s)).slice(0,20);$('#commandResults').innerHTML=list.length?list.map((c,i)=>`<button class="command-item ${i===0?'active':''}" data-command="${i}"><span><strong>${esc(c.title)}</strong><small>${esc(c.detail)}</small></span><small>${esc(c.type)}</small></button>`).join(''):`<div class="empty"><strong>No result</strong><span>Try a module, customer, product, invoice or document.</span></div>`;$$('[data-command]').forEach(b=>b.onclick=()=>{list[Number(b.dataset.command)].act();closeCommand();});}

function quickMenu(){ openModal('Create','Quick Actions',`<div class="quick-grid"><button class="quick-tile" data-q="customer"><strong>Customer</strong><small>Canonical legal/billing identity</small></button><button class="quick-tile" data-q="invoice"><strong>Invoice</strong><small>Immutable tax snapshot</small></button><button class="quick-tile" data-q="payment"><strong>Payment</strong><small>Receipt + receivable update</small></button><button class="quick-tile" data-q="product"><strong>Product</strong><small>Registry configuration</small></button><button class="quick-tile" data-q="asset"><strong>Asset</strong><small>Custody record</small></button><button class="quick-tile" data-q="inspection"><strong>Inspection room</strong><small>Controlled disclosure</small></button></div>`);$$('[data-q]').forEach(b=>b.onclick=()=>{const x=b.dataset.q;closeModal();if(x==='inspection')navigate('inspection');else setTimeout(()=>openCreate(x),50);}); }

// Global bindings
$('#commandTrigger').onclick=openCommand;$('#commandInput').oninput=e=>renderCommands(e.target.value);$('#commandInput').onkeydown=e=>{if(e.key==='Enter')$('#commandResults .command-item')?.click();if(e.key==='Escape')closeCommand();};$('#commandOverlay').onclick=e=>{if(e.target===$('#commandOverlay'))closeCommand();};
$('#drawerClose').onclick=closeDrawer;$('#drawerOverlay').onclick=e=>{if(e.target===$('#drawerOverlay'))closeDrawer();};$('#modalClose').onclick=closeModal;$('#modalOverlay').onclick=e=>{if(e.target===$('#modalOverlay'))closeModal();};$('#quickAction').onclick=quickMenu;
$('#sidebarCollapse').onclick=()=>$('#sidebar').classList.toggle('collapsed');
$('#notificationButton').onclick=()=>navigate('compliance');
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand();}if(e.key==='Escape'){if(!$('#commandOverlay').hidden)closeCommand();else if(!$('#modalOverlay').hidden)closeModal();else if(!$('#drawerOverlay').hidden)closeDrawer();}});
window.addEventListener('hashchange',()=>{page=(location.hash||'#overview').slice(1);renderNav();render();});

renderNav();render();
